### ISSUE TITLE
question: how to prepare kubebuilder env in kruise project

### ISSUE THREAD

**Issue by gotosre** [openkruise/kruise#1001]
i wanna run kruise testing case,but error occurrrrred.
2022/06/20 07:46:20 unable to start control plane itself: failed to start the controlplane. retried 5 times: fork/exec /usr/local/kubebuilder/bin/etcd: no such file or directory

follow the kubebuilder official docs, i install kubebuilder bin, but not work.

how to prepare it?

**Comment by veophi** [comment]
Plz try 
```
OS=$(uname -s | tr '[:upper:]' '[:lower:]')
ARCH=$(uname -m | sed 's/x86_64/amd64/')
curl -fsL "https://storage.googleapis.com/kubebuilder-tools/kubebuilder-tools-1.16.4-${OS}-${ARCH}.tar.gz" -o kubebuilder-tools
tar -zvxf kubebuilder-tools
sudo mv kubebuilder/ /usr/local/kubebuilder
```
