### ISSUE TITLE
[feature request] SidecarSet支持查看管控范围内Pod上的Sidecar当前版本

### ISSUE THREAD

**Issue by Reason94** [openkruise/kruise#1005]
**What would you like to be added**:
- SidecarSet升级完成后，快速了解哪些pod已经升级成新版本了
- SidecarSet管控范围内，各个Pod的sidecar版本，可按版本筛选pod

**Why is this needed**:
用于Paas平台集成，查看下某次金丝雀发布后哪些pod已经升级，以及本sidecar管控范围内pod上的sidecar版本

** 个人思路**:
sidecarset 像cloneset一样，增加labels信息，此类label会被写入pod的labels部分。
通过Selector机制快速查询

**Comment by zmberg** [comment]
@Reason94 look at this pr https://github.com/openkruise/kruise/pull/993, If add the version label here, eg. kruise.io/sidecar-version: v1 ,it should meet your needs.

**Comment by Reason94** [comment]
> @Reason94 look at this pr #993, If add the version label here, eg. kruise.io/sidecar-version: v1 ,it should meet your needs.

It seems that it can solve my needs. When will it be released?
