### ISSUE TITLE
[BUG] Why Optional Field <MaxUnavailable> can not be set nil?

### ISSUE THREAD

**Issue by ABNER-1** [openkruise/kruise#1006]
**What happened**:
I use advanced daemonset and update with partition feature. However, when I update to v1.1.0, I can not update when I don't set MaxUnavailable and MaxSurge with kruise controller log error msg "couldn't get unavailable numbers: invalid value for MaxUnavailable: nil value for IntOrString".

**What you expected to happen**:

As api doc said: "// The maximum number of DaemonSet pods that can be unavailable during the
	// update. Value can be an absolute number (ex: 5) or a percentage of total
	// number of DaemonSet pods at the start of the update (ex: 10%). Absolute
	// number is calculated from percentage by rounding up.
	// This cannot be 0 if MaxSurge is 0
	// Default value is 1.
	// Example: when this is set to 30%, at most 30% of the total number of nodes
	// that should be running the daemon pod (i.e. status.desiredNumberScheduled)
	// can have their pods stopped for an update at any given time. The update
	// starts by stopping at most 30% of those DaemonSet pods and then brings
	// up new DaemonSet pods in their place. Once the new pods are available,
	// it then proceeds onto other DaemonSet pods, thus ensuring that at least
	// 70% of original number of DaemonSet pods are available at all times during
	// the update.
	// +optional".
This is an optional field and default value is 1.

**How to reproduce it (as minimally and precisely as possible)**:
update daemon with nil MaxUnavailable.

**Anything else we need to know?**:

**Environment**:
- Kruise version: v1.1.0
- Kubernetes version (use `kubectl version`): 1.16
- Install details (e.g. helm install args): 
- Others:

**Comment by veophi** [comment]
@ABNER-1  Webhook will set [Default](url) for daemonset if it is nil when creating/updating it,  how do you update your daemonset?

**Comment by ABNER-1** [comment]
I use openkruise client v1.1.0-legacy to update. 
How can I debug this webhook log?

**Comment by FillZpp** [comment]
@ABNER-1 Could you paste your ads yaml by `kubectl get ads xxx -o yaml`?

**Comment by ABNER-1** [comment]
I will reproduce this case later.
I found in my k8s cluster, the webhook may be unreachable because our k8s setting. Maybe this is the reason why whe MaxUnavailable is nil.
