### ISSUE TITLE
[BUG] kruise-controller-manager failed to watch and list resources

### ISSUE THREAD

**Issue by aaronseahyh** [openkruise/kruise#1013]
**What happened**:
The following errors showed up in the pod logs of **kruise-controller-manager** during deployment of kruise:
```
E0629 10:27:44.185904       1 reflector.go:138] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:152: Failed to watch *v1alpha1.ImagePullJob: failed to list *v1alpha1.ImagePullJob: the server was unable to return a response in the time allotted, but may still be processing the request (get imagepulljobs.apps.kruise.io)
```
```
E0629 10:27:46.622115       1 reflector.go:138] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:152: Failed to watch *v1alpha1.BroadcastJob: failed to list *v1alpha1.BroadcastJob: the server was unable to return a response in the time allotted, but may still be processing the request (get broadcastjobs.apps.kruise.io)
```

**What you expected to happen**:
No errors when deploying kruise application.

**How to reproduce it (as minimally and precisely as possible)**:
1. Install kruise v1.2.0
2. Check pod logs of kruise-controller-manager

**Anything else we need to know?**:
Full pod logs: [manager.txt](https://github.com/openkruise/kruise/files/9018451/manager.txt)

**Environment**:
- Kruise version: v1.2.0
- Kubernetes version (use `kubectl version`): v1.18
- Install details (e.g. helm install args): 
```
helm fetch --untar --untardir charts openkruise/kruise --version 1.2.0
helm template charts/kruise > kruise-1.2.0.yaml
kustomize create --autodetect
kubectl apply -k . 
```

**Comment by FillZpp** [comment]
> the server was unable to return a response in the time allotted, but may still be processing the request

That's the timeout of HTTP request to API Server. I'm not sure why it happened, but I fount a same issue https://github.com/kubernetes/kubernetes/issues/60957 , see if can help you.
