### ISSUE TITLE
clonset 有关lifecycle 能否给一下详细一点的demo?

### ISSUE THREAD

**Issue by jonah-lab** [openkruise/kruise#1019]
**What would you like to be added**:
更详细的demo,有关cloneset PreDeleteHooked的操作方法

**Why is this needed**:
有关pod的信息如何获得？
如何在controller里面去操作其它的资源对象？

**Comment by FillZpp** [comment]
Here is a sample https://github.com/openkruise/samples/tree/master/lifecycle-hook-controller
