### ISSUE TITLE
[BUG] podip没有固定，使用persistentpodstates + flannel(host-local)

### ISSUE THREAD

**Issue by jiangfoxi** [openkruise/kruise#1020]
**What happened**: 
1. 通过构建host-local二进制，替换公司ipam host-local 插件二进制，并卸载掉flannel和cni0以及flannel重装flannel(执行https://github.com/openkruise/samples/blob/master/containernetworking/plugins/build_linux.sh)
2. 修改flannel cfg，增加capabilities（按照https://github.com/openkruise/kruise/blob/master/docs/proposals/20220421-persistent-pod-state.md此文档来修改）
cni-conf.json: |
    {
      "name": "cbr0",
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "flannel",
          "capabilities": {
              "io.kubernetes.cri.pod-annotations": true
          },
          "delegate": {
            "hairpinMode": true,
            "isDefaultGateway": true
          }
        },
        {
          "type": "portmap",
          "capabilities": {
            "portMappings": true
          }
        }
      ]
    }

3.然后部署一个sts，并删除sts pod，发现pod仍然没有固定，但是nodeAffinity 注入成功
**What you expected to happen**: 期待pod ip能固定

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kruise version: 1.2
- Kubernetes version (use `kubectl version`):v1.21.11
- Install details (e.g. helm install args):
- Others: flannel quay.io/coreos/flannel:v0.14.0-amd64

**Comment by zmberg** [comment]
@jiangfoxi pod need contains annotations["io.kubernetes.cri/reserved-ip-duration"] = 10.

**Comment by jiangfoxi** [comment]
加了之后貌似还是一样的没有保留ip
<img width="483" alt="image" src="https://user-images.githubusercontent.com/38380031/183876976-712fda37-7d68-4d48-882a-ac40121a2fd7.png">
delete之前
<img width="781" alt="image" src="https://user-images.githubusercontent.com/38380031/183877334-1ef299bc-d498-4a7d-97f8-e0074d7fd772.png">


delete之后，ip  还是变了
<img width="697" alt="image" src="https://user-images.githubusercontent.com/38380031/183877232-206aa162-dcf4-4f91-a7b5-14809b8ccfa7.png">

看是不是还需要一些日志进行分析？

**Comment by zmberg** [comment]
@jiangfoxi Need Log. Have you entered the DingDing Group?
