### ISSUE TITLE
cloneSet controller 获取所属Pod存在问题

### ISSUE THREAD

**Issue by dylandee** [openkruise/kruise#1032]
cloneset controller 在reconcile的时候，通过 fieldSelector 过滤出ownerRefrence 为 当前 cloneSet 的Pods 
(https://github.com/openkruise/kruise/blob/e45953001f1dfbf72ddffe7e1b77e121048f323d/pkg/controller/cloneset/cloneset_controller.go#L454)

这里会存在问题，如果一个pod 本来是属于某个cloneset，但是ref因为某些原因被删除了，那这个pod就会变成孤儿，生命周期失去管控

其实接下来的 claimPods 其实有一段逻辑是给 selector 选中，但是ownerRefrence没有的pod setownerRefrence(https://github.com/openkruise/kruise/blob/e45953001f1dfbf72ddffe7e1b77e121048f323d/pkg/util/refmanager/ref_manager.go#L258) 

replicaSet这个方法原本是没有这个 fieldSelector，这边添加了反而会存在上述我提的这个问题(https://github.com/kubernetes/kubernetes/blob/287888b191968198679159580b1bb76b529aa8c0/pkg/controller/controller_utils.go#L932)

**Comment by FillZpp** [comment]
@dylandee 是的，这是因为 CloneSet 目前在设计上，暂时不支持接管 orphan Pod（这一点与 ReplicaSet 不同），参考这个历史 PR #486 的讨论。

**Comment by dylandee** [comment]
好的，我看了一下这个pr，我同意你的观点，确实这是一种比较特殊的情况，风险大于收益
