### ISSUE TITLE
[feature request] partition support config like 100% - num

### ISSUE THREAD

**Issue by shiyan2016** [openkruise/kruise#1038]
**What would you like to be added**:

partition support config like 100% - num

**Why is this needed**:
In some case, we need canary release, which expect num(for example num=1) of  pods always keep the newest version even if hpa triggle scale  in the canary release time.

**Comment by veophi** [comment]
sounds good!

How about to support both `100%-num` and `100%-percent` ?

**Comment by FillZpp** [comment]
This should be a topic of the community meeting this week :)

**Comment by shiyan2016** [comment]
After discussion，partition will support config with float to improvement precision.
