### ISSUE TITLE
[feature request] How to distinguish between in-place restarts and problem pod restarts

### ISSUE THREAD

**Issue by chenshiwei-io** [openkruise/kruise#1044]
**What would you like to be added**:
> Version: v1.2
Container Restart
FEATURE STATE: Kruise v0.9.0

ContainerRecreateRequest provides a way to let users restart/recreate one or more containers in an existing Pod.

Just like the in-place update provided in Kruise, during container recreation, other containers in the same Pod are still running. Once the recreation is completed, nothing changes in the Pod except that the recreated container's restartCount is increased. Note that the files written into the rootfs of the previous container will be lost, but the data in volume mounts remain.

How to distinguish between in-place restarts and problem pod restartCount ?

**Why is this needed**:
I want to show  problem pod restartCount.

**Comment by FillZpp** [comment]
@no-frown How about a discussion in next community meeting?

**Comment by no-frown** [comment]
> @no-frown How about a discussion in next community meeting?

👌🏻
Is the discussion in the openkruise dingtalk group? I am in the group.

**Comment by hantmac** [comment]
How about add an annotation to indicate which container was restarted by crr ?

**Comment by FillZpp** [comment]
> > @no-frown How about a discussion in next community meeting?
> 
> 👌🏻 Is the discussion in the openkruise dingtalk group? I am in the group.

We'd better discuss this on the bi-weekly meeting, which will be notified in the dingtalk group.
