### ISSUE TITLE
[BUG]  Scale with partition for AdvancedStatefulSet is not expected

### ISSUE THREAD

**Issue by shiyan2016** [openkruise/kruise#1062]
**What happened**:
Create a asts with name=test and replicas=2, then after some pod spec and set partition=1, it will update test-1 to new revision.
Then update the asts to replicas=4 and partition=3, it will create test-2 with old revision and test-3 with new revision. So there are two updated revision pods( test-1, test-3) and two old revision pods( test-0, test-2). Which 

**What you expected to happen**:
After update asts to replicas=4 and partition=3, the result should be three old revision pods and one new revision pod.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kruise version: v1.2.0
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Others:

**Comment by veophi** [comment]
The meaning of `Partition` of StatefulSet with `OrderedReady` PodManagementPolicy  is quite different with CloneSet, its partition just make sure the pod with ordinal >= 'partition' to be upgraded.

There may be a tricky way to achieve what you want, you can set an `unorderedUpdate` with a  selector label to StatefulSet, the meaning of partition will  be in line with CloneSet.
