### ISSUE TITLE
[feature request] sts原地升级过程中，是会在crashbackoff状态停留？

### ISSUE THREAD

**Issue by song0071000** [openkruise/kruise#1067]
**What would you like to be added**:
最近测试了下，原地升级，在容器被重启后，pod的restart count貌似是上涨了。
而且可能会处于crashbackoff状态（我看起了readiness probe）？
这样就会出现一个问题，在10min内，如果多次原地升级，就会等待backoff的时间？
这样是符合预期的吗？如何规避等待时间？

**Why is this needed**:

**Comment by veophi** [comment]
If

**Comment by song0071000** [comment]
> If the container hash is changed, the `backoff` will be reset by Kubelet.

env from label  这种情况呢？

**Comment by song0071000** [comment]
env from metadata，这种原地升级：只改metadata.labels，触发原地升级，container hash也不会变化，表现出来的现象就是，多次反复操作，就会等待backoff了。


如下，多次更改spec.template.metadata.labels["kk"] 即可复现
`
apiVersion: apps.kruise.io/v1alpha1
kind: StatefulSet
metadata:
  name: web
  namespace: test
spec:
  podManagementPolicy: Parallel
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx
  serviceName: nginx
  template:
    metadata:
      labels:
        app: nginx
        kk: vv
    spec:
      containers:
        - env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: 'metadata.labels[''kk'']'
          image: 'nginx:1.9.1'
          imagePullPolicy: Always
          name: nginx
          ports:
            - containerPort: 80
              name: web
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /tmp/gs
              name: wwwroot
      dnsPolicy: ClusterFirst
      readinessGates:
        - conditionType: InPlaceUpdateReady
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 10
      volumes:
        - emptyDir: {}
          name: wwwroot
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
      minReadySeconds: 0
      partition: 0
      podUpdatePolicy: InPlaceIfPossible
    type: RollingUpdate
`

**Comment by song0071000** [comment]
> If the container hash is changed, the `backoff` will be reset by Kubelet.

 env from metadata，container hash 不会变化。这种情况，只能等待10min，让backoff reset 是吧？
