### ISSUE TITLE
[GLCC] Genereate openapi schema for kustomize

### ISSUE THREAD

**Issue by furykerry** [openkruise/kruise#1069]
OpenKruise does not work very well with kustomize. kustomize strategic merge only support k8s native resource type, and json patch is unable to merge array element using merge keys such as container name. 

However, kustomize support using openapi schema to specify merge key and patch strategy.

Background information can be refer: https://tech.aabouzaid.com/2022/11/set-openapi-patch-strategy-for-kubernetes-custom-resources-kustomize.html

The programme can be refer: https://github.com/argoproj/argo-rollouts/pull/1371

**What would you like to be added**:
generate openapi for openkruise resource types

**Why is this needed**:
Enable kustomize to patch correctly OpenKruise types.

**Comment by zmberg** [comment]
Background information can be refer: https://tech.aabouzaid.com/2022/11/set-openapi-patch-strategy-for-kubernetes-custom-resources-kustomize.html

The programme can be refer: https://github.com/argoproj/argo-rollouts/pull/1371

**Comment by y-ykcir** [comment]
@zmberg Hi, May I ask if this is the only selected issue for GLCC? Maybe I can take this. But it seems that this issue does not require too much proposal design. May I ask what content I need to prepare when applying?

**Comment by zmberg** [comment]
@y-ykcir Yes, this is glcc project. And you can apply for it in glcc.

**Comment by y-ykcir** [comment]
> @y-ykcir Yes, this is glcc project. And you can apply for it in glcc.

@zmberg Thanks, I have submitted the application.
