### ISSUE TITLE
rescheduleCriticalSeconds limited to max 98 seconds

### ISSUE THREAD

**Issue by martin2176** [openkruise/kruise#1072]
scheduleStrategy:
    type: Adaptive
    adaptive:
      rescheduleCriticalSeconds: 180

Invalid value: 180: rescheduleCriticalSeconds < 0 or rescheduleCriticalSeconds > 98 is not permitted
 I have 4 subsets . 
 Adding each subset lower the allowed value of reschedulecriticalseconds.

Can we allow user to specify a reasonable time such as 5 minutes.? Cloud Kubernetes deployments take atleast 2 minutes to spin up a node in response to an autoscaler event

**Comment by veophi** [comment]
sounds good

**Comment by martin2176** [comment]
Will someone triage this and approve/reject ?

**Comment by zmberg** [comment]
@caniszczyk I thinks it's good. Can you submit a pr for this?

**Comment by zmberg** [comment]
#823

**Comment by martin2176** [comment]
great and thank you.( I have not tested it)

**Comment by martin2176** [comment]
what is the max  value that is now allowed for rescheduleCriticalSeconds?
Would the documentation be eventually updated to reflect this
