### ISSUE TITLE
How does kruise eplement inplaceupdating with no change about pod lifecycle

### ISSUE THREAD

**Issue by marklinglon** [openkruise/kruise#1076]
how does kruise eplement  inplaceupdating with no change about pod lifecycle.

**Comment by marklinglon** [comment]
How does kruise eplement inplaceupdating with no change about pod lifecycle.[feature request] YOUR_TITLE

**Comment by marklinglon** [comment]
Which file can I find the reason

**Comment by FillZpp** [comment]
https://openkruise.io/docs/core-concepts/inplace-update
