### ISSUE TITLE
pod antiaffinity so kruise-manager pods dont end up on same host

### ISSUE THREAD

**Issue by martin2176** [openkruise/kruise#1085]
**I dont see an option in the helm chart to add a pod antiaffinity feature. **:

**This would force kubernetes to schedule openkruise manager pods to run on 2 different physical kubernetes hosts to give more availability to the kruise manager (which is the brain) **:

**Comment by FillZpp** [comment]
The chart contains a preferred anti-affinity to let the two managers be scheduled to different nodes if possible.

https://github.com/openkruise/charts/blob/master/versions/kruise/1.2.0/templates/manager.yaml#L98

**Comment by martin2176** [comment]
> The chart contains a preferred anti-affinity to let the two managers be scheduled to different nodes if possible.
> 
> https://github.com/openkruise/charts/blob/master/versions/kruise/1.2.0/templates/manager.yaml#L98

Can the pod antiaffinity be added to values.yaml so that it can be supplied during helm (as an enhancement request )

The reason being, the manager.yaml have podantiaffinity = preferredDuringSchedulingIgnoredDuringExecution
I would like podantiaffinity = requierdDuringSchedulingIgnoredDuringExecution so that it is a hard rule for the POD to end up on two different nodes and if a node is not available, just wait until a node is available .
