### ISSUE TITLE
[feature request] cloneset support  adding pvc

### ISSUE THREAD

**Issue by willise** [openkruise/kruise#1087]
**What would you like to be added**:
  volumeClaimTemplates:
    - metadata:
        name: data-vol
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 20Gi
    - metadata:
        name: data-vol2
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 20Gi
**Why is this needed**:
After cloneset has been created, it not to support to add more pvc. Like deployment, if there some field has been changed, pod should be deleted. So why does cloneset not support this? Any more information? Thanks.

**Comment by FillZpp** [comment]
> Like deployment, if there some field has been changed, pod should be deleted.

Deployment doesn't have `volumeClaimTemplates` field, both Deployment and CloneSet will update Pods when the `template` field changed.

**Comment by FillZpp** [comment]
We are designing the behavior of modifying `volumeClaimTemplates`, updating all Pods with PVCs, or resizing the existing PVCs if the storage changed.

**Comment by willise** [comment]
> We are designing the behavior of modifying `volumeClaimTemplates`, updating all Pods with PVCs, or resizing the existing PVCs if the storage changed.

Good news!

**Comment by zjzhangkui** [comment]
waiting for

**Comment by W-YJ** [comment]
do you have due time for releasing this feature? @FillZpp

**Comment by FillZpp** [comment]
How about a discussion round this approach at the community meeting this week? @willise @zjzhangkui @W-YJ 

/assign @zmberg @veophi

**Comment by zmberg** [comment]
https://github.com/openkruise/kruise/issues/905
