### ISSUE TITLE
kruise-controller-manager pod consuming about 250 mc (1/4 of a cpu) constant and consistent when idling

### ISSUE THREAD

**Issue by martin2176** [openkruise/kruise#1089]
I have deployed kruise controller manager with 1 pod as well as tried with 2 pods (to do leader election)
In all cases, the controller manager continuously uses a cpu of 80-90% of 200m limit when the controller manager is just idling away doing nothing (no admission or mutuating webhooks).
I have datadog on the cluster which will allow to see real time cpu /mem usage of container with a 2 second granularity. 
While I can't say constant use of 180mc of cpu is normal to kruise-manager even when its not actively doing anything, it does seem requiring further investigation. See graph of CPU at 2second granularity listed below
![image](https://user-images.githubusercontent.com/14482998/191971077-103f197c-ade9-49e7-bbbd-64979f46052f.png)

**Comment by martin2176** [comment]
To see how much CPU the kruise manager will use if it not restricted to use 200mc,, I gave it 500 mc of container Limit. 
Now that it have plenty of CPU, I can see its consuming between 30% to 50% of 500mc container limit. ie 150mc to 250mc
In my opinion an app which consumes 250mc of cpu when its not actively servicing anything is unusual. 
Note that the only feature I am using here is workloadspread and while its idling away there is no pod admission happening. 


![image](https://user-images.githubusercontent.com/14482998/192037693-2407cd02-854f-49be-918c-974cdfb949be.png)

**Comment by FillZpp** [comment]
All informers in kruise-controller-manager are running, including Pods, Nodes listwatching, even if you have not applied any Kruise resources.

**Comment by martin2176** [comment]
Yes it makes sense to consume cpu . 
1) My question is more along the lines of is it normal to consume 1/4 of a cpu when controller is essentially watching objects in a loop (not actively performing any mutuations of admission)

2) Would openkruise community publish a cpu|mem recommendation on what to expect the controller to consume from CPU|mem point of view and any benchmarking results upon which I can size the container resources

**Comment by FillZpp** [comment]
1. kruise-controller-manager will open pprof server on `:8090` by default. If you are familiar with go pprof, you can see what it is doing from cpu profile.
2. We have no exact recommendation for resources configuration, because the controller-manager requires different quantities of resources in different clusters, even if the clusters have similar pod or node scales, that also depends on how we use the resources, e.g. read/write frequency and which CRs or controllers are mainly used.

**Comment by martin2176** [comment]
> 1. kruise-controller-manager will open pprof server on `:8090` by default. If you are familiar with go pprof, you can see what it is doing from cpu profile.
> 2. We have no exact recommendation for resources configuration, because the controller-manager requires different quantities of resources in different clusters, even if the clusters have similar pod or node scales, that also depends on how we use the resources, e.g. read/write frequency and which CRs or controllers are mainly used.

I can run a pprof on the controller manager if someone from development is willing to look at the results. Personally the cpu usage is not really bothering me much. I opened this ticke for the benefit of users who are using open kruise  if developer community of kruise has interest in seeing cpu optimization opportunities

**Comment by martin2176** [comment]
> @martin2176 You can try to disable this feature via set the value as "false", it can help you reduce the use of many cpu and mem resources.
> 
> ![image](https://user-images.githubusercontent.com/28217554/210475257-62156203-e26c-4a79-83f8-96a32bc2074d.png)

Thank you for this suggestion.
