### ISSUE TITLE
[BUG] cloneset reuse terminating pod's name when pvc exists

### ISSUE THREAD

**Issue by willise** [openkruise/kruise#1099]
**What happened**:
The node is not ready and pod with pvc on this node is evicted. But as the kubelet is unready so it doesn't really delete the pod and the pod stuck in terminating state.
cloneset try to scale out a new pod and it finds there is a pvc exsits, so it reuse the pod name referred by pvc to create the pod. But the terminating pod  already exists then it fails.

**What you expected to happen**:
A new pod can be created successfully.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a cloneset with pvc
2. Stop the kubelet and wait 5min 

**Anything else we need to know?**:

**Environment**:
- Kruise version: 1.0.2
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Others:

**Comment by FillZpp** [comment]
@willise Yeah, this is the expected behavior for now. But I understand your intention, how about add a new optional strategy field in `spec.scaleStrategy` to decide whether it should reuse the instanceId of existing free PVCs when creating new Pods?

**Comment by willise** [comment]
> @willise Yeah, this is the expected behavior for now. But I understand your intention, how about add a new optional strategy field in `spec.scaleStrategy` to decide whether it should reuse the instanceId of existing free PVCs when creating new Pods?

 I think this works, but I have another concern about the old PVC. After the terminating pod is deleted finally, should the old PVC be deleted manually or be processed by cloneset?

**Comment by FillZpp** [comment]
> I think this works, but I have another concern about the old PVC. After the terminating pod is deleted finally, should the old PVC be deleted manually or be processed by cloneset?

With the field enabled, cloneset should cleanup those useless PVCs and then create new Pods with new PVCs.

**Comment by willise** [comment]
> With the field enabled, cloneset should cleanup those useless PVCs and then create new Pods with new PVCs.
Ok, I am looking forward it.

**Comment by FillZpp** [comment]
> Ok, I am looking forward it.

And you are welcome if interested in contributing this :)

**Comment by zmberg** [comment]
If the Pod is in the Terminating, it is still risky to delete the PVC directly. The difficulty with this way is that we can't quite tell if it's a normal process or a Hang. I agree with @FillZpp 's idea of adding AlwaysCreatePVC in spec.scaleStrategy to decide whether it should reuse the instanceId of existing free PVCs when creating new Pod.
