### ISSUE TITLE
[BUG] Cannot set the image of the SidecarSet with the kubectl set command

### ISSUE THREAD

**Issue by pengln** [openkruise/kruise#1106]
**What happened**:
```bash
$ sudo kubectl  set image sidecarsets.v1alpha1.apps.kruise.io/test-sidecarset sidecar1=debian:11 -n test

# response this: 
error: no kind "SidecarSet" is registered for version "apps.kruise.io/v1alpha1" in scheme "pkg/scheme/scheme.go:28"
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kruise version: 1.3.0
- Kubernetes version (use `kubectl version`): 1.25
- Install details (e.g. helm install args): default install mode
- Others:

**Comment by zmberg** [comment]
Yes, you can add pr to support this in repo https://github.com/openkruise/kruise-tools/tree/master/pkg/cmd/set.

**Comment by chengleqi** [comment]
Hi @zmberg @furykerry , I opened a PR to solve this issue. 
I was wondering if you would be able to spare some time to review my code changes in kruise-tools. Thanks.

**Comment by hantmac** [comment]
> Hi @zmberg @furykerry , I opened a PR to solve this issue. I was wondering if you would be able to spare some time to review my code changes in kruise-tools. Thanks.

Thanks for the pr. I will review it.
