### ISSUE TITLE
why kruise-daemon connection to apiserver?

### ISSUE THREAD

**Issue by Davidrjx** [openkruise/kruise#1107]
**What happened**:
in kruise-daemon pod, there is a connection to apisever but should not be as architecture or configuration.

**What you expected to happen**:
if actually connection to apiserver exists, support bind-address setting

**How to reproduce it (as minimally and precisely as possible)**:
deployment the tool with hostnetwork enable in manifest

**Anything else we need to know?**:
os distribution: debian 11

**Environment**:
- Kruise version: 1.2.0
- Kubernetes version (use `kubectl version`): 1.23.4
- Install details (e.g. helm install args): helm
- Others:

**Comment by FillZpp** [comment]
Kruise-daemon has to list watch resources from apiserver. And what do you mean "bind-address setting"?

**Comment by Davidrjx** [comment]
> Kruise-daemon has to list watch resources from apiserver. And what do you mean "bind-address setting"?

ok, sounds what  custom controller do with cache store syncing from apiserver but not see obvious bind-address option on help message.  As i known, it would use incluster config as default.

**Comment by zmberg** [comment]
@Davidrjx Can you describe in detail the problem you're running into? And how you want to modify, please give the code or yaml directly.
