### ISSUE TITLE
[feature request] Support unknown pod rschedule

### ISSUE THREAD

**Issue by zeusro** [openkruise/kruise#111]
**What would you like to be added**:

希望 Advanced StatefulSet 能够对失联 pod 进行重新调度

**Why is this needed**:

传统的StatefulSet，节点失联（unknown）之后，上面的pod会变成 unknown ，这时得手动删除它才会重新调度，希望阿里云的 Advanced StatefulSet 能够修复这部分问题。

**Comment by FillZpp** [comment]
When node become `node.kubernetes.io/not-ready` or `node.kubernetes.io/unreachable`, Pod on it should be evicted in 300s by default. 

After that, Advanced StatefulSet will create a new Pod and it will be scheduled to somewhere else.

**Comment by zeusro** [comment]
> When node become `node.kubernetes.io/not-ready` or `node.kubernetes.io/unreachable`, Pod on it should be evicted in 300s by default.
> 
> After that, Advanced StatefulSet will create a new Pod and it will be scheduled to somewhere else.

是这样子的吗,希望这方面文档补充得详细点.
