### ISSUE TITLE
[BUG] AdvancedCronJob无法使用tolerations

### ISSUE THREAD

**Issue by ziansong** [openkruise/kruise#1114]
在AdvancedCronJob中使用broadcastJobTemplate模板是无法添加tolerations关键字，加上之后无法执行
 template:
    broadcastJobTemplate:
      spec:
        template:
          spec:
            tolerations:
              - operator: Exists
 我在BroadcastJob中是可以添加这个字段的

**Comment by zmberg** [comment]
@ziansong I verified that it works, is it convenient for you to send your detailed yaml ?
