### ISSUE TITLE
[feature request] 如何区分容器重启是原地升级导致的还是容器自身crash？

### ISSUE THREAD

**Issue by song0071000** [openkruise/kruise#1115]
当前我们使用了这个kube_pod_container_status_restarts_total指标值做crash判定。这个值如果涨了1，那么判定该pod crash了。
比较迷惑的一点是：这样没法区分，正常的原地重启和异常的pod crash了。
这样我们每次发布应用时，都是判定该pod crash了，会有告警出来，这样误报率比较高。
这种场景下，该是如何去做crash的告警通知？

**Comment by zmberg** [comment]
Is it convenient to post the pod crash event?

**Comment by zmberg** [comment]
The in-place upgrade will stop your container, so your container process should exit normally with code of 0 after receiving the kill signal.

**Comment by song0071000** [comment]
> 

是的，现在就是这么做的。容器 收到kill信号时，exit code 就是0。
      lastState:
        terminated:
          containerID: >-
            containerd://xx
          exitCode: 0
          finishedAt: '2022-11-03T07:56:53Z'
          reason: Completed
          startedAt: '2022-11-03T07:51:25Z'
      name: ss-test
      ready: true
      restartCount: 1

**Comment by song0071000** [comment]
@zmberg  我更详细的描述了下

**Comment by furykerry** [comment]
actually there is one patch working on this [issue](https://github.com/openkruise/kruise/pull/1097), the patch try to update the actual restart counts in the pod annotations, but kube_pod_container_status_restarts_total metric is exported by kube state metrics, one possible solution is to export similar metrics in kruise state metrics 
https://github.com/openkruise/kruise-state-metrics
