### ISSUE TITLE
[BUG]version information in tutorial's doc is not math the tag version

### ISSUE THREAD

**Issue by kerecsen** [openkruise/kruise#112]
Hi,

when I switched the tag v0.1.0 on /docs/tutorial/kruise-install.md, I found the urls of YAML files would not change to the v0.1.0 version's address:

##### * e.g.
```
Install Kruise CRDs
kubectl apply -f https://raw.githubusercontent.com/kruiseio/kruise/master/config/crds/apps_v1alpha1_broadcastjob.yaml
kubectl apply -f https://raw.githubusercontent.com/kruiseio/kruise/master/config/crds/apps_v1alpha1_sidecarset.yaml
kubectl apply -f https://raw.githubusercontent.com/kruiseio/kruise/master/config/crds/apps_v1alpha1_statefulset.yaml
Install kruise-manager
kubectl apply -f https://raw.githubusercontent.com/kruiseio/kruise/master/config/manager/all_in_one.yaml
```
the verion in the urls were still master, and I checked the docker image's tag in https://raw.githubusercontent.com/kruiseio/kruise/master/config/manager/all_in_one.yaml was `:daily` which was updated 20 hours ago on dockerhub, but v0.1.0 was updated 5 days ago.

I suppose the version should be related to v0.1.0, when we change the tag to v0.1.0.  And maybe there are some other docs need to be modified.

**Comment by Fei-Guo** [comment]
I update the release note with the following and upload the correct all_in_one.yaml 

"To install the Kruise controller manager, download the attached all_in_one.yaml and apply it.
`kubectl apply -f all_in_one.yaml`"

Please check if this eases your confusion.

**Comment by kerecsen** [comment]
> I update the release note with the following and upload the correct all_in_one.yaml
> 
> "To install the Kruise controller manager, download the attached all_in_one.yaml and apply it.
> `kubectl apply -f all_in_one.yaml`"
> 
> Please check if this eases your confusion.

that's better now, people could get aware of it from the release.
