### ISSUE TITLE
[feature request] Let kruise daemon work behind HTTP coporate proxy

### ISSUE THREAD

**Issue by mgeri** [openkruise/kruise#1120]
**What would you like to be added**:
Possibility to set the HTTP_PROXY, HTTS_PROXY, and NO_PROXY env variables in kruise-daemon using kruise helm chart.

**Why is this needed**:
When working behind a corporate HTTP proxy, ImagePullJob fails to pull images.

In our case, we are using k3s, which allows setting the Containerd HTTP proxy so that images can be pulled from image repositories behind the proxy, while ImagePullJobs fail.

Manually setting the HTTP env vars in kruise-daemon, allow ImagePullJob to work as expected, e.g.:
```
        - name: HTTP_PROXY
          value: http://myproxy:8080
        - name: HTTPS_PROXY
          value: http://myproxy:8080
        - name: NO_PROXY
          value: localhost,0.0.0.0,127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.kruise-system,.svc,.cluster.local
```
It would be nice if custom env var could be set using helm chart values (at the moment, it seems that it's not supported).

**Comment by mgeri** [comment]
@zmberg Sure, I can do it. I will submit a pr in the chart repo in the next few days.

**Comment by mgeri** [comment]
@zmberg It's my first pr to kruise chart. Reading contribution guidelines, I need to bumb a new version folder with my changes because 1.3.0 is the last immutable version, right? If so, could 1.3.1 be fine?

**Comment by zmberg** [comment]
> @zmberg It's my first pr to kruise chart. Reading contribution guidelines, I need to bumb a new version folder with my changes because 1.3.0 is the last immutable version, right? If so, could 1.3.1 be fine?

I think you can immediate modify in kruise 1.3.0 version.
