### ISSUE TITLE
[BUG] Installing into a namespace other than kruise-system does not work because of hardcoded references to kruise-system

### ISSUE THREAD

**Issue by martin2176** [openkruise/kruise#1121]
**What happened**:
I am using the documented option "installation.namespace" to install kruise into a namespace of my choice.
However it doesn't work. Installation completes successfully but kruise's  mutating webhooks doesn't work because there are 4 hardcoded references to namespace kruise-system which are not templated with the variable {{ .Values.installation.namespace }}
Hence installation into a different namespace other than kruise-system breaks functionality because mutating web hook is referencing a service in kruise-system which doesnt exist.

<html>
<body>

--

<br class="Apple-interchange-newline">
</body>
</html>

**What you expected to happen**:
Be able to install kruise using helm into a namespace other than default kruise-system and expect the kruise functionalities to work.

**How to reproduce it (as minimally and precisely as possible)**:
Run a dry-run of helm install and examine the output
you will find the statefulset, webhookconfiguration have hardcoded references to kruise-system
helm install kruise openkruise/kruise --version 1.2.0 --set featureGates="WorkloadSpread=true\,KruiseDaemon=false" --set installation.namespace=openkruise --dry-run > /tmp/1
cat /tmp/1 |grep kruise-system
You will find 4 references where kruise-system is hardcoded
Or you can go straight into the templates and search for kruise-system.
you will find 4 hardcoded references to kruise-system which infact should have been "{{ .Values.installation.namespace }}"
https://github.com/openkruise/charts/blob/master/versions/kruise/1.3.0/templates/webhookconfiguration.yaml
https://github.com/openkruise/charts/blob/master/versions/kruise/1.3.0/templates/apps.kruise.io_statefulsets.yaml
**Anything else we need to know?**:
Easy enough to verify the bug by following steps above
**Environment**:
- Kruise version: all versions. tested on 1.2 and 1.3
- Kubernetes version (use `kubectl version`): v1.24.3
- Install details (e.g. helm install args): 
- helm install kruise openkruise/kruise --version 1.2.0 --set featureGates="WorkloadSpread=true\,KruiseDaemon=false" --set installation.namespace=openkruise
- Others:

**Comment by ziansong** [comment]
helm install kruise openkruise/kruise --version 1.2.0 --set featureGates="WorkloadSpread=true,KruiseDaemon=false" --set installation.namespace=openkruise -n openkruise  try again  add -n openkruise

**Comment by martin2176** [comment]
> helm install kruise openkruise/kruise --version 1.2.0 --set featureGates="WorkloadSpread=true,KruiseDaemon=false" --set installation.namespace=openkruise -n openkruise try again add -n openkruise

Reply:
I tried " helm install -n openkruise kruise openkruise/kruise --version 1.2.0 --set featureGates="WorkloadSpread=true,KruiseDaemon=false" --set installation.namespace=openkruise"

No luck. The installation still references kruise-system in several places. I have copied few such references.
I think if you look at the templates I referenced above (copying below again) there are hard coded references to kruise-system. Those references are not going to be changed unless they are changed to "{{ .Values.installation.namespace }}"
They are hardcoded kruise-system references which are not going to be substituted irrespective of how you specify the installation namespace name.

Few references after the installation completes
# Source: kruise/templates/apps.kruise.io_statefulsets.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.7.0
  name: statefulsets.apps.kruise.io
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: kruise-webhook-service
          **namespace: kruise-system**
          path: /convert
...
- clientConfig:
    caBundle: Cg==
    service:
      name: kruise-webhook-service
      **namespace: kruise-system**
      path: /validate-pod
  failurePolicy: Fail
...
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: kruise-webhook-service
      **namespace: kruise-system**
      path: /validate-apps-kruise-io-persistentpodstate

**Comment by zmberg** [comment]
@martin2176 Thank you for it, Can you take a pr for this bug fix ?

**Comment by martin2176** [comment]
> @martin2176 Thank you for this. Also, we made some corrections inside the code, but Charts should really be adjusted to variables, thank you very much, and can you take a pr for this bug fix ?

If you are asking me to fix this in the chart, I am sorry. I am not a developer or contributor on this project. I am just an experienced user . I also opened an issue in the github chart for openkruise for maintainers of the chart to fix the chart. I am not sure if there is anyone actively looking at the issues reported on chart repo

**Comment by yike21** [comment]
May I take this? For @martin2176  has a very clear instruction, it's easy to fix it now. I think it just needs to change hardcoded `kruise-system` to variable `{{ .Values.installation.namespace }}` in https://github.com/openkruise/charts/blob/master/versions/kruise/1.3.0/templates/webhookconfiguration.yaml and https://github.com/openkruise/charts/blob/master/versions/kruise/1.3.0/templates/apps.kruise.io_statefulsets.yaml. 
It's also related to the issue by @martin2176  https://github.com/openkruise/charts/issues/22.

**Comment by martin2176** [comment]
> May I take this? For @martin2176 has a very clear instruction, it's easy to fix it now. I think it just needs to change the 4 hardcoded references `kruise-system` to variable `{{ .Values.installation.namespace }}` in https://github.com/openkruise/charts/blob/master/versions/kruise/1.3.0/templates/webhookconfiguration.yaml and https://github.com/openkruise/charts/blob/master/versions/kruise/1.3.0/templates/apps.kruise.io_statefulsets.yaml. It's also related to the issue by @martin2176 [openkruise/charts#22](https://github.com/openkruise/charts/issues/22).

Pls do. I will do any post fix testing on my end
