### ISSUE TITLE
[feature request] kriuse supports configurable selection of a cr start or shutdown

### ISSUE THREAD

**Issue by Somiacao** [openkruise/kruise#1122]
For kriuse I currently only need to use the [Container Restart] function, that is, only crr, if the other cr resources are turned on. In fact, it causes a waste of resources and makes the component very heavy. So the switch configuration is more necessary for me.

Later I am also willing to contribute my code related to the configuration of the switch.

**Comment by veophi** [comment]
Cool

**Comment by zmberg** [comment]
https://github.com/openkruise/kruise/issues/697
