### ISSUE TITLE
The spec.injectionStrategy.revisionName described in the official document and crd are inconsistent.

### ISSUE THREAD

**Issue by skyshaokai** [openkruise/kruise#1123]
**What happened**:
The spec.injectionStrategy.revisionName described in the official document and crd are inconsistent.

In the official document is ：spec.injectionStrategy.revisionName 
<img width="661" alt="image" src="https://user-images.githubusercontent.com/11512967/201258942-1e6456ac-0d4a-48a6-9f54-ae0b81c85bbc.png">
But in the github crd yaml is ：spec.injectionStrategy.revision.revisionName
<img width="868" alt="image" src="https://user-images.githubusercontent.com/11512967/201259208-29110213-38b4-4260-87f8-1e2058888c73.png">

**Comment by zmberg** [comment]
@skyshaokai Thank you for this, and can you take a pr for this bug fix? Related Files: https://github.com/openkruise/openkruise.io/blob/master/docs/user-manuals/sidecarset.md, https://github.com/openkruise/openkruise.io/blob/master/versioned_docs/version-v1.3/user-manuals/sidecarset.md, https://github.com/openkruise/openkruise.io/blob/master/i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/sidecarset.md, https://github.com/openkruise/openkruise.io/blob/master/i18n/zh/docusaurus-plugin-content-docs/version-v1.3/user-manuals/sidecarset.md
