### ISSUE TITLE
Pod RestartPolicy not support "OnFailure" and  "Never" of cloneset

### ISSUE THREAD

**Issue by riverzhang** [openkruise/kruise#1129]
**What happened**:
set pod  RestartPolicy error: 
could not be patched: admission webhook "vcloneset.kb.io" denied the request: spec.template.spec.restartPolicy: Unsupported value: "Never": supported values: "Always"

https://github.com/openkruise/kruise/blob/master/pkg/webhook/cloneset/validating/validation.go#L80

**What you expected to happen**:
we can configure "OnFailure" and  "Never" of Pod RestartPolicy

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kruise version:
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Others:

**Comment by zmberg** [comment]
Generally, only job Pods will set restartPolicy to Never or OnFailure. Why would you set cloneSet to this?

**Comment by riverzhang** [comment]
> Generally, only job Pods will set restartPolicy to Never or OnFailure. Why would you set cloneSet to this?
If the container is abnormal, it is always trying to restart. I think we can stop the restart and terminate the deployment of the application. Otherwise, users may think that they are still trying through our cicid.

**Comment by riverzhang** [comment]
If the container is abnormal, it is always trying to restart. I think we can stop the restart and terminate the deployment of the application. Otherwise, users may think that they are still trying through our cicid.
