### ISSUE TITLE
[feature request] 垂直调整业务容器的资源

### ISSUE THREAD

**Issue by FengyunPan2** [openkruise/kruise#1130]
**What would you like to be added**:
1. 不重建pod，可以重建container，修改container的资源；
2.不重建pod也不重建container，直接修改container的资源；

**Why is this needed**:
重建会带来调度、网络、volume、镜像等方面的负担，影响调整业务容器资源的速度；
垂直调整资源，可以让业务容器无感知k8s的影响，几乎没有代价；

**Comment by zmberg** [comment]
这个issue提到kruise估计解决不了，k8s apiserver会对修改 container resources的请求直接拒绝掉。

**Comment by FengyunPan2** [comment]
> 

比如通过annotation，label等方式，不直接修改containe spec。或者其他思路

**Comment by FillZpp** [comment]
Not sure when https://github.com/kubernetes/kubernetes/pull/102884 could be merged.

**Comment by FengyunPan2** [comment]
> Not sure when [kubernetes/kubernetes#102884](https://github.com/kubernetes/kubernetes/pull/102884) could be merged.
Following [discussion in Slack](https://kubernetes.slack.com/archives/C2C40FMNF/p1659351363699209) the release team is REJECTING this exception request.
已经关注这两个pr很久了，这么多个版本过去了，pr还是不被merged； https://github.com/kubernetes/kubernetes/pull/102884 and https://github.com/kubernetes/autoscaler/issues/5046
