### ISSUE TITLE
[BUG] StatefulSet在开启并发模式下，scaleStrategy.maxUnavailable设置为100%会有问题

### ISSUE THREAD

**Issue by ivanszl** [openkruise/kruise#1134]
**What happened**:
设置sts的spec.podManagementPolicy = Parallel
spec.scaleStrategy.maxUnavailable = 100%
由于修改sts的模版，导致Pod启动不了，状态一直处于pending，后续重新修改会卡住

**What you expected to happen**:
重新修改后会作用于所有的Pod，可以快速修复业务服务

**How to reproduce it (as minimally and precisely as possible)**:
这个是大体调整的代码：https://github.com/ivanszl/kruise/commit/27880d1dd588c3610eda5777daa640b263cde7ec
**Anything else we need to know?**:

**Environment**:
- Kruise version:
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Others:

**Comment by zmberg** [comment]
thanks, i will take a look at this pr.

**Comment by zmberg** [comment]
https://github.com/openkruise/kruise/pull/1136

**Comment by furykerry** [comment]
#1136 fix this issue
