### ISSUE TITLE
[BUG] upgrade always get error log "has different plain hash with spec xxxx != xxxx"

### ISSUE THREAD

**Issue by frylion007** [openkruise/kruise#1137]
kruise asts upgrade always tell me like below:

W1129 09:39:58.946094       1 inplace_update_defaults.go:456] Find container nginx-test-sidecar in runtime-container-meta for Pod default/nginx-test-1 has different plain hash with spec 249708719 != 1328176414
W1129 09:39:58.946224       1 inplace_update_defaults.go:456] Find container nginx-test-sidecar in runtime-container-meta for Pod default/nginx-test-1 has different plain hash with spec 249708719 != 1328176414
W1129 09:39:58.946329       1 inplace_update_defaults.go:456] Find container nginx-test-sidecar in runtime-container-meta for Pod default/nginx-test-1 has different plain hash with spec 249708719 != 1328176414

pod annatation info maybe not update or  I use in wrong way?

**Comment by zmberg** [comment]
Can you show the cloneSet and pod yaml?

**Comment by zmberg** [comment]
@frylion007 Here are some logs of the in-place upgrade process, it is normal.
