### ISSUE TITLE
[feature request] Is there any recommended way of replacing selected pods safely in CloneSet？

### ISSUE THREAD

**Issue by abracadabra-aaa** [openkruise/kruise#1139]
**What would you like to be added**: 
Just an idea expecting for discussing. I am finding a way to replace some selected pods safely, which means it should scale up first, and then delete selective pods while every pod scaled up just now is available. The first method I can figure out is changing labels of the pods to avoid the matching of workloads' label selector, at the same time they should be matched by the Service. This is compatible for other workloads such as Deployment. Another way is to modify replicas dynamically, increase first and then decrease for example. This way will be complex and uncontrollable combining pod autoscaling. Also I learn the feature "Selective Pod deletion" of the CloneSet which will delete the pod before creating a new one if replicas is not modified, it is not easy to be used in pods safely replacement. So Is there any recommended way of replacing selected pods safely in CloneSet or other similar workloads？

**Why is this needed**:
Sometimes we hope for replacing the selective pod by new one (same content), considering high availability of the service we prefer an increasing-before-decreasing method. Using rolling update way to replace is too far from elegance.

**Comment by zmberg** [comment]
I think you can configure as follows:
```
spec:
  scaleStrategy:
    podsToDelete:
    - sample-28p44
    - sample-ptg5f
  minReadySeconds: 60
  updateStrategy:
    maxSurge: 1
    maxUnavailable: 0
```
maxSurge=1 and maxUnavailable=0 are guaranteed to be created first and then deleted. minReadySeconds=60 is guaranteed to the new pods is available.

**Comment by abracadabra-aaa** [comment]
It seems like a great way of combining these strategies. Thanks a lot.
