### ISSUE TITLE
[BUG] "no kind is registered for the type v1alpha1.SidecarSet in scheme" when use func runtime.Encode

### ISSUE THREAD

**Issue by zerunhu** [openkruise/kruise#1143]
**What happened**:
https://github.com/openkruise/kruise/blob/master/pkg/control/sidecarcontrol/history_control.go#L110
The code in this snippet produced an error "no kind is registered for the type v1alpha1.SidecarSet in scheme "pkg/runtime/scheme.go:100", i understand is that the SidecarSet is not registered in the scheme, I looked at [main.go](https://github.com/openkruise/kruise/blob/master/main.go#L64) and [apis/app/v1alpha1/sidecarset_type.go](https://github.com/openkruise/kruise/blob/master/apis/apps/v1alpha1/sidecarset_types.go#L322) and found that it was registered.
Is there any way to solve this problem?

**Environment**:
- Kruise version:  v1.3.0
- Kubernetes version (use `kubectl version`): v1.18

**Comment by zmberg** [comment]
@zerunhu Did you see this error in the kruise-manager log? Can you directly list the relevant logs?

**Comment by zerunhu** [comment]
> @zerunhu Did you see this error in the kruise-manager log? Can you directly list the relevant logs?

"no kind is registered for the type v1alpha1.SidecarSet in scheme "pkg/runtime/scheme.go:100" is the controller log
```
patchCodec = scheme.Codecs.LegacyCodec(appsv1alpha1.SchemeGroupVersion)
```
the scheme.Codecs is k8s default Codecs, does not contain SidecarSet
Did I change the code somewhere to cause this?

**Comment by veophi** [comment]
> > @zerunhu Did you see this error in the kruise-manager log? Can you directly list the relevant logs?
> 
> "no kind is registered for the type v1alpha1.SidecarSet in scheme "pkg/runtime/scheme.go:100" is the controller log
> 
> ```
> patchCodec = scheme.Codecs.LegacyCodec(appsv1alpha1.SchemeGroupVersion)
> ```
> 
> the scheme.Codecs is k8s default Codecs, does not contain SidecarSet Did I change the code somewhere to cause this?

@zerunhu  Did you delete this line? 
https://github.com/openkruise/kruise/blob/a0659ec836aa4858604240765e93ccb22042c106/pkg/control/sidecarcontrol/history_control.go#L43

**Comment by veophi** [comment]
@zerunhu SidecarSet is registered to runtime.Scheme in [this line](https://github.com/openkruise/kruise/blob/a0659ec836aa4858604240765e93ccb22042c106/main.go#L66).

**Comment by zerunhu** [comment]
> @zerunhu SidecarSet is registered to runtime.Scheme in [this line](https://github.com/openkruise/kruise/blob/a0659ec836aa4858604240765e93ccb22042c106/main.go#L66).

Thanks, I made a mistake in this line of registration
