### ISSUE TITLE
[feature request] Daemonset with restartPolicy

### ISSUE THREAD

**Issue by Shubhamurkade** [openkruise/kruise#1148]
**What would you like to be added**: A new field called as _restartPolicy_ for a daemonset spec. _OnFailure_ should be allowed as a value for it.

**Why is this needed**:
1. I would like to have a daemonset that doesn't keep restarting containers on their successful completion
2. The field _restratPolicy_ is currently allowed for a pod spec but for daemonset this field can have only _Always_ as the possible value.

PS: I tried modifying the daemonset controller code to allow _OnFailure_ as a possible value for _restartPolicy_ in a daemonset and it seems to be working. If this feature makes sense then please let me know so that I can raise a PR.

**Comment by zmberg** [comment]
@Shubhamurkade Why you need restartPolicy=OnFailure in DaemonSet? If you need pod that doesn't keep restarting containers on their successful completion, you can see broadcastJob https://openkruise.io/docs/user-manuals/broadcastjob.

**Comment by Shubhamurkade** [comment]
@zmberg Thanks for the info!
