### ISSUE TITLE
[BUG] ClonSet Duplicate document titles

### ISSUE THREAD

**Issue by newhans** [openkruise/kruise#1169]
https://openkruise.io/docs/user-manuals/cloneset/

There are two "Scale features" subheadings in both the Chinese and English versions of the document

**Comment by zmberg** [comment]
@newhans tks for this. Can you fix it and remove the second "Scale features" subheading in https://github.com/openkruise/openkruise.io

**Comment by fengshunli** [comment]
see https://github.com/openkruise/openkruise.io/pull/92 @zmberg
