### ISSUE TITLE
kruise除了helm容器安装，还有有二进制安装方式吗？

### ISSUE THREAD

**Issue by dmulizhihui** [openkruise/kruise#1176]
kruise除了helm容器安装，还有有二进制安装方式吗？

基于特殊的业务场景，需要把kruise 和 k8s 控制面一起二进制安装。
求答复！

**Comment by zmberg** [comment]
二进制安装？ 容器不能吗？ make build可以打出二进制来。

**Comment by diannaowa** [comment]
Run kruise out of Kubernetes cluster?

**Comment by dmulizhihui** [comment]
已解决，控制面安装CRD即可；

从 Windows 版邮件发送

发件人: liuzhenwei
发送时间: 2023年2月28日 0:06
收件人: openkruise/kruise
抄送: dmulizhihui; Author
主题: Re: [openkruise/kruise] kruise除了helm容器安装，还有有二进制安装方式吗？ (Issue #1176)

Run kruise out of Kubernetes cluster?
