### ISSUE TITLE
[docs request] kruise install with helm

### ISSUE THREAD

**Issue by hellolijj** [openkruise/kruise#118]
**What would you like to be added**:

docs request: kruise install with helm 

**Why is this needed**:

It is convient to install `kruise`  with helm [charts](https://developer.aliyun.com/hub/detail?spm=a2c6h.12873679.0.0.74e51107atHbj2&name=kruise&version=0.1.0#/?_k=up9kfg).

**Comment by Fei-Guo** [comment]
/assign @hellolijj 

As we discussed offline, we need to resolve the CRD yaml version problem in Helm chart before adding the the link in README.

**Comment by hellolijj** [comment]
> /assign @hellolijj
> 
> As we discussed offline, we need to resolve the CRD yaml version problem in Helm chart before adding the the link in README.

@Fei-Guo 

How about we make a folder named helm? it contains installed yaml file. then it use as follows?

```
$ git clone https://github.com/openkruise/kruise.git
$ cd kruise/helm
$ helm install ./
```

**Comment by hellolijj** [comment]
or we can update helm repo as kruise release?

**Comment by Fei-Guo** [comment]
One problem is that you allow user to configure image version in helm chart. Then using per release directory cannot help solving the version problem, unless you disallow this option
"manager.image.tag" 

I am ok with adding a helm directory in kruise repo and keep it updated for every release.
