### ISSUE TITLE
国内阿里云镜像无法拉取

### ISSUE THREAD

**Issue by mooncake020** [openkruise/kruise#1181]
**What happened**: 安装文档内国内阿里云镜像无法拉取；另外安装脚本内的...是几个意思？
$ helm install kruise https://... --set  manager.image.repository=openkruise-registry.cn-shanghai.cr.aliyuncs.com/openkruise/kruise-manager
这样对新人不太友好吧？

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kruise version:
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Others:

**Comment by zmberg** [comment]
@mooncake020 抱歉，这个版本没有同步，已经同步了。再试试，有什么问题随时沟通。
