### ISSUE TITLE
[BUG] Pod hang in PreparingUpdate state

### ISSUE THREAD

**Issue by shiyan2016** [openkruise/kruise#1183]
**What happened**:
When inplace update, the partition is set to replicas-1. When one pod is already in PreparingUpdate state, an old pod is reset at this time, and the newly generated instance will be the new version. While the PreparingUpdate pod will always be stuck at this time. Because the partition has been satisfied, but at this time the PreparingUpdate pod may be the flow has been pulled out, which will lead to a decrease in available instances.

**What you expected to happen**:
The newly created pod should be old revision pod to ensure cluster availability.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Need also pay attention to Updating state pod.

**Environment**:
- Kruise version:
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Others:

**Comment by zmberg** [comment]
@shiyan2016 Can you fix this bug?

**Comment by zhouguangming** [comment]
Any update?  Hope this issue will be fixed 🙏
