### ISSUE TITLE
new node auto download base image

### ISSUE THREAD

**Issue by 1054518207** [openkruise/kruise#1217]
Hi, I just want to know when a new node joins cluster, if the node would download base images pre-downloaded on other nodes automatically?

**Comment by zmberg** [comment]
@1054518207 Yes, you can use the [ImagePullJob](ImagePullJob) to pre-download image on new node.

**Comment by 1054518207** [comment]
> @1054518207 Yes, you can use the [ImagePullJob](ImagePullJob) to pre-download image on new node.

Do you mean that I need to manually create an ImagePullJob containing the base images to trigger the pre-download function, instead of the node automatically obtaining the list of base images from other nodes in cluster to download the base images?
