### ISSUE TITLE
[feature request] Optimize UnitedDeployment replicas settings

### ISSUE THREAD

**Issue by veophi** [openkruise/kruise#1220]
**What would you like to be added**:
Currently, UnitedDeployment requires the sum of `subsets[x].replicas` must equal to `spec.replicas`. Actually, it is very clumsy.

We expect that：
- If `spec.replicas` is not set (`nil`),  `subsets[i]` just follows `subsets[i].replicas` (should validate all of subsets replicas are not `nil`);
- If `spec.replicas` is set (not `nil`), we should allow at most **ONE** subset replicas is `nil`, and it should equals to `spec.replicas - <sum of other subset replicas>`;

**Comment by y-ykcir** [comment]
I want to try this, can you assign this to me?

**Comment by y-ykcir** [comment]
@veophi Since `Subsets[i].replicas` can be set to a percentage, if `spec.replicas` is not set (`nil`), should we not allow `Subsets[i].replicas` to be set to a percentage?

**Comment by y-ykcir** [comment]
@veophi I'm sorry to ask another question. At which stage should we fill in values that have not been set? Reconcile or mutate

**Comment by y-ykcir** [comment]
@veophi I browsed the code [here](https://github.com/openkruise/kruise/blob/fa653fe417ab8703347eb3d6542afd74fa5622cc/pkg/controller/uniteddeployment/allocator.go#L168), and it shows that all subsets which are not set replicas will be averagely allocated by the rest replicas, this means that the current logic allows **more than two** `subset.replicas` to be unset. Should we change this logic to only allow **at most ONE** subset replicas is `nil`? If so, the code for these average logic may need to be modified. PTAL, thanks.

**Comment by veophi** [comment]
> @veophi Since `Subsets[i].replicas` can be set to a percentage, if `spec.replicas` is not set (`nil`), should we not allow `Subsets[i].replicas` to be set to a percentage?

No, we should reject this configurations

**Comment by veophi** [comment]
> @veophi I browsed the code [here](https://github.com/openkruise/kruise/blob/fa653fe417ab8703347eb3d6542afd74fa5622cc/pkg/controller/uniteddeployment/allocator.go#L168), and it shows that all subsets which are not set replicas will be averagely allocated by the rest replicas, this means that the current logic allows **more than two** `subset.replicas` to be unset. Should we change this logic to only allow **at most ONE** subset replicas is `nil`? If so, the code for these average logic may need to be modified. PTAL, thanks.

@y-ykcir Sorry, I didn't notice this code before. I think the logic of this code is reasonable and doesn't need any modification. What do you think?

**Comment by y-ykcir** [comment]
> > @veophi I browsed the code [here](https://github.com/openkruise/kruise/blob/fa653fe417ab8703347eb3d6542afd74fa5622cc/pkg/controller/uniteddeployment/allocator.go#L168), and it shows that all subsets which are not set replicas will be averagely allocated by the rest replicas, this means that the current logic allows **more than two** `subset.replicas` to be unset. Should we change this logic to only allow **at most ONE** subset replicas is `nil`? If so, the code for these average logic may need to be modified. PTAL, thanks.
> 
> @y-ykcir Sorry, I didn't notice this code before. I think the logic of this code is reasonable and doesn't need any modification. What do you think?

@veophi I think if spec.replicas is set, the current logic of averaging may be more reasonable. Additionally, it seems that the original logic did not mention the situation where spec.replicas was not set as mentioned in the issue, but instead defaulted to 1. Maybe we can add optimization for this situation?

**Comment by veophi** [comment]
> I think if spec.replicas is set, the current logic of averaging may be more reasonable. Additionally, it seems that the original logic did not mention the situation where spec.replicas was not set as mentioned in the issue, but instead defaulted to 1. Maybe we can add optimization for this situation?

@y-ykcir I agree.
