### ISSUE TITLE
[BUG] 使用sidecarset引入projected的serviceAccountToken类型的volume报错

### ISSUE THREAD

**Issue by zhaoxuechao01** [openkruise/kruise#1231]
**What happened**:
  - name: istio-token
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          audience: istio-ca
          expirationSeconds: 43200
          path: istio-token

<img width="318" alt="图片" src="https://user-images.githubusercontent.com/97726999/226564226-9c9a14cf-e935-4298-8688-890a24aeb570.png">

<img width="1433" alt="图片" src="https://user-images.githubusercontent.com/97726999/226564137-8390f768-a5b1-4ea9-8d70-fab7dc1c5984.png">

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kruise version:
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Others:

**Comment by zmberg** [comment]
This can be solved by adding a default 'serviceAccountName' to [the code](https://github.com/openkruise/kruise/blob/master/pkg/webhook/sidecarset/validating/sidecarset_create_update_handler.go#L284). For community documents please refer to: https://kubernetes.io/docs/concepts/storage/projected-volumes/#serviceaccounttoken .

@zhaoxuechao01 Can you submit the fix pr?
