### ISSUE TITLE
[BUG]  pr1197 拓扑功能不符合预期

### ISSUE THREAD

**Issue by Mc7GK** [openkruise/kruise#1234]
(1)当预期总数=当前pod数时 可用区预期数相反。
![image](https://user-images.githubusercontent.com/46585627/227415091-4c288c32-dd67-4b51-849b-cb85c1a30a58.png)
(2)当预期大于/小于 当前pod数时，会平分pod到两个可用区
![image](https://user-images.githubusercontent.com/46585627/227415570-6e22bfce-d3ec-49f4-8354-1118c6319381.png)

**Comment by veophi** [comment]
@Mc7GK  能看一下你 kruise pod 的启动命令么？感觉像是 WorkloadSpread 这个 feature-gate 没打开

**Comment by veophi** [comment]
fixed
