### ISSUE TITLE
webhook的判断逻辑

### ISSUE THREAD

**Issue by dsxing** [openkruise/kruise#1236]
**What happened**:
使用kruise干扰了所有pod的创建,
https://github.com/openkruise/kruise/blob/master/pkg/webhook/pod/mutating/pod_readiness.go#L33  为什么这里的判断是 &&；我理解是不是应该为 || ，含义是只有featuregate打开并且是kruise创建的pod才做操作，如果featuregate关闭**或者**不是kruise创建的pod就skip

**What you expected to happen**:
kruise只作用于kruise创建的pod

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kruise version:1.3.0
- Kubernetes version (use `kubectl version`):1.24
- Install details (e.g. helm install args):helm
- Others:

**Comment by dsxing** [comment]
@FillZpp

**Comment by zmberg** [comment]
KruisePodReadinessGate 这个feature-gate 默认是关闭的，你这边是打开了吗？

**Comment by zmberg** [comment]
@dsxing 这个字段是跟容器重启能力相关的，所以，它不见得一定要 kruise 的Pod。Deployment的Pod也可以使用这个能力的

**Comment by dsxing** [comment]
谢谢解答。请教另外一个问题，webhook(mutating和validating)能否只处理kruise 的Pod？

**Comment by zmberg** [comment]
@dsxing 不是的，所有的Pod都可以的。
