### ISSUE TITLE
Install kubebuilder before running test by makefile

### ISSUE THREAD

**Issue by wu8685** [openkruise/kruise#124]
In order to use controller-runtime test framework, we should install kubebuilder before running test.

**Comment by FillZpp** [comment]
@wu8685 There is no need to install kubebuilder for running test. Just `make test` is fine.

**Comment by wu8685** [comment]
Without kubebuilder installed, it is not able to run kubebuilder generated test case. 
Additionally, it is a convenient way to build up a test environment, by which we can test our codes better.

**Comment by Fei-Guo** [comment]
Fixed by https://github.com/openkruise/kruise/commit/fe73a2e404ccae28998eceec2874be10eb421568
