### ISSUE TITLE
[feature request] Advanced Workload pre-download image support attach metadata in ImagePullJob

### ISSUE THREAD

**Issue by zmberg** [openkruise/kruise#1240]
**What would you like to be added**:
ImagePullJob support attach metadata into cri interface, issue https://github.com/openkruise/kruise/issues/1155.

And Kruise Advanced Workload also need to support this feature, related code: https://github.com/openkruise/kruise/blob/master/pkg/util/imagejob/utilfunction/imagejob_util.go#L54

**Comment by YTGhost** [comment]
I am interested in this work, can you assign it to me?
