### ISSUE TITLE
[Feature] Optimize the situation where the ImageID remains unchanged but changing the Tag for in-place upgrades.

### ISSUE THREAD

**Issue by zmberg** [openkruise/kruise#1242]
**What happened**:
When changing the Tag for in-place upgrades, if the ImageID remains unchanged, it may cause the upgrade to be stuck and unable to complete.

**Comment by diannaowa** [comment]
I think, we can record the imageID and ContainerID in the `apps.kruise.io/inplace-update-state` when update images.  Then we can compare the ContainerID in `inplace-update-state` with the current ContainerID while the imageID remains unchanged, to determine whether the update is complete.
