### ISSUE TITLE
[BUG] kruise-daemon failed to start on macbook

### ISSUE THREAD

**Issue by iambowen** [openkruise/kruise#1245]
**What happened**:
kruise-daemon-ztfhr                          0/1     CrashLoopBackOff   19 (3m55s ago)   68m

kruise-daemon failed to start, and the following is the failed log:

```
I0407 08:24:42.006907       1 feature_gate.go:245] feature gates: &{map[]}
I0407 08:24:42.009165       1 daemon.go:99] Starting daemon on docker-desktop ...
I0407 08:24:42.306909       1 request.go:597] Waited for 91.340875ms due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/discovery.k8s.io/v1?timeout=32s
I0407 08:24:42.407699       1 request.go:597] Waited for 192.123292ms due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/discovery.k8s.io/v1beta1?timeout=32s
I0407 08:24:42.408105       1 request.go:597] Waited for 192.532167ms due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/node.k8s.io/v1beta1?timeout=32s
I0407 08:24:42.413914       1 request.go:597] Waited for 107.015291ms due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/admissionregistration.k8s.io/v1?timeout=32s
E0407 08:24:42.415328       1 factory.go:214] /hostvarrun/docker.sock exists, but not found /hostvarrun/dockershim.sock
F0407 08:24:42.415356       1 main.go:66] Failed to new daemon: failed to new runtime factory: not found container runtime sock
```

**What you expected to happen**:
it should start
**How to reproduce it (as minimally and precisely as possible)**:
use docker desktop and context switch to docker-desktop
use official guide to install opencruise
**Anything else we need to know?**:

**Environment**:
- Kruise version:  1.4.0 
- Kubernetes version (use `kubectl version`): 1.24
- Install details (e.g. helm install args): default helm install command by the guide
- Others:

**Comment by zmberg** [comment]
Because kruise daemon need connect to cri sock, you can use params **daemon.socketLocation and daemon.socketFile**, details [installation](https://openkruise.io/docs/installation).

**Comment by zmberg** [comment]
@iambowen I think there may be some problems in your environment, can you list the files under your /var/run directory?
