### ISSUE TITLE
[Issue] Pod ip is changed ?

### ISSUE THREAD

**Issue by zeminhuang** [openkruise/kruise#125]
before:
[root@k8s-master kruise]# kubectl  get pods -owide
NAME       READY   STATUS    RESTARTS   AGE     IP             NODE        NOMINATED NODE   READINESS GATES
sample-0   1/1     Running   0          5m20s   10.244.1.113   k8s-node1   <none>           1/1
sample-1   1/1     Running   0          5m37s   10.244.1.111   k8s-node1   <none>           1/1
sample-2   1/1     Running   0          5m37s   10.244.1.112   k8s-node1   <none>           1/1

[root@k8s-master kruise]# kubectl  get pod sample-0 -oyaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2019-09-09T12:26:51Z"
  generateName: sample-
  labels:
    app: sample
    controller-revision-hash: sample-55d9756b4
    statefulset.kubernetes.io/pod-name: sample-0
  name: sample-0
  namespace: default
  ownerReferences:
  - apiVersion: apps.kruise.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: sample
    uid: ea7a8c04-d2ed-11e9-860a-000c29e1052e
  resourceVersion: "1247700"
  selfLink: /api/v1/namespaces/default/pods/sample-0
  uid: 1a070092-d2fd-11e9-860a-000c29e1052e
spec:
  containers:
  - image: nginx:latest
    imagePullPolicy: Always
    name: main
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-wplr9
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: sample-0
  nodeName: k8s-node1
  priority: 0
  readinessGates:
  - conditionType: InPlaceUpdateReady
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  subdomain: fake-service
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-wplr9
    secret:
      defaultMode: 420
      secretName: default-token-wplr9
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: null
    status: "True"
    type: InPlaceUpdateReady
  - lastProbeTime: null
    lastTransitionTime: "2019-09-09T12:26:51Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2019-09-09T12:26:54Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2019-09-09T12:26:54Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2019-09-09T12:26:51Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://216437085a3dabc4ec6a5d0db6c1b0e8d77759d61a11f85154a218c91e990714
    image: **nginx:latest**
    imageID: docker-pullable://nginx@sha256:53ddb41e46de3d63376579acf46f9a41a8d7de33645db47a486de9769201fec9
    lastState: {}
    name: main
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: "2019-09-09T12:26:53Z"
  hostIP: 192.168.24.138
  phase: Running
  podIP: 10.244.1.113
  qosClass: BestEffort
  startTime: "2019-09-09T12:26:51Z"

------------------------
after:

[root@k8s-master kruise]# kubectl  get pods -owide
NAME       READY   STATUS    RESTARTS   AGE   IP             NODE        NOMINATED NODE   READINESS GATES
sample-0   1/1     Running   0          4s    10.244.1.116   k8s-node1   <none>           1/1
sample-1   1/1     Running   0          14s   10.244.1.114   k8s-node1   <none>           1/1
sample-2   1/1     Running   0          14s   10.244.1.115   k8s-node1   <none>           1/1

[root@k8s-master kruise]# kubectl  get pod sample-0 -oyaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2019-09-09T12:36:11Z"
  generateName: sample-
  labels:
    app: sample
    controller-revision-hash: sample-588f7cf4d6
    statefulset.kubernetes.io/pod-name: sample-0
  name: sample-0
  namespace: default
  ownerReferences:
  - apiVersion: apps.kruise.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: sample
    uid: ea7a8c04-d2ed-11e9-860a-000c29e1052e
  resourceVersion: "1248512"
  selfLink: /api/v1/namespaces/default/pods/sample-0
  uid: 67d1af77-d2fe-11e9-860a-000c29e1052e
spec:
  containers:
  - image: nginx:alpine
    imagePullPolicy: IfNotPresent
    name: main
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-wplr9
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: sample-0
  nodeName: k8s-node1
  priority: 0
  readinessGates:
  - conditionType: InPlaceUpdateReady
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  subdomain: fake-service
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-wplr9
    secret:
      defaultMode: 420
      secretName: default-token-wplr9
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: null
    status: "True"
    type: InPlaceUpdateReady
  - lastProbeTime: null
    lastTransitionTime: "2019-09-09T12:36:11Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2019-09-09T12:36:13Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2019-09-09T12:36:13Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2019-09-09T12:36:11Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://ff1cf915ea37f3f0efaaa0a75c9235489c8e342cb838c67f1697a1cdbf2d2795
    image: nginx:alpine
    imageID: docker-pullable://nginx@sha256:23b4dcdf0d34d4a129755fc6f52e1c6e23bb34ea011b315d87e193033bcd1b68
    lastState: {}
    name: main
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: "2019-09-09T12:36:12Z"
  hostIP: 192.168.24.138
  phase: Running
  podIP: 10.244.1.116
  qosClass: BestEffort
  startTime: "2019-09-09T12:36:11Z"

**Comment by FillZpp** [comment]
Can you show the result of these two command:
```
kubectl get controllerrevision sample-55d9756b4 -o yaml

kubectl get controllerrevision sample-588f7cf4d6 -o yaml
```

BTW, please paste your code in [markdown code block](https://www.markdownguide.org/extended-syntax/#fenced-code-blocks).

**Comment by zeminhuang** [comment]
[root@k8s-master kruise]# kubectl get controllerrevision sample-55d9756b4 -o yaml
apiVersion: apps/v1
data:
  spec:
    template:
      $patch: replace
      metadata:
        creationTimestamp: null
        labels:
          app: sample
      spec:
        containers:
        - image: nginx:latest
          imagePullPolicy: Always
          name: main
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        readinessGates:
        - conditionType: InPlaceUpdateReady
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
kind: ControllerRevision
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps.kruise.io/v1alpha1","kind":"StatefulSet","metadata":{"annotations":{},"name":"sample","namespace":"default"},"spec":{"podManagementPolicy":"Parallel","replicas":3,"selector":{"matchLabels":{"app":"sample"}},"serviceName":"fake-service","template":{"metadata":{"labels":{"app":"sample"}},"spec":{"containers":[{"image":"nginx:latest","name":"main"}],"readinessGates":[{"conditionType":"InPlaceUpdateReady"}]}},"updateStrategy":{"rollingUpdate":{"maxUnavailable":2,"podUpdatePolicy":"InPlaceIfPossible"},"type":"RollingUpdate"}}}
  creationTimestamp: "2019-09-09T10:38:09Z"
  labels:
    app: sample
    controller.kubernetes.io/hash: 55d9756b4
  name: sample-55d9756b4
  namespace: default
  ownerReferences:
  - apiVersion: apps.kruise.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: sample
    uid: ea7a8c04-d2ed-11e9-860a-000c29e1052e
  resourceVersion: "1247607"
  selfLink: /apis/apps/v1/namespaces/default/controllerrevisions/sample-55d9756b4
  uid: ea7bc601-d2ed-11e9-860a-000c29e1052e
revision: 5
------
[root@k8s-master kruise]# kubectl get controllerrevision sample-588f7cf4d6 -o yaml
apiVersion: apps/v1
data:
  spec:
    template:
      $patch: replace
      metadata:
        creationTimestamp: null
        labels:
          app: sample
      spec:
        containers:
        - image: nginx:alpine
          imagePullPolicy: IfNotPresent
          name: main
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        readinessGates:
        - conditionType: InPlaceUpdateReady
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
kind: ControllerRevision
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps.kruise.io/v1alpha1","kind":"StatefulSet","metadata":{"annotations":{},"name":"sample","namespace":"default"},"spec":{"podManagementPolicy":"Parallel","replicas":3,"selector":{"matchLabels":{"app":"sample"}},"serviceName":"fake-service","template":{"metadata":{"labels":{"app":"sample"}},"spec":{"containers":[{"image":"nginx:alpine","name":"main"}],"readinessGates":[{"conditionType":"InPlaceUpdateReady"}]}},"updateStrategy":{"rollingUpdate":{"maxUnavailable":2,"podUpdatePolicy":"InPlaceIfPossible"},"type":"RollingUpdate"}}}
  creationTimestamp: "2019-09-09T10:39:47Z"
  labels:
    app: sample
    controller.kubernetes.io/hash: 588f7cf4d6
  name: sample-588f7cf4d6
  namespace: default
  ownerReferences:
  - apiVersion: apps.kruise.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: sample
    uid: ea7a8c04-d2ed-11e9-860a-000c29e1052e
  resourceVersion: "1248421"
  selfLink: /apis/apps/v1/namespaces/default/controllerrevisions/sample-588f7cf4d6
  uid: 24b34525-d2ee-11e9-860a-000c29e1052e
revision: 6

**Comment by FillZpp** [comment]
Obviously, the `imagePullPolicy` also changed during you updated statefulset.

**Comment by zeminhuang** [comment]
i am only  modify image version , nginx:latest  modify  nginx:alpine.
[root@k8s-master kruise]# cat example-state.yaml 
apiVersion: apps.kruise.io/v1alpha1
kind: StatefulSet
metadata:
  name: sample
spec:
  replicas: 3
  serviceName: fake-service
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      readinessGates:
        - conditionType: InPlaceUpdateReady
      containers:
        - name: main
          image: **nginx:alpine**
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      podUpdatePolicy: InPlaceIfPossible
      maxUnavailable: 2
