### ISSUE TITLE
[question] 使用阿里云ASK部署的业务pod是否能够使用Kruise的原地升级能力？

### ISSUE THREAD

**Issue by ktalg** [openkruise/kruise#1252]
根据阿里云ASK（使用虚拟节点来部署pod）[文档](https://help.aliyun.com/document_detail/86366.html?spm=a2c4g.127525.0.0.2f203241AGlC0J#section-427-2sb-jfu) 描述：

> 使用限制
> 使用ASK集群前，需要注意以下使用限制：
>   不支持DaemonSet型工作负载。您可以通过将DaemonSet重新配置为Pod的Sidecar容器来运行

和Kruise[文档说明](https://openkruise.io/zh/docs/core-concepts/inplace-update/#%E4%BD%BF%E7%94%A8%E8%A6%81%E6%B1%82)

是否无法在aliyun ASK上使用kruise原地升级能力呢？当结合ASK使用Kruise时还有什么能力的缺失吗？

**Comment by furykerry** [comment]
OpenKruise DaemonSet and BroadcastJob does not works with serverless container such as ASK. Other advance workloads work just fine

**Comment by ktalg** [comment]
> OpenKruise DaemonSet and BroadcastJob does not works with serverless container such as ASK. Other advance workloads work just fine.
> 
> Since serverless container platform does not support install custom DaemonSet , kruise daemon not works with ASK, so functionality powered by Kruise daemon also not works, such as ContainerRecreateRequest, ImagepullJobs.
> 
> In addition, since DaemonSet not works on ASK, sidecar management becomes more important, and OpenKruise sidecarset can help you greatly in ASK

Thanks for the reply, just to confirm again, we only use advanced-statefulset and in-place upgrade feature, which is fully supported on ACK, right?

**Comment by furykerry** [comment]
> Thanks for the reply, just to confirm again, we only use advanced-statefulset and in-place update feature, which is fully supported on ACK, right?
advanced-statefulset and in-place update works in ASK, but the following feature not works without kruise daemon
* InPlaceUpdateEnvFromMetadata
* PreDownloadImageForInPlaceUpdate
