### ISSUE TITLE
[Feature Request] Re-tag the image pulled by ImagePullJob

### ISSUE THREAD

**Issue by lifanxi** [openkruise/kruise#1260]
**What would you like to be added**:
We need to re-tag the image after pulling the image from the image repository. Can the functionality be added to define the re-tagging rules in the ImagePullJob so the image can be re-tagged automatically after the images are downloaded successfully on the nodes? 

Another possible way to accomplish this requirement is to enable a post-download hook for the ImagePullJob, so we can write custom scripts to do the re-tag.

**Why is this needed**:

We have a  hybrid cluster in which the nodes are running on different CPU architectures. So different nodes need to download different images. But we want to use a unified image name in a Deployment so that the Pods of the Deployment can be running on any nodes. 

For example, we have:
```docker-repo.com/repo/image:v1.0-x86```
```docker-repo.com/repo/image:v1.0-aarch64```

We want different nodes to pull different images based on their architecture. Then re-tag the image to a unified name: ```docker-repo.com/repo/image:v1.0```. So we can use ```docker-repo.com/repo/image:v1.0``` in a Deployment and make sure the Pods can be launched on any nodes.

**Comment by furykerry** [comment]
it is not necessary to retag image on the node, one can build multi-arch image and pass it to k8s. 
https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

**Comment by lifanxi** [comment]
> it is not necessary to retag image on the node, one can build multi-arch image and pass it to k8s. https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

Thank for you pointing this out. Multi-arch image is not a choice for me because we are using a very old version of Docker, which does not support the ```manifest``` or ```buildx``` command. 

Actually, this is just one of the reasons why we need the re-tag feature. We have other situations in which a re-tag is needed: the images stored in the repository use hash value as their tags (and we do not have permission to control what we can store in the repository), and we want to re-tag it with a human-readable logic version number for easier use in K8s.

**Comment by lifanxi** [comment]
Based on Bi-weekly Community Meeting discussions, it seems that CRI does not have the "tag" interface, so it is difficult to implement this feature. If only implement this for Docker, it will not be a complete solution.

**Comment by zmberg** [comment]
@lifanxi I will close this issue for now, and we can communicate further when there are updates.
