### ISSUE TITLE
[BUG] sidecarSet in-place update failed

### ISSUE THREAD

**Issue by ktalg** [openkruise/kruise#1270]
**What happened**:
After changing the container image of sidecarSet, the container that has been injected is not restarted and it's image is not updated
**What you expected to happen**:
The injected container is restarted and its image becomes up to date
**How to reproduce it (as minimally and precisely as possible)**:
1. declare a SidecarSet(ss) that contains only a container with an image: `nginx`, then declare a Pod that will be injected into the side car, and subsequently see that the nginx container is injected normally
2. change the image of SidecarSet from `nginx` to `nginx:1.23` (just add a tag)
3. pod's nginx container is not restarted, and its image is not updated to `nginx:1.23` 

**Environment**:
- Kruise version: v1.2.0
- Kubernetes version (use `kubectl version`): v1.22.3
- Install details (e.g. helm install args):
- Others:

**Comment by diannaowa** [comment]
May be related to imageID,Since nginx and nginx:1.23 has the same image ID. 
You can change  the image of SidecarSet from nginx to  nginx:1.24 for test.
