### ISSUE TITLE
[BUG] Issue with invalid parallelism for ImagePullJob.

### ISSUE THREAD

**Issue by 1182986209** [openkruise/kruise#1271]
**What happened**:使用imagepulljob镜像预热功能，设置了parallelism=1，但是实际active值总是超过parallelism，不能控制并发
<img width="1713" alt="截屏2023-05-01 15 12 50" src="https://user-images.githubusercontent.com/17643681/235421255-791dcded-1520-4c52-96fd-5fcd170ec3fd.png">

**What you expected to happen**:预期active值要小于parallelism

**How to reproduce it (as minimally and precisely as possible)**

**Anything else we need to know?**:

**Environment**:
- Kruise version:1.3.0
- Kubernetes version (use `kubectl version`):v1.23.10
- Install details (e.g. helm install args):
- Others:

**Comment by 1182986209** [comment]
这个问题有人看下不

**Comment by furykerry** [comment]
@veophi PTAL

**Comment by veophi** [comment]
I cannot repeat this bug. Is it reproducible in your environment? @1182986209 
![image](https://github.com/openkruise/kruise/assets/28217554/4f37be64-0515-400d-871d-e18e5d910edd)

**Comment by 1182986209** [comment]
> I cannot repeat this bug. Is it reproducible in your environment? @1182986209 ![image](https://user-images.githubusercontent.com/28217554/242457227-4f37be64-0515-400d-871d-e18e5d910edd.png)

yes, this problem becomes very frequent. Now I have to control the selected nodes list to prevent the active value not exceed the parallelism

**Comment by zmberg** [comment]
@1182986209 Can you show the whole ImagePullJob yaml?
