### ISSUE TITLE
[QUESTION] too many open files 

### ISSUE THREAD

**Issue by ColinChamber** [openkruise/kruise#1276]
**What happened**:
 kubectl  -n kruise-system logs kruise-controller-manager-7d78fc5c97-62xwb  
```
I0507 09:19:14.058206       1 reflector.go:219] Starting reflector *v1.Job (0s) from sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:152
panic: failed to new ca-cert watcher: too many open files

goroutine 301 [running]:
github.com/openkruise/kruise/pkg/webhook/util/health.Checker.func1()
        /workspace/pkg/webhook/util/health/checker.go:117 +0x185
sync.(*Once).doSlow(0x0?, 0x0?)
        /usr/local/go/src/sync/once.go:68 +0xc2
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:59
github.com/openkruise/kruise/pkg/webhook/util/health.Checker(0xc10df924837590b9?)
        /workspace/pkg/webhook/util/health/checker.go:111 +0x5e
github.com/openkruise/kruise/pkg/webhook.Checker(0x5?)
        /workspace/pkg/webhook/server.go:137 +0x35
github.com/openkruise/kruise/pkg/webhook.WaitReady()
        /workspace/pkg/webhook/server.go:145 +0x71
main.main.func2()
        /workspace/main.go:187 +0x65
created by main.main
        /workspace/main.go:185 +0xc8a
```
![image](https://user-images.githubusercontent.com/95634254/236669843-95c56a51-d664-469f-851c-a44337a181b1.png)
![image](https://user-images.githubusercontent.com/95634254/236669900-0828e95d-42f2-4d29-8ca7-4f00a8f039bc.png)

**What you expected to happen**:
Running

**How to reproduce it (as minimally and precisely as possible)**:
just helm install and then it doesn't work.

**Anything else we need to know?**:

**Environment**:
- Kruise version: v1.4.0
- Kubernetes version (use `kubectl version`):
Client Version: v1.26.2
Kustomize Version: v4.5.7
Server Version: v1.26.1
- Install details (e.g. helm install args):
helm install kruise openkruise/kruise --version 1.4.0
- Others:
I am trying to use openkruise in minikube.
minikube version: v1.29.0

**Comment by ColinChamber** [comment]
After temporarily resolving the issue by modifying the max open file, my colleague's ulimit -n is also set to 1024, but he did not encounter this problem. It seems that there might be some deeper reasons behind it. If you have time, please help investigate this issue. Thank you for your time.

**Comment by zmberg** [comment]
This [function](https://github.com/openkruise/kruise/blob/master/pkg/webhook/util/health/checker.go#L111) will only be executed once, and I have not been able to reproduce it locally. Can you check the system to see if it is possible that other processes are consuming too much resources?

**Comment by yike21** [comment]
It's a resource exhaustion issue. Maybe you can fix it with
```shell
sysctl fs.inotify.max_user_watches=16384
sysctl -w fs.inotify.max_user_watches=100000
sysctl -w fs.inotify.max_user_instances=100000
```

**Comment by ColinChamber** [comment]
Thanks. After the cluster restart, I was also unable to reproduce it.
