### ISSUE TITLE
[feature request] can SidecarSet replace istio inject webhook entirely?

### ISSUE THREAD

**Issue by cywang1905** [openkruise/kruise#1281]
**What would you like to be added**:
Is SidecarSet now complete enough to replace istio injection webhook? Is it possible to improve the [demo doc](https://github.com/openkruise/samples/tree/master/hotupgrade) to add this piece of content? 
Also, the [docs](https://openkruise.io/zh/docs/user-manuals/sidecarset#sidecar%E7%83%AD%E5%8D%87%E7%BA%A7%E7%89%B9%E6%80%A7) says that Ali Cloud ASM has implemented hot upgrade of istio sidecar container based on SidecarSet, but the link is not working. Is there a new link or ASM has deprecated the hot upgrade capability, can you update the relevant content? 

**Why is this needed**:
As an istio user, I was researching the sidecar container hot upgrade implementation when I learned that OpenKruise SidecarSet claims to support sidecar container hot upgrade. However, when I followed the demo, I found I need to disable istio's sidecar injection webhook and using SidecarSet entirely instead.
I have doubts about the reliability of SidecarSet as a complete replacement for istio injection webhook, and would like to see demo docs that can be implemented.

Thanks a lot.

**Comment by zmberg** [comment]
@cywang1905 OpenKruise provides a general mechanism, so we do not actually provide complete documentation and implementation for Istio hot upgrades. However, you can refer to [MOSN](https://mosn.io/blog/posts/mosn-sidecarset-hotupgrade/), and Istio should have a similar implementation.
