### ISSUE TITLE
[feature request]  Sidecar terminator ignore the exit code of the sidecar container

### ISSUE THREAD

**Issue by zmberg** [openkruise/kruise#1285]
**What would you like to be added**:
OpenKruise job sidecar terminator controller watches and terminates sidecar containers for such job-type Pods when its main containers completed, details: [JobSidecarTerminator](https://openkruise.io/docs/user-manuals/jobsidecarterminator).

But, the above feature contains certain limitation of "Your sidecar container must respond the SIGTERM signal, and the entrypoint should exit 0 when received this signal." If the exit code of the sidecar container is non-zero, Job will judge the pod failure.

So i hope JobSidecarTerminator can solve the above problem and ensure that the job is completed normally even if the exit code of the sidecar container is non-zero.

**Comment by diannaowa** [comment]
There is my workaround:  [[link](https://github.com/diannaowa/kruise/commit/97dda1dc7f14342eb56c547aaed730231e99b0d9)]

@zmberg PTAL
