### ISSUE TITLE
[BUG] SidecarSet Expectations Leakage Bug.

### ISSUE THREAD

**Issue by zmberg** [openkruise/kruise#1293]
**What would you like to be added**:
If the Pod is deleted after SidecarSet Update sidecar container, SidecarSet expection may leakage, for details:
![66DA1F1F-1432-4FED-B0E6-C01650EBF37D](https://github.com/openkruise/kruise/assets/25051767/310bcfa8-db02-4067-982c-7b4e05e23680)

**Comment by wangwu50** [comment]
我正在修复这个issue

**Comment by wangwu50** [comment]
我看了下代码，想和您讨论这块逻辑我理解的对不对。
正常逻辑： 先getMatchingPods获取所有match的pod（这里过滤了删除的pod），然后进行更新updatePods操作，pod更新完会把pod name记录在updateExpectations里面。第二次Reconcile进入的时候，会调用ObserveUpdated将已经更新的pod name删除。这样SatisfiedExpectations方法就不会卡住。
出问题的逻辑：这时候如果一个pod被删除了，getMatchingPods过滤了删除的pod，删除的pod name在ObserveUpdated永远不会从updateExpectations移除，然后执行到SatisfiedExpectations就会卡住。

**Comment by wangwu50** [comment]
我初步的解决思路是这样的：找到inflightPods后，查询一下这些pod是否被删除，如果被删除，就清理updateExpectations缓存

**Comment by wangwu50** [comment]
@zmberg

**Comment by zmberg** [comment]
> 我看了下代码，想和您讨论这块逻辑我理解的对不对。 正常逻辑： 先getMatchingPods获取所有match的pod（这里过滤了删除的pod），然后进行更新updatePods操作，pod更新完会把pod name记录在updateExpectations里面。第二次Reconcile进入的时候，会调用ObserveUpdated将已经更新的pod name删除。这样SatisfiedExpectations方法就不会卡住。 出问题的逻辑：这时候如果一个pod被删除了，getMatchingPods过滤了删除的pod，删除的pod name在ObserveUpdated永远不会从updateExpectations移除，然后执行到SatisfiedExpectations就会卡住。

非常赞，就是这样的。不过解决的思路可以稍微的换一下，通过在 event handler 里面收到 pod的事件来变更 expections。可以参考一下，cloneSet的实现。
