### ISSUE TITLE
[feature request] Upgrade kruise apis version from v1alphal1 to v1beta1

### ISSUE THREAD

**Issue by zmberg** [openkruise/kruise#1297]
**What would you like to be added**:
Upgrade kruise apis version from v1alphal1 to v1beta1

**Comment by sbdtu5498** [comment]
/assign
@zmberg should we maintain backward compatibility as well or simply deprecate v1alpha1?

**Comment by maheshkasabe** [comment]
Hello @zmberg Can you assign this to me i would love to work on this one!

**Comment by ahmetb** [comment]
This would be great even though it's largely cosmetic. I think many of these APIs have been out for 4+ years, yet it's not super reassuring to integrate with v1alpha1/CloneSet when we're building workload operators at our company.
