### ISSUE TITLE
[feature request] SidecarSet灰度发布支持多个版本

### ISSUE THREAD

**Issue by Reason94** [openkruise/kruise#1327]
**What would you like to be added**:
SidecarSet当前的灰度发布updateStrategy仅支持对一个版本进行灰度，希望支持多个版本同时灰度。

**Why is this needed**:
SidecarSet的用来管理整个PaaS平台的Sidecar，该Sidecar迭代频繁时，会有多个Feature同时进行；测试验证或者上线时会产生多个版本需要灰度，当前一套SidecarSet灰度升级能力无法满足这个场景。
场景存在的必要性和通用型：新Feature来源于不同的业务方，多人开发Sidecar上线节奏不一，业务方希望自己的Fearture快速上线验证

**Comment by zmberg** [comment]
我们内部也有这个需求，不过 SidecarSet 不是集群级别的，而是 一个业务方一个，是不是就可以了？

**Comment by Reason94** [comment]
> 
业务方下面会有更细的部署粒度吗？我理解一个业务方一个需要配套paas平台自动管控SidecarSet，可以降低这个场景的灰度升级成本，但对于一些想更细粒度实现灰度场景或者SidecarSet集群管控场景还是不太够用。
另外从集群级别SidecarSet拆分为细粒度管控，需要重建Pod么？

**Comment by zmberg** [comment]
> SidecarSet灰度发布支持多个版本
支持多版本发布太复杂了，这个不好实现。

> 另外从集群级别SidecarSet拆分为细粒度管控，需要重建Pod么？
有一些 hack 的方式，如果你感兴趣可以联系我钉钉，可以搞定的。
