### ISSUE TITLE
[BUG] sidecarset container can't find the volume

### ISSUE THREAD

**Issue by jzeng4** [openkruise/kruise#1330]
**What happened**:
We are using sidecarset to inject sidecar container into the main applications. The volumes are specified in the sidecarset but the sidecarset container/init container can't find the volume.

**What you expected to happen**:
The sidecarset container should find the volumes. No errors are expected.

**How to reproduce it (as minimally and precisely as possible)**:
sidecarset volume and volume mount looks like:

     Volume Mounts:
          Mount Path:  /app-config
          Name:        app-config
          Read Only:   true
          Mount Path:  /toki-grpc-backend-lare-dir
          Name:        toki-grpc-backend-lare-dir
          Read Only:   true
          Mount Path:  /var/sidecars
          Name:        sidecar-file-sharing
          Mount Path:  /var/sidecars123
          Name:        workdir1
      Volumes:
          Host Path:
              Path:  /etc/riddler
              Type:  Directory
          Name:    riddler-certs
    ...
         Empty Dir:
         Name:  workdir1

We see the following errors:
> cloneset-controller  failed to create pod: Pod "toki-5bxzs-f48q7" is invalid: spec.initContainers[4].volumeMounts[3].name: Not found: "workdir1",

**Anything else we need to know?**:

**Environment**:
- Kruise version: 1.4.0
- Kubernetes version (use `kubectl version`):
- Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.14", GitCommit:"0f77da5bd4809927e15d1658fb4aa8f13ad890a5", GitTreeState:"clean", BuildDate:"2022-06-15T14:11:36Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.25) and server (1.21) exceeds the supported minor version skew of +/-1
- Install details (e.g. helm install args):
- Others:

**Comment by zmberg** [comment]
@jzeng4 Can you show the complete sidecarSet yaml, so i can test it on my local environment.

**Comment by jzeng4** [comment]
Name:         test-lisidecar-grid-conf-agent-dh5qg
Namespace:    
Labels:       app=toki-grpc-backend
              configTags=
              instanceDiscriminator=i002
              product=toki
              productTag=
              sidecarAppName=grid-conf-agent
              sidecarProductName=grid-conf-agent
Annotations:  configVersion: 
              fabric: corp-lca1
              version: 0.0.11
API Version:  apps.kruise.io/v1alpha1
Kind:         SidecarSet
Metadata:
  Creation Timestamp:  2023-07-12T21:41:20Z
  Generate Name:       test-lisidecar-grid-conf-agent-
  Generation:          1
  Managed Fields:
    API Version:  apps.kruise.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:configVersion:
          f:fabric:
          f:kubectl.kubernetes.io/last-applied-configuration:
          f:version:
        f:generateName:
        f:labels:
          .:
          f:app:
          f:configTags:
          f:instanceDiscriminator:
          f:product:
          f:productTag:
          f:sidecarAppName:
          f:sidecarProductName:
      f:spec:
        .:
        f:containers:
        f:initContainers:
        f:injectionStrategy:
        f:selector:
          .:
          f:matchLabels:
            .:
            f:app:
            f:configTags:
            f:instanceDiscriminator:
            f:product:
            f:productTag:
        f:updateStrategy:
          .:
          f:maxUnavailable:
          f:type:
        f:volumes:
    Manager:      k8s-deployment-operator
    Operation:    Update
    Time:         2023-07-12T21:41:20Z
    API Version:  apps.kruise.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:matchedPods:
        f:observedGeneration:
        f:readyPods:
        f:updatedPods:
    Manager:         kruise-manager
    Operation:       Update
    Time:            2023-07-12T21:43:14Z
  Resource Version:  1650014593
  UID:               1760c731-b8dd-484a-ba5c-fba2c196b978
Spec:
  Containers:
    Command:
      /bin/bash
      -c
      sleep 365d
    Env:
      Name:   MAIN_APP_NAME
      Value:  toki-grpc-backend
      Name:   MAIN_APP_INSTANCE_ID
      Value:  i002
    Image:    lca1-container-image-registry.corp.test.com:8083/lps-image/test/grid-conf-agent/grid-conf-agent:0.0.11
    Name:     grid-conf-agent
    Resources:
      Limits:
        Cpu:     2
        Memory:  750Mi
      Requests:
        Cpu:     1
        Memory:  550Mi
    Security Context:
      Run As Group:  1000015500
      Run As User:   1000015500
    Share Volume Policy:
    Upgrade Strategy:
    Volume Mounts:
      Mount Path:  /etc/riddler
      Name:        riddler-certs
      Read Only:   true
      Mount Path:  /var/sidecars
      Name:        sidecar-file-sharing
      Mount Path:  /export/content/lid/apps/grid-conf-agent/install/var
      Name:        toki-grpc-backend-lare-dir
      Sub Path:    grid-conf-agent
      Mount Path:  /export/content/lid/apps/grid-conf-agent/install/appsConfig
      Name:        app-config
      Sub Path:    grid-conf-agent
  Init Containers:
    Command:
      /bin/bash
      -c
      mkdir -p /export/content/lid/apps/grid-conf-agent/install/logs && mkdir -p /export/content/lid/apps/grid-conf-agent/install/data && chown -R 1000015500:1000015500 /export/content/lid/apps/grid-conf-agent/install/logs && chown -R 1000015500:1000015500 /export/content/lid/apps/grid-conf-agent/install/data
    Image:  lca1-container-image-registry.corp.test.com:8083/lps-image/test/grid-conf-agent/grid-conf-agent:0.0.11
    Name:   prepare-writable-volume-mounts-grid-conf-agent
    Resources:
      Limits:
        Cpu:     200m
        Memory:  32M
      Requests:
        Cpu:     200m
        Memory:  32M
    Security Context:
      Run As Group:  0
      Run As User:   0
    Share Volume Policy:
    Upgrade Strategy:
    Volume Mounts:
      Mount Path:  /export/content/lid/apps/grid-conf-agent/install/logs
      Name:        toki-grpc-backend-i002-logs
      Sub Path:    grid-conf-agent
      Mount Path:  /export/content/lid/apps/grid-conf-agent/install/data
      Name:        toki-grpc-backend-i002-data
      Sub Path:    grid-conf-agent
    Args:
      -c
      /k8s-lare request-app-cert appinfo --application grid-conf-agent --product-tag  --instance toki-grpc-backend-i002 --fabric corp-lca1 --cert-file-owner 1000015500 --cert-file-group 1000015500 --cert-dir /grid-conf-agent-lare-dir
    Command:
      /bin/bash
    Env:
      Name:   REQUESTS_CA_BUNDLE
      Value:  /etc/pki/tls/certs/ca-bundle.crt
      Name:   KUBELET_IDENTITY_KEY
      Value:  /var/run/kubelet/identity.key
      Name:   KUBELET_IDENTITY_CERT
      Value:  /var/run/kubelet/identity.cert
      Name:   KUBERNETES_CA_BUNDLE
      Value:  /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      Name:   CLUSTER_PRODUCT_TAG
      Value:  k8s-0
      Name:   SELF_POD_NAME
      Value From:
        Field Ref:
          API Version:  v1
          Field Path:   metadata.name
      Name:             SELF_POD_NAMESPACE
      Value From:
        Field Ref:
          API Version:  v1
          Field Path:   metadata.namespace
      Name:             SELF_NODE_NAME
      Value From:
        Field Ref:
          API Version:  v1
          Field Path:   spec.nodeName
      Name:             SELF_POD_IP
      Value From:
        Field Ref:
          API Version:  v1
          Field Path:   status.podIP
      Name:             SELF_POD_UID
      Value From:
        Field Ref:
          API Version:  v1
          Field Path:   metadata.uid
      Name:             FABRIC
      Value:            corp-lca1
    Image:              lca1-container-image-registry.corp.test.com:8083/lps-image/test/go-lare-cli/k8s-lare:0.0.10
    Name:               grid-conf-agent-get-grestin-certs
    Resources:
      Limits:
        Memory:  1G
      Requests:
        Cpu:     500m
        Memory:  1G
    Security Context:
      Run As Group:  0
      Run As User:   0
    Share Volume Policy:
    Upgrade Strategy:
    Volume Mounts:
      Mount Path:  /etc/riddler
      Name:        riddler-certs
      Read Only:   true
      Mount Path:  /grid-conf-agent-lare-dir
      Name:        toki-grpc-backend-lare-dir
      Sub Path:    grid-conf-agent
      Mount Path:  /app-config
      Name:        app-config
      Sub Path:    grid-conf-agent
      Mount Path:  /var/run/lipki/pki-agent.sock
      Name:        pki-agent-sock
      Read Only:   true
    Args:
      -f
      corp-lca1
      --debug
      --root
      /export/content/lid/apps/grid-conf-agent/install
      --env-cfg-path
      /grid-conf-agent-lare-dir/env.cfg
      --env-kv-path
      /grid-conf-agent-lare-dir/env_conf.sh
      --owner-uid
      1000015500
      --owner-gid
      1000015500
      --identity-loc
      /grid-conf-agent-lare-dir
      --identity-cert-kind
      kubernetes
      --product
      grid-conf-agent
      --product-tag
      
      --application
      grid-conf-agent
      --instanceid
      toki-grpc-backend-i002
      --product-version
      0.0.11
      --service-name
      grid-conf-agent
      --slice-id
      5c86fc3c-2dce-48ea-aabf-40dd62446d8c
      --app-instance-json-path
      /grid-conf-agent-lare-dir/application-instance.json
      --app-config-remote-url
      https://artifactory.corp.test.com:8083/artifactory/release/com/test/grid-conf-agent/config/app/grid-conf-agent-corp-lca1/0.0.11-v0.20.0/grid-conf-agent-corp-lca1-0.0.11-v0.20.0.tgz
      --app-config-dest-loc
      /app-config
      --context-path
      
      --action
      gen-env-vars,create-app-instance-json,prepare-cfgs
    Command:
      /usr/local/test/bin/configure-app-runtime
    Env:
      Name:   REQUESTS_CA_BUNDLE
      Value:  /etc/pki/tls/certs/ca-bundle.crt
      Name:   KUBELET_IDENTITY_KEY
      Value:  /var/run/kubelet/identity.key
      Name:   KUBELET_IDENTITY_CERT
      Value:  /var/run/kubelet/identity.cert
      Name:   KUBERNETES_CA_BUNDLE
      Value:  /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      Name:   CLUSTER_PRODUCT_TAG
      Value:  k8s-0
      Name:   SELF_POD_NAME
      Value From:
        Field Ref:
          API Version:  v1
          Field Path:   metadata.name
      Name:             SELF_POD_NAMESPACE
      Value From:
        Field Ref:
          API Version:  v1
          Field Path:   metadata.namespace
      Name:             SELF_NODE_NAME
      Value From:
        Field Ref:
          API Version:  v1
          Field Path:   spec.nodeName
      Name:             SELF_POD_IP
      Value From:
        Field Ref:
          API Version:  v1
          Field Path:   status.podIP
      Name:             SELF_POD_UID
      Value From:
        Field Ref:
          API Version:  v1
          Field Path:   metadata.uid
      Name:             FABRIC
      Value:            corp-lca1
    Image:              lca1-container-image-registry.corp.test.com:8083/lps-image/test/configure-app-runtime/configure-app-runtime:0.0.46
    Name:               grid-conf-agent-configure-app-runtime
    Resources:
      Limits:
        Memory:  1G
      Requests:
        Cpu:     500m
        Memory:  1G
    Share Volume Policy:
    Upgrade Strategy:
    Volume Mounts:
      Mount Path:  /etc/riddler
      Name:        riddler-certs
      Read Only:   true
      Mount Path:  /grid-conf-agent-lare-dir
      Name:        toki-grpc-backend-lare-dir
      Sub Path:    grid-conf-agent
      Mount Path:  /app-config
      Name:        app-config
      Sub Path:    grid-conf-agent
      Mount Path:  /var/sidecars
      Name:        sidecar-file-sharing
    Command:
      /bin/bash
      -c
      mkdir -p /var/sidecars/cert/grid-conf-agent && mkdir -p /var/sidecars/cfg/grid-conf-agent && mkdir -p /var/sidecars/uds/grid-conf-agent;setfacl -d -m g:1000015500:6 /var/sidecars/uds/grid-conf-agent;cp /app-config/*/*.cfg /var/sidecars/cfg/grid-conf-agent/;cp /toki-grpc-backend-lare-dir/application-*.json /toki-grpc-backend-lare-dir/env* /var/sidecars/cfg/grid-conf-agent/;cp /toki-grpc-backend-lare-dir/identity.* /var/sidecars/cert/grid-conf-agent/;chmod 400 /var/sidecars/cert/grid-conf-agent/identity.cert && chmod 400 /var/sidecars/cfg/grid-conf-agent/sidecar.cfg;chmod 500 /var/sidecars/cert/grid-conf-agent && chmod 500 /var/sidecars/cfg/grid-conf-agent && chmod 777 /var/sidecars/uds/grid-conf-agent;chown -R 1000015500 /var/sidecars/cert/grid-conf-agent && chown -R 1000015500 /var/sidecars/cfg/grid-conf-agent && chown -R 1000015500 /var/sidecars/uds/grid-conf-agent;
    Image:  lca1-container-image-registry.corp.test.com:8083/lps-image/test/grid-conf-agent/grid-conf-agent:0.0.11
    Name:   configure-sidecar-file-sharing
    Resources:
    Security Context:
      Run As Group:  0
      Run As User:   0
    Share Volume Policy:
    Upgrade Strategy:
    Volume Mounts:
      Mount Path:  /app-config
      Name:        app-config
      Read Only:   true
      Mount Path:  /toki-grpc-backend-lare-dir
      Name:        toki-grpc-backend-lare-dir
      Read Only:   true
      Mount Path:  /var/sidecars
      Name:        sidecar-file-sharing
      Mount Path:  /var/sidecars123
      Name:        workdir1
  Injection Strategy:
  Selector:
    Match Labels:
      App:                     toki-grpc-backend
      Config Tags:             
      Instance Discriminator:  i002
      Product:                 toki
      Product Tag:             
  Update Strategy:
    Max Unavailable:  1
    Type:             RollingUpdate
  Volumes:
    Host Path:
      Path:  /etc/riddler
      Type:  Directory
    Name:    riddler-certs
    Empty Dir:
    Name:  app-config
    Empty Dir:
      Medium:  Memory
    Name:      toki-grpc-backend-lare-dir
    Empty Dir:
    Name:  sidecar-file-sharing
    Host Path:
      Path:  /var/run/lipki/pki-agent.sock
      Type:  Socket
    Name:    pki-agent-sock
    Empty Dir:
    Name:  app-conf-private
    Empty Dir:
    Name:  libexec
    Empty Dir:
    Name:  workdir
    Empty Dir:
    Name:  workdir1
    Host Path:
      Path:  /export/content/lid/logs/toki-grpc-backend/i002
      Type:  DirectoryOrCreate
    Name:    toki-grpc-backend-i002-logs
    Host Path:
      Path:  /export/content/data/toki-grpc-backend/i002/data
      Type:  DirectoryOrCreate
    Name:    toki-grpc-backend-i002-data
Status:
  Matched Pods:         0
  Observed Generation:  1
  Ready Pods:           0
  Updated Pods:         0
Events:                 <none>

**Comment by jzeng4** [comment]
the other volumes are ok because they were also defined in the main pod. The volume "workdir1" is only defined in sidecarsets. Then it can't be found when creating pod:

>cloneset-controller failed to create pod: Pod "toki-5bxzs-f48q7" is invalid: spec.initContainers[4].volumeMounts[3].name: Not found: "workdir1",

**Comment by zmberg** [comment]
> the sidecarset is generated by our code and i used "kubeclt describe sidecarsets" to get: https://justpaste.it/8a030

Can you use 'kubectl get sidecarsets xxx -oyaml' to get?

**Comment by jzeng4** [comment]
Cloneset: https://justpaste.it/2d71c
Sidecarset: https://justpaste.it/d2yri

Please help thank you!

**Comment by jzeng4** [comment]
@zmberg I think I found the problem. And sorry, our cluster is using the very old verion.

The init container volume is not supported until v1.1.0:
https://github.com/openkruise/kruise/releases/tag/v1.1.0
