### ISSUE TITLE
[feature request] Consider exposing node labels via downward api

### ISSUE THREAD

**Issue by xvdy** [openkruise/kruise#1333]
**What would you like to be added**:
Consider exposing node labels via downward api #40610

**Why is this needed**:
对于跨多个 az 的集群，pod 能够感知到目前自己在哪个 az，期望是将 az 信息通过环境变量暴露，kruise 是否有办法支持这样的能力？
对标这个 issue：https://github.com/kubernetes/kubernetes/issues/40610

**Comment by zmberg** [comment]
@xvdy 这个能力Kruise 支持不了昂。

**Comment by furykerry** [comment]
maybe we could populate pod labels using node labels in podmarker
