### ISSUE TITLE
[BUG] daemon not support docker cri-dockerd

### ISSUE THREAD

**Issue by beastpu** [openkruise/kruise#1337]
**What happened**:
kruise daemon start failed
1 factory.go:214] /hostvarrun/docker.sock exists, but not found /hostvarrun/dockershim.sock

**What you expected to happen**:
I have installed Kubernetes using RKE1, which only supports the Docker runtime. However, the version I installed (1.26) does not support dockershim, but RKE1 installed cri-dockerd as an alternative solution. I am considering using cri-dockerd as a replacement for dockershim.

**Anything else we need to know?**:

**Environment**:
- Kruise version: 1.4.0
- Kubernetes version (use `kubectl version`): 1.26.0

**Comment by zzr93** [comment]
Here is a workaround before this PR merged ==>
helm install kruise openkruise/kruise --version 1.5.0 --set daemon.socketFile="cri-dockerd.sock"

**Comment by beastpu** [comment]
resolved
