### ISSUE TITLE
how to config external api-server address？

### ISSUE THREAD

**Issue by jinyuchen724** [openkruise/kruise#134]
hi:
    I changed install config like this:

spec:
      containers:
        - command:
            - /manager
          args:
            - "--metrics-addr=127.0.0.1:8080"
            - "--logtostderr=true"
            - "--v=4"
            - "--master=http://10.39.128.35:80"
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SECRET_NAME
              value: kruise-webhook-server-secret
            - name: KUBERNETES_SERVICE_HOST
              value: 10.39.128.35
            - name: KUBERNETES_SERVICE_PORT
              value: "80"

**But i got this error:**

`I0923 12:19:52.712803       1 main.go:54] entrypoint "level"=0 "msg"="setting up client for manager"  
I0923 12:19:52.713181       1 main.go:62] entrypoint "level"=0 "msg"="setting up manager"  
E0923 12:19:52.715201       1 :0] kubebuilder/manager "msg"="Failed to get API Group-Resources" "error"="Get https://10.39.128.35:80/api?timeout=32s: http: server gave HTTP response to HTTPS client"  
E0923 12:19:52.715226       1 main.go:74] entrypoint "msg"="unable to set up overall controller manager" "error"="Get https://10.39.128.35:80/api?timeout=32s: http: server gave HTTP response to HTTPS client"  `

why I use 80 port，but manager still use "https" to access api-server?How can i do it？
thank you!

**Comment by Fei-Guo** [comment]
You have two approaches to connect APIServer from controller manager:
- InCluster Mode (default):
  In this case, the cluster config only supports "https:"
https://github.com/kubernetes/client-go/blob/2bd34d193bacaec5c976bef54bbc1f80939b81ec/rest/config.go#L435
  It is hardcoded to avoid security vulnerability. 
- kubeconfig mode (can be out of cluster )
```
// If --kubeconfig is set, will use the kubeconfig file at that location.  Otherwise will assume running
// in cluster and use the cluster provided kubeconfig.
```
if you start the controller manager by specifying a kubeconfig file, it will use the server url provided by the kubeconfig in cluster map. 

In your case, by adding `--master` option will not work. You can try the kubeconfig mode by
providing a proper kubeconfig file to start the controller manager.

**Comment by jinyuchen724** [comment]
> You have two approaches to connect APIServer from controller manager:
> 
> * InCluster Mode (default):
>   In this case, the cluster config only supports "https:"
>   https://github.com/kubernetes/client-go/blob/2bd34d193bacaec5c976bef54bbc1f80939b81ec/rest/config.go#L435
>   It is hardcoded to avoid security vulnerability.
> * kubeconfig mode (can be out of cluster )
> 
> ```
> // If --kubeconfig is set, will use the kubeconfig file at that location.  Otherwise will assume running
> // in cluster and use the cluster provided kubeconfig.
> ```
> 
> if you start the controller manager by specifying a kubeconfig file, it will use the server url provided by the kubeconfig in cluster map.
> 
> In your case, by adding `--master` option will not work. You can try the kubeconfig mode by
> providing a proper kubeconfig file to start the controller manager.

Thank you for your reply，but my kubeconfig already specifying api-server address。
like this... I didn't quite understand why。

`apiVersion: v1
clusters:
- cluster:
    server: http://10.39.128.35
  name: default-cluster
contexts:
- context:
    cluster: default-cluster
    namespace: default
    user: default-auth
  name: default-context
current-context: default-context
kind: Config
preferences: {}`

> proper

thank you for you apply,I check my kubeconfig and my config is:

`#ps -ef|grep kubelet
root      4630     1  3 Jul22 ?        2-03:36:14 /usr/bin/kubelet --hostname-override=10.33.224.155 --logtostderr=true --log-dir=/var/log/kubernetes --v=2 --kubeconfig=/etc/kubernetes/kubeconfig --allow-privileged=true --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin --cluster-domain cluster.local --image-pull-progress-deadline=10m0s --cluster-dns 10.32.0.129,10.32.0.130
root     21341 17865  0 10:22 pts/6    00:00:00 grep --color=auto kubelet`

#cat /etc/kubernetes/kubeconfig
apiVersion: v1
clusters:
- cluster:
    server: http://10.39.128.35
  name: default-cluster
contexts:
- context:
    cluster: default-cluster
    namespace: default
    user: default-auth
  name: default-context
current-context: default-context
kind: Config
preferences: {}

**Comment by Fei-Guo** [comment]
You need to make sure the APIServer enables  MutatingAdmissionWebhook and ValidatingAdmissionWebhook

For example,

--enable-admission-plugins=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota
