### ISSUE TITLE
[feature request] DaemonSet support revision status

### ISSUE THREAD

**Issue by Hanmengnan** [openkruise/kruise#1341]
**What would you like to be added**:

DaemonSet hasn't supported revision status. So I want to introduce revision status related fields in the DaemonSet status, just like in [https://openkruise.io/docs/user-manuals/cloneset/#template-and-revision](https://openkruise.io/docs/user-manuals/cloneset/#template-and-revision)

**Why is this needed**:

**Comment by zmberg** [comment]
@Hanmengnan What fields do you want to add, please list them in details.
