### ISSUE TITLE
[ENHANCEMENT] "isSidecarSetNotUpdate" ambiguous function name

### ISSUE THREAD

**Issue by Colvin-Y** [openkruise/kruise#1342]
The function name and its implementation have ambiguity. The function `isSidecarSetNotUpdate` should return `true` for `NotUpdate` SidecarSet and `false` otherwise. However, the current implementation is as follows:
```go
func isSidecarSetNotUpdate(s *appsv1alpha1.SidecarSet) bool {
	if s.Spec.UpdateStrategy.Type == appsv1alpha1.NotUpdateSidecarSetStrategyType {
		klog.V(3).Infof("sidecarSet spreading RollingUpdate config type, name: %s, type: %s", s.Name, s.Spec.UpdateStrategy.Type)
		return false
	}
	return true
}
```
The return results are opposite to the function name, which can make the code reading challenging.
This function is called in `sidecarset_processor.go` in a strange way:
```go
// 4. SidecarSet upgrade strategy type is NotUpdate
if !isSidecarSetNotUpdate(sidecarSet) {
	return reconcile.Result{}, nil
}
```
I believe the ideal way to call it should be:
```go
if isSidecarSetNotUpdate(sidecarSet) {
	return reconcile.Result{}, nil
}
```
Therefore, the implementation of the function should be corrected as follows:
```go
func isSidecarSetNotUpdate(s *appsv1alpha1.SidecarSet) bool {
	if s.Spec.UpdateStrategy.Type == appsv1alpha1.NotUpdateSidecarSetStrategyType {
		klog.V(3).Infof("sidecarSet spreading RollingUpdate config type, name: %s, type: %s", s.Name, s.Spec.UpdateStrategy.Type)
		return true
	}
	return false
}
```

**Comment by Colvin-Y** [comment]
/@botname label kind/enhancement

**Comment by veophi** [comment]
@Colvin-Y  Just fix it!

**Comment by Colvin-Y** [comment]
> 

Uhuh, thx for your reply, there's a pr I've pushed
