### ISSUE TITLE
LFX-Mentorship-Fall: Openkruise workload integration with Argo-cd & Helm

### ISSUE THREAD

**Issue by zmberg** [openkruise/kruise#1345]
**What would you like to be added**:
[Argo-cd](https://argo-cd.readthedocs.io/en/stable/) and [Helm](https://helm.sh/docs/) is a popular Gitops tool in the community that supports native K8S workload publishing. Similarly, [OpenKruise](https://openkruise.io/docs/) workloads are widely used in the community, so integrating OpenKruise with Argo-cd will help the development of the cloud-native ecosystem, and is a popular request from the Kruise community.

The OpenKruise workloads are as follows: [CloneSet](https://openkruise.io/docs/user-manuals/cloneset), [Advanced StatefulSet](https://openkruise.io/docs/user-manuals/advancedstatefulset), [Advanced DaemonSet](https://openkruise.io/docs/user-manuals/advanceddaemonset), [BroadcastJob](https://openkruise.io/docs/user-manuals/broadcastjob), [AdvancedCronJob](https://openkruise.io/docs/user-manuals/advancedcronjob) and [Kruise Rollout](https://openkruise.io/rollouts/user-manuals/api-specifications).

Argo-cd also has corresponding support for these custom workloads mentioned above, which can be implemented by writing corresponding lua scripts, refer: https://github.com/argoproj/argo-cd/tree/master/resource_customizations.

Helm also supports the [hook mechanism](https://helm.sh/docs/topics/charts_hooks/), which allows for the checking of custom resources.

There are two objectives that need to be achieved for this topic:
- **the kruise workload lua scripts are merged into the argo-cd repository.**
- **Implement a publicly available image capable of checking Kruise workload resources, enabling checking of krusie resources during the helm install/upgrade process**

**Comment by maheshkasabe** [comment]
Hello @FillZpp & @zmberg I find this issue pretty interesting and it pretty much aligns with my interest and preconceived skills, I have good amount of knowledge & enough projects regarding kubernetes and Argo-CD, I am currently a Mentee @Google Summer of Code & Imporving the CI/CD pipeline of NRNBs Graphspace project. I am quite familiar with Kruise project and have used it in my personal projects, i have joined the slack of kruise and will be posting more updates regardging this in the community discussion only!

**Comment by Zekrom-7780** [comment]
Hello @FillZpp  & @zmberg , I am pretty interested in this project. I was a part of the [Google Summer of Code 2022](https://summerofcode.withgoogle.com/programs/2022/projects/sJVwWlZC), where I used Docker containers, created and manipulating docker images  , and I also custom trained an SSD-Mobilenet V2 Model to detect only humans specifically, amongst other things. I have also experience in writing Lua scripts, as a part of the screening exercise for [Microsoft's RLOS](https://vowpalwabbit.org/rlos/2023/projects), where I had integraed Lua to C++. 
i have joined the slack of kruise and will be posting more updates regarding this

**Comment by ronitblenz** [comment]
Greetings @FillZpp and @zmberg 

I am interested to work on this project. I am currently a **Google Summer of Code Mentee**. I have experience with cloud native environment and also I am a **Cloud Native Community Group Chapter Lead** and volunteering at **Kubernetes Sig Contribex’s Comms in KubeCon Contributor Summit North America 2023**. I was privileged to be the only Under-20 to receive a Travel Scholarship from The Linux Foundation to attend **Open Source Summit Europe 2022 at Dublin, Ireland**. 

I have completed my tasks after application as well.
I would love to contribute for LFX Mentorship this season. 
Looking forward to add value.
Thanks in advance!

**Comment by octonawish-akcodes** [comment]
I am interested in this porject

**Comment by chococandy63** [comment]
Hello @FillZpp & @zmberg,

I'm interested in this project. I'm currently a CNCF zero to merge Incubator program mentee and involved in exploring different CNCF organizations and trying to contribute as my much as I can. I have experience in Docker, kubernetes, and currently learning about Lua. 
Previously, I've tried contributing to Fedora, KDE. I've also been awarded with LiFT 2023 scholarship for women in open source track and Dan Kohn Virtual Student scholarship to attend KubeCon 2023 virtually. 

I would love to contribute for LFX Mentorship this season.
Looking forward to learn more about CNCF ecosystem :)
Thank you!
