### ISSUE TITLE
[BUG] cloneset FailedUpdate:  failed to update pod

### ISSUE THREAD

**Issue by skyshaokai** [openkruise/kruise#1351]
**What happened**:
cloneset FailedUpdate: 

failed to update pod inf.cloudnative-consumer.higgs.bd.nb-wd-pqhcx in-place(revision inf.cloudnative-consumer.higgs.bd.nb-wd-75c8dd9595): Operation cannot be fulfilled on pods "inf.cloudnative-consumer.higgs.bd.nb-wd-pqhcx": the object has been modified; please apply your changes to the latest version and try again

get cloneset yaml ：
`  updateStrategy:
    inPlaceUpdateStrategy: {}
    maxSurge: 0
    maxUnavailable: 50%
    partition: 2
    type: InPlaceIfPossible
status:
  availableReplicas: 3
  collisionCount: 0
  conditions:
  - lastTransitionTime: "2023-08-01T12:31:54Z"
    message: 'Operation cannot be fulfilled on pods "inf.cloudnative-consumer.higgs.bd.nb-wd-pqhcx":
      the object has been modified; please apply your changes to the latest version
      and try again'
    status: "True"
    type: FailedUpdate
  currentRevision: inf.cloudnative-consumer.higgs.bd.nb-wd-7575fd79fd
  expectedUpdatedReplicas: 1
  labelSelector: em_app=cloudnative-consumer,em_env_type=ONLINE,em_logic_idc=bd,em_platform=higgs,em_product_line=inf
  observedGeneration: 32
  readyReplicas: 3
  replicas: 3
  updateRevision: inf.cloudnative-consumer.higgs.bd.nb-wd-75c8dd9595
  updatedReadyReplicas: 0
  updatedReplicas: 0`

**Environment**:
- Kruise version:  1.4.0

**Comment by veophi** [comment]
> Operation cannot be fulfilled on pods "inf.cloudnative-consumer.higgs.bd.nb-wd-pqhcx": the object has been modified; please apply your changes to the latest version and try again

Just ignore, refer to: https://github.com/kubernetes/kubernetes/issues/28149

**Comment by skyshaokai** [comment]
> > Operation cannot be fulfilled on pods "inf.cloudnative-consumer.higgs.bd.nb-wd-pqhcx": the object has been modified; please apply your changes to the latest version and try again
> 
> Just ignore, refer to: [kubernetes/kubernetes#28149](https://github.com/kubernetes/kubernetes/issues/28149)


The error message here lasted for 1 hour and still hasn't been recovered. What could be the reason? Is there an error message that persists for a long time when Openkruise waits for the pod  in-place update?

**Comment by skyshaokai** [comment]
The problem caused by k8s apiserver. After the apiserver returned to normal, the Openkruise controller was restarted and restored.
