### ISSUE TITLE
release-1.4使用make docker-build构建镜像出错

### ISSUE THREAD

**Issue by song0071000** [openkruise/kruise#1362]
release-1.4使用make docker-build构建镜像出错，信息如下：

> => ERROR [stage-1 2/5] RUN apk add --no-cache ca-certificates=\~20220614-r4 bash=\~5.2.15-r0 expat=\~2.5.0-r0   &&  4.3s
\------
 \> [stage-1 2/5] RUN apk add --no-cache ca-certificates=\~20220614-r4 bash=\~5.2.15-r0 expat=\~2.5.0-r0   && rm -rf /var/cache/apk/*:
#6 0.365 fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/main/aarch64/APKINDEX.tar.gz
#6 3.250 fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/community/aarch64/APKINDEX.tar.gz
#6 4.227 ERROR: unable to select packages:
#6 4.243   ca-certificates-20230506-r0:
#6 4.243     breaks: world[ca-certificates~20220614-r4]
\------
executor failed running [/bin/sh -c apk add --no-cache ca-certificates=~20220614-r4 bash=~5.2.15-r0 expat=~2.5.0-r0   && rm -rf /var/cache/apk/*]: exit code: 1
make: *** [docker-build] Error 1

怎么调整能使其正常构建？

**Comment by zmberg** [comment]
```
RUN apk add --no-cache ca-certificates bash expat \
  && rm -rf /var/cache/apk/*
```

And you can submit the pr for this fix.
