### ISSUE TITLE
[BUG]log always print "Watch close"

### ISSUE THREAD

**Issue by huzhengchuan** [openkruise/kruise#137]
**What happened**:
deploy kruise in my k8s cluster, create  statefulsets.apps.kruise.io app work ok, and the app pod is running, but the kruise controller manager frequently print "watch close" logs .  is it normal?
<pre>

# kubectl logs -f kruise-controller-manager-0 -n kruise-system
I0925 13:30:24.865164       1 pod_create_handler.go:77] [sidecar inject] begin to process /
I0925 13:30:42.172745       1 reflector.go:357] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Watch close - *v1.Pod total 18 items received
I0925 13:30:43.426671       1 reflector.go:357] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:196: Watch close - *v1.Secret total 0 items received
I0925 13:31:22.204516       1 reflector.go:357] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Watch close - *v1.PersistentVolumeClaim total 36 items received
I0925 13:31:22.204910       1 reflector.go:357] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Watch close - *v1alpha1.StatefulSet total 0 items received
I0925 13:31:33.077634       1 reflector.go:357] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Watch close - *v1.Node total 628 items received
I0925 13:31:52.269176       1 reflector.go:357] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Watch close - *v1alpha1.SidecarSet total 0 items received
I0925 13:33:52.406022       1 reflector.go:357] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Watch close - *v1alpha1.BroadcastJob total 0 items received
I0925 13:33:52.406847       1 reflector.go:357] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Watch close - *v1.ControllerRevision total 0 items received
I0925 13:34:02.413296       1 reflector.go:357] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:196: Watch close - *v1.Service total 0 items received
I0925 13:36:13.653563       1 reflector.go:357] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:196: Watch close - *v1beta1.MutatingWebhookConfiguration total 0 items received
I0925 13:37:26.181909       1 reflector.go:357] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Watch close - *v1.Pod total 9 items received
I0925 13:37:26.214689       1 reflector.go:357] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Watch close - *v1alpha1.StatefulSet total 0 items received
I0925 13:37:26.430959       1 reflector.go:357] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:196: Watch close - *v1.Secret total 0 items received
I0925 13:37:37.214645       1 reflector.go:357] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Watch close - *v1.PersistentVolumeClaim total 0 items received
</pre>

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kruise version: mastre-5bb9bd0c214225c3a232feb6eb9ab71ab333f025
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"33b6acd980c7df292d851628dc5842042f5da9b4", GitTreeState:"archive", BuildDate:"2019-08-02T11:08:51Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"33b6acd980c7df292d851628dc5842042f5da9b4", GitTreeState:"archive", BuildDate:"2019-08-02T11:08:51Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g: `cat /etc/os-release`): centos-7
- Kernel (e.g. `uname -a`): 3.10.0-693.25.4.el7
- Install tools:  
- Others:

**Comment by Fei-Guo** [comment]
First of all, watch close is not a catastrophic failure because client-go runtime will re-Listwatch the resources when ListAndWatch fails. See 
https://github.com/openkruise/kruise/blob/91014db6b272634f008747086a3ab7f6be49d724/vendor/k8s.io/client-go/tools/cache/reflector.go#L130

But if it occurs frequently like in your case (every a few minutes), it indeed indicates the environment has problem, probably due to unstable networking connectivity or even APIServer problem. 

Since you are using Kubernetes 1.11 which is a pretty old version, it is hard for us to reproduce the problem in our setups (at least 1.12). Can you at least try a Kubernetes > 1.12 (say 1.14 minikube) and see if the same problem occurs?

**Comment by Fei-Guo** [comment]
I observe the similar in my local setup, will take a look.

**Comment by Fei-Guo** [comment]
In fact, this is an expected behavior in client go
```
timeoutSeconds := int64(minWatchTimeout.Seconds() * (rand.Float64() + 1.0))
		options = metav1.ListOptions{
			ResourceVersion: resourceVersion,
			// We want to avoid situations of hanging watchers. Stop any wachers that do not
			// receive any events within the timeout window.
			TimeoutSeconds: &timeoutSeconds,
		}
```
https://github.com/openkruise/kruise/blob/07325e51eef9976d95481cbccabe2f956a218f1c/vendor/k8s.io/client-go/tools/cache/reflector.go#L235

The timeout is a random number between 5 to 10 mins by default.

**Comment by huzhengchuan** [comment]
thanks
