### ISSUE TITLE
[BUG] Continuous container restart requests will cause longer intervals between each restart.

### ISSUE THREAD

**Issue by 00wuyu00** [openkruise/kruise#1371]
**What happened**:
Continuous container restart request

**What you expected to happen**:
The speed of restarts remains consistent.

**How to reproduce it (as minimally and precisely as possible)**:
Continuous create container restart request

**Anything else we need to know?**:
speculate  the "container restart backoff" mechanism may result in longer intervals between restarts.

**Environment**:
- Kruise version: 1.3
- Kubernetes version (use `kubectl version`): 1.24
- Install details (e.g. helm install args):
- Others:

**Comment by lowang-bh** [comment]
Usally, this is normal phenomena to prevent frequency error.
