### ISSUE TITLE
关于原地升级失败的问题

### ISSUE THREAD

**Issue by zhengjr9** [openkruise/kruise#1375]
现象：
更新了配置文件后，使用原地升级出现容器启动失败的现象
Pod事件：
Error: failed to start container "container-0": Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/var/lib/kubelet/pods/3057b9df-c7bc-4b99-ad30-7a7c3be9ad24/volume-subpaths/common/container-0/0" to rootfs at "/apps/bard/conf/common-dev.yaml": mount /var/lib/kubelet/pods/3057b9df-c7bc-4b99-ad30-7a7c3be9ad24/volume-subpaths/common/container-0/0:/apps/bard/conf/common-dev.yaml (via /proc/self/fd/6), flags: 0x5001: no such file or directory: unknown

**Comment by hantmac** [comment]
@zhengjr9 What is your Kubernetes version? Maybe your Kubernetes version does not support dockershim and support cri-dockerd runtime.  More details in this issue https://github.com/openkruise/kruise/issues/1337
