### ISSUE TITLE
[ISSUE] remove `./vendor/` contents

### ISSUE THREAD

**Issue by nashtsai** [openkruise/kruise#1379]
**What happened**:
Remove `./vendor/` contents, as the contents can be fetched via `go mod vendor`.

**Comment by furykerry** [comment]
we keep vendor directory deliberately to ease kruise building in some region with poor and unstable network. are their any problem if we keep the vendor?

**Comment by nashtsai** [comment]
> we keep vendor directory deliberately to ease kruise building in some region with poor and unstable network. are their any problem if we keep the vendor?

Unnecessary download, and for people can reach "github.com" they shouldn't have problem of "poor and unstable network", and there is GOPROXY .
