### ISSUE TITLE
[BUG]demo create failed

### ISSUE THREAD

**Issue by huzhengchuan** [openkruise/kruise#138]
**What happened**:
kubectl create -f ./config/samples/apps_v1alpha1_broadcastjob-never-complete.yaml run error
<pre>
[root@ samples]# kubectl create -f ./apps_v1alpha1_broadcastjob-never-complete.yaml 
Error from server (InternalError): error when creating "./apps_v1alpha1_broadcastjob-never-complete.yaml": Internal error occurred: Internal error occurred: jsonpatch replace operation does not apply: doc is missing path: /spec/failurePolicy/Type
</pre>

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kruise version: master-5bb9bd0c214225c3a232feb6eb9ab71ab333f025
- Kubernetes version (use `kubectl version`): 1.11.5
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Fei-Guo** [comment]
This is indeed a bug. We are working on a fix. Thanks for catching this.
