### ISSUE TITLE
[feature request] kruise api (client) for rust

### ISSUE THREAD

**Issue by liangyuanpeng** [openkruise/kruise#1388]
**What would you like to be added**:

Rust API for openkruise.

**Why is this needed**:

Hi community,  xline is a cncf sandbox project and it is a High-Performance Geo-distributed Metadata Management System. And [xline-operator](https://github.com/xline-kv/xline-operator) is the operator for xline.

In some designs, we may want to use advanced statefulset, so we need to have an openkruise rust api client. It is obviously a correct choice to maintain the rust client in the kruise official organization.

I can work for maintaining the rust api of openkruise and it's need the openkruise community does things:

-  create the repo for client api of rust , 
- create a github team of client-api-rust (for release rust api to https://crates.io/)

Maybe this issue should transfer to [openkruise/community](https://github.com/openkruise/community)

Looking for your reply, thanks!

**Comment by zmberg** [comment]
Can you submit for this?

**Comment by liangyuanpeng** [comment]
@zmberg  Just for confirm that do you mean transfer this issue to community repo?

**Comment by zmberg** [comment]
@liangyuanpeng Sorry for not looking particularly hard before. I've taken care of step one, [client-rust](https://github.com/openkruise/client-rust), and what should I do for step two?

**Comment by liangyuanpeng** [comment]
Thanks a lot!
