### ISSUE TITLE
[BUG] StatefulSet update pod failed with volumeClaimTemplates changed

### ISSUE THREAD

**Issue by imsunv** [openkruise/kruise#1389]
**What happened**:
```
    - type: FailedUpdatePod
      status: "True"
      lastTransitionTime: 2023-08-25T01:52:07Z
      message: >
        StatefulPodControl failed to update Pod error: Pod "xx-t1-test-0" is
        invalid: spec: Forbidden: pod updates may not change fields other than
        `spec.containers[*].image`, `spec.initContainers[*].image`,
        `spec.activeDeadlineSeconds`, `spec.tolerations` (only additions to
        existing tolerations) or `spec.terminationGracePeriodSeconds` (allow it
        to be set to 1 if it was previously negative)
          core.PodSpec{
          	Volumes: []core.Volume{
        + 		{

        + 			Name: "data-pvc",

        + 			VolumeSource: core.VolumeSource{

        + 				PersistentVolumeClaim: &core.PersistentVolumeClaimVolumeSource{ClaimName: "data-pvc-xx-t1-test-0"},

        + 			},

        + 		},
          		{Name: "log-dir", VolumeSource: {EmptyDir: &{}}},
          		{Name: "tools-dir", VolumeSource: {EmptyDir: &{}}},
          		... // 3 identical elements
          	},
```

**What you expected to happen**:
pod recreate with volumeClaimTemplates changed

**How to reproduce it (as minimally and precisely as possible)**:
kruise statefulset apply and pod created succeed

add  volumeClaimTemplates to the statefulset and caused error.

**Anything else we need to know?**:

statefulset update policy:
podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
      maxUnavailable: 1
      podUpdatePolicy: ReCreate
      inPlaceUpdateStrategy:
        gracePeriodSeconds: 10
      minReadySeconds: 0

**Environment**:
- Kruise version:  1.4.0
- Kubernetes version (use `kubectl version`): v1.26.3-aliyun.1
- Install details (e.g. helm install args):
- Others:

**Comment by zmberg** [comment]
I don't know how you did it, I verified locally that nothing happens. Also, if you change only the volumeClaimTemplates kruise will not rebuild the pod automatically, you need to delete the pod manually and then trigger the rebuild.
