### ISSUE TITLE
[BUG] error: no kind "StatefulSet" is registered for version "apps.kruise.io/v1beta1" in scheme "pkg/scheme/scheme.go:28"

### ISSUE THREAD

**Issue by pengln** [openkruise/kruise#1396]
**What happened**:
error: no kind "StatefulSet" is registered for version "apps.kruise.io/v1beta1" in scheme "pkg/scheme/scheme.go:28"

**What you expected to happen**:
kubectl exec into container via asts

**How to reproduce it (as minimally and precisely as possible)**:
kubectl exec asts/xxxx .......

**Anything else we need to know?**:

**Environment**:
- Kruise version: 1.4.0
- Kubernetes version (use `kubectl version`): 1.25.0
- Install details (e.g. helm install args):
- Others:

**Comment by veophi** [comment]
why not just execute `kubectl exec <pod-name> ...` ?

**Comment by pengln** [comment]
I can ignore the name of the pod, and just go with the business application.

**Comment by zmberg** [comment]
@pengln You can't do that, it's unsupported. It's normal for the community kubectl to not introduce the kruise scheme, and there's not much we can do about it.
