### ISSUE TITLE
[BUG] Pulling some mirrors must fail due to timeout

### ISSUE THREAD

**Issue by GeekWolfBoy** [openkruise/kruise#1406]
**What happened**:
Pulling some mirrors must fail due to timeout

**What you expected to happen**:
the size of image is expect 
**How to reproduce it (as minimally and precisely as possible)**:
create imagepulljob wiht this yaml:
```
apiVersion: apps.kruise.io/v1alpha1
kind: ImagePullJob
metadata:
  name: job-with-never
spec:
  image: SomeBigImageOver3GB
  parallelism: 10    
  selector:          
    matchLabels:
      xiaowen1: test1
  completionPolicy:
    type: Never                 
  pullPolicy: 
    backoffLimit: 10
    timeoutSeconds: 600
```
**Anything else we need to know?**:
## daemon log:
```
I0906 08:46:09.035322       1 imagepuller_controller.go:208] Start syncing for 21.2.44.62
I0906 08:46:09.046408       1 imagepuller_controller.go:213] Finished syncing for 21.2.44.62
I0906 08:46:09.108082       1 utils.go:48] Received new image SomeBigImageOver3GB:0.1.12
I0906 08:46:09.108103       1 imagepuller_controller.go:208] Start syncing for 21.2.44.62
I0906 08:46:09.108161       1 imagepuller_worker.go:94] starting new workerpool for SomeBigImageOver3GB
I0906 08:46:09.108260       1 imagepuller_worker.go:317] starting worker SomeBigImageOver3GB:0.1.12 version 0
I0906 08:46:09.108278       1 imagepuller_worker.go:428] Worker is starting to pull image SomeBigImageOver3GB:0.1.12 version 0
....
I0906 08:47:11.042151       1 imagepuller_worker.go:197] stopping worker SomeBigImageOver3GB:0.1.12 which is not in spec
W0906 08:47:11.042161       1 imagepuller_worker.go:306] Worker to pull image SomeBigImageOver3GB:0.1.12 is stopped
I0906 08:47:11.042258       1 imagepuller_worker.go:456] Pulling image SomeBigImageOver3GB:0.1.12 is stopped.
W0906 08:47:11.042278       1 imagepuller_worker.go:330] Worker failed to pull image SomeBigImageOver3GB:0.1.12, cost 1m1.934003668s, err: pulling image SomeBigImageOver3GB:0.1.12 is stopped
```
## ImagePullJob Event 
```
Events:
  Type     Reason           Age   From                       Message
  ----     ------           ----  ----                       -------
  Warning  PullImageFailed  8m3s  nodeimage-controller       Failed to pull image SomeBigImageOver3GB:0.1.12 on node 21.2.44.62 for node has not responded for a long time
  Warning  PullImageFailed  8m1s  kruise-daemon-imagepuller  Image SomeBigImageOver3GB:0.1.12 pulling image SomeBigImageOver3GB:0.1.12 is stopped
```
## NodeImage Status:
![NodeImage Status](https://github.com/openkruise/kruise/assets/12298523/78de5a20-60ec-464f-b78e-f420529a529d)
 
**Environment**:
- Kruise version:v1.4.0
- Kubernetes version (use `kubectl version`):v1.20.6-tke.28
- Install details (e.g. helm install args):
```
 helm install kruise openkruise/kruise --version 1.4.0
```
- Others:
<img width="1286" alt="企业微信截图_7549dab9-0c0f-4935-b18c-b690341515a9" src="https://github.com/openkruise/kruise/assets/12298523/19715a38-bdb4-46b3-bbfb-6a10b257e0a0">

<img width="779" alt="image" src="https://github.com/openkruise/kruise/assets/12298523/bee68d9c-9d38-4c47-baa7-afae4b523e0c">

**Comment by ls-2018** [comment]
Let me try.

**Comment by ls-2018** [comment]
I noticed that after the daemon listens for changes, it executes the
`w.statusUpdater.UpdateStatus(newStatus)`
But this doesn't actually update the data in etcd, it's done by the sync function triggered by the controller.


So when the `pull` mirror exceeds 10m and the `sync` function is not triggered, the `controller` decides that the `imagepull` has failed.

Shouldn't we make `w.statusUpdater.UpdateStatus(newStatus) ` actually update the data in etcd?
@zmberg

**Comment by ls-2018** [comment]
Or we set the controller's resync time to a value less than 10 minutes, which triggers the sync function to ensure that the state brushes to etcd before it times out

**Comment by GeekWolfBoy** [comment]
> So when the `pull` mirror exceeds 10m and the `sync` function is not triggered, the `controller` decides that the `imagepull` has failed.

but，It‘s just spend 1 minute，not 10 minute。that is my second promblem. @FillZpp @ls-2018

**Comment by GeekWolfBoy** [comment]
The same issue has been reported and fixed before：
https://github.com/openkruise/kruise/pull/1280/files#diff-43652af1c47ca4b39fe1e7103be8c21672b66a48375088210ac08f2cf7e6ca4c

**Comment by ls-2018** [comment]
You're right, I need to validate some other thoughts.

**Comment by GeekWolfBoy** [comment]
The timeout in the controller code is set to 10 minutes, but the displayed timeout is 1 minute. Why?
