### ISSUE TITLE
[feature request] cloneset中template设置hostname, 每个pod的hostname都保证不一样

### ISSUE THREAD

**Issue by FengFees** [openkruise/kruise#1434]
**What happened**:
当前我们业务会有其他组件来探测其健康状况，使用的是访问pod ip的方式，但是存在pod重创ip变化的情况，探测会失败。我们期望可以不通过ip的方式来进行访问，社区statefulset可以配置hostname和subdomain，通过headless service来直接访问pod，但是cloneset在template下配置hostname，其下的pod都会使用同一个hostname。

**What you expected to happen**:
是否可以和statefulset一致，template配置一个Hostname，保证每个pod都使用自己的name配置到hostname上

**Comment by furykerry** [comment]
can you use advance statefulset instand of cloneset ?

**Comment by FengFees** [comment]
> can you use advance statefulset instand of cloneset ?

需要用到cloneset 原地升级的能力，本身业务是有状态的。并且我们想对特定的pod进行扩缩容

**Comment by furykerry** [comment]
advance statefulset also support in-place update, and you can also delete specific pod through ordinal-reserve capability
https://openkruise.io/docs/user-manuals/advancedstatefulset/#ordinals-reserveskip

**Comment by FengFees** [comment]
> advance statefulset also support in-place update, and you can also delete specific pod through ordinal-reserve capability https://openkruise.io/docs/user-manuals/advancedstatefulset/#ordinals-reserveskip

会对特定pod做一些配置的更新，而不仅仅是扩容数量。纵向的扩缩容而不是横向的。

**Comment by furykerry** [comment]
Can you be more specific about the configuration changes, do you mean adjust the resource requirement e.g. inplace VPA? If that is the case, if you're in k8s > 1.27, you can do such VPA even with Kruise advance statefulset.
