### ISSUE TITLE
[feature request] ResourceDistribution support cluster config

### ISSUE THREAD

**Issue by huiwq1990** [openkruise/kruise#1437]
**What would you like to be added**:

Add targetNamespace and kubeConfig fields for ResourceDistribution,  so we can deliever resources to multiple clusters.

**Why is this needed**:

Multi clusters are popular in the years, we want to deliever resource from host cluster to managered clusters.

**Comment by zmberg** [comment]
@huiwq1990 Do you use a tool like argo-cd for multi-cluster?

**Comment by huiwq1990** [comment]
> @huiwq1990 Do you use a tool like argo-cd for multi-cluster?

I do not want to introduce that heavy component. It's more like https://github.com/kubeops/config-syncer/tree/master.

**Comment by zmberg** [comment]
@huiwq1990 Now do you manage the multi clusters?

**Comment by huiwq1990** [comment]
> @huiwq1990 Now do you manage the multi clusters?

Yes, I want to distribute resources to others clusters.

**Comment by zmberg** [comment]
@huiwq1990 The overall architecture and positioning of Kruise does not directly address the issue of multi-clustering, you can use some multi-cluster management tools, e.g., argo-cd to distribute resourceDistribution to different clusters.

**Comment by huiwq1990** [comment]
@zmberg We want to use kruise as a base component, and don't import too many components. And just like fluxcd it support set [kubeconfig](https://fluxcd.io/flux/components/helm/helmreleases/#remote-clusters--cluster-api) , I think it's not multi-cluster management.

**Comment by zmberg** [comment]
@huiwq1990 openkruise is still positioned as a single cluster and won't be doing the multi-cluster thing for a while. However, you can actually solve this problem by distributing the kruise resourceDistribution to different clusters through multi-cluster tools such as argo-cd
