### ISSUE TITLE
[BUG] Cloneset rolling update becomes slow gradually during the deployment

### ISSUE THREAD

**Issue by dragondscv** [openkruise/kruise#1442]
**What happened**:
I recently observe that the rolling update of cloneset slows down gradually during the deployment. For example, I have a cloneset having 198 pods `and maxSurge` 25% and `maxUnavailable` 0. At the beginning of the deployment, 50 pods are created(useSurge is 50) which is expected:
```
Calculate diffs for CloneSet XXXX, replicas=198, partition=0, maxSurge=50, maxUnavailable=0, allPods=248, 
newRevisionPods=51, newRevisionActivePods=51, oldRevisionPods=197, oldRevisionActivePods=197, 
unavailableNewRevisionCount=51, unavailableOldRevisionCount=0, preDeletingCount=0, toDeleteNewRevisionCount=0, 
toDeleteOldRevisionCount=0. Result: {scaleNum:0 scaleNumOldRevision:0 scaleUpLimit:0 deleteReadyLimit:0 useSurge:50 
useSurgeOldRevision:0 updateNum:147 updateMaxUnavailable:50}
```
However, near the end of the deployment, it slows down creating new pods(useSurge is 22):
```
 Calculate diffs for CloneSet XXXX, replicas=198, partition=0, maxSurge=50, maxUnavailable=0, allPods=220, 
newRevisionPods=176, newRevisionActivePods=176, oldRevisionPods=44, oldRevisionActivePods=44, 
unavailableNewRevisionCount=14, unavailableOldRevisionCount=0, preDeletingCount=0, toDeleteNewRevisionCount=0, 
toDeleteOldRevisionCount=0. Result: {scaleNum:0 scaleNumOldRevision:0 scaleUpLimit:0 deleteReadyLimit:0 useSurge:22 
useSurgeOldRevision:0 updateNum:22 updateMaxUnavailable:22}
```
Since we specify maxSurge to be 25%, I think it should create more pods(up to 50 or the remaining of the old version pods).

**What you expected to happen**:
Rolling update should not slow down while there is still room to create new pods.

**How to reproduce it (as minimally and precisely as possible)**:
Set `maxSurge` to 25% and `maxUnavailable` to 0 and do a rolling updates.

**Anything else we need to know?**:

**Environment**:
- Kruise version: 1.1.0
- Kubernetes version (use `kubectl version`): 1.22
- Install details (e.g. helm install args):
- Others:

**Comment by ls-2018** [comment]
I think that's right. Because newRevisionActivePods= 176 away from target, 22 away from target. It's the final stage

**Comment by dragondscv** [comment]
It is true that it is 22 pods away from the target. But it can just create those 22 pods right way because I use 25% maxSurge (`allPods` can be up to 248). Look at the total number of pods which is just `allPods`=220. That's why I feel it is not right.

Another example which could be easy to understand is like this:

what we expect to see if maxsurge=5
```
NAME     DESIRED   UPDATED   UPDATED_READY
time-0   10        5         0     
time-1   10        10        5     
time-2   10        10        10     
```
what we actually see
```
NAME     DESIRED   UPDATED   UPDATED_READY
time-0   10        5         0     
time-1   10        7         4     
time-2   10        8         4  
time-3   10        9         6
time-3   10        10        10
```
This could be easily re-produceable. Simple create a cloneset with `maxSurge` 25% and `maxUnavailable` 0 and watch the rolling update progress:
```
$ kubectl get cloneset sample-app -n sample-namespace
NAME             DESIRED   UPDATED   UPDATED_READY   READY   TOTAL   AGE
sample-app   50                 49                   48                          50          51       155d
```

**Comment by ls-2018** [comment]
1, each time the pod status changes, the tuning will be triggered to make it possible to update the progress
2, As for why 220 is not 248, I think it has something to do with the logic of ①. Because it is not processed batch by batch, but based on pod event updates. In addition, from the perspective of resources, I think the implementation of kruise can also save some resources.   how about you? @zmberg

**Comment by dragondscv** [comment]
`TOTAL` should be constantly around 63 until it reaches the end of the update.
However, cloneset rolling update starts to slow down at the last batch. If you use maxSurge 25% in the above example, it starts to slow down when UPDATED is 37(50-50*0.25).

**Comment by ls-2018** [comment]
Yeah.
It starts to slow down when UPDATED is 37(50-50*0.25). At this point, the TOTAL should be about 63.
When UPDATED is 49, it's almost over. The TOTAL should be about 51.

**Comment by dragondscv** [comment]
This affects our deployment speed for large applications. 
I feel we may need to look into the calcuate function https://github.com/openkruise/kruise/blob/v1.1.0/pkg/controller/cloneset/sync/cloneset_sync_utils.go#L74
or the update function https://github.com/openkruise/kruise/blob/master/pkg/controller/cloneset/sync/cloneset_update.go#L81
But I am not very familiar with the logic. Will someone help us on this?

**Comment by dragondscv** [comment]
Just want to follow up on this since this is affecting our deployment. Do we know what may cause this?
