### ISSUE TITLE
openkruise broadcastjob 宿主机容器残留问题

### ISSUE THREAD

**Issue by HitShyzzz** [openkruise/kruise#1446]
**What happened**:broadcastjob发起巡检在一个宿主机巡检失败产生容器残留，会导致更多的宿主机产生容器残留

**What you expected to happen**:当前宿主机巡检失败产生容器残留，kruise能采取一些措施来保证其他宿主机不产生残留

**How to reproduce it (as minimally and precisely as possible)**:broadcasjob发起巡检让其中一个宿主机执行失败产生容器残留，观察其他宿主机执行情况

**Anything else we need to know?**:broadcastjob.json
![1](https://github.com/openkruise/kruise/assets/90769624/3dc08b93-3bee-490e-9cea-a278491dd215)
![2](https://github.com/openkruise/kruise/assets/90769624/1e034aaf-4886-4bfa-a76c-2d96978bcc0c)
![3](https://github.com/openkruise/kruise/assets/90769624/35c2eadf-752e-457a-aee0-997cee51ff4b)
![4](https://github.com/openkruise/kruise/assets/90769624/00160e84-ba16-41cf-8a13-a31a41737850)
![5](https://github.com/openkruise/kruise/assets/90769624/b793c875-1229-49bc-ba0d-4920100856d1)

**Environment**:
- Kruise version:1.0.0
- Kubernetes version (use `kubectl version`):1.17.5
- Install details (e.g. helm install args):
- Others:

**Comment by veophi** [comment]
残留是指？希望一个 pod 任务失败后，其他成功的 pod 能被 gc？

**Comment by HitShyzzz** [comment]
残留是说执行失败的pod不能被清除。
第2句话是我想表达的意思。

**Comment by veophi** [comment]
> 残留是说执行失败的pod不能被清除。 第2句话是我想表达的意思。

@HitShyzzz  你期望失败的pod留下还是不留下?

**Comment by zmberg** [comment]
@HitShyzzz 你这两个字段配置了吗？ 
![image](https://github.com/openkruise/kruise/assets/25051767/1008747e-2270-4481-90cb-a87d5c4b9385)

**Comment by HitShyzzz** [comment]
> @HitShyzzz 你这两个字段配置了吗？ ![image](https://user-images.githubusercontent.com/25051767/280900626-1008747e-2270-4481-90cb-a87d5c4b9385.png)

ttlSecondsAfterFinished设置的是5分钟，activeDeadlineSeconds设置的是1小时，这样设置会不会有什么问题？

**Comment by HitShyzzz** [comment]
> > 残留是说执行失败的pod不能被清除。 第2句话是我想表达的意思。
> 
> @HitShyzzz 你期望失败的pod留下还是不留下?

失败的pod也能被清除
