### ISSUE TITLE
[BUG] kruise-daemon should use ClusterFirstWithHostNet for the DNS Policy

### ISSUE THREAD

**Issue by chasain** [openkruise/kruise#1447]
**What happened**: kruise-daemon isn't able to resolve internal DNS entries, i.e. a locally host docker proxy

**What you expected to happen**: kruise-daemon should be able to resolve service.namespace.svc.cluster.local entries

**How to reproduce it (as minimally and precisely as possible)**: host a docker proxy in a cluster and use an ImagePull job to try to pull images through it, DNS lookup will fail

**Anything else we need to know?**: This is caused by not defining a dnsPolicy and the default ClusterFirst getting assigned, but since it's created with `hostNetwork: true` this has the effect of setting DNS to the node's DNS. It has to be changed manually to use the Cluster DNS, more info at https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy

**Environment**:
- Kruise version: 1.5.0
- Kubernetes version (use `kubectl version`): 1.23.17+k3s1
- Install details (e.g. helm install args):  
```
  manager:
    replicas: 1
  installation:
    createNamespace: false
  daemon:
    socketLocation: /var/run/k3s
```
- Others:

**Comment by zmberg** [comment]
@chasain Can you submit pr for this issue in repo https://github.com/openkruise/charts/tree/master/versions/kruise/1.5.1 ?

**Comment by amghazanfari** [comment]
can i work on this issue? @zmberg

**Comment by opencmit2** [comment]
Hi @zmberg 
Let me try it
