### ISSUE TITLE
[BUG]  no test cases actually run in controller_revision_test file 

### ISSUE THREAD

**Issue by Spground** [openkruise/kruise#1456]
**What happened**:

No tests actually run when you run the cmd to test `github.com/openkruise/kruise/pkg/controller/cloneset/revision` pkg.

``` shell
go test -timeout 180s -run ^TestCreateApplyRevision$ github.com/openkruise/kruise/pkg/controller/cloneset/revision -v
```

**What you expected to happen**:

The specified test case in `github.com/openkruise/kruise/pkg/controller/cloneset/revision` runs successfully .

**How to reproduce it (as minimally and precisely as possible)**:

``` shell
go test -timeout 180s -run ^TestCreateApplyRevision$ github.com/openkruise/kruise/pkg/controller/cloneset/revision -v
```

**Anything else we need to know?**:

The root cause is that no `m.Run()` call, so no tests will run.

https://github.com/openkruise/kruise/blob/c27205573753f7785594d52ea0e85db1d8aeffc7/pkg/controller/cloneset/revision/cloneset_revision_test.go#L34

**Environment**:
- Kruise version:
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Others:

**Comment by ls-2018** [comment]
![image](https://github.com/openkruise/kruise/assets/38821215/a9ef0ed5-0851-4e1d-b87a-9f953eaa9f16)
Passed the test in my environment, not sure if there is something wrong with your environment

**Comment by Spground** [comment]
您的来信我已收到，我会尽快回复！谢谢！

**Comment by Spground** [comment]
> ![image](https://user-images.githubusercontent.com/38821215/284808012-a9ef0ed5-0851-4e1d-b87a-9f953eaa9f16.png) Passed the test in my environment, not sure if there is something wrong with your environment

yes, output shows tests passed when you run `go test`. However,  that's not true, tests still passed if you change test case that's designed to never pass.

e.g change `TestCreateApplyRevision ` , then run the test case, it still passed.

```go
func TestCreateApplyRevision(t *testing.T) {
	t.Fail() // the test case Must fail
}
```

**Comment by ls-2018** [comment]
you are right, is it convenient to submit a pr? 👏

**Comment by Spground** [comment]
您的来信我已收到，我会尽快回复！谢谢！
