### ISSUE TITLE
[feature request] PodUnavailableBudget支持与workload资源一对多匹配

### ISSUE THREAD

**Issue by wxjackie** [openkruise/kruise#1470]
**What would you like to be added**:
PUB（PodUnavailableBudget）提供额外字段，来支持1个PUB资源对多个工作负载资源（Sts/Deployment）独立生效。

**Why is this needed**:
在我们的Operator场景中，一个CR会包含很多组StatefulSet，这些StatefulSet对应需要的PUB配置完全相同。假设我有200个Sts，那么就需要创建出对应的200个PUB资源，同时创建/管理这些配置完全相同的PUB比较繁琐，相应的Operator对APIServer的请求数也会提高。可以考虑引入类似group by的语义字段

**Comment by zmberg** [comment]
是可以支持的昂，你可以直接配置 selector 就行了昂。

**Comment by wxjackie** [comment]
> 是可以支持的昂，你可以直接配置 selector 就行了昂。

@zmberg 想要的效果是，假设有200个sts，每个sts 3副本。我们想让每个sts都要保证最少有1个可用。用selector的话，我理解minAvailable/maxUnavailable是针对selector选中的所有的pod的吧，好像不能满足我们这种场景
