### ISSUE TITLE
how to use ImageListPullJob pull images by cronjob everydays

### ISSUE THREAD

**Issue by zj452008181** [openkruise/kruise#1471]
**What would you like to be added**:
i want to pull images  by tag 'latest' everyday,but the ImageListPullJob only pull once

**Why is this needed**:
we used the latest tag to reduce maintenance

**Comment by veophi** [comment]
Just set `completionPolicy` as `Never` for ImageListPullJob. It will pull image every 24h.

If you pull `latest` tag image, you may see this pr: https://github.com/openkruise/kruise/commit/c27205573753f7785594d52ea0e85db1d8aeffc7 (will release in the next version).

**Comment by zj452008181** [comment]
> 只需将 ImageListPullJob 的 `completionPolicy` 设置为 `Never`。它每 24 小时就会拉取一次图像。
> 
> 如果您提取 `latest` 标签图像，您可能会看到此 pr：[c272055](https://github.com/openkruise/kruise/commit/c27205573753f7785594d52ea0e85db1d8aeffc7)（将在下一个版本）。
感谢，后续有计划做成cronjob让用户自定义吗，因为我们镜像更新时间是比较固定的每周两天。
还有个问题是镜像拉取任务执行时，我在主机上执行docker pull命令会卡住没有反应，这是kruis导致的吗
