### ISSUE TITLE
[feature request] Exclude specified namespaces from webhooks

### ISSUE THREAD

**Issue by voron** [openkruise/kruise#1472]
It may be useful to exclude specific namespaces from kruise webhooks. It may help to remove GKE warnings like following
```
This cluster has an admission webhook installed that is intercepting system-critical requests in the last 24 hours. Intercepting these requests can impact availability of the GKE control plane. 
```
[GKE manual](https://cloud.google.com/kubernetes-engine/docs/how-to/optimize-webhooks#unsafe-webhooks)

```
kruise-mutating-webhook-configuration | Intercepting resources in the kube-system namespace
kruise-validating-webhook-configuration | Intercepting resources in the kube-system namespace
```

**Comment by zmberg** [comment]
@voron yes, can you submit a patch for this issue, related code: https://github.com/openkruise/charts/tree/master/versions/kruise/1.5.
