### ISSUE TITLE
helm install kruise  kurise.tgz安装失败

### ISSUE THREAD

**Issue by readreamer23** [openkruise/kruise#1476]
helm install kruise  kurise.tgz安装失败
报错提示如下：
statueful.apps.kruise.io is invalid spec.conversion.webhookclientconfig:required value:required when stratey is set to webhook,but not allowed because the customResourceWebhookConversion feature is disabled
最后从heml list看kruise还装上了，但是status是failed状态。
请问大家有遇到类似问题吗？怎么才能在低版本的k8s上成功安装0.10.2版本的openkruise呢？

**Comment by zmberg** [comment]
@readreamer23 你的 k8s 的这个feaetureGate 需要打开昂。。
![image](https://github.com/openkruise/kruise/assets/25051767/9db93200-03e1-47d0-99cf-672a5b18dd83)

**Comment by readreamer23** [comment]
请问怎么操作才能打开？

**Comment by readreamer23** [comment]
请问怎么打开呢？

**Comment by zmberg** [comment]
@readreamer23 这是k8s 的featureGate吧，你官网搜一下如何打开吧。

**Comment by readreamer23** [comment]
好的 谢谢
