### ISSUE TITLE
[feature request] SidecarSet init containers are sorted by name when injected to target pod(s)

### ISSUE THREAD

**Issue by sheronw** [openkruise/kruise#1484]
**What would you like to be added**:
According to [SidecarSet's documentation](https://openkruise.io/docs/next/user-manuals/sidecarset/#sidecarset-features), Kruise injects init containers of `SidecarSet` by their name in ascending order. I also found that in [webhook code](https://github.com/openkruise/kruise/blob/6f1b1d4f4866ed1f7a8bb75104ab74f3a19252d2/pkg/webhook/pod/mutating/sidecarset.go#L142), a sorting is done before appending `SidecarSet`'s init containers to the target pod.

Maybe this feature is too trivial to be added, would adding prefix to the name of init container a good workaround to preserve the sequence? (e.g. `1-init-container-to-be-executed-first`, `2-init-container-to-be-executed-later`) Or there is a better way to enforce precedence?

**Why is this needed**:
Just curious, what's the reason behind this design decision? As for k8s pod's case, init containers run to completion sequentially, but the original sequence of injected init container from `SidecarSet` is changed by the sorting.

**Comment by ls-2018** [comment]
@sheronw 
This order specifies the order in which dependent keys are added in the corresponding configmap.
If a key in a configmap is attached to a container, it will remain pending if the key does not exist.

I think the existing features can meet your needs.
