### ISSUE TITLE
[feature request] JobSidecarTerminator support exec sidecar preStop bash

### ISSUE THREAD

**Issue by zmberg** [openkruise/kruise#1486]
**What would you like to be added**:
[job sidecar terminator](https://openkruise.io/docs/user-manuals/jobsidecarterminator) can watch and terminate sidecar containers for such job-type Pods when its main containers completed. 

But, currently jobsidecarterminator does not execute the sidecar preStop bash.

Expectly, jobsidecarterminator also can execute sidecar container preStop bash. The relevant code https://github.com/openkruise/kruise/blob/master/pkg/controller/sidecarterminator/kill_container_action.go#L52

**Comment by huangchenzhao** [comment]
hello, I am new to kruise, and I want to try this issue :)
