### ISSUE TITLE
[BUG] ImageID unchanged, in-place upgrade block

### ISSUE THREAD

**Issue by zmberg** [openkruise/kruise#1493]
When the image is changed from docker.io/library/nginx:alpine to nginx:alpine, in-place upgrades block.
**What happened**:
```
apiVersion: apps.kruise.io/v1beta1
kind: StatefulSet
metadata:
  name: sample-res
spec:
  podManagementPolicy: Parallel
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sample
  serviceName: fake-service
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
        # docker.io/library/nginx:alpine
        - image: nginx:alpine
          imagePullPolicy: Always
          name: main
      dnsPolicy: ClusterFirst
      readinessGates:
        - conditionType: InPlaceUpdateReady
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
      minReadySeconds: 0
      partition: 0
      podUpdatePolicy: InPlaceIfPossible
    type: RollingUpdate

```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kruise version: v1.5.1
- Kubernetes version (use `kubectl version`): 1.20.x
- containerd: 1.5.13
- Install details (e.g. helm install args):
- Others:

**Comment by diannaowa** [comment]
Is kruise-daemon running successfully on all nodes?
