### ISSUE TITLE
[feature request] 当运行时使用containerd时ImagePullJob支持调用cri接口

### ISSUE THREAD

**Issue by wangyx2464** [openkruise/kruise#1496]
**What would you like to be added**:
目前使用云平台的K8s环境提供运行时为containerd 1.16.x，使用imagepulljob执行镜像预热时报错“http: server gave HTTP response to HTTPS client”，且验证crictl和ctr两种命令行方式拉取镜像，ctrctl可以正常拉取，而ctr结果与镜像预热报错一致，推断云平台提供的containerd仅完成了cri相关实现，而镜像预热调用的应该是containerd自身接口而不是cri接口。

**Why is this needed**:
从与k8s整合考虑，支撑cri接口方式对用户来说可以不需要关注、调整containerd配置，更友好一些。或者能否支持imagepulljob指定客户端协议（这个方案我也不确定对这个问题是否有效，随口一聊）。

**Comment by furykerry** [comment]
what is your openkruise version, now openkruise always use CRI runtime if possible
