### ISSUE TITLE
Advanced DaemonSet 修改 Spec.Selector 导致旧 pod 残留

### ISSUE THREAD

**Issue by bitpeng** [openkruise/kruise#1498]
OpenKruise 用户，使用过程中有如下疑问，因此向社区寻求帮助。
1. k8s 标准的工作负载资源如 Deployment, StatefulSet, DaemonSet 的 Spec.Selector 字段都是 immutable；
2. OpenKruise的 CloneSet，Advanced StatefulSet 的 Spec.Selector 字段也是禁止更改的。参见：

`./pkg/webhook/cloneset/validating/validation.go:199:            allErrs = append(allErrs, field.Forbidden(field.NewPath("spec"), "updates to cloneset spec for fields other than 'replicas', 'template', 'lifecycle', 'scaleStrategy', 'updateStrategy', 'minReadySeconds', 'volumeClaimTemplates' and 'revisionHistoryLimit' are forbidden"))
`
`
./pkg/webhook/statefulset/validating/statefulset_validation.go:329:             allErrs = append(allErrs, field.Forbidden(field.NewPath("spec"), "updates to statefulset spec for fields other than 'replicas', 'template', 'reserveOrdinals', 'lifecycle', 'revisionHistoryLimit', 'persistentVolumeClaimRetentionPolicy', `volumeClaimTemplates` and 'updateStrategy' are forbidden"))
`

3. 但是 Advanced DaemonSet 的 Spec.Selector 字段却没有不能修改的限制，并且修改该字段后，新 pod 重建成功，且旧 pod 依然残留（旧 pod OwnerReference 属性被删除）；
4. 请问 Advanced DaemonSet 的 Spec.Selector 字段被设置为可修改且修改后旧 Pod 依然残留，这是特性还是 bug 呢？如果是 特性，该特性有什么作用呢？

**Comment by zmberg** [comment]
@bitpeng 你是正确的，确实是一个BUG。不知道社区是否有同学愿意修复，参考 [CloneSet 实现](https://github.com/openkruise/kruise/blob/master/pkg/webhook/cloneset/validating/cloneset_create_update_handler.go#L67)。
