### ISSUE TITLE
[feature request] 是否存在一种 gsstate 不允许缩容时回收 pod

### ISSUE THREAD

**Issue by yourihua** [openkruise/kruise#1500]
**What would you like to be added**:
是否存在这种状态

**Why is this needed**:
当需要严格控制 pod 不被允许回收时可以设置这样的 gstate，例如根据人数扩容了广场类型的 gameplay，人数下降时触发缩容逻辑，当时 gameplay 又存在玩家时，gsstate 为不被允许回收，则可以满足。

**Comment by chrisliu1995** [comment]
是可以的。GameServer只有处于opsState为WaitToBeDeleted的时候才会被缩容，其他情况下不允许缩容。这是OKG的自动伸缩机制。具体可以参考文档：https://openkruise.io/zh/kruisegame/user-manuals/gameservers-scale#%E6%B8%B8%E6%88%8F%E6%9C%8D%E7%9A%84%E6%B0%B4%E5%B9%B3%E8%87%AA%E5%8A%A8%E4%BC%B8%E7%BC%A9

**Comment by yourihua** [comment]
> 是可以的。GameServer只有处于opsState为WaitToBeDeleted的时候才会被缩容，其他情况下不允许缩容。这是OKG的自动伸缩机制。具体可以参考文档：https://openkruise.io/zh/kruisegame/user-manuals/gameservers-scale#%E6%B8%B8%E6%88%8F%E6%9C%8D%E7%9A%84%E6%B0%B4%E5%B9%B3%E8%87%AA%E5%8A%A8%E4%BC%B8%E7%BC%A9

我参考 https://openkruise.io/zh/kruisegame/user-manuals/gameservers-scale/ 这篇文档，发现只是回收优先级不同，一样也会回收？

**Comment by chrisliu1995** [comment]
> > 是可以的。GameServer只有处于opsState为WaitToBeDeleted的时候才会被缩容，其他情况下不允许缩容。这是OKG的自动伸缩机制。具体可以参考文档：https://openkruise.io/zh/kruisegame/user-manuals/gameservers-scale#%E6%B8%B8%E6%88%8F%E6%9C%8D%E7%9A%84%E6%B0%B4%E5%B9%B3%E8%87%AA%E5%8A%A8%E4%BC%B8%E7%BC%A9
> 
> 我参考 https://openkruise.io/zh/kruisegame/user-manuals/gameservers-scale/ 这篇文档，发现只是回收优先级不同，一样也会回收？

自动和手动是两种情况。自动是通过keda external scaler进行了副本数目的调整，只会缩WaitToBeDeleted的gs；而在手动调整副本数目的时候gss不会做强制地保护。使用自动伸缩可以满足您的需求。
