### ISSUE TITLE
can not found the v1.4.1 tag in releases 

### ISSUE THREAD

**Issue by yanhongchang** [openkruise/kruise#1504]
**What would you like to be added**:
please add the v1.4.1 release or tag

**Why is this needed**:
I want install kruise  v1.4.1 by helm, but I can not found the v1.4.1 release or tag in kruise project, I need to know which commit is the v.1.4.1.

**Comment by im-jinxinwang** [comment]
Hi @yanhongchang 
![image](https://github.com/openkruise/kruise/assets/39941928/6d8ab748-0f96-4e65-95c8-e0476257dc16)

**Comment by yanhongchang** [comment]
> Hi @yanhongchang ![image](https://private-user-images.githubusercontent.com/39941928/306192337-6d8ab748-0f96-4e65-95c8-e0476257dc16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0ODMwODYsIm5iZiI6MTcwODQ4Mjc4NiwicGF0aCI6Ii8zOTk0MTkyOC8zMDYxOTIzMzctNmQ4YWI3NDgtMGY5Ni00ZTY1LTk1YzgtZTA0NzYyNTdkYzE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDAyMzMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3NDQxYzMyNWE3MDJmYTNkMzkxZTVjOWYwZGQ4MmU5ZmQ5NWZlOWIzOWE2Njk1YTkxYzlkYjIzNmU1NzRjOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gZ7MVbawf7FW1TQS4S00iMrH5OjN7bOdUIjwL-0hLBo)

Thanks for you reply, but I want to know the v1.4.1 in openkruise/kruise project instead of the openkruise/charts.
