### ISSUE TITLE
[BUG] K8s1.21 安装kruise 提示docker客户端版本过低

### ISSUE THREAD

**Issue by zhujg6** [openkruise/kruise#1508]
**What happened**:

`W0220 09:22:32.434558       1 factory.go:119] Failed to list images for docker (unix:///hostvarrun/docker.sock, unix:///hostvarrun/dockershim.sock): Error response from daemon: client version 1.23 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version
F0220 09:22:32.434578       1 main.go:66] Failed to new daemon: failed to new runtime factory: Error response from daemon: client version 1.23 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version`
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
K8s 1.21版本 container-runtime docker://25.0.3  安装kruise kruise-daemonSet报下面的错误 
**Anything else we need to know?**:
我看了下源码 这块使用了docker API 指定死了 1.23版本是否和这个有关系？
`c, err := dockerapi.NewClient(d.runtimeURI, "1.23", nil, nil)`

**Environment**:
- Kruise version: v1.5.2 
- Kubernetes version (use `kubectl version`): 1.21
- Install details (e.g. helm install args): helm install kruise openkruise/kruise --version 1.5.2 --set manager.image.repository=xxx.harbor:5000/xxx/kruise-manager --kubeconfig ~/Desktop/xxx-cluster1.kubeconfig
- Others:

**Comment by furykerry** [comment]
it seems Docker removed support for API version older than 1.24, openkruise has not yet support newer version of Docker since many our users had switch from Docker to Containerd. You're welcome to submit patch for newer Docker support
