### ISSUE TITLE
Export defaults package to the kruise-api repo

### ISSUE THREAD

**Issue by ahmetb** [openkruise/kruise#1509]
We're using CloneSet v1alpha1 in a production setting, and our controller is racing with the CloneSet defaulting webhook.

When we calculate a CloneSet.spec and submit it to the apiserver, the defaulting happens. Next time we get the object, we reconcile the managed CloneSet again from scratch (without the defaults), so an extra "Update" happens (because what we calculated != what we got via informer).

We want to use the `defaults.SetDefaultsCloneSet`  method https://github.com/openkruise/kruise/blob/5421ee7c8e9e54ec38c1c1e20f4deb4a722f47a7/apis/apps/defaults/v1alpha1.go#L256 however it is hellish to import the kruise repo due to its imports e.g. 

- 	k8s.io/kube-scheduler v0.0.0
- 	github.com/docker/distribution v2.8.2+incompatible
- 	github.com/google/cadvisor v0.39.3
- 	github.com/heketi/heketi v10.3.0+incompatible
- 	github.com/ishidawataru/sctp v0.0.0-20190723014705-7c296d48a2b5
- 	github.com/moby/ipvs v1.0.1

and we're not looking to import these packages.

It would be ideal 

1. if you copy the `defaults` package to the https://godoc.org/github.com/openkruise/kruise-api
2. make the `SetDefaultsCloneSets` method **versioned** i.e. define it directly on the `v1alpha1.CloneSet` type.

Appreciate if you can address this.

**Comment by furykerry** [comment]
it may not be the best solution to determine whether the cloneset is reconciled or not. The defaulting logics are the implementation detail of openkruise. For example, SetDefaultsCloneSets will reference the package "k8s.io/kubernetes/pkg/apis/core/v1" not just "k8s.io/api/core/v1". And if there is other mutating webhook that alter cloneset object, the logic also breaks. Maybe one solution is to record the update cloneset spec in the cloneset annotation or other CR.

**Comment by ahmetb** [comment]
I think it is not an internal implementation detail. It's standard practice to offer such a method just like core APIs do. 

We already disable PodTemplate defaulting feature gate on Kruise, so realistically we're only interested in the Kruise-specific fields. 

As you noted, this defaulting won't be guaranteed and susceptible to library version vs API version drifts but we'll take it. :)

**Comment by manan1979** [comment]
I want to try to solve this issue, can you assign it to me ?

**Comment by ahmetb** [comment]
We can actually close this issue. I realized this pkg imports `k8s.io/kubernetes` module, which is a massive pain in the back to import in any Go project.
