### ISSUE TITLE
v1.5.2 release changlog and tgz doesn't match the code updates in v1.5.2 git tag

### ISSUE THREAD

**Issue by chenchun** [openkruise/kruise#1513]
**What happened**:
It seems weird to me that the https://github.com/openkruise/kruise/commits/v1.5.2 merged https://github.com/openkruise/kruise/pull/1385, whereas the https://github.com/openkruise/charts/releases/download/kruise-1.5.2/kruise-1.5.2.tgz doesn't contain the crd updates of imagePullPolicy field in kruise/templates/apps.kruise.io_imagelistpulljobs.yaml and the v1.5.2
 https://github.com/openkruise/kruise/blob/master/CHANGELOG.md doesn't mention this feature.
So I have to wait for the next release to use https://github.com/openkruise/kruise/pull/1385?

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kruise version:
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Others:

**Comment by zmberg** [comment]
@chenchun #1385 is a new feature merged in after 1.5.0, 1.5.x will theoretically only cherry-pick some specific security or bugfixes. we'll be looking at hitting 1.6.0 in the near future to make sure that's the feature!

**Comment by chenchun** [comment]
> 1.5.x will theoretically only cherry-pick some specific security or bugfixes.

I agree with this principle, but it seems this is not what happened. https://github.com/openkruise/kruise/commits/v1.5.2 contains the commit in https://github.com/openkruise/kruise/pull/1385
