### ISSUE TITLE
[BUG] 下发了一批镜像预热任务似乎一直不能完成所有节点的预热，也没有失败的情况

### ISSUE THREAD

**Issue by GeekWolfBoy** [openkruise/kruise#1517]
**What happened**:
<img width="1104" alt="image" src="https://github.com/openkruise/kruise/assets/12298523/486275e8-1f83-4f48-a949-3e3303bd8024">

**What you expected to happen**:
完成所有节点的预热
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
<img width="1264" alt="image" src="https://github.com/openkruise/kruise/assets/12298523/8aa888d9-b51d-4066-920a-87ab99e94429">

**Environment**:
- Kruise version:
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Others:

**Comment by zmberg** [comment]
下面的配置3600S 才会超时的，估计是有Node异常，或者拉镜像太慢或者失败了。。。可以等待超时后，看看异常Node 的kruise-daemon 日志来进一步排查
```yaml
pullPolicy:                
    backoffLimit: 3
    timeoutSeconds: 1200
```

**Comment by GeekWolfBoy** [comment]
> 下面的配置3600S 才会超时的，估计是有Node异常，或者拉镜像太慢或者失败了。。。可以等待超时后，看看异常Node 的kruise-daemon 日志来进一步排查
> 
> ```yaml
> pullPolicy:                
>     backoffLimit: 3
>     timeoutSeconds: 1200
> ```

依然不能成功

**Comment by zmberg** [comment]
你能知道哪些失败的Node吗？ 看一下 kruise-daemon 的日志

**Comment by WangZhen-Ddm** [comment]
<img width="1154" alt="image" src="https://github.com/openkruise/kruise/assets/31559770/87854d84-9e06-461a-bdc9-9b509bef9983">
同样的问题。查看kruise-controller报错，是在下发ImageListPullJob的时候，并发场景下会产生nodeImage.spec镜像被覆盖的问题。这导致nodeImage中的desired数量不符合预期。具体报错代码段如上。
