### ISSUE TITLE
[BUG] Can't install due to webhook race condition

### ISSUE THREAD

**Issue by cerebrate** [openkruise/kruise#1521]
**What happened**:

When I try to install Kruise using Helm (`helm install kruise kruise/kruise --namespace=kruise-system --values=./kruise-chart-values.yaml --version=1.5.2`) with the chart values below:

```
installation:
  createNamespace: false

manager:
  replicas: 1
```

...while the _kruise-daemon_ pods start up correctly, no _kruise-controller-manager_ pod is ever created, and that deployment remains in _ReplicaFailure_ state. The following error message is given on the underlying ReplicaSet:

```
Error creating: Internal error occurred: failed calling webhook "mpod.kb.io": failed to call webhook: Post "https://kruise-webhook-service.kruise-system.svc:443/mutate-pod?timeout=10s": dial tcp 10.96.134.53:443: connect: connection refused
```

(On checking, this service indeed has no associated endpoints.)
 
**What you expected to happen**:

The Kruise install to complete successfully.

**How to reproduce it (as minimally and precisely as possible)**:

This reliably happens for me on installation. No other repro steps are required.

**Anything else we need to know?**:

**Environment**:
- Kruise version: 1.5.2
- Kubernetes version (use `kubectl version`): 1.29.2
- Install details (e.g. helm install args): As above.

**Comment by furykerry** [comment]
it seems that you pass createNamespace=false, please make sure the kruise installation namespace( kruise-system) has the label `control-plane=openkruise`, kruise webhook will skip namespace with this label

**Comment by furykerry** [comment]
we can enhance the webhook configuration to utilize the default namespace label 'kubernetes.io/metadata.name'  so that it works with createNamespace=false

**Comment by cerebrate** [comment]
Ah, thank you!

(We were caught out by our own local policies, which require creating the namespaces for all apps in a separate operation before the app install. I've added the necessary label to the namespace docs so that that shouldn't catch us out again, even if we have to rebuild the cluster.)
