### ISSUE TITLE
[feature request] 是否可以支持cloneset重建升级复用PVC

### ISSUE THREAD

**Issue by lucaspeng12138** [openkruise/kruise#1529]
是否可以支持cloneset重建升级复用PVC

因为PVC上的数据资源比较重要，希望复用，但同时需要修改initContainer的镜像之类的，需要重建pod的场景

**Comment by zmberg** [comment]
@lucaspeng12138 这种场景我们建议使用 advanced statefulSet 昂。。因为，如果升级也复用PVC，那其实也就是 statefulset 了。

**Comment by lucaspeng12138** [comment]
@zmberg 但是在statefulset下，却无法完全解决缩容任意节点后，产生的扩容和重建等问题，是必需有顺序的

**Comment by furykerry** [comment]
你能详细说下什么叫做扩容和重建是有顺序的么？statefulset 默认扩容发布都是按照ordinal 顺序来的， 什么场景顺序不满足呢

**Comment by lucaspeng12138** [comment]
@furykerry 抱歉我没有表达清楚，我想说需要扩容和重建是和前面已有的pod无顺序关系，就像deployment一样，退出的pod就是退出了，扩容的时候无需考虑与已有pod的关系（顺序关系）

场景是在集群缩容然后扩容的情况下，希望缩容指定的Pod，然后一段时间后发生扩容，如果是statefulset，只能使用保留序号缩容指定的pod，然后扩容的时候，考虑是否解禁保留序号，这种解决方案可能会比较繁琐，而且保留序号的list越来越长，可能会对yaml和kruise的controller带来比较多的工作（同时麻烦请问保留序号的list，可以支持多长呢？多谢🙏）

另一个场景是node异常退出，我们没有办法通过pod的名称，感知是否是新的PVC（PVC上数据是可复用的），就会对业务产生一些影响，或许我们可以通过其他方式感知这个事情，但是暂时还没有比较好的方案

**Comment by zmberg** [comment]
@lucaspeng12138 今天晚上七点半会有社区会议，钉钉群，如果你方便的话，可以社区会议沟通，更加高效一些。
