### ISSUE TITLE
[BUG] when statefulset reserveOrdinals exist, scale down pvc failed

### ISSUE THREAD

**Issue by zmberg** [openkruise/kruise#1530]
**What happened**:
1. Create StatefulSet reserveOrdinals=[0], replicas = 3, pvcTemplate = log
2. Currently will create three pvc=log-web-1, log-web-2, log-web-3
3. Scale down StatefulSet replicas=2, But log-web-3 also exist.
**What you expected to happen**:
Pvc log-web-3 will be deleted.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kruise version:
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Others:

**Comment by furykerry** [comment]
fixed by https://github.com/openkruise/kruise/pull/1531
