### ISSUE TITLE
[feature request] Remove go mod vendor

### ISSUE THREAD

**Issue by zmberg** [openkruise/kruise#1533]
**What would you like to be added**:
Kruise code currently contains go mod vendor, i think we should remove it.
**Why is this needed**:

**Comment by hzliangbin** [comment]
I found it in scripts:
https://github.com/openkruise/kruise/blob/912de49a6d5eade0db5c73331c960e0fd0ef5670/scripts/generate_openapi.sh#L3
https://github.com/openkruise/kruise/blob/912de49a6d5eade0db5c73331c960e0fd0ef5670/scripts/generate_client.sh#L3

after removing the `go mod vendor`, we can't  ensure vendor dir exsits.
