### ISSUE TITLE
[feature request] StatefulSet support ordinals, and sync k8s 1.28 statefulset controller 

### ISSUE THREAD

**Issue by zmberg** [openkruise/kruise#1534]
**What would you like to be added**:
document: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#start-ordinal

**Why is this needed**:

**Comment by furykerry** [comment]
fixed by https://github.com/openkruise/kruise/pull/1648 and https://github.com/openkruise/kruise/pull/1643
