### ISSUE TITLE
[feature request] Advanced Statefulset support manage pvc 

### ISSUE THREAD

**Issue by Colvin-Y** [openkruise/kruise#1537]
**What would you like to be added**:
Once user change asts .spec.volumeClaimTemplates.spec.resources.requests.storage, try resize pvc.\
So asts may need provide some pvc scale policy:
1. only scale-up
2. scale-up + scale-down(may failed)
3. when replicas changed, can create/remove pvc

**Why is this needed**:
In current situation, we always control pvc by our self, volumeClaimTemplates is only used when asts creating

**Comment by furykerry** [comment]
duplicate of. https://github.com/openkruise/kruise/issues/905, we're considering to implement this
