### ISSUE TITLE
[feature request] Advanced support manage headless service

### ISSUE THREAD

**Issue by Colvin-Y** [openkruise/kruise#1538]
**What would you like to be added**:
If user assigned asts .spec.serviceName and it not exists, asts controller will create a headless service.
In this case, asts may need support to manage the lifecycle of the headless svc, and provide some policy to open/close this feature. 

**Why is this needed**:
In most cases, user will use headless service to access pod owned by asts

**Comment by furykerry** [comment]
what do you mean by manage the lifecycle of headless svc? can you elaborate what operator needed over the svc other that creation and deletion?

**Comment by Colvin-Y** [comment]
> what do you mean by manage the lifecycle of headless svc? can you elaborate what operation is needed over the svc other that creation and deletion?

Yes, I mean asts controller can manage lifecycle of the headless svc created by itself.  I can't think of anything else at the moment, but create asts with headless will be useful, I think :)

**Comment by furykerry** [comment]
> I can't think of anything else at the moment, but create asts with headless will be useful, I think :)
If you only want to create and delete svc along with asts, , it can be achieved using helm chart, kruise workload is not designed to replace k8s package manager.

**Comment by Colvin-Y** [comment]
> > I can't think of anything else at the moment, but create asts with headless will be useful, I think :)
> 
> If you only want to create and delete svc along with asts, , it can be achieved using helm chart, kruise workload is not designed to replace k8s package manager.

Good suggestion, thx
