### ISSUE TITLE
[feature request] Support a SidecarSet canary on a newly created pod with version control for injection and selector

### ISSUE THREAD

**Issue by amirakhmedov** [openkruise/kruise#1539]
**What would you like to be added**:
Add support for a `SidecarSet` canary on a newly created pod with a canary labels set using [version control for injection](https://openkruise.io/docs/user-manuals/sidecarset/#version-control-for-injection) and [selector](https://openkruise.io/docs/user-manuals/sidecarset/#selector).

**Why is this needed**:
I want to use the combination of the two to canary a new version of a sidecar on pods with a canary label attached. This will guarantee that newly created pods will get injected a stable version of the sidecar. It works fine if only in-place update is possible. But if in-place update is impossible, let's say a canary version requires a new env variable to be added, then a newly created pod with a canary label set on it still gets injected a stable version of the sidecar.
I would like to see a mutating webhook to take into consideration `.spec.updateStrategy.selector` to make a decision which version of a `SidecarSet` (stable or canary) to use.

**Comment by zmberg** [comment]
> I would like to see a mutating webhook to take into consideration .spec.updateStrategy.selector to make a decision which version of a SidecarSet (stable or canary) to use.

@amirakhmedov Good idea. Very good optimization.

**Comment by EraKin575** [comment]
@zmberg is this issue still relevant?
