### ISSUE TITLE
[feature request] support structured logging 

### ISSUE THREAD

**Issue by furykerry** [openkruise/kruise#1551]
**What would you like to be added**:
Follow the proposal of kubernetes, OpenKruise should use structured logging instead of  unstructured logging and shall output json format if argument `--logging-format=json` is used. 
https://kubernetes.io/blog/2020/09/04/kubernetes-1-19-introducing-structured-logs/

Pick a file or directory that you would like to improve and [migrate existing log calls to use structured logs](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md). It's a great and easy way to make your first contribution to Kruise!

**Why is this needed**:
OpenKruise currently use unstructured plain text as the logging format, which may logging processing hard. 

- [x] pkg/control
- [x] pkg/controller
- [ ] pkg/daemon
- [ ] pkg/webhook
- [ ] pkg/util
- [ ] cmd

**Comment by MajLuu** [comment]
/assign 
I will try to add structured logging in `pkg/control` dir, if i do it quickly, I will be pleasure to try other instances.

**Comment by manan1979** [comment]
is this issue open?

**Comment by furykerry** [comment]
yes，it is still open, other packages also need  structured logging, i've updated the issue to list the packages need  structured logging change

**Comment by jairuigou** [comment]
Hi, I want to try `pkg/controller` for my first commit to Kruise. Is anyone else working on this package?
