### ISSUE TITLE
[feature request] Change rollout CustomResourceDefinition configuration conversionReviewVersions to v1

### ISSUE THREAD

**Issue by zmberg** [openkruise/kruise#1558]
**What would you like to be added**:
ConversionReview v1beta1 deprecated in v1.16 in favor of apiextensions.k8s.io/v1, refer to: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#webhook-request-and-response

1. Change rollout CustomResourceDefinition configuration conversionReviewVersions to v1, related code: https://github.com/openkruise/rollouts/blob/master/config/crd/patches/webhook_in_batchreleases.yaml and https://github.com/openkruise/rollouts/blob/master/config/crd/patches/webhook_in_rollouts.yaml
2. webhook controller, related code: https://github.com/openkruise/rollouts/blob/master/pkg/webhook/util/crd/crd.go#L79

**Why is this needed**:

**Comment by im-jinxinwang** [comment]
@zmberg 
I understand that it is enough to remove v1beta1?
```go
newCRD.Spec.Conversion.Webhook = &apiextensionsv1.WebhookConversion{
    ClientConfig:             webhookConfig.DeepCopy(),
    ConversionReviewVersions: []string{"v1"},
}

```

**Comment by chenshiwei-io** [comment]
Is it just changing 'v1beta1' to 'v1' in the configuration of these two CRDs, and then deleting 'v1beta1' from the code? I want to try submitting the feature request."
/assign

**Comment by chenshiwei-io** [comment]
@zmberg This feature belongs to [#rollouts](https://github.com/openkruise/rollouts), Is the rollouts PR I submitted associated with this issue?
