### ISSUE TITLE
Slack link is no more active

### ISSUE THREAD

**Issue by karancode** [openkruise/kruise#158]
The slack channel link on the github readme has been expired ([slack channel](https://join.slack.com/t/kruise-workspace/shared_invite/enQtNjU5NzQ0ODcyNjYzLWMzZDI5NTM3ZjM1MGY2Mjg1NzU4ZjBjMDJmNjZmZTEwYTZkMzk4ZTAzNmY5NTczODhkZDU2NzVhM2I2MzNmODc))
> Slack: channel address

**Comment by Fei-Guo** [comment]
It does not in my computer. @FillZpp How about yours?

**Comment by FillZpp** [comment]
@Fei-Guo Me, too.  Perhaps it works for ones have signed in?

**Comment by karancode** [comment]
@FillZpp I think so too. I see [this](https://ibb.co/19HY5Xp) when I try to join!
