### ISSUE TITLE
[BUG] tag v1.6.2 unit-test TestMatchRegistryAuths case4(test4) failed

### ISSUE THREAD

**Issue by Colvin-Y** [openkruise/kruise#1583]
**What happened**:
I use kruise tag v1.6.2 to  run unit-test with go version 1.19 & 1.20
**What you expected to happen**:
All unit-test should pass but case TestMatchRegistryAuths(https://github.com/openkruise/kruise/blob/v1.6.2/pkg/daemon/criruntime/imageruntime/helpers_test.go#L89) failed,
**How to reproduce it (as minimally and precisely as possible)**:
Run test case TestMatchRegistryAuths
**Anything else we need to know?**:

**Environment**:
- Kruise version: tag v1.6.2
- Kubernetes version (use `kubectl version`): unit-test
- Install details (e.g. helm install args):
- Others:

**Comment by ABNER-1** [comment]
I attempted to reproduce it, but it passed. Can you still reproduce it now?

**Comment by Colvin-Y** [comment]
> I attempted to reproduce it, but it passed. Can you still reproduce it now?

yes, maybe I use M1? I'm really confused

**Comment by ABNER-1** [comment]
Hi, @Colvin-Y .
I successfully reproduced the issue and discovered that it fails on any PC without Docker installed.

The core code stack is here:
```
credentialprovider.ReadDockerConfigJSONFile (config.go:146) k8s.io/kubernetes/pkg/credentialprovider
credentialprovider.ReadDockerConfigFile (config.go:171) k8s.io/kubernetes/pkg/credentialprovider
credentialprovider.(*defaultDockerConfigProvider).Provide (provider.go:79) k8s.io/kubernetes/pkg/credentialprovider
credentialprovider.(*CachingDockerConfigProvider).Provide (provider.go:103) k8s.io/kubernetes/pkg/credentialprovider
credentialprovider.(*providersDockerKeyring).Lookup (keyring.go:269) k8s.io/kubernetes/pkg/credentialprovider
credentialprovider.UnionDockerKeyring.Lookup (keyring.go:299) k8s.io/kubernetes/pkg/credentialprovider
<autogenerated>:2
secret.ConvertToRegistryAuths (parse.go:33) github.com/openkruise/kruise/pkg/util/secret
imageruntime.TestMatchRegistryAuths.func6 (helpers_test.go:112) github.com/openkruise/kruise/pkg/daemon/criruntime/imageruntime
testing.tRunner (testing.go:1689) testing
testing.(*T).Run.gowrap1 (testing.go:1742) testing
runtime.goexit (asm_arm64.s:1222) runtime
 - Async Stack Trace
testing.(*T).Run (testing.go:1742) testing
```

`ReadDockerConfigJSONFile(nil)` will returns different results based on whether Docker is installed.

**Comment by Colvin-Y** [comment]
> ReadDockerConfigJSONFile

Hi, @ABNER-1.
Thanks for your reply, but actually I've installed docker
```
➜  ~ cat ~/.docker/config.json
{
	"auths": {
	},
	"credsStore": "desktop",
	"currentContext": "desktop-linux"
}
```
And I've tried to print the result from function `secret.ConvertToRegistryAuths(cs.GetSecrets(), repoToPull)`
```
infos: [{echoserver test}]
--- FAIL: TestMatchRegistryAuths (0.00s)
    --- FAIL: TestMatchRegistryAuths/test4 (0.00s)
        helpers_test.go:120: convertToRegistryAuths failed
FAIL
```

What config should I check?

**Comment by ABNER-1** [comment]
I plan to debug it again this weekend. However, if you'd like to take a crack at it, please feel free to do so. @Colvin-Y

**Comment by Colvin-Y** [comment]
> I plan to debug it again this weekend. However, if you'd like to take a crack at it, please feel free to do so. @Colvin-Y

Thank u! I also plan to figure out what the whole test cases are doing. @ABNER-1

**Comment by ABNER-1** [comment]
![image](https://github.com/openkruise/kruise/assets/24547351/dc608ea1-3ca2-46eb-b967-2e0804098ef6)
```go
func readDockerConfigJSONFileFromBytes(contents []byte) (cfg DockerConfig, err error) {
	var cfgJSON DockerConfigJSON
	if err = json.Unmarshal(contents, &cfgJSON); err != nil {
		return nil, errors.New("error occurred while trying to unmarshal json")
	}
	cfg = cfgJSON.Auths
	return
}
```

The 'auths' value in docker/config.json will be regarded as authentication information for the public Docker registry. It should be disregarded in Test Case 4.

**Comment by ABNER-1** [comment]
A simple solution in my opinion:
`len(infos) != cs.Expect`  =>  `len(infos) < cs.Expect`
refer code: https://github.com/openkruise/kruise/blob/a836e90578067d0c44372bc3be116cc3d06babed/pkg/daemon/criruntime/imageruntime/helpers_test.go#L116

**Comment by Colvin-Y** [comment]
> ![image](https://private-user-images.githubusercontent.com/24547351/331962724-dc608ea1-3ca2-46eb-b967-2e0804098ef6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3OTY3NDksIm5iZiI6MTcxNjc5NjQ0OSwicGF0aCI6Ii8yNDU0NzM1MS8zMzE5NjI3MjQtZGM2MDhlYTEtM2NhMi00NmViLWI5NjctMmUwODA0MDk4ZWY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDA3NTQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyOGEyOWE1YTZhODY4ZWJjZmVmNmMzYWY3YTAwMTJkMWZmNjc3ODk1M2VjYmE4ZWQ3YzgwNmNjZGZiN2Y0ZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7-NqSaJKqwZwV8OhzBeLy7FM_t6wFvWNVlpWBmsG4II)
> 
> ```go
> func readDockerConfigJSONFileFromBytes(contents []byte) (cfg DockerConfig, err error) {
> 	var cfgJSON DockerConfigJSON
> 	if err = json.Unmarshal(contents, &cfgJSON); err != nil {
> 		return nil, errors.New("error occurred while trying to unmarshal json")
> 	}
> 	cfg = cfgJSON.Auths
> 	return
> }
> ```
> 
> The 'auths' value in docker/config.json will be regarded as authentication information for the public Docker registry. It should be disregarded in Test Case 4.

Got it!  thx!
