### ISSUE TITLE
[BUG] 开发环境报错咨询

### ISSUE THREAD

**Issue by zonghaishang** [openkruise/kruise#1594]
**What happened**:

goland mac环境打开工程，获取布道相关依赖，控制台报错, 需要做什么配置吗？：

```
GOROOT=/Users/yiji/gosdk/go1.22.2 #gosetup
GOPATH=/Users/yiji/go #gosetup
/Users/yiji/gosdk/go1.22.2/bin/go list -modfile=/Users/yiji/opensource/kruise/go.mod -m -json -mod=mod all #gosetup
go: k8s.io/cli-runtime@v0.0.0: invalid version: unknown revision v0.0.0
go: k8s.io/cluster-bootstrap@v0.0.0: invalid version: unknown revision v0.0.0
go: k8s.io/kube-aggregator@v0.0.0: invalid version: unknown revision v0.0.0
go: k8s.io/kube-controller-manager@v0.0.0: invalid version: unknown revision v0.0.0
go: k8s.io/kube-proxy@v0.0.0: invalid version: unknown revision v0.0.0
go: k8s.io/kubectl@v0.0.0: invalid version: unknown revision v0.0.0
go: k8s.io/legacy-cloud-providers@v0.0.0: invalid version: unknown revision v0.0.0
go: k8s.io/metrics@v0.0.0: invalid version: unknown revision v0.0.0
go: k8s.io/pod-security-admission@v0.0.0: invalid version: unknown revision v0.0.0
go: k8s.io/sample-apiserver@v0.0.0: invalid version: unknown revision v0.0.0
```

<img width="1749" alt="image" src="https://github.com/openkruise/kruise/assets/15549777/fa5943ef-8ddb-4191-bc3c-885a794b6d8a">

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kruise version:
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Others:

**Comment by ABNER-1** [comment]
这是一个已知问题，是因为这个版本去除了 vendor 依赖导致的。

**Comment by ABNER-1** [comment]
这是一个已知问题，是因为这个版本去除了 vendor 依赖导致的

**Comment by ABNER-1** [comment]
这是一个已知问题，是因为这个版本去除了 vendor 依赖导致的。我在 PR 里尝试进行了解决，但尚未合入。在这之前，你可以参考该解决方案进行解决。

**Comment by zonghaishang** [comment]
我通过docs里面 contributing   go mod vendor管理 ，本地可以方便看代码了。 等你这个pr合并，我pull代码试试
<img width="1375" alt="image" src="https://github.com/openkruise/kruise/assets/15549777/3e88ae74-c902-494d-9123-74b2176c1189">

**Comment by zonghaishang** [comment]
thanks, it works now, close it
