### ISSUE TITLE
[feature request] Using sidecar type container for SidecarSet

### ISSUE THREAD

**Issue by resouer** [openkruise/kruise#161]
**What would you like to be added**:

We may want to consider have https://github.com/kubernetes/enhancements/blob/master/keps/sig-apps/sidecarcontainers.md in plan as soon as it's ready. 

Let's use this issue as tracker.

1. feature tracker: https://github.com/kubernetes/enhancements/issues/753
2. main kubelet change: https://github.com/kubernetes/kubernetes/pull/80744

**Comment by furykerry** [comment]
sidecar type container in the kep doesn't align well with the one in sidecarset. sidecarset can operator *any" container in a pod, no matter it is a "sidecar", an  "ambasador" or an "adaptor" per [pod design pattern](https://matthewpalmer.net/kubernetes-app-developer/articles/multi-container-pod-design-patterns.html)
