### ISSUE TITLE
[feature request] ResourceDistribution point at secret

### ISSUE THREAD

**Issue by kfox1111** [openkruise/kruise#1612]
**What would you like to be added**:

The ability for a ResourceDistribution to point at an existing secret to sync to other namespaces

**Why is this needed**:
Some tools such as cert-manager create the secret that needs to be synced to other namespaces. It can not easily be created in the ResourceDistribution object itself.

**Comment by furykerry** [comment]
can you describe the use case in more detail ? what kind of secrets and why it should be sync to other namespaces? If ResourceDistribution can reference an existing secret, it will be a potential security problem. Kruise cannot tell whether the user has the privilege to read the existing secret, sync the secret to a namespace of an un-authorized user is dangerous.

**Comment by kfox1111** [comment]
https://cert-manager.io/docs/devops-tips/syncing-secrets-across-namespaces/ has the use case and a list of other tools doing the same thing.

**Comment by kfox1111** [comment]
Still an issue
