### ISSUE TITLE
[feature request] Support cri-docker

### ISSUE THREAD

**Issue by BraceCY** [openkruise/kruise#1631]
**What would you like to be added**:
https://github.com/openkruise/kruise/blob/1c07d4d22f64fae3520b27712c50f81b8bd85b33/pkg/daemon/criruntime/factory.go#L207
criruntime will add support for cri-docker.sock

**Why is this needed**:
The community's dockershim is abandoned, but there are still many existing Kubernetes clusters that use docker runtime. Dockershim.sock is currently migrated to cri-docker.sock, so it is expected that the Kruise-Daemon component can continue to support cri-docker adaptation.

**Comment by chengjoey** [comment]
/assign

not `cri-docker.sock` but `cri-dockerd.sock`

**Comment by liangyuanpeng** [comment]
I think this is resolved, and can be close.

**Comment by furykerry** [comment]
the fix will be included in the kruise 1.7 release
