### ISSUE TITLE
[BUG] 为什么首次通过修改annotation来实现原地升级就会激活backoff定时器？

### ISSUE THREAD

**Issue by xbchaos** [openkruise/kruise#1632]
**What happened**:

我在试验通过env from annotation方案来实现原地升级。

可是经过反复多次操作发现：首次修改annotation之后，如果10分钟内再次操作，就必定会在Pod事件中看到容器先进入backoff状态、然后过10秒或几十秒才能够最终原地升级完成，相反，如果是前后两次操作的间隔超过了10分钟，就能够很顺利地完成原地升级。

根据我对backoff的理解，看起来是首次修改annotation之后backoff定时器就被激活了。

那么，这个现象是正常的吗？如果是正常的话，能优化或者通过某种方式避免吗？

（顺便提一下：如果是通过修改容器镜像来实现原地升级，每次都很顺利，不会看到容器进入backoff状态）

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

两次修改annotation的操作，间隔10分钟以内，即可复现。

**Anything else we need to know?**:

**Environment**:
- Kruise version:
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Others:

**Comment by ABNER-1** [comment]
这两种原地升级的方式其实是不一样的链路：
1. update image 走的是 kubelet 的原有机制
2. env from metadata 走的是 kruise daemon 调用 cri 的接口 stop container

**Comment by xbchaos** [comment]
> 这两种原地升级的方式其实是不一样的链路：
> 
> 1. update image 走的是 kubelet 的原有机制
> 2. env from metadata 走的是 kruise daemon 调用 cri 的接口 stop container

是的，但是有可能有某种优化措施来避免前面提到的现象吗？对于有状态应用来说，如果要花费几十秒才能完成原地升级，导致的可能是这几十秒期间都无法正常提供服务😭

**Comment by ABNER-1** [comment]
我找了下资料，这个 backoff 策略是写死的。
一般生产环境我们不会允许没有冷静期的变更，还真没遇到过这么频繁的变更

**Comment by xbchaos** [comment]
> 我找了下资料，这个 backoff 策略是写死的。 一般生产环境我们不会允许没有冷静期的变更，还真没遇到过这么频繁的变更

感谢解答！🙏
