### ISSUE TITLE
[feature request] Google Cloud's GKE Autopilot support

### ISSUE THREAD

**Issue by suyanhj** [openkruise/kruise#1649]
**What would you like to be added**:
Use openkruise in gke Autopilot

**Why is this needed**:
I need to use the automatic injection sidecar function of openkruise

**Problem**:
When using helm deployment in gke Autopilot, gke will prompt a permission denied error, as shown below
![image](https://github.com/openkruise/kruise/assets/95021771/757f8750-b389-4d21-8131-4547633b46ce)

I checked the helm template and found that HostNetwork and HostPath need to be used. I learned from the gke Autopilot help document that only partners supported by Google can complete the privilege escalation operation, such as accessing the /var/run directory of the host
gcloud about permission restrictions: https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-security

**Comment by furykerry** [comment]
sidecar injection function does not need kruise daemon, so you can just turn off the KruiseDaemon featuregate. 

you may follow the guide here : 
https://openkruise.io/docs/installation#optional-feature-gate

**Comment by zmberg** [comment]
@suyanhj So far it looks like it's the kruise-daemon component that doesn't meet the requirements, what are the main capabilities you use if you use kruise? kruise-daemon is an optional installation if you are not using capabilities like pre-download image.

helm install kruise openkruise/kruise  --set featureGates="KruiseDaemon=false"

**Comment by suyanhj** [comment]
> helm install kruise openkruise/kruise --set featureGates=“KruiseDaemon=false”

Thank you, this can be deployed successfully
