### ISSUE TITLE
[feature request] Add StatefulSet pod index as pod label 

### ISSUE THREAD

**Issue by ABNER-1** [openkruise/kruise#1660]
**What would you like to be added**:
Add StatefulSet pod index as pod label 

**Why is this needed**:
the pod index of a StatefulSet pod will now be added as a pod a label, 
upstream PR https://github.com/kubernetes/kubernetes/pull/119232
upstream KEP https://github.com/kubernetes/enhancements/pull/4019

**Comment by ABNER-1** [comment]
add kind/good-first-issue label

**Comment by cr7258** [comment]
Hello, I want to work on this issue, can you assign it to me?
