### ISSUE TITLE
[BUG] openkruise部署时daemonset启动失败，报错如下

### ISSUE THREAD

**Issue by qq547475331** [openkruise/kruise#1663]
I0717 09:21:24.408050       1 remote_runtime.go:72] "Connecting to runtime service" endpoint="unix:///hostvarrun/dockershim.sock"
I0717 09:21:24.408397       1 remote_runtime.go:117] "Validating the CRI v1 API runtime version"
W0717 09:21:24.409711       1 factory.go:121] Failed to new runtime service for docker (unix:///hostvarrun/docker.sock, unix:///hostvarrun/dockershim.sock): validate service connection: CRI v1 runtime API is not implemented for endpoint "unix:///hostvarrun/dockershim.sock": rpc error: code = Unimplemented desc = unknown service runtime.v1.RuntimeService
I0717 09:21:24.409749       1 cri.go:44] "Connecting to image service" endpoint="/hostvarrun/containerd/containerd.sock"
I0717 09:21:24.409765       1 util_unix.go:103] "Using this endpoint is deprecated, please consider using full URL format" endpoint="/hostvarrun/containerd/containerd.sock" URL="unix:///hostvarrun/containerd/containerd.sock"
I0717 09:21:24.410006       1 helpers.go:227] "Finding the CRI API image version"
E0717 09:21:24.476885       1 cri.go:61] "Failed to determine CRI image API version" err="unable to determine image API version: rpc error: code = Unimplemented desc = unknown service runtime.v1.ImageService"
W0717 09:21:24.476908       1 factory.go:103] Failed to new image service for containerd (, unix:///hostvarrun/containerd/containerd.sock): unable to determine image API version: rpc error: code = Unimplemented desc = unknown service runtime.v1.ImageService
F0717 09:21:24.476926       1 main.go:69] Failed to new daemon: failed to new runtime factory: validate service connection: CRI v1 runtime API is not implemented for endpoint "unix:///hostvarrun/dockershim.sock": rpc error: code = Unimplemented desc = unknown service runtime.v1.RuntimeService

**Comment by qq547475331** [comment]
volumeMounts:
        - mountPath: /hostvarrun
          name: runtime-socket
          readOnly: true
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kruise-daemon
      serviceAccountName: kruise-daemon
      terminationGracePeriodSeconds: 10
      tolerations:
      - operator: Exists
      volumes:
      - hostPath:
          path: /var/run
          type: ""
        name: runtime-socket

**Comment by qq547475331** [comment]
[root@longxi-master201 ~]# systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2024-07-17 16:47:14 CST; 40min ago
     Docs: https://docs.docker.com
 Main PID: 1178 (dockerd)
    Tasks: 59
   Memory: 410.0M
   CGroup: /system.slice/docker.service
           └─1178 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock

**Comment by qq547475331** [comment]
`[root@longxi-master201 ~]# cat /usr/lib/systemd/system/docker.service
[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network-online.target firewalld.service containerd.service
Wants=network-online.target
Requires=docker.socket containerd.service

[Service]
Type=notify
# the default is not to use systemd for cgroups because the delegate issues still
# exists and systemd currently does not support the cgroup feature set required
# for containers run by docker
ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
ExecReload=/bin/kill -s HUP $MAINPID
TimeoutSec=0
RestartSec=2
Restart=always

# Note that StartLimit* options were moved from "Service" to "Unit" in systemd 229.
# Both the old, and new location are accepted by systemd 229 and up, so using the old location
# to make them work for either version of systemd.
StartLimitBurst=3

# Note that StartLimitInterval was renamed to StartLimitIntervalSec in systemd 230.
# Both the old, and new name are accepted by systemd 230 and up, so using the old name to make
# this option work for either version of systemd.
StartLimitInterval=60s

# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity

# Comment TasksMax if your systemd version does not support it.
# Only systemd 226 and above support this option.
TasksMax=infinity

# set delegate yes so that systemd does not reset the cgroups of docker containers
Delegate=yes

# kill only the docker process, not all processes in the cgroup
KillMode=process
OOMScoreAdjust=-500

[Install]
WantedBy=multi-user.target
[root@longxi-master201 ~]#
`

**Comment by qq547475331** [comment]
[root@longxi-master201 ~]# cat /usr/lib/systemd/system/docker.service
[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network-online.target firewalld.service containerd.service
Wants=network-online.target
Requires=docker.socket containerd.service

[Service]
Type=notify

ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
ExecReload=/bin/kill -s HUP $MAINPID
TimeoutSec=0
RestartSec=2
Restart=always



StartLimitBurst=3


StartLimitInterval=60s


LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity


TasksMax=infinity


Delegate=yes


KillMode=process
OOMScoreAdjust=-500

[Install]
WantedBy=multi-user.target
[root@longxi-master201 ~]#

**Comment by qq547475331** [comment]
[root@longxi-master201 ~]# systemctl status docker.socket
● docker.socket - Docker Socket for the API
   Loaded: loaded (/usr/lib/systemd/system/docker.socket; disabled; vendor preset: disabled)
   Active: active (running) since Wed 2024-07-17 16:47:00 CST; 45min ago
   Listen: /var/run/docker.sock (Stream)
    Tasks: 0 (limit: 100281)
   Memory: 0B
   CGroup: /system.slice/docker.socket

7月 17 16:47:00 longxi-master201 systemd[1]: Starting Docker Socket for the API.
7月 17 16:47:00 longxi-master201 systemd[1]: Listening on Docker Socket for the API.
[root@longxi-master201 ~]# cat /usr/lib/systemd/system/docker.socket
[Unit]
Description=Docker Socket for the API

[Socket]
ListenStream=/var/run/docker.sock
SocketMode=0660
SocketUser=root
SocketGroup=docker

[Install]
WantedBy=sockets.target
[root@longxi-master201 ~]#

**Comment by ABNER-1** [comment]
从 v1.6.0 (alpha/beta) 开始，Kruise-Daemon 将不再支持 v1alpha2 CRI 的运行时。如果你关闭了 Kruise-Daemon 组件（featureGates="KruiseDaemon=false"），你依然可以在只支持 v1alpha2 CRI 的运行时节点所在集群上安装和使用 OpenKruise。

docker 只支持 v1alpha2 CRI 。
@qq547475331 

以下解决方案可供参考：
- 可以降级 kruise 到 1.5.x 
- 切换/升级运行时
- 关闭 kruise-daemon 组件

**Comment by qq547475331** [comment]
好的 多谢，已解决

**Comment by qq547475331** [comment]
`# Default values for kruise.

crds:
  managed: true

# values for kruise installation
installation:
  namespace: kruise-system
  createNamespace: true
  roleListGroups:
    - '*'

featureGates: "ImagePullJobGate=true,KruiseDaemon=false"

# KUBE_CACHE_MUTATION_DETECTOR
enableKubeCacheMutationDetector: false

manager:
  # settings for log print
  log:
    # log level for kruise-manager
    level: "4"

  replicas: 2
  image:
    repository: harbor.com.cn/openkruise/kruise-manager
    tag: v1.6.3
  webhook:
    port: 9876
  metrics:
    port: 8080
  healthProbe:
    port: 8000
  pprofAddr: "localhost:8090"

  resyncPeriod: "0"

  # resources of kruise-manager container
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
`

**Comment by wsw136** [comment]
> 从 v1.6.0 (alpha/beta) 开始，Kruise-Daemon 将不再支持 v1alpha2 CRI 的运行时。如果你关闭了 Kruise-Daemon 组件（featureGates="KruiseDaemon=false"），你依然可以在只支持 v1alpha2 CRI 的运行时节点所在集群上安装和使用 OpenKruise。
> 
> docker 只支持 v1alpha2 CRI 。 @qq547475331
> 
> 以下解决方案可供参考：
> 
> * 可以降级 kruise 到 1.5.x
> * 切换/升级运行时
> * 关闭 kruise-daemon 组件

我这边不是用docker引擎，是用containerd引擎，kruise在测试用1.7.2版本，需要怎么修改吗？kruise-daemon也是报一摸一样的错误，关闭kruise-daemon 组件有什么影响吗
