### ISSUE TITLE
[feature request] support json format logging

### ISSUE THREAD

**Issue by AiRanthem** [openkruise/kruise#1680]
**What would you like to be added**:

Follow the proposal of kubernetes, OpenKruise should use structured logging instead of unstructured logging and shall output json format if argument --logging-format=json is used. 

Structured log output has already been addressed in issue #1551 , but so far it still cannot output logs in JSON format.

When the Golang version of OpenKruise is upgraded to 1.21 or above, consideration can be given to using the new log/slog library as the logger implementation for klog to achieve the goal of outputting structured logs in JSON format.

**Why is this needed**:

OpenKruise currently use unstructured plain text as the logging format, which may logging processing hard.

**Comment by furykerry** [comment]
fixed in https://github.com/openkruise/kruise/pull/1703
