### ISSUE TITLE
[BUG] local kind test tools are invalid

### ISSUE THREAD

**Issue by AiRanthem** [openkruise/kruise#1686]
**What happened**:

I want to use command `make create-cluster` to set up a Kind cluster locally for testing purposes. By default, the Makefile builds Kind results in an error since there is no code in the `tools/src/kind` directory. To resolve this, I have to manually download the Kind executable by running the command `go install sigs.k8s.io/kind@v0.23.0`, and then copy it into the `tools/bin` directory to proceed with further operations.

**What you expected to happen**:

when I type `make create-cluster` command, the Makefile should download the Kind executable to `tools/bin` automatically instead of building the ghost code.

**How to reproduce it (as minimally and precisely as possible)**:

1. clone a clean kruise repository
2. type `make create-cluster`

**Anything else we need to know?**:

**Environment**:
- Kruise version: 1.6.3
- Kubernetes version (use `kubectl version`): Any
- Install details (e.g. helm install args): Nothing
- Others:

**Comment by ABNER-1** [comment]
You are right.
