### ISSUE TITLE
[Broadcast job]  how to use broadcast job to configure Docker configuration and then restart Docker service

### ISSUE THREAD

**Issue by zjz0924** [openkruise/kruise#170]
**What would you like to be added**:
I want to use broadcast job to configure Docker configuration and then restart Docker service

**Why is this needed**:
I need to configure Docker in many hosts,  manual configuration is not realistic. So I want to use broadcast job to do this.

**My Issue**:
I don't know how to execute host command in container to restart docker service.  And there are no related demos or docs for such situation.  

Do you have any solutions or suggestions? 
Thank you.

**Comment by jian-he** [comment]
@zjz0924 
This has less to do with broadcastjob. This is a question about whether we can run a command on host from within a container. Better asking this question in docker community.

I googled it and find this document https://stackoverflow.com/questions/32163955/how-to-run-shell-script-on-host-from-docker-container
you can check if it's useful

**Comment by FillZpp** [comment]
Rotten issues close after 90d of inactivity.
