### ISSUE TITLE
[BUG] Kruise should not be updating CustomResourceDefinitions

### ISSUE THREAD

**Issue by ahmetb** [openkruise/kruise#1710]
**What happened**:

In my kube-apiserver audit logs I have noticed that Kruise is making `update` `customresourcedefinitions` and I thought that's really weird.

**What you expected to happen**:

Controllers should not be updating CRDs, especially if the CRD is managed by another system (say, like a Helm chart deployed through a CD tool like ArgoCD/Flux, or even kubectl).

This is just a bad idea in general and makes the system unpredictable. I don't know any other operator that updates its own CRDs. It's just a bad idea to mutate something so critical from within the controller. It doesn't make sense to me to give Kruise permissions to `create`/`update`/`delete` any `customresourcedefinitions` ([reference](https://github.com/openkruise/kruise/blob/11fdf8fa110c300f4c000f53a25da8ec056341b2/config/rbac/role.yaml#L41-L50)) especially because this permission is not specific to Kruise's own CRDs.

Kruise is doing other weird things like "delete protection" for its own customresourcedefinitions. This sort of stuff is not ideal for every operator to do on their own. For example, if kruise webhook goes down, no other CustomResourceDefinition can be deleted in the cluster [because Kruise is intercepting all CRD deletion requests](https://github.com/openkruise/kruise/blob/11fdf8fa110c300f4c000f53a25da8ec056341b2/config/webhook/manifests.yaml#L442-L451). That's just weird and it would be great if this was configurable in the helm chart.

I highly recommend Kruise to stop doing these and take example from other operators. 

**How to reproduce it (as minimally and precisely as possible)**:

[It's in the code](https://github.com/openkruise/kruise/blob/11fdf8fa110c300f4c000f53a25da8ec056341b2/pkg/webhook/util/crd/crd.go#L77-L109) so you can see it probably on many clusters. 

**Anything else we need to know?**: N/A

**Environment**:
- Kruise version: probably many all versions including the current head 11fdf8fa110c
- Kubernetes version (use `kubectl version`): Not applicable
- Install details (e.g. helm install args): Not applicable
- Others:  Not applicable

**Comment by furykerry** [comment]
@ahmetb very good sugguestion, we will revisit our webhook and rbac setting, and make corresponding changes, e.g.  
1. only request only the permission of openkruise CRD
2. change the failPolicy of the webhookconfiguration of deletion protection to skip

**Comment by ahmetb** [comment]
Those were secondary issues I mentioned. The main issue is Kruise mutating its own CRD which still does not make sense. It sounds like a hacky solution to a problem that I don't yet understand.

**Comment by furykerry** [comment]
previously openkruise only support self signed webhook certificates, so it need populate the crd with self signed certificates. In release 1.7, openkruise also support external signed webhook certificates using cert-manager, so if external cert is enabled, openkruise will not mutate its own CRD

**Comment by ahmetb** [comment]
I understand that the Kruise operator has a self-signed certificate configuration mode and where the controller updates the CRDs, because CRDs have a conversion webhook section that has a `clientConfig.caBundle` field that requires to be kept in sync.

Here's what I'm seeing on our audit logs (we're using Kruise 1.5): Basically every minute there's a CRD update (and it's specifically happening to the `statefulsets.apps.kruise.io` CRD which we actually don't even use).

<img width="984" alt="image" src="https://github.com/user-attachments/assets/97c0b502-fd18-435a-94f9-ce821130f51a">

This sounds buggy to me since 1) it's happening so many times 2) it's happening only to a particular CRD that I don't even use (maybe other CRDs don't have conversion, I don't know, [but the code seems pretty generic](https://github.com/openkruise/kruise/blob/11fdf8fa110c300f4c000f53a25da8ec056341b2/pkg/webhook/util/crd/crd.go#L77-L109)).

**Comment by furykerry** [comment]
#1717 is working on this bug
