### ISSUE TITLE
[feature request] add docs about how to use workloadspread with customized workload

### ISSUE THREAD

**Issue by furykerry** [openkruise/kruise#1729]
**What would you like to be added**:
explain in detail about 
1. the configmap item`WorkloadSpread_Watch_Custom_Workload_WhiteList` and the meaning of each field
2. rbac changs of kruise-manager 
3. other related config required to enable customized workload support of workloadspread
4. 
**Why is this needed**:

**Comment by ABNER-1** [comment]
/assign @AiRanthem 
related PR https://github.com/openkruise/openkruise.io/pull/209
