### ISSUE TITLE
[Request] Add a feature-gate to limit CloneSet pod name length within 63 chars or less.

### ISSUE THREAD

**Issue by veophi** [openkruise/kruise#1736]
**What would you like to be added**:

Align the pod name limitation of CloneSet with Deployment if enable the feature-gate.

**Why is this needed**:

Pod name may be used as some label value that is limited within 63 chars or less..

**Comment by ABNER-1** [comment]
@veophi  There is a similar issue https://github.com/openkruise/kruise/issues/1627.

Do you think that if CloneSet supports the use of generateName to randomly generate names by api-server when the length exceeds a certain threshold, it would meet your requirements?

**Comment by furykerry** [comment]
can the pod name be saved in annotation value instead of label value?
