### ISSUE TITLE
[feature request] 需要一个命令行补全工具！帮助我更快的在mac终端上补全

### ISSUE THREAD

**Issue by Bearfirm** [openkruise/kruise#1759]
**What would you like to be added**:

kubectl kruise -- 后面可否自动补全一下。

**Why is this needed**:

这个功能应该很有用。

**Comment by hantmac** [comment]
@Bearfirm The new version https://github.com/openkruise/kruise-tools/releases/tag/v1.1.3 support auto completion, just have a try.
