### ISSUE TITLE
[BUG] Advance  Statefulset 是否存在以下 bug

### ISSUE THREAD

**Issue by skilxn-go** [openkruise/kruise#178]
根据代码看来：
使用 
> InPlaceOnlyPodUpdateStrategyType
 
作为更新策略时，对于这个 InPlaceOnly 的限制是在 Validating Webhook 完成的，也就是说我只变更 image 就可以把更新写入 spec
然而在 
> shouldDoInPlaceUpdate 

函数中
```go
func shouldDoInPlaceUpdate(
	set *appsv1alpha1.StatefulSet,
	updateRevision *apps.ControllerRevision,
	oldRevisionName string,
	revisions []*apps.ControllerRevision,
) (bool, *InPlaceUpdateSpec) {
	if set.Spec.UpdateStrategy.RollingUpdate == nil {
		return false, nil
	}
	if set.Spec.UpdateStrategy.RollingUpdate.PodUpdatePolicy != appsv1alpha1.InPlaceIfPossiblePodUpdateStrategyType &&
		set.Spec.UpdateStrategy.RollingUpdate.PodUpdatePolicy != appsv1alpha1.InPlaceOnlyPodUpdateStrategyType {
		return false, nil
	}

	var oldRevision *apps.ControllerRevision
	for _, r := range revisions {
		if r.Name == oldRevisionName {
			oldRevision = r
			break
		}
	}
	// the old ControllerRevision might be already deleted
	if oldRevision == nil {
		return false, nil
	}
// other codes
```
如果 revisions 找不到了，则认为无法原地升级，然后后面看代码，流程就进入正常的 delete pod 升级了。
是否是我说的这样呢？
如果是的话，这个是否和 “InPlaceOnly“ 含义相悖？

**Comment by FillZpp** [comment]
@skilxn-go  Actually, "old ControllerRevision not found" should not happen for `truncateHistory` can only delete non-live revisions, otherwise someone has deleted the revision manually. In this case, we have no choice but to recreate pods with non-existing revisions.

**Comment by skilxn-go** [comment]
Got it, it makes sense
