### ISSUE TITLE
[feature request] UnitedDeployment deploymentTemplate support strategy and minReadySeconds 

### ISSUE THREAD

**Issue by seuljetaime** [openkruise/kruise#1791]
**What would you like to be added**:
UnitedDeployment deploymentTemplate support strategy and minReadySeconds 

**Why is this needed**:
在UnitedDeployment中配置spec.template.deploymentTemplate.spec.strategy  或者 spec.updateStrategy 对deployment不生效，还是默认的25%滚动更新。
配置spec.template.deploymentTemplate.spec.minReadySeconds也是对deployment不生效

**Comment by AiRanthem** [comment]
@seuljetaime 您好，我想了解一下这边使用 UnitedDeployment 的具体场景，能否联系邮箱 airanthem@qq.com？
