### ISSUE TITLE
[BUG]  kruise-controller pod logs ---- panic: failed to new ca-cert watcher: too many open files

### ISSUE THREAD

**Issue by zwbrealm** [openkruise/kruise#1799]
**What happened**:
当我使用helm安装kruise 1.4.1版本之后，出现了这个问题
![image](https://github.com/user-attachments/assets/e3f688d0-e3f2-4a62-8155-02b33a26d5ac)

kruise-controller-manager这两个pod始终处于 CrashLoopBackOff状态

查看kubectl logs ，完整报错如下
I1022 11:02:44.599454       1 feature_gate.go:245] feature gates: &{map[]}
I1022 11:02:44.600385       1 deleg.go:130] setup "msg"="new clientset registry"  
I1022 11:02:44.896331       1 deleg.go:130] controller-runtime/metrics "msg"="Metrics server is starting to listen"  "addr"=":8080"
I1022 11:02:44.897892       1 deleg.go:130] setup "msg"="register field index"  
I1022 11:02:44.903725       1 deleg.go:130] setup "msg"="setup webhook"  
I1022 11:02:44.907171       1 server.go:145] controller-runtime/webhook "msg"="Registering webhook" "path"="/mutate-apps-kruise-io-v1alpha1-broadcastjob" 
I1022 11:02:44.907290       1 server.go:94] Registered webhook handler /mutate-apps-kruise-io-v1alpha1-broadcastjob
I1022 11:02:44.907381       1 server.go:145] controller-runtime/webhook "msg"="Registering webhook" "path"="/validate-apps-kruise-io-v1alpha1-imagepulljob" 
I1022 11:02:44.907428       1 server.go:94] Registered webhook handler /validate-apps-kruise-io-v1alpha1-imagepulljob
I1022 11:02:44.907511       1 server.go:145] controller-runtime/webhook "msg"="Registering webhook" "path"="/mutate-apps-kruise-io-v1alpha1-advancedcronjob" 
I1022 11:02:44.907559       1 server.go:94] Registered webhook handler /mutate-apps-kruise-io-v1alpha1-advancedcronjob
I1022 11:02:44.907629       1 server.go:145] controller-runtime/webhook "msg"="Registering webhook" "path"="/validate-apps-kruise-io-v1alpha1-imagelistpulljob" 
I1022 11:02:44.907692       1 server.go:94] Registered webhook handler /validate-apps-kruise-io-v1alpha1-imagelistpulljob
I1022 11:02:44.907792       1 server.go:145] controller-runtime/webhook "msg"="Registering webhook" "path"="/validate-apps-kruise-io-v1alpha1-resourcedistribution" 
I1022 11:02:44.907848       1 server.go:94] Registered webhook handler /validate-apps-kruise-io-v1alpha1-resourcedistribution
I1022 11:02:44.907923       1 server.go:145] controller-runtime/webhook "msg"="Registering webhook" "path"="/validate-apps-kruise-io-v1alpha1-advancedcronjob" 
I1022 11:02:44.907984       1 server.go:94] Registered webhook handler /validate-apps-kruise-io-v1alpha1-advancedcronjob
I1022 11:02:44.908071       1 server.go:145] controller-runtime/webhook "msg"="Registering webhook" "path"="/validate-apps-kruise-io-v1alpha1-workloadspread" 
I1022 11:02:44.908143       1 server.go:94] Registered webhook handler /validate-apps-kruise-io-v1alpha1-workloadspread
I1022 11:02:44.908222       1 server.go:145] controller-runtime/webhook "msg"="Registering webhook" "path"="/validate-apps-kruise-io-v1alpha1-broadcastjob" 
I1022 11:02:44.908285       1 server.go:94] Registered webhook handler /validate-apps-kruise-io-v1alpha1-broadcastjob
I1022 11:02:44.908380       1 server.go:145] controller-runtime/webhook "msg"="Registering webhook" "path"="/validate-apps-kruise-io-v1alpha1-cloneset" 
I1022 11:02:44.908426       1 server.go:94] Registered webhook handler /validate-apps-kruise-io-v1alpha1-cloneset
I1022 11:02:44.908498       1 server.go:145] controller-runtime/webhook "msg"="Registering webhook" "path"="/validate-customresourcedefinition" 
I1022 11:02:44.908541       1 server.go:94] Registered webhook handler /validate-customresourcedefinition
I1022 11:02:44.908613       1 server.go:145] controller-runtime/webhook "msg"="Registering webhook" "path"="/mutate-apps-kruise-io-v1alpha1-uniteddeployment" 
I1022 11:02:44.908681       1 server.go:94] Registered webhook handler /mutate-apps-kruise-io-v1alpha1-uniteddeployment
I1022 11:02:44.908789       1 server.go:145] controller-runtime/webhook "msg"="Registering webhook" "path"="/validate-apps-statefulset" 
I1022 11:02:44.908846       1 server.go:94] Registered webhook handler /validate-apps-statefulset
I1022 11:02:44.908927       1 server.go:145] controller-runtime/webhook "msg"="Registering webhook" "path"="/mutate-apps-kruise-io-v1alpha1-imagelistpulljob" 
I1022 11:02:44.908977       1 server.go:94] Registered webhook handler /mutate-apps-kruise-io-v1alpha1-imagelistpulljob
I1022 11:02:44.909082       1 server.go:145] controller-runtime/webhook "msg"="Registering webhook" "path"="/validate-apps-kruise-io-podprobemarker" 
I1022 11:02:44.909138       1 server.go:94] Registered webhook handler /validate-apps-kruise-io-podprobemarker
I1022 11:02:44.909220       1 server.go:145] controller-runtime/webhook "msg"="Registering webhook" "path"="/mutate-apps-kruise-io-v1alpha1-nodeimage" 
I1022 11:02:44.909275       1 server.go:94] Registered webhook handler /mutate-apps-kruise-io-v1alpha1-nodeimage
I1022 11:02:44.909353       1 server.go:145] controller-runtime/webhook "msg"="Registering webhook" "path"="/validate-apps-kruise-io-v1alpha1-nodeimage" 
I1022 11:02:44.909425       1 server.go:94] Registered webhook handler /validate-apps-kruise-io-v1alpha1-nodeimage
I1022 11:02:44.909500       1 server.go:145] controller-runtime/webhook "msg"="Registering webhook" "path"="/validate-policy-kruise-io-podunavailablebudget" 
I1022 11:02:44.909549       1 server.go:94] Registered webhook handler /validate-policy-kruise-io-podunavailablebudget
I1022 11:02:44.909624       1 server.go:145] controller-runtime/webhook "msg"="Registering webhook" "path"="/mutate-apps-kruise-io-v1alpha1-sidecarset" 
I1022 11:02:44.909667       1 server.go:94] Registered webhook handler /mutate-apps-kruise-io-v1alpha1-sidecarset
I1022 11:02:44.909738       1 server.go:145] controller-runtime/webhook "msg"="Registering webhook" "path"="/validate-apps-kruise-io-v1alpha1-sidecarset" 
I1022 11:02:44.909834       1 server.go:94] Registered webhook handler /validate-apps-kruise-io-v1alpha1-sidecarset
I1022 11:02:44.909918       1 server.go:145] controller-runtime/webhook "msg"="Registering webhook" "path"="/validate-apps-deployment" 
I1022 11:02:44.909961       1 server.go:94] Registered webhook handler /validate-apps-deployment
I1022 11:02:44.910037       1 server.go:145] controller-runtime/webhook "msg"="Registering webhook" "path"="/mutate-apps-kruise-io-v1alpha1-daemonset" 
I1022 11:02:44.910086       1 server.go:94] Registered webhook handler /mutate-apps-kruise-io-v1alpha1-daemonset
I1022 11:02:44.910153       1 server.go:145] controller-runtime/webhook "msg"="Registering webhook" "path"="/mutate-apps-kruise-io-v1alpha1-imagepulljob" 
I1022 11:02:44.910208       1 server.go:94] Registered webhook handler /mutate-apps-kruise-io-v1alpha1-imagepulljob
I1022 11:02:44.910291       1 server.go:145] controller-runtime/webhook "msg"="Registering webhook" "path"="/validate-apps-kruise-io-statefulset" 
I1022 11:02:44.910339       1 server.go:94] Registered webhook handler /validate-apps-kruise-io-statefulset
I1022 11:02:44.910423       1 server.go:145] controller-runtime/webhook "msg"="Registering webhook" "path"="/validate-apps-kruise-io-v1alpha1-uniteddeployment" 
I1022 11:02:44.910490       1 server.go:94] Registered webhook handler /validate-apps-kruise-io-v1alpha1-uniteddeployment
I1022 11:02:44.910564       1 server.go:145] controller-runtime/webhook "msg"="Registering webhook" "path"="/mutate-apps-kruise-io-statefulset" 
I1022 11:02:44.910604       1 server.go:94] Registered webhook handler /mutate-apps-kruise-io-statefulset
I1022 11:02:44.910682       1 server.go:145] controller-runtime/webhook "msg"="Registering webhook" "path"="/validate-apps-replicaset" 
I1022 11:02:44.910726       1 server.go:94] Registered webhook handler /validate-apps-replicaset
I1022 11:02:44.910865       1 server.go:145] controller-runtime/webhook "msg"="Registering webhook" "path"="/mutate-apps-kruise-io-v1alpha1-containerrecreaterequest" 
I1022 11:02:44.910929       1 server.go:94] Registered webhook handler /mutate-apps-kruise-io-v1alpha1-containerrecreaterequest
I1022 11:02:44.911003       1 server.go:145] controller-runtime/webhook "msg"="Registering webhook" "path"="/validate-namespace" 
I1022 11:02:44.911048       1 server.go:94] Registered webhook handler /validate-namespace
I1022 11:02:44.911128       1 server.go:145] controller-runtime/webhook "msg"="Registering webhook" "path"="/mutate-pod" 
I1022 11:02:44.911174       1 server.go:94] Registered webhook handler /mutate-pod
I1022 11:02:44.911258       1 server.go:145] controller-runtime/webhook "msg"="Registering webhook" "path"="/validate-pod" 
I1022 11:02:44.911308       1 server.go:94] Registered webhook handler /validate-pod
I1022 11:02:44.911404       1 server.go:145] controller-runtime/webhook "msg"="Registering webhook" "path"="/mutate-apps-kruise-io-v1alpha1-cloneset" 
I1022 11:02:44.911455       1 server.go:94] Registered webhook handler /mutate-apps-kruise-io-v1alpha1-cloneset
I1022 11:02:44.911537       1 server.go:145] controller-runtime/webhook "msg"="Registering webhook" "path"="/validate-apps-kruise-io-v1alpha1-daemonset" 
I1022 11:02:44.911585       1 server.go:94] Registered webhook handler /validate-apps-kruise-io-v1alpha1-daemonset
I1022 11:02:44.911656       1 server.go:145] controller-runtime/webhook "msg"="Registering webhook" "path"="/validate-apps-kruise-io-persistentpodstate" 
I1022 11:02:44.911712       1 server.go:94] Registered webhook handler /validate-apps-kruise-io-persistentpodstate
I1022 11:02:44.911802       1 server.go:145] controller-runtime/webhook "msg"="Registering webhook" "path"="/convert" 
I1022 11:02:44.911916       1 server.go:145] controller-runtime/webhook "msg"="Registering webhook" "path"="/healthz" 
I1022 11:02:44.911960       1 deleg.go:130] setup "msg"="initialize webhook"  
I1022 11:02:44.947850       1 webhook_controller.go:181] Starting webhook-controller
I1022 11:02:44.947917       1 shared_informer.go:240] Waiting for caches to sync for webhook-controller
I1022 11:02:44.948093       1 reflector.go:219] Starting reflector *v1.CustomResourceDefinition (0s) from pkg/webhook/util/controller/webhook_controller.go:186
I1022 11:02:44.948119       1 reflector.go:255] Listing and watching *v1.CustomResourceDefinition from pkg/webhook/util/controller/webhook_controller.go:186
I1022 11:02:44.948266       1 reflector.go:219] Starting reflector *v1.ValidatingWebhookConfiguration (0s) from k8s.io/client-go/informers/factory.go:134
I1022 11:02:44.948285       1 reflector.go:255] Listing and watching *v1.ValidatingWebhookConfiguration from k8s.io/client-go/informers/factory.go:134
I1022 11:02:44.948317       1 reflector.go:219] Starting reflector *v1.Secret (0s) from k8s.io/client-go/informers/factory.go:134
I1022 11:02:44.948343       1 reflector.go:255] Listing and watching *v1.Secret from k8s.io/client-go/informers/factory.go:134
I1022 11:02:44.948370       1 reflector.go:219] Starting reflector *v1.MutatingWebhookConfiguration (0s) from k8s.io/client-go/informers/factory.go:134
I1022 11:02:44.948400       1 reflector.go:255] Listing and watching *v1.MutatingWebhookConfiguration from k8s.io/client-go/informers/factory.go:134
I1022 11:02:45.003562       1 webhook_controller.go:100] Secret kruise-webhook-certs added
I1022 11:02:45.003626       1 webhook_controller.go:134] ValidatingWebhookConfiguration kruise-validating-webhook-configuration added
I1022 11:02:45.003699       1 webhook_controller.go:117] MutatingWebhookConfiguration kruise-mutating-webhook-configuration added
I1022 11:02:46.509209       1 webhook_controller.go:153] CustomResourceDefinition uniteddeployments.apps.kruise.io added
I1022 11:02:46.509274       1 webhook_controller.go:153] CustomResourceDefinition podprobemarkers.apps.kruise.io added
I1022 11:02:46.509284       1 webhook_controller.go:153] CustomResourceDefinition resourcedistributions.apps.kruise.io added
I1022 11:02:46.509361       1 webhook_controller.go:153] CustomResourceDefinition daemonsets.apps.kruise.io added
I1022 11:02:46.509403       1 webhook_controller.go:153] CustomResourceDefinition workloadspreads.apps.kruise.io added
I1022 11:02:46.509436       1 webhook_controller.go:153] CustomResourceDefinition containerrecreaterequests.apps.kruise.io added
I1022 11:02:46.509454       1 webhook_controller.go:153] CustomResourceDefinition persistentpodstates.apps.kruise.io added
I1022 11:02:46.509465       1 webhook_controller.go:153] CustomResourceDefinition nodeimages.apps.kruise.io added
I1022 11:02:46.509473       1 webhook_controller.go:153] CustomResourceDefinition statefulsets.apps.kruise.io added
I1022 11:02:46.509482       1 webhook_controller.go:153] CustomResourceDefinition advancedcronjobs.apps.kruise.io added
I1022 11:02:46.509490       1 webhook_controller.go:153] CustomResourceDefinition clonesets.apps.kruise.io added
I1022 11:02:46.509506       1 webhook_controller.go:153] CustomResourceDefinition imagepulljobs.apps.kruise.io added
I1022 11:02:46.509517       1 webhook_controller.go:153] CustomResourceDefinition broadcastjobs.apps.kruise.io added
I1022 11:02:46.509526       1 webhook_controller.go:153] CustomResourceDefinition sidecarsets.apps.kruise.io added
I1022 11:02:46.509535       1 webhook_controller.go:153] CustomResourceDefinition nodepodprobes.apps.kruise.io added
I1022 11:02:46.548637       1 shared_informer.go:270] caches populated
I1022 11:02:46.548669       1 shared_informer.go:247] Caches are synced for webhook-controller 
I1022 11:02:46.548686       1 webhook_controller.go:196] Started webhook-controller
I1022 11:02:46.548796       1 webhook_controller.go:222] Starting to sync webhook certs and configurations
I1022 11:02:46.553604       1 fs.go:126] cert directory doesn't exist, creatingdirectory/tmp/kruise-webhook-certs
I1022 11:02:46.554407       1 atomic_writer.go:178] performed write of new data to ts data directoryts directory/tmp/kruise-webhook-certs/..2024_10_22_11_02_46.3997087535
I1022 11:02:46.901655       1 webhook_controller.go:224] Finished to sync webhook certs and configurations
I1022 11:02:46.901763       1 deleg.go:130] setup "msg"="starting manager"  
I1022 11:02:46.901872       1 deleg.go:130] setup "msg"="wait webhook ready"  
I1022 11:02:46.901981       1 internal.go:383]  "msg"="Starting metrics server"  "path"="/metrics"
I1022 11:02:46.901982       1 server.go:213] controller-runtime/webhook/webhooks "msg"="Starting webhook server"  
I1022 11:02:46.901893       1 leaderelection.go:248] attempting to acquire leader lease kruise-system/kruise-manager...
**panic: failed to new ca-cert watcher: too many open files**

goroutine 255 [running]:
github.com/openkruise/kruise/pkg/webhook/util/health.Checker.func1()
        /workspace/pkg/webhook/util/health/checker.go:117 +0x185
sync.(*Once).doSlow(0x0?, 0x0?)
        /usr/local/go/src/sync/once.go:68 +0xc2
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:59
github.com/openkruise/kruise/pkg/webhook/util/health.Checker(0xc1bdff75b5c1f561?)
        /workspace/pkg/webhook/util/health/checker.go:111 +0x5e
github.com/openkruise/kruise/pkg/webhook.Checker(0x5?)
        /workspace/pkg/webhook/server.go:137 +0x35
github.com/openkruise/kruise/pkg/webhook.WaitReady()
        /workspace/pkg/webhook/server.go:145 +0x71
main.main.func2()
        /workspace/main.go:216 +0x65
created by main.main
        /workspace/main.go:214 +0xf3e

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kruise version:1.4.1
- Kubernetes version (use `kubectl version`):
-kind 搭建的集群，一个物理机器上，有1个master node，1个 worker node
-# kubectl version
kind version 0.22.0
Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.20.15
WARNING: version difference between client (1.30) and server (1.20) exceeds the supported minor version skew of +/-1
- Install details (e.g. helm install args):
- 
- Others:
- 我使用内存48G,32cpu核的物理机器

**Comment by ABNER-1** [comment]
@zwbrealm 
看起来是文件句柄太多的原因，
可以进容器查看下相关参数
`lsof -p < kruise PID>`
同时查看文件句柄限制和系统限制
`ulimit -n `
`cat /proc/sys/fs/file-max`

**Comment by zwbrealm** [comment]
已解决
