### ISSUE TITLE
Create a Roadmap

### ISSUE THREAD

**Issue by xiang90** [openkruise/kruise#18]
- new planned workload controllers
- planned features for existing controllers
- planned new release date

/cc @jian-he + @Fei-Guo

**Comment by Fei-Guo** [comment]
https://github.com/openkruise/kruise/blob/master/docs/roadmap/2019-Q3.md 
Here is the roadmap. Close the issue.

**Comment by xiang90** [comment]
@Fei-Guo Can we link the roadmap from front page readme for better discoverability?
