### ISSUE TITLE
[BUG] kubectl-kruise rollout approve rollouts failed

### ISSUE THREAD

**Issue by zmberg** [openkruise/kruise#1809]
**What happened**:
kubectl-kruise rollout approve rollouts/rollouts-demo -n default
error: no kind "Rollout" is registered for version "rollouts.kruise.io/v1alpha1" in scheme "pkg/runtime/scheme.go:100"
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kruise rollout version: v0.5.1
- kubectl-kruise version: 1.1.3 
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Others:

**Comment by zmberg** [comment]
![image](https://github.com/user-attachments/assets/5aba025c-1ead-45b4-9104-06e868c3062d)

**Comment by AiRanthem** [comment]
https://github.com/openkruise/kruise-tools/pull/105
