### ISSUE TITLE
[feature request] Share env in SidecarSet

### ISSUE THREAD

**Issue by cutiechi** [openkruise/kruise#198]
**What would you like to be added**:

I define a SidecarSet has one filebeat container for collect log, the filebeat configuration file have two varible 'COMPONENT_TYPE' and 'LOG_DIR', but the set not known what value when inject pod starting

**Why is this needed**:
I want to share one env for SidecarSet and Injected container

**Comment by furykerry** [comment]
@cutiechi how do you expect the sidecar container to get the environment ? Do you have a common container naming, for example, make the sidecar share the environment with container called 'app'
