### ISSUE TITLE
why use webhook-server-service, not use kruise-webhook-server-service

### ISSUE THREAD

**Issue by devops4cc** [openkruise/kruise#202]
I have installed kruise in my kubernetes cluster according the official docucment, the service kruise-webhook-server-service has been created
 kubectl get services -n kruise-system
NAME                                TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
kruise-controller-manager-service   ClusterIP   10.233.25.247   <none>        443/TCP   45m
kruise-webhook-server-service       ClusterIP   10.233.27.148   <none>        443/TCP   45m

kubectl describe service kruise-webhook-server-service -n kruise-system
Name:              kruise-webhook-server-service
Namespace:         kruise-system
Labels:            <none>
Annotations:       <none>
Selector:          control-plane=controller-manager
Type:              ClusterIP
IP:                10.233.35.200
Port:              <unset>  443/TCP
TargetPort:        9876/TCP
Endpoints:         10.233.92.133:9876
Session Affinity:  None
Events:            <none>

but when I try to deploy a statefulset service, it report below error

Error from server (InternalError): error when creating "deployscripts/hadoop/statefulset.yaml": Internal error occurred: failed calling webhook "validating-create-update-statefulset.kruise.io": Post https://webhook-server-service.kruise-system.svc:443/validating-create-update-statefulset?timeout=30s: service "webhook-server-service" not found
Error from server (InternalError): error when creating "deployscripts/hadoop/statefulset.yaml": Internal error occurred: failed calling webhook "validating-create-update-statefulset.kruise.io": Post https://webhook-server-service.kruise-system.svc:443/validating-create-update-statefulset?timeout=30s: service "webhook-server-service" not found
Error from server (InternalError): error when creating "deployscripts/hadoop/statefulset.yaml": Internal error occurred: failed calling webhook "validating-create-update-statefulset.kruise.io": Post https://webhook-server-service.kruise-system.svc:443/validating-create-update-statefulset?timeout=30s: service "webhook-server-service" not found
Error from server (InternalError): error when creating "deployscripts/hadoop/statefulset.yaml": Internal error occurred: failed calling webhook "validating-create-update-statefulset.kruise.io": Post https://webhook-server-service.kruise-system.svc:443/validating-create-update-statefulset?timeout=30s: service "webhook-server-service" not found

why the controller try to find webhook-server-service, not kruise-webhook-server-service?

**Comment by FillZpp** [comment]
@devops4cc Cloud you describe your installation commands, via helm chart or yamls?

**Comment by devops4cc** [comment]
the issue has been fixed, I execute a wrong yaml file, the issue was fixed after I removed ValidatingWebhookConfiguration  and mutating-webhook-configuration

[kubeadmin@node1 ~]$ kubectl get MutatingWebhookConfiguration
NAME                                    CREATED AT
istio-sidecar-injector                  2019-12-28T10:44:46Z
kruise-mutating-webhook-configuration   2019-12-30T08:16:45Z
mutating-webhook-configuration          2019-12-28T10:35:37Z
[kubeadmin@node1 ~]$ kubectl delete MutatingWebhookConfiguration mutating-webhook-configuration
mutatingwebhookconfiguration.admissionregistration.k8s.io "mutating-webhook-configuration" deleted
[kubeadmin@node1 ~]$ kubectl get ValidatingWebhookConfiguration
NAME                                      CREATED AT
istio-galley                              2019-12-28T11:25:38Z
kruise-validating-webhook-configuration   2019-12-30T08:16:45Z
validating-webhook-configuration          2019-12-28T10:35:37Z
[kubeadmin@node1 ~]$ kubectl delete ValidatingWebhookConfiguration validating-webhook-configuration
validatingwebhookconfiguration.admissionregistration.k8s.io "validating-webhook-configuration" deleted

thank you for quickly response, I shouldn't execute kubectl apply -f webhookconfiguration.yaml, the service kruise-webhook-server-service didn't created when I first install kruise so I tried to execute that webhookconfiguration.yaml

**Comment by CKchen0726** [comment]
@devops4cc Hi, have you encountered this problem?
Response:
`Error from server (InternalError): error when creating "server.yaml": Internal error occurred: failed calling webhook "mserver.kb.io": failed to call webhook: Post "https://webhook-service.system.svc:443/mutate-apps-kruise-io-v1alpha1-sidecarset?timeout=10s": service "webhook-service" not found`

**Comment by FillZpp** [comment]
@CKchen0726 Which chart did you install? Please make sure that you should use the latest `v0.10.0` or `v1.0-alpha.1`.

**Comment by CKchen0726** [comment]
@devops4cc I download source code, `make build`, then `docker build`, and finally deploy a pod with this image

**Comment by CKchen0726** [comment]
@FillZpp Error from server (InternalError): Internal error occurred: failed calling webhook "msidecarset.kb.io": failed to call webhook: Post "https://kruise-webhook-service.kruise-system.svc:443/mutate-apps-kruise-io-v1alpha1-sidecarset?timeout=10s": dial tcp 10.105.217.237:443: connect: connection refused
ps:
NAME                   TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
nova-webhook-service   ClusterIP   10.105.217.237   <none>        443/TCP   6d3h

I fix this problem by `kubectl delete MutatingWebhookConfiguration kruise-mutating-webhook-configuration`

By the way, when I deploy a pod, there is no webhook `mutate` and `validate` logs,

**Comment by veophi** [comment]
> @FillZpp Error from server (InternalError): Internal error occurred: failed calling webhook "msidecarset.kb.io": failed to call webhook: Post "https://kruise-webhook-service.kruise-system.svc:443/mutate-apps-kruise-io-v1alpha1-sidecarset?timeout=10s": dial tcp 10.105.217.237:443: connect: connection refused ps: NAME TYPE CLUSTER-IP EXTERNAL-IP PORT(S) AGE nova-webhook-service ClusterIP 10.105.217.237 443/TCP 6d3h
> 
> I fix this problem by `kubectl delete MutatingWebhookConfiguration kruise-mutating-webhook-configuration`
> 
> By the way, when I deploy a pod, there is no webhook `mutate` and `validate` logs,

Have you applied the `kruise-webhook-service`？

**Comment by veophi** [comment]
> @FillZpp Error from server (InternalError): Internal error occurred: failed calling webhook "msidecarset.kb.io": failed to call webhook: Post "https://kruise-webhook-service.kruise-system.svc:443/mutate-apps-kruise-io-v1alpha1-sidecarset?timeout=10s": dial tcp 10.105.217.237:443: connect: connection refused ps: NAME TYPE CLUSTER-IP EXTERNAL-IP PORT(S) AGE nova-webhook-service ClusterIP 10.105.217.237 443/TCP 6d3h
> 
> I fix this problem by `kubectl delete MutatingWebhookConfiguration kruise-mutating-webhook-configuration`
> 
> By the way, when I deploy a pod, there is no webhook `mutate` and `validate` logs,

plz check your configurations of `kruise-validating-webhook-configuration`, and notice these fields:

```
    service:
      name: kruise-webhook-service
      namespace: kruise-system
      path: /validate-apps-deployment
      port: 443
```

**Comment by veophi** [comment]
> > > @FillZpp Error from server (InternalError): Internal error occurred: failed calling webhook "msidecarset.kb.io": failed to call webhook: Post "https://kruise-webhook-service.kruise-system.svc:443/mutate-apps-kruise-io-v1alpha1-sidecarset?timeout=10s": dial tcp 10.105.217.237:443: connect: connection refused ps: NAME TYPE CLUSTER-IP EXTERNAL-IP PORT(S) AGE nova-webhook-service ClusterIP 10.105.217.237 443/TCP 6d3h
> > > I fix this problem by `kubectl delete MutatingWebhookConfiguration kruise-mutating-webhook-configuration`
> > > By the way, when I deploy a pod, there is no webhook `mutate` and `validate` logs,
> > 
> > 
> > plz check your configurations of `kruise-mutating-webhook-configuration`, and notice these fields:
> > ```
> >     service:
> >       name: kruise-webhook-service
> >       namespace: kruise-system
> >       path: /validate-apps-deployment
> >       port: 443
> > ```
> 
> I create a pod by pod.yaml, not deployment, is it necessary to notice `/validate-apps-deployment`?

I mean whether your `"kruise-webhook-service"` name is right.

**Comment by CKchen0726** [comment]
@veophi

**Comment by CKchen0726** [comment]
@veophi I deploy kruise by Way 1 provided by README.md, there is the same problem too.
`root@master:/data/cck/k8s_test# kubectl get svc -n kruise-system
NAME                     TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
kruise-webhook-service   ClusterIP   10.106.125.211   <none>        443/TCP   12h
root@master:/data/cck/k8s_test# kubectl -n kruise-system get svc kruise-webhook-service -o yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"kruise-webhook-service","namespace":"kruise-system"},"spec":{"ports":[{"port":443,"targetPort":9876}],"selector":{"control-plane":"controller-manager"}}}
  creationTimestamp: "2021-11-09T13:13:10Z"
    ...
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-11-09T13:13:10Z"
  name: kruise-webhook-service
  namespace: kruise-system
  resourceVersion: "1081310"
  uid: c4c3c0fd-13c3-481d-a25d-295d59c7c3a2
spec:
  clusterIP: 10.106.125.211
  clusterIPs:
  - 10.106.125.211
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9876
  selector:
    control-plane: controller-manager
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
`

**Comment by veophi** [comment]
@CKchen0726  You may try to execute `./scripts/uninstall.sh` before `make deploy`.

**Comment by CKchen0726** [comment]
@veophi It does not work.

`**root@node3:/mnt/disk/go/src/kruise# make uninstall**`
/mnt/disk/go/src/kruise/bin/controller-gen "crd:trivialVersions=true,preserveUnknownFields=false" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
/mnt/disk/go/src/kruise/bin/kustomize build config/crd | kubectl delete -f -
customresourcedefinition.apiextensions.k8s.io "advancedcronjobs.apps.kruise.io" deleted
customresourcedefinition.apiextensions.k8s.io "broadcastjobs.apps.kruise.io" deleted
customresourcedefinition.apiextensions.k8s.io "clonesets.apps.kruise.io" deleted
customresourcedefinition.apiextensions.k8s.io "containerrecreaterequests.apps.kruise.io" deleted
customresourcedefinition.apiextensions.k8s.io "daemonsets.apps.kruise.io" deleted
customresourcedefinition.apiextensions.k8s.io "imagepulljobs.apps.kruise.io" deleted
customresourcedefinition.apiextensions.k8s.io "nodeimages.apps.kruise.io" deleted
customresourcedefinition.apiextensions.k8s.io "podunavailablebudgets.policy.kruise.io" deleted
customresourcedefinition.apiextensions.k8s.io "resourcedistributions.apps.kruise.io" deleted
customresourcedefinition.apiextensions.k8s.io "sidecarsets.apps.kruise.io" deleted
customresourcedefinition.apiextensions.k8s.io "statefulsets.apps.kruise.io" deleted
customresourcedefinition.apiextensions.k8s.io "uniteddeployments.apps.kruise.io" deleted
customresourcedefinition.apiextensions.k8s.io "workloadspreads.apps.kruise.io" deleted
`**root@node3:/mnt/disk/go/src/kruise# make deploy IMG=${IMG}**`
/mnt/disk/go/src/kruise/bin/controller-gen "crd:trivialVersions=true,preserveUnknownFields=false" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
cd config/manager && /mnt/disk/go/src/kruise/bin/kustomize edit set image controller=***/nova:test
/mnt/disk/go/src/kruise/bin/kustomize build config/default | kubectl apply -f -
namespace/kruise-system unchanged
customresourcedefinition.apiextensions.k8s.io/advancedcronjobs.apps.kruise.io created
customresourcedefinition.apiextensions.k8s.io/broadcastjobs.apps.kruise.io created
customresourcedefinition.apiextensions.k8s.io/clonesets.apps.kruise.io created
customresourcedefinition.apiextensions.k8s.io/containerrecreaterequests.apps.kruise.io created
customresourcedefinition.apiextensions.k8s.io/daemonsets.apps.kruise.io created
customresourcedefinition.apiextensions.k8s.io/imagepulljobs.apps.kruise.io created
customresourcedefinition.apiextensions.k8s.io/nodeimages.apps.kruise.io created
customresourcedefinition.apiextensions.k8s.io/podunavailablebudgets.policy.kruise.io created
customresourcedefinition.apiextensions.k8s.io/resourcedistributions.apps.kruise.io created
customresourcedefinition.apiextensions.k8s.io/sidecarsets.apps.kruise.io created
customresourcedefinition.apiextensions.k8s.io/statefulsets.apps.kruise.io created
customresourcedefinition.apiextensions.k8s.io/uniteddeployments.apps.kruise.io created
customresourcedefinition.apiextensions.k8s.io/workloadspreads.apps.kruise.io created
serviceaccount/kruise-daemon unchanged
role.rbac.authorization.k8s.io/kruise-leader-election-role unchanged
clusterrole.rbac.authorization.k8s.io/kruise-daemon-role configured
clusterrole.rbac.authorization.k8s.io/kruise-manager-role configured
rolebinding.rbac.authorization.k8s.io/kruise-leader-election-rolebinding unchanged
clusterrolebinding.rbac.authorization.k8s.io/kruise-daemon-rolebinding unchanged
clusterrolebinding.rbac.authorization.k8s.io/kruise-manager-rolebinding unchanged
secret/kruise-webhook-certs unchanged
service/kruise-webhook-service unchanged
deployment.apps/kruise-controller-manager unchanged
daemonset.apps/kruise-daemon unchanged
mutatingwebhookconfiguration.admissionregistration.k8s.io/kruise-mutating-webhook-configuration configured
validatingwebhookconfiguration.admissionregistration.k8s.io/kruise-validating-webhook-configuration configured
echo -e "resources:\n- manager.yaml" > config/manager/kustomization.yaml
`**root@node3:/mnt/disk/go/src/kruise# kubectl create -f config/samples/apps_v1alpha1_cloneset.yaml**`
Error from server (InternalError): error when creating "config/samples/apps_v1alpha1_cloneset.yaml": Internal error occurred: failed calling webhook "mcloneset.kb.io": failed to call webhook: Post "https://kruise-webhook-service.kruise-system.svc:443/mutate-apps-kruise-io-v1alpha1-cloneset?timeout=10s": dial tcp 10.106.125.211:443: connect: connection refused
`**root@node3:/mnt/disk/go/src/kruise# kubectl -n kruise-system describe svc kruise-webhook-service**`
Name:              kruise-webhook-service
Namespace:         kruise-system
Labels:            <none>
Annotations:       <none>
Selector:          control-plane=controller-manager
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                10.106.125.211
IPs:               10.106.125.211
Port:              <unset>  443/TCP
TargetPort:        9876/TCP
Endpoints:         <none>
Session Affinity:  None
Events:            <none>
