### ISSUE TITLE
can not list stetefulset after install openkruise

### ISSUE THREAD

**Issue by devops4cc** [openkruise/kruise#203]
**What happened**:
we can get the pod list
$ kubectl get pods -n healthcare-mpaas
NAME                       READY   STATUS    RESTARTS   AGE
hadoop-hdfs-datanode-0     1/1     Running   0          124m
hadoop-hdfs-datanode-1     1/1     Running   0          124m
hadoop-hdfs-datanode-2     1/1     Running   0          124m
hadoop-hdfs-namenode-0     1/1     Running   0          124m
hadoop-hdfs-namenode-1     1/1     Running   0          99m
hadoop-nodemanager-0       1/1     Running   0          113m
hadoop-nodemanager-1       1/1     Running   0          113m
hadoop-nodemanager-2       1/1     Running   0          113m
hadoop-resourcemanager-0   1/1     Running   0          113m

but can not get statefulset list
$ kubectl get statefulset --all-namespaces
NAMESPACE       NAME                        READY   AGE
kruise-system   kruise-controller-manager   1/1     131m
kube-system     auth-server-db              3/3     45h
logging         elasticsearch-logging       1/1     45h

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kruise version:
  0.3.0
- Kubernetes version (use `kubectl version`):
1.15.3 
- OS (e.g: `cat /etc/os-release`):
cat /etc/redhat-release
CentOS Linux release 7.5.1804 (Core)

- Kernel (e.g. `uname -a`):
$ uname -a
Linux node1 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by FillZpp** [comment]
The group of Advanced StatefulSet is `apps.kruise.io`. 
Use `kubectl get statefulset.apps.kruise.io` or `kubectl get sts.apps.kruise.io`.

Besides, you cloud follow this tutorial for the first time using Kruise.  
https://github.com/openkruise/kruise/blob/master/docs/tutorial/advanced-statefulset.md
