### ISSUE TITLE
[Feature request] Advanced StatefulSet Auto Remediation

### ISSUE THREAD

**Issue by Fei-Guo** [openkruise/kruise#204]
**Problem** 

When creating new Pods in scaling or rollout workflow, it is possible that a created Pod cannot reach `Ready` state due to certain node problems. For example, node misconfiguration may cause constant failures on pulling images or starting the containers. 

**Proposal**

We can add a `AutoRemediation` flag in the advanced statefulset which enables controller to delete a stuck pending Pod, and record the failing node in the statefulset meta data (say annotation). Then next time controller can add a Pod-node anti-affinity rule so that Pods will not be scheduled to the failing node. The failing node annotation should be cleared after certain amount of time (manually or by controller).

**Comment by shyung** [comment]
The function of Advanced StatefulSet should be pure. The node problems, I supposed, are more suitable to be solved by a new controller, which can stain the nodes according to a series of strategies to make full use of the pod eviction mechanism.:sweat_smile:

**Comment by FillZpp** [comment]
@shyung Good point, thanks.
