### ISSUE TITLE
[New controller] PodMarker - A labeling tool

### ISSUE THREAD

**Issue by Fei-Guo** [openkruise/kruise#205]
Many advanced K8s workload management features require the use of labels. In some cases, labels are needed after Pods are created so that adding them to Pod template does not help .  For example, 

- A canary release plan may want to upgrade X number of Pods out of Y number of total replica. We can add a label to the chosen Pod so that the rollout controller can upgrade these Pods first.

- Pod container may provides a query service. We can add label based on query result so that we can rollout Pods based on container running status.

A PodMarker controller aims to fully automate the above process, and add labels to Pods dynamically based on specified rules. 

In the initial version, we can start with a very simple rule.
- For a specific workload, mark x number of replicas with specified label `key:val`

**Comment by fengzixu** [comment]
I would like to implement this feature for kruise.

**Comment by FillZpp** [comment]
closed by the new feature request #640
