### ISSUE TITLE
[feature request] 可以用 Image 字段来判断原地升级成功吗？

### ISSUE THREAD

**Issue by skilxn-go** [openkruise/kruise#217]
我注意到当前是根据 ImageID 的变更来认为原地升级成功的。
这里是否能够通过 containerStatues.image 字段来判断呢？我认为应该也是唯一的

**Comment by FillZpp** [comment]
We can not use `containerStatues[x].image` to check whether in-place update has succeeded. When there are multiple tags for one imageID on Node, it is decided by the CRI implement that which image name is returned to Kubelet.

For example, images `nginx:alpine` and `nginx:mainline-alpine` have the same imageID:

```bash
$ docker images | grep nginx
nginx                    alpine              36189e6707f4        10 days ago         21.5MB
nginx                    mainline-alpine     36189e6707f4        10 days ago         21.5MB
```

We updated `spec.containers[0].image = "nginx:alpine"` in Pod spec, the `status.containerStatues[0].image` might be reported as `nginx:alpine` or `nginx:mainline-alpine`.

If it is `nginx:mainline-alpine`, there is no way to find whether this in-place update is finished or not.
