### ISSUE TITLE
best practice for webhook service

### ISSUE THREAD

**Issue by luodw** [openkruise/kruise#225]
Is it a recommended way to use  webhook to inject sidecar container? If yes, webhook service must be very stable.  If webhook has something wrong, It will be a disaster, as it can not create pod any more. So there are some other best practice?

**Comment by Fei-Guo** [comment]
We do, I think we can set up multiple replica for controller manager, aka, the webhook service. @FillZpp may add more about this.

**Comment by FillZpp** [comment]
Fixed by #321
