### ISSUE TITLE
how to guarantee the start order of main and sidecar container?[feature request]

### ISSUE THREAD

**Issue by luodw** [openkruise/kruise#232]
**What would you like to be added**:
how to guarantee the start order of main and sidecar container?

**Why is this needed**:
There are cases that main container should start before  sidecar container，or sidecar container  should start before main container. what is the best bractice to do with it?

**Comment by furykerry** [comment]
There is indeed some plan to add a field in SidecarContainer struct, to specify the injection behavior. say 'BeforeAppContainer" specify that to inject the sidecar container before all containers in the original pod spec, or "AfterAppContainer" specify that to inject the sidecar container after all containers in the original pod spec. 

Yet this injection policy CANNOT guarantee the start order of container, and can ONLY serve as a best effort to ensure starting order. Although kubelet always start container in the order of container list specified in the pod spec, but the starting is asynchronous, and a container can crash and get restarted by kubelet. If strict ordering is required, app starting code must have some handling logic, and you can use post start hook to wait for the starting condition of other dependent container.

**Comment by luodw** [comment]
I ask another question，how to share infomation between main container and sidecar  container？ may be share volume？

**Comment by furykerry** [comment]
1. one can specify a volume in the sidecarset with the same name as the one used by main container, and the volume will be shared
2. or one can specify some env in the sidecarset using downward api, which reference pod label or annotation.
3. or one can simply access /dev/shm 
4. or one can just using lo network interface

**Comment by FillZpp** [comment]
Supported feature: https://openkruise.io/docs/user-manuals/containerlaunchpriority

**Comment by wgitg** [comment]
@FillZpp  If the sidecar container is injected by the SidecarSet, how do we control the exact order for the automatically injected container?

**Comment by zmberg** [comment]
@wgitg The order between multiple sidecars is currently not guaranteed. But, is it for the boot order, if so can consider[Container Launch Priority](https://openkruise.io/docs/user-manuals/containerlaunchpriority).
