### ISSUE TITLE
workload migration tools [feature request]

### ISSUE THREAD

**Issue by xcm153** [openkruise/kruise#238]
**What would you like to be added**:
We need a workload migration tools for migrate pod from deployment  to cloneset .
The process like rolling update with maxSurge=1 maxUnavailable=0 .

**Why is this needed**:
Cloneset can`t automatic takeover oprhaned pod , we need a tools to do it

**Comment by FillZpp** [comment]
Thanks for the nice suggestion. We have provided [kruise-tools](https://github.com/openkruise/kruise-tools) as a migration tool for users.
