### ISSUE TITLE
[feature request]provide a flag to turn off pod webhook register if not needed

### ISSUE THREAD

**Issue by pigletfly** [openkruise/kruise#252]
**What would you like to be added**:

**Why is this needed**:

currently pod webhook is registered for SidecarSet controller,but if we are not using SidecarSet, I think it's better not to register related webhook.If kruise webhook server is down, Pod can't be created in the cluster.

**Comment by FillZpp** [comment]
@pigletfly We supported two ways to disable some of the controllers/webhooks: https://github.com/openkruise/kruise#optional-enable-specific-controllers .

You may need to delete the `SidecarSet` CRD and restart kruise-manager, or you can add `CUSTOM_RESOURCE_ENABLE` env into kruise-manager container, which should be set to the kinds you need, such as `CUSTOM_RESOURCE_ENABLE=StatefulSet`
