### ISSUE TITLE
[feature request] SidecarSet: Support Shared Volume Between Sidecar and Main Pod

### ISSUE THREAD

**Issue by watermeion** [openkruise/kruise#254]
**What would you like to be added**:
add a strategy and implements for merging shared volumes or other pod level configs in sidecar mutation webhook.

**Why is this needed**:
If the sidecar and the main container should share the same pod level config such as volume etc, sidecarset should ensure the merging operation in mutation webhook can do as the user wish.

eg:  Use Case: Log Collection 
SidecarSet defines a volume name: log-volume
Deployment or Pod defines the same volume name: log-volume
These will conflict while rs creating pod after SidecarSet mutation webhook mutating the pod in version 0.4.1

**Comment by FillZpp** [comment]
@watermeion Please have a look at #255 , could it solve your problem?

**Comment by watermeion** [comment]
> @watermeion Please have a look at #255 , could it solve your problem?

@FillZpp Yes, thanks!  When or Which version  will this fix release?

**Comment by FillZpp** [comment]
@watermeion This will be contained in v0.5.0, which should release at mid-May.

**Comment by FillZpp** [comment]
@watermeion Hey, we have released v0.5.0 yesterday which contains this volume merge logic for SidecarSet. You may be interested to have a try. 😄

**Comment by watermeion** [comment]
awesome~!
