### ISSUE TITLE
[BUG] using maxSurge and partition UPDATED_READY pod not correct

### ISSUE THREAD

**Issue by shiyan2016** [openkruise/kruise#260]
**What happened**:
create an cloneset with replicas:8 maxSurge: 10% maxUnavaliable: 10% partition: 5
perform some update for the cloneset, when the update finish, the cloneset pod status as follows:
```bash
NAME              DESIRED   UPDATED   UPDATED_READY   READY   TOTAL   AGE
guestbook-clone   8         4         4               9       9       25m
```

**What you expected to happen**:
```bash
NAME              DESIRED   UPDATED   UPDATED_READY   READY   TOTAL   AGE
guestbook-clone   8         3         3               8       8       25m
```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kruise version: master
- Kubernetes version (use `kubectl version`): 1.14.6

**Comment by mkloveyy** [comment]
We have the same confusion about this.

**Comment by FillZpp** [comment]
@shiyan2016 Actually the status is what we expected to be, let me explain it.

1. `replicas:8, maxSurge: 10%` means the CloneSet will scale to 9 Pods during update.
2. `replicas:8, maxUnavaliable: 10%` means the CloneSet will keep at most 1 Pod to be unavailable during update.
3. `partition: 5` means the CloneSet will keep 5 Pods not to update.

When you started to update, controller will firstly create 1 more Pod because of `maxSurge`, then it update Pods until there are 5 old Pods left.

So currently there are 9 Pods running, 4 of them is updated revision and 5 of them is still old revision.

Doc ref: https://github.com/openkruise/kruise/tree/master/docs/concepts/cloneset#maxsurge

**Comment by shiyan2016** [comment]
@FillZpp I know this behavior likes the behavior during deployment rolling update. But when we set partition and reach the partition old pods left, it thinks this work is done. This is a final state, not a processing state. So in my opinion, I think keep 3 new updated revision pod is more reasonable. During the process that reach the partition old pods, it can keep replicas+maxSurge  pods.

**Comment by FillZpp** [comment]
@shiyan2016 Understand what you said.
But we want to support a condition that users could set `replicas=8, partition=8, maxSurge=10%`, which will keep all `replicas` number of Pods remain running and scale out 1 more Pod to verify.

**Comment by Fei-Guo** [comment]
Is this possible to manipulate the output of DESIRED?  For example, it can be 9(8) for update case where the number outside of the brackets is "replica+maxsurge" and the number inside bracket is "replica". In other cases, the DESIRED number is 8(8).

**Comment by FillZpp** [comment]
@Fei-Guo I'am afraid we cloud not print the output like `9(8)`. `printcolumn` must be a clear type without format.
https://github.com/openkruise/kruise/blob/master/config/crds/apps_v1alpha1_cloneset.yaml#L12

**Comment by shiyan2016** [comment]
@FillZpp @Fei-Guo If we keep updated ready replicas-partition+maxsurge pods when partition update done, it will waste resource especially for the big cluster. For example, I have a cloneset with replicas 200, maxSurge 20%, set partition to 100, and need to keep this state for a period of time. Then in this period of time, it will keep more 40 pod.

**Comment by FillZpp** [comment]
@shiyan2016 How about we add a validation that forbids users to set `maxSurge` together with `partition` for it might be a little confusing?

**Comment by shiyan2016** [comment]
@FillZpp Forbid setting maxSurge and partition together, it is not friendly for Recreate update strategy when updating small cluster which will cause some pods not ready that cannot provide services.

**Comment by fatedier** [comment]
> MaxSurge is the maximum number of pods that can be scheduled above the desired replicas during the update.

It depends on how to understand the `update` state.

For current design, `update` means the process of updating all pods from last versions to update version.

But maybe for other users, they do an update operation from `replicas: 5, partition: 0, maxSurge=1, version: 1` to `replicas: 5, partition: 4, maxSurge=1, version: 2`.   What they want are 1 new pod and 4 old pods. `maxSurge` pods can be create to help recreate old pod and unnecessary after we achieve the expect state.

> @shiyan2016 Understand what you said.
> But we want to support a case that users could set `replicas=8, partition=8, maxSurge=10%`, which will keep all `replicas` number of Pods remain running and scale out 1 more Pod to verify.

Set `replicas=9, partition=8, maxSurge=10%` can get the same result.

**Comment by FillZpp** [comment]
@shiyan2016 @fatedier Thanks for all your suggestions. It sounds reasonable to make `maxSurge` work with `partition`. 

Let's confirm the process again. For a CloneSet to update revision from `v1` to `v2` with `replicas=5, partition=3, maxSurge=1, maxUnavailable=0`:

1. Controller firstly creates 1 Pod in `v2` (currently `v1` * 5, `v2` * 1)
2. When there are `v1` * 3 Pods left which matches `partition`, controller will delete 1 Pod in `v2` (currently `v1` * 3, `v2` * 2)

Then if we update CloneSet to `partition=0`:

1. Controller firstly creates 1 Pod in `v2` (currently `v1` * 3, `v2` * 3)
2. When all Pods have reached `v2`, controller will delete 1 Pod in `v2` (currently `v2` * 5)

**Comment by fatedier** [comment]
@FillZpp It's fine for me.

**Comment by shiyan2016** [comment]
@FillZpp That's what I expected.

**Comment by zhouguangming** [comment]
Can we consider to have a new policy named RollingUpdate or something else just like Deployment for MaxSurge？

**Comment by shiyan2016** [comment]
@zhouguangming @FillZpp I tried set ReCreate and MaxSurge together, it still work. It seems a little contradiction in k8s design. And in deployment, only rolling update strategy can set maxSurge.

**Comment by mkloveyy** [comment]
@FillZpp 
I think it should be easier to understand by renaming ReCreate to RollingUpdate. As in K8S Deployment, only RollingUpdate strategy supports MaxSurge and MaxUnavailable.

**Comment by fatedier** [comment]
Can we also support `maxSurge` for `In-place update`.

For some stateless applications, they always want to keep enough replicas(not take up extra resources all the time). But for some reason(such as to keep the scheduling result), they prefer `In-place` update.

If we support `maxSurge` for `In-place` update, the process will be changed to:

`version v1 -> v2, replicas=5, maxSurge=1, maxUnavailable=0`

1. Create 1 `v2` pod.
2. Wait for new pod ready, in-place update 1 `v1` pod to `v2`.
3. Continue the process as before.
4. After all pods has been updated to `v2`, remove the 1 `v2` pod created in the beginning(we should consider how to detect this).

**Comment by FillZpp** [comment]
@shiyan2016 @zhouguangming  It might be a misunderstanding, the policy types in CloneSet are not same as Deployment.  

@mkloveyy is partly right. But why we call it `ReCreate` instead of `RollingUpdate`?

1. The mainly difference between `RollingUpdate` and `Recreate` in Deployment are rolling and killing-all. In this respect, all policies in CloneSet are rolling update (we do not support killing-all).
2. The types in CloneSet indicate how we update each Pod, recreate it or in-place update it. No matter which type we use, the Pods are all rolling with strategies like maxSurge/maxUnavailable.

**Comment by FillZpp** [comment]
@fatedier We do support to use `maxSurge` with in-place update. 
The only question is since the `v2` Pod created in the beginning is available, why should we delete this specific Pod finally?

**Comment by fatedier** [comment]
> @fatedier We do support to use `maxSurge` with in-place update.
> The only question is since the `v2` Pod created in the beginning is available, why should we delete this specific Pod finally?

The `v2` pod created in the beginning is aimed to keep enough ready pods during the `in-place` update (5 `v1` -> 5 `v2`). After all pods have been updated to new version and ready, we get 6 `v2` pods and the beginning one is unexpected.

**Comment by FillZpp** [comment]
@fatedier How about open a new issue to track this requirement?

**Comment by fatedier** [comment]
> @fatedier How about open a new issue to track this requirement?

Sure. I will do that.

**Comment by mkloveyy** [comment]
@FillZpp Understood. The definition of ReCreate is different between in CloneSet and in Deployment and all strategies in CloneSet are RollingUpdate.
