### ISSUE TITLE
[feature request] Support Deployment for UnitedDeployment

### ISSUE THREAD

**Issue by uhari03** [openkruise/kruise#262]
**What would you like to be added**:
Currently UnitedDeployment only supports Statefulsets. The docs do mention that Deployments will be supported soon, but no timelines exist.

**Why is this needed**:
I am personally looking to support biased spreading of pods in a deployment across Availability Zones. I am also more than happy to contribute, but will love some pointers on where I can start.

**Comment by Fei-Guo** [comment]
May I ask why StatefulSet or AdvancedStateful does not fit your requirement?

**Comment by uhari03** [comment]
@Fei-Guo we currently have folks deploying "Deployment" objects into k8s clusters.
We want the transition to UnitedDeployment to be as smooth and as simple as possible. Deployment support will assist with this.

We may also have a small subset of users doing special tooling around Deployment objects (blue/green deployment is one example). Using statefulsets may result in additional work being done on those tools as well.

**Comment by wu8685** [comment]
Generally, you can consider to start by providing an adapter for Deployment by implementing the [interface](https://github.com/openkruise/kruise/blob/master/pkg/controller/uniteddeployment/adapter/adapter.go#L26). 

Considering Deployment does not has `partition` feature, current `[UpdateStrategy](https://github.com/openkruise/kruise/blob/master/pkg/apis/apps/v1alpha1/uniteddeployment_types.go#L105)` may be disabled in this case.

**Comment by Fei-Guo** [comment]
@uhari03 I encourage you to start adding deployment support. Let me know if further assist is needed. You can find me via the slack channel (id: Fei Guo).

**Comment by uhari03** [comment]
I agree that UpdateStrategy might need to be disabled initially for deployment objects.
But I'm sure more can be done with it to expand.

Initially it should be fine since Deployments support rollout strategies themselves.

I appreciate the pointers, let me take a look at the pointers you both provided.
