### ISSUE TITLE
[feature request] Support Partition for the CloneSet creation

### ISSUE THREAD

**Issue by mkloveyy** [openkruise/kruise#265]
**What would you like to be added**:
Support Partition for the CloneSet creation.

**Why is this needed**:
We hope that the CloneSet creation can have the same behavior with CloneSet update.

**Comment by FillZpp** [comment]
@mkloveyy We do support partition during creating Pods. 
Ref: https://github.com/openkruise/kruise/blob/master/pkg/controller/cloneset/core/cloneset_core.go#L72

**Comment by mkloveyy** [comment]
@FillZpp It's not creating pods from old to new versions, but the first creation of CloneSet(from nil to v1).

**Comment by FillZpp** [comment]
@mkloveyy I don't quite understand. Could you please describe it with a case?

**Comment by mkloveyy** [comment]
### What happened:
Create CloneSet for the first time with replicas:8 partition: 5. When the creation finish, the CloneSet pod status as follows (partition isn't active):
```
NAME              DESIRED   UPDATED   UPDATED_READY   READY   TOTAL   AGE
guestbook-clone   8         8         8               8       8       25m
```
### What you expected to happen:
```
NAME              DESIRED   UPDATED   UPDATED_READY   READY   TOTAL   AGE
guestbook-clone   8         3         3               8       8       25m
```

**Comment by fatedier** [comment]
@mkloveyy Does this behavior really make sense? What's scenario requires you must do this instead of creating a cloneset with 3 replicas?

**Comment by mkloveyy** [comment]
ok，I wil close the issue.
