### ISSUE TITLE
I have three questions about `SidecarSet`. Could anyone help?

### ISSUE THREAD

**Issue by skilxn-go** [openkruise/kruise#277]
Two of them are about [these codes](https://github.com/openkruise/kruise/blob/eb63c9b2aa9fa52ba7eb2e14f9dd140d9cfa4bb2/pkg/controller/sidecarset/sidecarset_utils.go#L227-L239)
```golang
func isPodImageConsistent(pod *corev1.Pod) bool {
	containerSpecImage := make(map[string]string, len(pod.Spec.Containers))
	for _, container := range pod.Spec.Containers {
		containerSpecImage[container.Name] = container.Image
	}

	for _, containerStatus := range pod.Status.ContainerStatuses {
		if containerSpecImage[containerStatus.Name] != containerStatus.Image {
			return false
		}
	}
	return true
}
```
1. Using container spec image for `PodImageConsistent` is not reliable, right? If two image has the same imagelayer with different tags, `containerStatus.Image` may differ to `pod.Spec.Containers.Image` forever. Why don't we use the same detect method as Advanced Statefulset?

2. Why should we care about user's containers' image consistent which can only be changed by an in-place update? I think if the user wants to block sidecar updating, they should make the pod `NotReady` themselves, like what Advanced Statefulset does.

And the last one is about [this code](https://github.com/openkruise/kruise/blob/eb63c9b2aa9fa52ba7eb2e14f9dd140d9cfa4bb2/pkg/controller/sidecarset/sidecarset_controller.go#L179)
![image](https://user-images.githubusercontent.com/8231208/83494615-1e3ef880-a4e9-11ea-9c31-5b397e9d8585.png)

3. Shouldn't we check the `updateCache.isSidecarUpdated` here?

**Comment by FillZpp** [comment]
@skilxn-go Thanks for these nice suggestions.

1 & 2: It is really a bad idea to compare images between spec and status. We used to think about considering other containers to be image consistent before sidecar updating. But as you said, there is no need to do this, for both `CloneSet`, `Advanced StatefulSet` will make Pods NotReady before in-place update and original workloads like `Deployment` only update Pods with deletion.

3: Clearly, it is a bug. We should check both updateCache and Pod getting from informer in this loop.

May I ask if you have interest in optimizing these problems? 😄 
Thanks again for your feedback!

**Comment by skilxn-go** [comment]
Sure, I'm trying to use `SidecarSet` in our project, so I need to fix them anyway. I will open new issues for tracking these problems separately.
