### ISSUE TITLE
[BUG]scale clonesets error

### ISSUE THREAD

**Issue by cuishuaigit** [openkruise/kruise#278]
**What happened**:
when i scale clone,something was wrong
**What you expected to happen**:
scale clone  1 to  3
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
→ kubectl scale --replicas=2 clone guestbook-clone
+ kubectl scale --replicas=2 clone guestbook-clone
The clonesets "guestbook-clone" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
**Environment**:
k8s 1.15
- Kruise version:
v0.5.0
- Kubernetes version (use `kubectl version`):
k8s 1.15
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by FillZpp** [comment]
@cuishuaigit This is a bug in kubectl v1.15, references:
- https://github.com/kubernetes/kubernetes/issues/80515
- https://github.com/kubermatic/kubeone/issues/593

Cloud you test it with kubectl 1.16+ ?

**Comment by cuishuaigit** [comment]
thanks a lot @FillZpp v1.18 work for me
