### ISSUE TITLE
[feature request] support manual rolling update of the upstream deployment 

### ISSUE THREAD

**Issue by xiegang1** [openkruise/kruise#279]
**What would you like to be added**:
We'd like to have the function of the rolling update of the deployment controlled by people manually.

**Why is this needed**:
kruise supports manual rolling out in clone set. But it against the pod. Some cloud native framework, like istio, usually operate the deployment directly. So, if we want to use those third party framework, we have to use the original k8s items, like deployment, etc.

**Comment by furykerry** [comment]
> We'd like to have the function of the rolling update of the deployment controlled by people manually.

I'm afraid it is not possible since apps/deployment is controlled by the k8s controller not the kruise one. We cannot change the behavior of apps/deployment without changing [code](https://github.com/kubernetes/kubernetes).

**Comment by xiegang1** [comment]
So, in Ali, with kruise, how do we cooperate it to the third-party framework, like istio, which operates the unstream controller, like deployment?

**Comment by FillZpp** [comment]
@xiegang1 It seems istio injects sidecars for Pods, so it does not depend on the Pod managed by either original `Deployment` or `CloneSet` in OpenKruise?
