### ISSUE TITLE
[BUG]kruise在阿里云serverless集群上的错误

### ISSUE THREAD

**Issue by Aerospace191** [openkruise/kruise#283]
kruise在serverless集群上会有如下错误：
`[root@QA cashier_backend]# kubectl apply -f nginx.yaml 
Error from server (InternalError): error when creating "nginx.yaml": Internal error occurred: failed calling webhook "validating-create-update-statefulset.kruise.io": Post https://webhook-server-service.kruise-system.svc:443/validating-create-update-statefulset?timeout=30s: service "webhook-server-service" not found`
但是集群中的svc是kruise在创建时自动创建的：
`[root@QA cashier_backend]# kubectl get svc -n kruise-system
NAME                                TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
kruise-controller-manager-service   ClusterIP   172.19.9.227   <none>        443/TCP   110m
kruise-webhook-server-service       ClusterIP   172.19.1.94    <none>        443/TCP   106m
`
请问如何才能在serverless集群上成功使用kruise服务？

**Comment by FillZpp** [comment]
@Aerospace191 How did you install kruise, via helm or all_in_one.yaml ?

**Comment by FillZpp** [comment]
Rotten issues close after 90d of inactivity.
