### ISSUE TITLE
[BUG] setting maxSurge and partition, cloneset's behavior is not suitable

### ISSUE THREAD

**Issue by shiyan2016** [openkruise/kruise#286]
**What happened**:
Create a cloneset with replicas 8, partition 6, maxSurge 50% and maxUnavaliable 0. Do some update for the cloneset pod template, it will create 8*50%=4 update pod, and after ready delete 4+2=6 pod.

**What you expected to happen**:
During the update, the update pod creation should not 
exceed maxSurge and replicas-partition. In this case, just create 2 update pod, after ready delete 2+2=4 pod.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kruise version: v0.5.0
- Kubernetes version (use `kubectl version`): v1.17.4
- OS (e.g: `cat /etc/os-release`):  ubuntu 16.04

**Comment by FillZpp** [comment]
@shiyan2016 What a coincidence! @fatedier and I just talked about this yesterday.

He has submitted a PR to fix it #285

**Comment by shiyan2016** [comment]
Ok. That's great. I will pay attention to the PR #285.

**Comment by FillZpp** [comment]
@shiyan2016 Hi, the PR has been merged. It should be released in v0.5.1 this month.

**Comment by shiyan2016** [comment]
@FillZpp  When will v0.5.1 be released？

**Comment by FillZpp** [comment]
@shiyan2016 Hi, it will be released next week.

By the way, to get more feedback of Kruise's adoption in industry, would you mind helping comment in issue #289  to give more information about your enterprise's Kruise usage. Thanks a lot in advance. 😄

**Comment by shiyan2016** [comment]
@FillZpp  How about the v0.5.1 release ?

**Comment by FillZpp** [comment]
Already fixed in `v0.6.0`.
