### ISSUE TITLE
[feature request]Add metric for kruise‘s cr 

### ISSUE THREAD

**Issue by peacocktrain** [openkruise/kruise#299]
**What would you like to be added**:
statefulset/cloneset/sidecarset/job  need to add metric with replica, available, unavailable, complete, number of resource .....

**Why is this needed**:
For example, Deploy has kube-state-metric, which can provide the metric, so we can well count and monitor it in Prometheus. Kruise's CR also needs these things

**Comment by ryanzhang-oss** [comment]
Is the Prometheus/Grafana setup up already so all we need to do is to collect the metrics and emit them through Prometheus client?

**Comment by peacocktrain** [comment]
> Is the Prometheus/Grafana setup up already so all we need to do is to collect the metrics and emit them through Prometheus client?

yes, Implement the metric and teach him out

**Comment by ryanzhang-oss** [comment]
teach him out?

**Comment by peacocktrain** [comment]
> teach him out?

Translation software error， export them

**Comment by peacocktrain** [comment]
@ryanzhang-oss Are you going to start another program like Kube-state-metrics?

**Comment by ryanzhang-oss** [comment]
> @ryanzhang-oss Are you going to start another program like Kube-state-metrics?

what do u mean by "another program"? Another container? process? goRoutine?

**Comment by peacocktrain** [comment]
> what do u mean by "another program"? Another container? process? goRoutine?

写在kruise里， 还是像Kube-state-metrics一样另写一个项目单独部署？

**Comment by liangyuanpeng** [comment]
is it implement from https://github.com/openkruise/kruise-state-metrics?

**Comment by FillZpp** [comment]
@liangyuanpeng Yes, the project is still in progress and will be packaged in v1.0 release.
