### ISSUE TITLE
[feature request] Build ARM/ARM64 images

### ISSUE THREAD

**Issue by windnod** [openkruise/kruise#300]
**What would you like to be added**:
Provide ARM/ARM64 images.

**Why is this needed**:
Need work on ARM machines.

**Comment by Fei-Guo** [comment]
The ubuntu:lastest image supports arm arch so you may just simply change the docker file to specify the GOARCH to arm when building the image.

```
diff --git a/Dockerfile b/Dockerfile
index dee6a800..a1b6a8fe 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -15,7 +15,7 @@ COPY pkg/ pkg/
 COPY vendor/ vendor/

 # Build
-RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on go build -mod=vendor -a -o manager ./cmd/manager
+RUN CGO_ENABLED=0 GOOS=linux GOARCH=arm GO111MODULE=on go build -mod=vendor -a -o manager ./cmd/manager

 # Copy the controller-manager into a thin image
 FROM ubuntu:latest
diff --git a/Makefile b/Makefile
index c2a73033..244dc1d4 100644
--- a/Makefile
+++ b/Makefile
@@ -1,6 +1,6 @@

 # Image URL to use all building/pushing image targets
-IMG ?= openkruise/kruise-manager:test
+IMG ?= openkruise/kruise-manager-arm:test
 # Produce CRDs that work back to Kubernetes 1.11 (no version conversion)
 CRD_OPTIONS ?= "crd:trivialVersions=true"
```
Let us know if this one works as we don't have arm machine to verify at this moment. 

Thanks

**Comment by cerebrate** [comment]
I have this working fine on ARM, but I would like to extend the feature request slightly. I have a multiple architecture cluster incorporating both amd64 and arm nodes, so I would particularly appreciate it if OpenKruise came with a multi-arch image.

My current method of building these for my cluster uses `docker buildx`, which I believe is still technically experimental. Given that, would you be interested in a PR that does this?

**Comment by Fei-Guo** [comment]
Are you suggesting to include two binaries (one for arm and one for amd64) in one image?

**Comment by cerebrate** [comment]
I think it’s two images in one manifest rather than two binaries in one image?

The one I built for myself is cerebrate/kruise-manager:0.7.0 on Docker Hub; when one of my nodes pulls that repository and tag, it automatically gets the image that matches the architecture of the node.

**Comment by Fei-Guo** [comment]
@cerebrate Understood!  Yes. You are certainly welcome to help to build multi-arch image for Kruise. 

Thanks
