### ISSUE TITLE
[BUG] CloneSet requires dataSource

### ISSUE THREAD

**Issue by billonahill** [openkruise/kruise#301]
**What happened**:
Applied a CloneSet without a dataSource and got this error:
```
The CloneSet "testcloneset" is invalid: spec.volumeClaimTemplates.spec.dataSource: Invalid value: "null": spec.volumeClaimTemplates.spec.dataSource in body must be of type object: "null"
Error: exit status 1
```

**What you expected to happen**:
The config is applied.

**How to reproduce it (as minimally and precisely as possible)**:
Apply a CloneSet config that does not include `spec.volumeClaimTemplates.spec.dataSource`.

**Anything else we need to know?**:
Link to slack discussion:
https://kruise-workspace.slack.com/archives/CK5G41AF3/p1593025696007200

**Environment**:
- Kruise version: observed in 0.4.1, 0.5.0
- Kubernetes version (use `kubectl version`): 1.18
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by reverson** [comment]
We install the CRD from here, which has the dataSource requirement I believe: https://github.com/openkruise/kruise/blob/master/config/crds/apps.kruise.io_clonesets.yaml

Versus the one from here that does not have the CRD: https://github.com/openkruise/kruise/blob/master/charts/kruise/v0.5.0/templates/apps_v1alpha1_cloneset.yaml

**Comment by Fei-Guo** [comment]
This seems to be a controller-tools problem. We have filed this issue to track 

https://github.com/kubernetes-sigs/controller-tools/issues/457

By the mean time, we may add a temporal script to manually workaround this problem. @FillZpp.

**Comment by FillZpp** [comment]
I have submitted a PR [kubernetes-sigs/controller-tools#460](https://github.com/kubernetes-sigs/controller-tools/pull/460) for controller-tools.

If it can not be released in the short term, I will use a *kruise-fork* controller-tools to fix it for a while.

**Comment by shiyan2016** [comment]
@FillZpp It happened when I applied cloneset with pvcs. And when I apply the new crd yaml. The problem still exists. Since I delete and recreate the crd, it repaired. But this will cause the cloneset object deleted.

**Comment by FillZpp** [comment]
@shiyan2016 You may replace the crd yaml using `kubectl replace` instead of applying it?
