### ISSUE TITLE
[feature request]How to manage more and more operators? A system of operators is wanted.

### ISSUE THREAD

**Issue by zhangxiaoyu-zidif** [openkruise/kruise#303]
**What would you like to be added**:
How to manage more and more operators? A system of operators is wanted.

**Why is this needed**:
* More and more operators are created, we need a system to manage it.
* Operators' rolling update should follow specified security policies.
* Other reasons for Kubernetes cluster stability.

**Comment by zhangxiaoyu-zidif** [comment]
ping @Fei-Guo @FillZpp 

Should we start our thread on operator Platform here ?

**Comment by kfox1111** [comment]
https://github.com/operator-framework/operator-lifecycle-manager

Its now a cncf incubating project
