### ISSUE TITLE
[BUG] CloneSet pods not created when PVC is terminating

### ISSUE THREAD

**Issue by reverson** [openkruise/kruise#313]
**What happened**: The cloneset was scaling, and somehow one of the pods got into a state where it's PVC was being Terminated, while the pod itself was running.  The pod continued to run fine, but all other pods were stuck in a Pending state, and no new pods would get created (even in a Pending state) until the offending one was deleted.

I saw this in the logs 
```
0716 19:33:59.712743       1 cloneset_controller.go:212] Not satisfied scale for staging/nodemanager-7d9e1, scaleDirtyPods=map[delete:[ebs-nodemanager-7d9e1-htcdq]]
````

Before that pod was deleted, all other pods that had been created were in the Pending state, with odd errors in the events.
```
  Warning  FailedScheduling   2m50s (x148 over 33m)  default-scheduler   persistentvolumeclaim "ebs-nodemanager-7d9e1-9hftn" not found
```

**What you expected to happen**: Pods would continue to come up and run successfully, even though this one was in an odd state

**How to reproduce it (as minimally and precisely as possible)**: I'm not entirely sure what happened.

**Anything else we need to know?**:

**Environment**:
- Kruise version: 0.5
- Kubernetes version (use `kubectl version`): 1.16.8
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by reverson** [comment]
I'm not sure how this happened, but I was able to reproduce this again.

Best I can tell, if you deploy a cloneset, and then immediately scale it down this triggers (so deploy a 10 replica cloneset, and then immediately scale down to 3 replicas). That is the usecase I'm currently running into.

I can add some delay to my scaling logic so that we only scale after a certain time period, but I would hope that this wouldn't cause this issue.

**Comment by reverson** [comment]
So I was able to just reproduce this by scaling up my cloneset, immediately scale it down, and then I see the following.

The number of pods running in the end is correct (3), but the data in the get cloneset call is wrong. These are the pods scaled down.
```
I0717 00:08:28.152895       1 main.go:75] Deleting pods [nodemanager-eb28e-mqnhd nodemanager-eb28e-kbsl7 nodemanager-eb28e-v6zbt nodemanager-eb28e-zflnz]
```
These are the pods the kruise-controller-manager started to delete (or at least the EBS volumes it started to delete).
```
I0717 00:09:34.491768       1 cloneset_controller.go:212] Not satisfied scale for reverson/nodemanager-eb28e, scaleDirtyPods=map[delete:[ebs-nodemanager-eb28e-bjzg7 ebs-nodemanager-eb28e-kbsl7 ebs-nodemanager-eb28e-mqnhd]]
```
So it seems that the cloneset-instance-ids on the PVCs are getting duplicated, which I validated here
```
for i in 958s6 bjzg7 t6q4k v6zbt zflnz; do echo $i; kubectl -n reverson get pvc ebs-nodemanager-eb28e-$i  -o yaml | grep cloneset-instance-id; done
958s6
    apps.kruise.io/cloneset-instance-id: 958s6
bjzg7
    apps.kruise.io/cloneset-instance-id: kbsl7
t6q4k
    apps.kruise.io/cloneset-instance-id: t6q4k
v6zbt
    apps.kruise.io/cloneset-instance-id: t6q4k
zflnz
    apps.kruise.io/cloneset-instance-id: t6q4k
```

**Comment by reverson** [comment]
Now these are the PVCS and their cloneset-instance-ids after waiting a bit.
```
NAME                          STATUS        ...      AGE    CLONESET-INSTANCE-ID
ebs-nodemanager-eb28e-958s6   Bound        ...   61m    958s6
ebs-nodemanager-eb28e-bjzg7   Terminating   ...   61m    kbsl7
ebs-nodemanager-eb28e-t6q4k   Bound         ...   61m    t6q4k
```
And the pods running
```
nodemanager-eb28e-958s6  
nodemanager-eb28e-bjzg7   
nodemanager-eb28e-t6q4k   
```
Weirdly the PVCs with the cloneset-instance-id of `t6q4k` that were associated with pods that got deleted ended up getting removed.

**Comment by reverson** [comment]
Just repro'd this case by scaling my cloneset from 3 to 10 and looking at the pvc instance-id, of the 7 that got created, 1 of them was created with the wrong instance-id.
```
name    instance-id
ebs-nodemanager-eb28e-4jbrz    4jbrz
ebs-nodemanager-eb28e-8xtz5    8xtz5
ebs-nodemanager-eb28e-958s6   958s6
ebs-nodemanager-eb28e-chndw    chndw
ebs-nodemanager-eb28e-f2bfg    lmgh4
ebs-nodemanager-eb28e-hxk77    hxk77
ebs-nodemanager-eb28e-lmgh4    lmgh4
ebs-nodemanager-eb28e-mkcfg    mkcfg
ebs-nodemanager-eb28e-nq5wv    nq5wv
ebs-nodemanager-eb28e-t6q4k    t6q4k
```

**Comment by Fei-Guo** [comment]
We have identified the root cause. We have not hit cases where a pvc can be stuck in terminating stage (maybe due to some finalizers set by other controllers) before. This case can be optimized and we are preparing a fix.

**Comment by FillZpp** [comment]
@reverson Sorry for inconveniencing you. It looks like two problems in it:

1. Terminating PVC will block the CloneSet to scale out again.
2. PVCs have wrong instance-id.

For the former one, I have found [where the problem is](https://github.com/openkruise/kruise/blob/master/pkg/controller/cloneset/cloneset_event_handler.go#L262). Currently the `pvcEventHandler` must wait for PVC already deleted in informer (which means this PVC have deleted in etcd) and then observe it in expectation. So if your PVC keeps in terminating state, the expectation will always be not satisfied. We will improve the `pvcEventHandler`, it should observe PVCs when they have been set `DeletionTimestamp`.

For the latter one, I have no idea why it happened yet. So I fixed the former one and pushed a test image `openkruise/kruise-manager:v0.5.0-test.1`. Would you please update to this image and test it again? I really appreciate what you've tested for it.

**Comment by reverson** [comment]
I'm unable to test this in the environment we use (we build and host the image locally), but I tested this locally and wasn't able to reproduce either issue.

Is there a code branch I can use to build and test in our staging environment?

**Comment by FillZpp** [comment]
@reverson Sure. Could you test it with repo `https://github.com/FillZpp/kruise` and branch `fix-cloneset-blocking-by-terminating-pvc`? If not, I can create a test branch in repo `openkruise/kruise` for you.

**Comment by reverson** [comment]
If it's possible to set it up with a branch in the openkruise repo that
would be much easier for us to test.

**Comment by FillZpp** [comment]
@reverson Done. You could test it with branch `testing-cloneset-blocked-by-terminating-pvc` now :)

**Comment by reverson** [comment]
I've confirmed that I don't see the scaling issue when there are terminating PVCs now.

Should we open another issue for the issue with pvcs getting created with the wrong cloneset id? I attempted to delete a pod manually that would had an incorrect instance-id, but I see the pod gets recreated with the same name, so I can't see if the underlying PVC would also get deleted.

**Comment by Fei-Guo** [comment]
> Should we open another issue for the issue with pvcs getting created with the wrong cloneset id? I attempted to delete a pod manually that would had an incorrect instance-id, but I see the pod gets recreated with the same name, so I can't see if the underlying PVC would also get deleted.

Yes. I would suggest to open another issue to track incorrect instance-id problem which seems to be irrelevant to the PVC stuck problem.

Thanks
