### ISSUE TITLE
[BUG] CloneSet PVCs get set with incorrect cloneset-instance-id

### ISSUE THREAD

**Issue by reverson** [openkruise/kruise#320]
**What happened**: When scaling up a cloneset, the PVCs that are created get the proper name, but the incorrect cloneset-isntance-id

**What you expected to happen**: PVCs get the same name and cloneset-instance-id.

**How to reproduce it (as minimally and precisely as possible)**: In my environment (AWS) scale up the cloneset from 3 to 10 instances and run the following command
`kubectl  get pvc -L apps.kruise.io/cloneset-instance-id` there will be a bunch of pvcs with names link `pvc-cloneset-1234`, with cloneset-instance-ids of something other than `1234`, which will map to another cloneset instance.

**Anything else we need to know?**: This appears to also cause PVCs that have the wrong cloneset-instance-id to either get into a terminating state when the instance that "owns" it is deleted, or stay around when the instance that is using it is deleted, but the instance that "owns" it isn't.

This is an example of what I see.
```
NAME    ...    CLONESET-INSTANCE-ID
...
ebs-cloneset-6qgvx    ...   8cf7z
...
```

**Environment**:
- Kruise version: Latest master 
- Kubernetes version (use `kubectl version`): 1.16

**Comment by reverson** [comment]
This may be related to #349 as it fails also on the PVC creation, but I'm having a hard time finding the connection.

The only place I can see in the code that sets the PVC instance ID is in cloneset_utils.go:GetPersistentVolumeClaims.  I have a commit here that I think may address the issue, but I can't see why the reference to the pod would change out from the function while it's running. https://github.com/reverson/kruise/commit/8687fe4ab93485a8fcb420e79eaf7925b9a7061d

**Comment by reverson** [comment]
Odd, even with that commit (which sets the id as a var instead of inspecting it twice) the tag still gets set incorrectly.

```
ebs-nodemanager-eb28e-72lt5   Bound    pvc-39a16ca0-0341-4cc8-995c-c5100d309330   20Gi       RWO            gp2-reclaimdelete-waitforconsumer-expansible   5m59s   f4ndd
```

**Comment by reverson** [comment]
I think I may have identified the cause for this and #349.  The controller-runtime uses a cache for the api connection, which uses a shared api client connection. When all 3 of the default cloneset workers attempt to create a cloneset pvc at the same time, I believe this causes some data corruption within the controller-runtime code.
https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/typed_client.go#L34 <- gets the connection from cache
https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/client_cache.go#L100 <- is the cache

If the PVC controller is slow, this call may take a while and so another PVC creation may come in in the meantime and use the same connection to create as there is no locking around either the PVC creation, nor the api client connection.

I'm putting in a PR to add locking around the Create call within CloneSet and will link it here after I run some tests and upload it here.

**Comment by FillZpp** [comment]
@reverson Could you please retest **incorrect instance-id** and **concurrent write panic** with the latest master branch, since we have merged #361 ?

**Comment by reverson** [comment]
Yep, I tested this briefly and did not see the issues during my tests.

**Comment by FillZpp** [comment]
> Yep, I tested this briefly and did not see the issues during my tests.

Cool. So this issue can be closed.
