### ISSUE TITLE
[feature request]Sidecar Resource is calculated according to the proportion of POD Resource.

### ISSUE THREAD

**Issue by peacocktrain** [openkruise/kruise#329]
**What would you like to be added**:
SidecarSet，Sidecar Resource is calculated according to the proportion of POD Resource.

**Why is this needed**:
We have some thoughts on the sidecar resource limit.  Business containers consume more resources, so sidecar should also consume more resources than other Pods. so sidecar resource should be set up in two ways，defined and proportional

**Comment by Fei-Guo** [comment]
This sounds to be a reasonable request.  @ryanzhang-oss FYI.

**Comment by ryanzhang-oss** [comment]
@peacocktrain  I think this is a reasonable ask. However, I wonder if you can be a bit more specific on the use case? Like exactly what does the sidecar is trying to achieve?

**Comment by peacocktrain** [comment]
> @peacocktrain I think this is a reasonable ask. However, I wonder if you can be a bit more specific on the use case? Like exactly what does the sidecar is trying to achieve?

Network sidecars，like  envoy.  Logs sidecars. We give sidecar to all pods，but 4C pod flow is significantly higher than 2C

**Comment by ryanzhang-oss** [comment]
What is a 4C pod? Is the sidecar's resource proportional to the total resource of the pod or the "main" container?

**Comment by ryanzhang-oss** [comment]
@peacocktrain Another question is how do you plan to consolidate the differences between this value proportional to the size of the pod and the `Requests` and `Limits` value set in the sidecar container. Will this value replace them all?

**Comment by peacocktrain** [comment]
> What is a 4C pod? Is the sidecar's resource proportional to the total resource of the pod or the "main" container?

“main” container

**Comment by peacocktrain** [comment]
> @peacocktrain Another question is how do you plan to consolidate the differences between this value proportional to the size of the pod and the `Requests` and `Limits` value set in the sidecar container. Will this value replace them all?

In our scenario, limit=request because Sidecar does not change the POD's qos

**Comment by peacocktrain** [comment]
> What is a 4C pod? Is the sidecar's resource proportional to the total resource of the pod or the "main" container?

emmm. 4C is the total requested resource of the pod, This value participates in the schedule

**Comment by ryanzhang-oss** [comment]
> In our scenario, limit=request because Sidecar does not change the POD's qos

now we have 3/4 values,  you can set the Requests and Limits value set in the sidecar container spec with the additional value proportional to the "main" container. Do you want to void the Requests and Limits value set in the sidecar container spec and use the additional value alone?

**Comment by peacocktrain** [comment]
`you can set the Requests and Limits value set in the sidecar container spec with the additional value proportional to the "main" container`,That's what I want

**Comment by ryanzhang-oss** [comment]
> That's what I want

so now we have 3 values, how do you want those to consolidate? What exactly does each value mean?

**Comment by peacocktrain** [comment]
@ryanzhang-oss  What is the 3 values?

**Comment by ryanzhang-oss** [comment]
1. The proportional value you asked
2. Resource requests in the sidecar container spec
3. Resource limits in the sidecar container spec

**Comment by peacocktrain** [comment]
If (request or limit is set in sidecarset) it depends on the value.
else If  (can we looking for the container which the largest resource in POD) calculate that and make request=limit
else nil

**Comment by ryanzhang-oss** [comment]
> it depends on the value.

can you elaborate on what exactly does "depends" mean here?

**Comment by peacocktrain** [comment]
> can you elaborate on what exactly does "depends" mean here?

pod.spec.container[].resources = sidecar.resource

**Comment by ryanzhang-oss** [comment]
so here is the semantics

when the proportional value is set, then the sidecar container limit will be the max (limit, proportional value) and the sidecar's request is also set to that value if it's not set.
