### ISSUE TITLE
Remove public IP in docs/tutorial/README.md

### ISSUE THREAD

**Issue by Fei-Guo** [openkruise/kruise#33]
We should not expose public IP in any doc.  Please replace the public ip in tutorial readme with XXX.XXX.XXX.XXX in text and figure. @wonderflow please help if you can.

**Comment by jian-he** [comment]
The IPs are not public IPs, and the IPs are there to demonstrate that the IPs of all pods are not changed before and after update.
I removed the naming of nodeNames in the readme.
