### ISSUE TITLE
[feature request]Cloneset under the update strategy of recreate join reserved IP inherited features

### ISSUE THREAD

**Issue by peacocktrain** [openkruise/kruise#330]
**What would you like to be added**:
In cloneset recreate updated, updated pod can inherit old pod IP. 

**Why is this needed**:
Pod wants to keep ip

**Comment by FillZpp** [comment]
@peacocktrain Kruise has no way to keep pod IP inherited during recreate update, since IP is allocated by your cni plugin.

**Comment by peacocktrain** [comment]
> @peacocktrain Kruise has no way to keep pod IP inherited during recreate update, since IP is allocated by your cni plugin.

@FillZpp When cloneset updating, the delete POD'S IP can be recorded, and write to the new POD's annotation . IP allocation is indeed implemented by CNI, but it also needs to be allocated.
