### ISSUE TITLE
[BUG] failed installation

### ISSUE THREAD

**Issue by kenoshi** [openkruise/kruise#331]
**What happened**:

Kruise-manager keeps crashing with

I0811 23:04:49.494039       1 :0] kubebuilder/webhook "level"=0 "msg"="starting the webhook server."
E0811 23:04:49.494207       1 :0] kubebuilder/webhook "msg"="server returns an unexpected error" "error"="open /tmp/cert/cert.pem: no such file or directory"
E0811 23:04:49.494247       1 main.go:124] entrypoint "msg"="unable to run the manager" "error"="open /tmp/cert/cert.pem: no such file or directory"

**What you expected to happen**:

For it not to crash

**How to reproduce it (as minimally and precisely as possible)**:

Launched it through spinnaker, and watch it crash

**Anything else we need to know?**:

Note that spinnaker uses v2 renderer, I'm hoping this v3 chart won't be affected

**Environment**:
- Kruise version: 0.5.0
- Kubernetes version (use `kubectl version`): latest
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by FillZpp** [comment]
@kenoshi I'm not familiar with spinnaker, so you did not install Kruise with helm?

**Comment by FillZpp** [comment]
Issues go stale after 90d of inactivity.
