### ISSUE TITLE
[feature request] configMap should support partition update

### ISSUE THREAD

**Issue by lichaojacobs** [openkruise/kruise#332]
**What would you like to be added**:

configMap which mounted in pod should support partition upgrade when rolling update statefulset. 

**Why is this needed**:

when we use k8s configMap to separate config from docker image. we sometimes need upgrade config only instead of image. In this case, we also need partition update pod config just like docker image.

**Comment by Fei-Guo** [comment]
I am trying to understand the problem. If the configMap name is changed with the new version, the partition based upgrade should just work as usual.  Are you talking about a case where configmap name is not changed but the data values are changed during update?

**Comment by lichaojacobs** [comment]
Yes, or is there a way that statefulset can support muti-version configMap partition based upgrade？Sometimes we need to define a pod in place upgrade using special configMap

> I am trying to understand the problem. If the configMap name is changed with the new version, the partition based upgrade should just work as usual. Are you talking about a case where configmap name is not changed but the data values are changed during update?

**Comment by Fei-Guo** [comment]
It seems that the simplest way is to create a new configmap and change configmap name in the Pod template for the new version. Of course, the Pod will be created to use the new version. Directly changing cfgMap content has a few issues, for example, kubelet automatically refreshes the mounted cfgMap for all the Pods that use it. This makes the cfgMap take effect in a partition manner even harder.

**Comment by lichaojacobs** [comment]
Thanks for advice.  we just want configMap partition based upgrade instead of recreating pod for it is too heavy to recreate pod if only config changed.

**Comment by lichaojacobs** [comment]
we finally decide to use sidecar in kruise to achieve our goal
