### ISSUE TITLE
[BUG] Failed to create kruise-controller-manager-0

### ISSUE THREAD

**Issue by jiyeyuran** [openkruise/kruise#338]
**What happened**:
Failed to create pod. show error message: can't find volume "cert" to mount into container "manager"
**What you expected to happen**:
Pod successfully created.
**How to reproduce it (as minimally and precisely as possible)**:
Deploy kruise on aliyun ask.
**Anything else we need to know?**:
No
**Environment**:
- Kruise version: 0.5
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by FillZpp** [comment]
@jiyeyuran How did you install kruise? Can you find this secret `kubectl get secret -n kruise-system kruise-webhook-server-secret`

**Comment by jiyeyuran** [comment]
Install following doc instruction.
```
helm install kruise https://github.com/openkruise/kruise/releases/download/v0.5.0/kruise-chart.tgz --set manager.custom_resource_enable="CloneSet\,SidecarSet"
```
```
kubectl get secret -n kruise-system kruise-webhook-server-secret
```
got empty and no cert information. 

The latest version 0.6.0 works.

**Comment by FillZpp** [comment]
@jiyeyuran OK, enjoy 0.6.0
