### ISSUE TITLE
[Question]  About the `pause` feature in CloneSet rollout

### ISSUE THREAD

**Issue by hantmac** [openkruise/kruise#348]
![image](https://user-images.githubusercontent.com/7600925/91154946-be757980-e6f4-11ea-996e-c810e50588a1.png)

`不过控制器还是会做 replicas 数量管理`  没有太理解这句话。意思是如果暂停后继续发布的话，控制器依然以暂停前的 replicas 为准吗？

**Comment by FillZpp** [comment]
@hantmac 不是。paused 语义是控制器暂时不会对存量 Pod 做升级，但是你调整 replicas 数量控制器还是会做扩缩容的。

**Comment by hantmac** [comment]
> @hantmac 不是。paused 语义是控制器暂时不会对存量 Pod 做升级，但是你调整 replicas 数量控制器还是会做扩缩容的。

那 paused 后再执行扩容，扩容出来的版本是新版本 or 旧版本？如果是新版本，那旧版本怎么办？旧版本什么时候消失（是 paused=false的时候吗？）感觉这里有点不好理解🤔，像是操作之间没有做原子化。

**Comment by dylandee** [comment]
> > @hantmac 不是。paused 语义是控制器暂时不会对存量 Pod 做升级，但是你调整 replicas 数量控制器还是会做扩缩容的。
> 
> 那 paused 后再执行扩容，扩容出来的版本是新版本 or 旧版本？如果是新版本，那旧版本怎么办？旧版本什么时候消失（是 paused=false 的时候吗？）感觉这里有点不好理解🤔，像是操作之间没有做原子化。

从源码上看：
scale down的时候，delete的是旧版本
scale up的时候，create的是新版本

`func (c *commonControl) NewVersionedPods(currentCS, updateCS *appsv1alpha1.CloneSet,
	currentRevision, updateRevision string,
	expectedCreations, expectedCurrentCreations int,
	availableIDs []string,
) ([]*v1.Pod, error) {
	var newPods []*v1.Pod
	if expectedCreations <= expectedCurrentCreations {
		newPods = c.newVersionedPods(currentCS, currentRevision, expectedCreations, &availableIDs)
	} else {
		newPods = c.newVersionedPods(currentCS, currentRevision, expectedCurrentCreations, &availableIDs)
		newPods = append(newPods, c.newVersionedPods(updateCS, updateRevision, expectedCreations-expectedCurrentCreations, &availableIDs)...)
	}
	return newPods, nil
}`

**Comment by hantmac** [comment]
@dylandee Thanks, 理解了。不过我觉得 paused 的时候应该禁止 scale up/down 比较好。paused 的时候要么继续完成新版本发布，要么回退到旧版本，一点拙见。

**Comment by leeweir** [comment]
> @dylandee Thanks, 理解了。不过我觉得 paused 的时候应该禁止 scale up/down 比较好。paused 的时候要么继续完成新版本发布，要么回退到旧版本，一点拙见。

感觉这个你要做的话，可以外部系统控制，对于 发布（更新镜像） 和 扩缩 ，本质上就是两个行为。
