### ISSUE TITLE
[feature request] UnitedDeployment supports CloneSet

### ISSUE THREAD

**Issue by likeyao** [openkruise/kruise#355]
**What would you like to be added**:
UnitedDeployment supports CloneSet

**Why is this needed**:
运行环境是阿里云ACK集群，接入了ECI。目前通过UnitedDeployment+Advanced StatefulSet让POD按比例分配在ECS/ECI上。新需求需要在已有功能之上实现“指定容器缩容”，所以希望能UnitedDeployment能够支持CloneSet。

**Comment by Fei-Guo** [comment]
This is in our roadmap. Since you ask for it now, we will bump the priority. This feature will be included in our next release.

**Comment by Fei-Guo** [comment]
By the way, please try to file PR using english so that more people can understand the ask. Thanks!

**Comment by FillZpp** [comment]
It has been implemented in #378 .
