### ISSUE TITLE
Cannot run kruise locally with remote cluster

### ISSUE THREAD

**Issue by wgitg** [openkruise/kruise#358]
Experimenting with the kruise, so I followed the instruction [here](https://github.com/openkruise/kruise/blob/master/docs/debug/README.md)

When I set the kubeconfig with local deployed cluster such as kind, I can start the controller manager.

**What failed**
When I set the kubeconfig with  remote cluster, I encountered the following error:

```
E0830 12:02:40.084509  169201 main.go:121] setup "msg"="unable to initialize webhook" "error"="failed to ensure configuration: not found MutatingWebhookConfiguration kruise-mutating-webhook-configuration"  
exit status 1
```
**What I want**
As the instruction says, if I set kubeconfig and webhook host to local IP, the controller should be able to start controller with remote cluster as well. Referring to kruise documentation:
```
by allowing to start webbook server in local host directly. With this fix, one can start/debug kruise-manager process locally which connects to a local or remote Kubernetes cluster.
```

**Comment by hantmac** [comment]
What is your k8s version?
And you need to add params in each Kube-Apiserver instance  --admission-controll validatingAdmissionWebhook 
  MutatingAdmissionwebhook.

**Comment by wgitg** [comment]
Yes, we are running on Kubernetes 1.18, and the instances up already set up with the admission hook.
Right now I am starting to investigate on if the CA bundle is correctly set for the remote cluster...

**Comment by wgitg** [comment]
The other debugging route is: Anybody knows where is the `kruise-mutating-webhook-configuration` registered at the first place, before it is get queried [here](https://github.com/openkruise/kruise/blob/master/pkg/webhook/util/configuration/configuration.go#L40)
Right now the client just complains 

```
get mutatingwebhookconfigurations.admissionregistration.k8s.io "kruise-mutating-webhook-configuration" not found

```

**Comment by wgitg** [comment]
Closing the issue since somehow sorted out. basically I did the following things if anybody has the problem again:
1. delete everything previously installed in the remote cluster via helm
2. change to use the workstation machine and set the webhook host to the IP.
3. uninstalled minikube and kind previously used for local testing.
