### ISSUE TITLE
默认创建的sidecarset只支持注入default namespace下的，如何配置支持其他namespace

### ISSUE THREAD

**Issue by chestarss** [openkruise/kruise#364]

**Comment by Fei-Guo** [comment]
SidecarSet is cluster scoped crd. It mutates Pods in all namespaces besides kube-system and kube-public.

Check this for details
https://github.com/openkruise/kruise/blob/1bc2c39a5633b05d5492d4431ec8dd5bd89259c0/pkg/webhook/pod/mutating/pod_create_handler.go#L60
