### ISSUE TITLE
[BUG]官方文档例子没有注入容器

### ISSUE THREAD

**Issue by sunnoy** [openkruise/kruise#368]
**Environment**:
- Kruise version: 0.6.0 
- Kubernetes version (use `kubectl version`): 1.18.3

https://openkruise.io/en-us/docs/sidecarset.html 这个文档跟着走没有注入容器

**Comment by sunnoy** [comment]
kruise-system ns不监听么

**Comment by FillZpp** [comment]
@sunnoy Yes, SidecarSet injection will ignore namespaces with `control-plane: controller-manager` label to avoid circular dependency, including `kruise-system`.

**Comment by sunnoy** [comment]
ok
