### ISSUE TITLE
no kind "CloneSet" is registered for version "apps.kruise.io/v1alpha1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"

### ISSUE THREAD

**Issue by wgitg** [openkruise/kruise#370]
I used `CloneSet` to deploy my service. However, when I try to get rollout status or history, I will get the following error message

```
no kind "CloneSet" is registered for version "apps.kruise.io/v1alpha1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"
```

I am expecting the roll out history will be the same feature as for Deployment?

**Comment by Fei-Guo** [comment]
Are you using Kubectl?  Kubectl cannot support CRD without code changes.

**Comment by wgitg** [comment]
Thanks for the reply. Yes. I am using `kubectl`. 

So how can we view deployment history using `Cloneset`?

If needed to implement on our own, any idea where to do it? Only in kubectl?

**Comment by Fei-Guo** [comment]
cloneset controller essentially create controllerrevisions API objects.
Try `k get controllerrevisions -n kruise-system`

**Comment by wgitg** [comment]
Th
