### ISSUE TITLE
[BUG]sidecar pod webhook SidecarIgnoredNamespaces not work

### ISSUE THREAD

**Issue by huzhengchuan** [openkruise/kruise#372]
**What happened**:
use the sidecar controller of openkruise with k8s 1.18.5, pod webhook ignore kube-system namespaces pod inject, but not work.  

https://github.com/openkruise/kruise/blob/1bc2c39a5633b05d5492d4431ec8dd5bd89259c0/pkg/webhook/pod/mutating/pod_create_handler.go#L171

	will decode pod, but found the debug log print like this, cannot get pod.name and pod.namespace.
I0913 19:40:44.685659   60487 pod_create_handler.go:78] [sidecar inject] begin to process /

pod can get labels and annotations work well.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
deploy openkruise in k8s 1.18.5, and recreate pod, check the log.

**Anything else we need to know?**:

bug log 
<pre>
I0913 19:40:44.682307   60487 sidecarset_controller.go:110] begin to process sidecarset log-sidecar
I0913 19:40:44.685659   60487 pod_create_handler.go:78] [sidecar inject] begin to process /
I0913 19:40:44.685762   60487 pod_create_handler.go:118] [sidecar inject] before mutating: {"kind":"Pod","apiVersion":"v1","metadata":{"generateName":"app-deploy-6b88bb98bd-","creationTimestamp":null,"labels":{"app-type":"long-term","pod-template-hash":"6b88bb98bd"},"ownerReferences":[{"apiVersion":"apps/v1","kind":"ReplicaSet","name":"app-deploy-6b88bb98bd","uid":"33d884bc-72cc-43f4-9004-9b07e5b189ac","controller":true,"blockOwnerDeletion":true}]},"spec":{"volumes":[{"name":"log-volume","emptyDir":{}},{"name":"default-token-dl4c7","secret":{"secretName":"default-token-dl4c7"}}],"containers":[{"name":"app-deploy","image":"nginx:latest","command":["sleep","3600011111111111111111"],"resources":{},"volumeMounts":[{"name":"log-volume","mountPath":"/app/logs"},{"name":"default-token-dl4c7","readOnly":true,"mountPath":"/var/run/secrets/kubernetes.io/serviceaccount"}],"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","serviceAccountName":"default","serviceAccount":"default","hostNetwork":true,"securityContext":{},"schedulerName":"default-scheduler","tolerations":[{"key":"node.kubernetes.io/not-ready","operator":"Exists","effect":"NoExecute","tolerationSeconds":300},{"key":"node.kubernetes.io/unreachable","operator":"Exists","effect":"NoExecute","tolerationSeconds":300}],"priority":0,"enableServiceLinks":true},"status":{}}
I0913 19:40:44.685814   60487 pod_create_handler.go:141] [sidecar inject] after mutating: {"kind":"Pod","apiVersion":"v1","metadata":{"generateName":"app-deploy-6b88bb98bd-","creationTimestamp":null,"labels":{"app-type":"long-term","pod-template-hash":"6b88bb98bd"},"annotations":{"kruise.io/sidecarset-hash":"{\"log-sidecar\":\"442df92z2xf622288vd56xf4782cc49756c42557bbdcz5z452cw8b896xcf4564\"}","kruise.io/sidecarset-hash-without-image":"{\"log-sidecar\":\"84xc477ff54wvdxb457b48f578x4f82cvzffdb677548z22728fwc974b7v4546c\"}"},"ownerReferences":[{"apiVersion":"apps/v1","kind":"ReplicaSet","name":"app-deploy-6b88bb98bd","uid":"33d884bc-72cc-43f4-9004-9b07e5b189ac","controller":true,"blockOwnerDeletion":true}]},"spec":{"volumes":[{"name":"log-volume","emptyDir":{}},{"name":"default-token-dl4c7","secret":{"secretName":"default-token-dl4c7"}}],"containers":[{"name":"app-deploy","image":"nginx:latest","command":["sleep","3600011111111111111111"],"resources":{},"volumeMounts":[{"name":"log-volume","mountPath":"/app/logs"},{"name":"default-token-dl4c7","readOnly":true,"mountPath":"/var/run/secrets/kubernetes.io/serviceaccount"}],"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"},{"name":"log-collector","image":"nginx:latest","command":["sleep","000000000000000000"],"env":[{"name":"IS_INJECTED","value":"true"}],"resources":{},"volumeMounts":[{"name":"log-volume","mountPath":"/log"}],"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","serviceAccountName":"default","serviceAccount":"default","hostNetwork":true,"securityContext":{},"schedulerName":"default-scheduler","tolerations":[{"key":"node.kubernetes.io/not-ready","operator":"Exists","effect":"NoExecute","tolerationSeconds":300},{"key":"node.kubernetes.io/unreachable","operator":"Exists","effect":"NoExecute","tolerationSeconds":300}],"priority":0,"enableServiceLinks":true},"status":{}}
</pre>

**Environment**:
- Kruise version: master
- Kubernetes version (use `kubectl version`): k8s1.18.5
- OS (e.g: `cat /etc/os-release`): centos7
- Kernel (e.g. `uname -a`): 4.18
- Install tools: deploy bin 
- Others:

**Comment by furykerry** [comment]
According to "after mutating" log entry, the sidecar container is injected as expected since pod is not within namespace kube-system or kube-public. The log entry of "begin to process" do have some problem since the pod use generated name.

**Comment by huzhengchuan** [comment]
<pre>
func (h *PodCreateHandler) sidecarsetMutatingPod(ctx context.Context, pod *corev1.Pod) error {
	for _, namespace := range SidecarIgnoredNamespaces {
		if pod.Namespace == namespace {
			return nil
		}
	}

	klog.V(3).Infof("[sidecar inject] begin to process %s/%s", pod.Namespace, pod.Name)

	sidecarSets := &appsv1alpha1.SidecarSetList{}
	if err := h.Client.List(ctx, sidecarSets); err != nil {
		return err
	}
</pre>

in sidecarsetMutatingPod func, it use pod.Namespace, but the pod.Namespace is "", ignore SidecarIgnoredNamespaces can't work.

**Comment by Fei-Guo** [comment]
@huzhengchuan Is this a 1.18 specific problem? Most of our tests are done in 1.16.  Have you verified if 1.16 works in your environment? This can help us narrow down the problem.

**Comment by huzhengchuan** [comment]
set  namespaceSelector in ValidatingWebhookConfiguration  to ignore namespace.
