### ISSUE TITLE
[BUG] MutatingWebhookConfiguration gets resets after re-applying helm chart

### ISSUE THREAD

**Issue by shamil** [openkruise/kruise#374]
**What happened**:

As far as I understand (by reading the code), once helm release deployed, it creates `MutatingWebhookConfiguration` configuration which automatically converted to `template` (in annotations) by the `kruise-controller-manager`. Which means the original `MutatingWebhookConfiguration` created by helm chart is no longer present.

If I run `helm upgrade`, the `MutatingWebhookConfiguration` gets reset to what is in the chart and the `MutatingWebhookConfiguration` is no longer valid, which breaks `kruise-controller-manager`. If I restart the `kruise-controller-manager` pod(s) it will re-create the `template` again and everything back to normal. Until I run `helm upgrade` again.

**What you expected to happen**:

I expect that after initial `helm install` I can successfully run `helm upgrade` without breaking `kruise` operation.

**How to reproduce it (as minimally and precisely as possible)**:

1. Run `helm install` as documented
2. Run `helm upgrade`, this will re-generate `MutatingWebhookConfiguration` 

**Possible solution**:

Use config map as template and do not base on `MutatingWebhookConfiguration` configuration to convert it to template.

**Environment**:

- Kruise version: `0.6`
- Kubernetes version: `1.16`
- OS (e.g: `cat /etc/os-release`): `Ubuntu 18.04`
- Install tools: `kops` and `helm3`

**Comment by shamil** [comment]
@FillZpp any input? do you need any more information about this issue?

**Comment by FillZpp** [comment]
@shamil Sorry for replying late. I understand your situation, but can you describe why you should run `helm upgrade` for the same chart?

In our design, if `helm upgrade` a new chart, the whole `MutatingWebhookConfiguration` will be reset. And when the new `kruise-controller-manager` starts, it will update the `MutatingWebhookConfiguration` again.

Also, we can not define the  `MutatingWebhookConfiguration` as a ConfigMap in chart. Because we need `helm uninstall` to delete all resources related to Kruise, including the `MutatingWebhookConfiguration`.

**Comment by shamil** [comment]
Hi @FillZpp 

I will want to run `helm upgrade` when I change the values, for example once  I decided that I want or enable or disable specific controllers using `manager.custom_resource_enable` value.

The design you have in place can lead to problem which will cause kruise to stop working and potentially also affect all other operations in the cluster, since `MutatingWebhookConfiguration` has some client configurations for all `apiGroups` .

I don't see why you can't put it as part of `ConfigMap`, if you mean that all webhook configurations will remain after `helm uninstall`, then this is easily fixable and usually recommended way by Kubernetes. Use garbage collection feature ([ownerReference](https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/)) when you create webhook configuration resources. This is what most controllers/operators doing.

**Comment by shamil** [comment]
@FillZpp not sure why this was closed, bu the problem still exists even after upgrading to 0.6.1

**Comment by FillZpp** [comment]
> @FillZpp not sure why this was closed, but the problem still exists even after upgrading to 0.6.1

v0.6.1 does not supported this feature, #387 will be released in v0.7.0 soon.
