### ISSUE TITLE
[BUG]kubectl edit/apply changes on sidecarset isn't updating the injected containers in deployment

### ISSUE THREAD

**Issue by wgitg** [openkruise/kruise#375]
I see the sidecarset containers are appended to the pod container lists in creation time. However, I am trying to figure out how come the sidecar container image field is changed is not causing the deployment to recreate. After all, the containers injected into the deployment pod is just another container for the deployment pod. So according to the official doc that Deployment pod will be updated when any fields in .spec.template.* changed. 
So I did the following experiment: 
However,

**What happened**:
I only see the containers are injected when the deployment is created. 
I updated the version in the sidecarset container using kubectl edit/apply, however, 
1. I do not see the pod updated.
2. I do not see only the sidecar container in the deployment pod gets killed and restarted.
3. I do not see pod describe shows the updated sidecar container version changed.

for example, one of the pod, no update on the sidecar1. where I changed the centos:6.7 from centos:latest
```
 sidecar1:
    Container ID:  docker://b213fcfe0ac1431a5e1ddef58c61b732624e25c3407737c1de3840d3dd0c0f6a
    Image:         centos:latest
...
  Normal  Pulled     25m   kubelet, minikube  Container image "nginx:latest" already present on machine
  Normal  Created    25m   kubelet, minikube  Created container nginx
  Normal  Started    25m   kubelet, minikube  Started container nginx
  Normal  Pulling    25m   kubelet, minikube  Pulling image "centos:latest"
  Normal  Pulled     25m   kubelet, minikube  Successfully pulled image "centos:latest"
  Normal  Created    25m   kubelet, minikube  Created container sidecar1
  Normal  Started    25m   kubelet, minikube  Started container sidecar1
```
```
$ kubectl get sidecarset test-sidecarset -o yaml | grep -A4 status
status:
  matchedPods: 3
  observedGeneration: 5
  readyPods: 3
  updatedPods: 0
```
**What you expected to happen**:

only the injected sidecar container gets killed and restarted. other containers in the pod are intact. the pod is the same pod. and I expect the pod describe should show the changes of the sidecar container version update. I also expect the status would show that updated pods to be 3.

I also expect some insights around how the image version updated in the sidecar is not causing the deployment pod to be recreated?

**How to reproduce it (as minimally and precisely as possible)**:
install the minikube, and installed the openkruise, and use the sidecarset example in the openkruise.io and  then create a deployment object with the matching label. then use kubectl edit/apply change the version
**Anything else we need to know?**:

**Environment**:
- Kruise version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by FillZpp** [comment]
@wgitg It might be caused by the changing of `imagePullPolicy`, which has different default value between latest and no-latest images.

Could you retest it using images without `latest`, such as update the sidecar from `centos:6.7` to `centos:6.8`?

**Comment by takakawa** [comment]
Same Problem:

- Kubernetes version: v1.19.3

- kruise-0.6.0

- 5.9.7-1.el7.elrepo.x86_64

- centos7
