### ISSUE TITLE
support sidecar  sequential start

### ISSUE THREAD

**Issue by PualrDwade** [openkruise/kruise#389]
**What would you like to be added**:

sidecarSet workload should support user-defined startup sequence

**Why is this needed**:

sometimes we should ensure that certain agent containers start before business containers, then we need defined the startup sequence

**Comment by Fei-Guo** [comment]
FYI, for normal containers, the start up order is random.

Quoted from Tim Hockin: 
"In short, no. We have 2 stages for now - init and "normal". The issues around sequencing get really hard in the face of restarts and crashes." 

If you want to ensure the order, you have to do it in the application layer.

**Comment by PualrDwade** [comment]
close
