### ISSUE TITLE
[BUG] In kubelet log: Kubelet is trying to update pod condition "InPlaceUpdateReady" for pod xxx. But it is not owned by kubelet.

### ISSUE THREAD

**Issue by sourcedelica** [openkruise/kruise#392]
**What happened**:
In syslog, I noticed these messages for all of the pods in the demo Guestbook cloneset.
```
Oct  8 00:29:58 nuc-linux2 k3s[5530]: E1008 00:29:58.843304    5530 status_manager.go:194] Kubelet is trying to update pod condition "InPlaceUpdateReady" for pod "redis-master-zqmf9_default(0871175e-e0ef-419a-984b-5b606e06dd4b)". But it is not owned by kubelet.
Oct  8 00:29:58 nuc-linux2 k3s[5530]: E1008 00:29:58.843895    5530 status_manager.go:194] Kubelet is trying to update pod condition "InPlaceUpdateReady" for pod "guestbook-clone-89kt2_default(0abf5b48-ce38-4f44-a842-68ff9e85014e)". But it is not owned by kubelet.
```

**How to reproduce it (as minimally and precisely as possible)**:
Install guestbook demo using instructions at https://github.com/openkruise/kruise/blob/master/docs/tutorial/cloneset.md

**Environment**:
- Kruise version: openkruise/kruise-manager:v0.6.0
- Kubernetes version (use `kubectl version`):
```
Running k3s v1.18.6+k3s1
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:47:40Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6+k3s1", GitCommit:"6f56fa1d68a5a48b8b6fdefa8eb7ead2015a4b3a", GitTreeState:"clean", BuildDate:"2020-07-16T20:46:15Z", GoVersion:"go1.13.11", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
- Kernel (e.g. `uname -a`):
```
Linux nuc-linux1 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by FillZpp** [comment]
@sourcedelica This is just a useless warning printed by Kubelet, you can ignore it.

The earlier k8s did not support customize conditions, so Kubelet added this log. But for k8s >= 1.12, it supports Pod readinessGates which allows users to add customize conditions, but the warning log has not removed yet.

**Comment by sourcedelica** [comment]
The problem is that it logs once a minute.  It sounds like you are saying this is a bug in the Kubelet and I should log the bug there?  I checked https://github.com/kubernetes/kubernetes/issues and there are no issues matching this one which is a surprise.
