### ISSUE TITLE
[BUG] Dockerfile should pin specific ubuntu version

### ISSUE THREAD

**Issue by lowkeyliesmyth** [openkruise/kruise#406]
**What happened**: 

Get released kruise-manager image: `docker pull openkruise/kruise-manager:v0.6.1`
Check underlying OS release:
```
docker run --rm  --entrypoint "/bin/cat"  openkruise/kruise-manager:v0.6.1 /etc/os-release
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**What you expected to happen**: 
Latest ubuntu LTS release 20.04 would be used since the Dockerfile references `FROM ubuntu:latest`. Instead, version 18.04.4 is used.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kruise version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by FillZpp** [comment]
@lowkeyliesmyth emm... this might be caused by the cached image on my vm. I used `--no-cache` option for `docker build` each time, but it seems no effect on the base image.
