### ISSUE TITLE
[feature request] Provide a way to filter Pods running the Canary version when using partition in CloneSet

### ISSUE THREAD

**Issue by maxking** [openkruise/kruise#413]
**What would you like to be added**:
Partition feature in CloneSet is really useful to run Canary versions of the applications. However, there is no easy way to filter the Pods that have been updated to the Canary version and the ones running the "old versions" so that we can run tests and analyses against the Canary version. 

While if you really want to do it, you could get the current `Update Revision` from the Status of the CloneSet resource and use that to filter the Pods with `controller-revision-hash`, but that hash keeps changing. 

Would it be possible to extend CloneSet to allow users to provide label(s) to Pods running the Canary version(s)? Once the partition is set to 0 (there are no canary versions), the labels would be removed from all the Pods. 

**Why is this needed**:
We would like the ability establish a convention for labeling Pods that are Canary so administrators can differentiate between the stable and canary ones and be able to filter them to run tests or route test traffic at them.

**Comment by 27149chen** [comment]
+1 for this feature
It is really helpful if an app in pod is  aware of it (in a canary stage / is a new pod during uprgade), so that we can use different policy to run this app, for example, do not accept traffic by default
