### ISSUE TITLE
[BUG] Internal error occurred: failed calling webhook  mcloneset.kb.io

### ISSUE THREAD

**Issue by hantmac** [openkruise/kruise#453]
**What happened**:

When create or update cloneSet I got the error 
'error="Internal error occurred: failed calling webhook \"mcloneset.kb.io\": Post https://kruise-webhook-service.kruise-system.svc:443/mutate-apps-kruise-io-v1alpha1-cloneset?timeout=30s: x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"webhook-cert-ca\")"'
**What you expected to happen**:
No such error
**How to reproduce it (as minimally and precisely as possible)**:
When creating or updating cloneSet, this error will happen sporadically.

**Anything else we need to know?**:

**Environment**:
- Kruise version:

v0.6.1

- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T23:49:07Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.9-aliyun.1", GitCommit:"4f7ea78", GitTreeState:"", BuildDate:"2020-05-08T07:29:59Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g: `cat /etc/os-release`):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`):
3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by alandtsang** [comment]
I am stuck with the same problem

**Comment by FillZpp** [comment]
@hantmac @alandtsang Can you describe how to reproduce it? Install kruise in a new Kubernetes cluster, or upgrade kruise from a historic version?

**Comment by 27149chen** [comment]
@FillZpp I'm the colleague of @hantmac who encountered this issue.
In fact, I don't know how to reproduce it, because it is not 100% reproducible. I just met this issue twice, one create and one patch.
If you want to dig into it, I can provide the logs or other info.

**Comment by alandtsang** [comment]
@FillZpp Thanks for the reply, it cannot be reproduced stably. When yaml is deployed multiple times, the content of caBundle in ValidatingWebhookConfiguration will sometimes be empty.

**Comment by FillZpp** [comment]
> @FillZpp Thanks for the reply, it cannot be reproduced stably. When yaml is deployed multiple times, the content of caBundle in ValidatingWebhookConfiguration will sometimes be empty.

This reminds me... Do you have some components that will deploy the kruise chart repeatedly? @alandtsang @27149chen 
This will lead to the `MutatingWebhookConfiguration/ValidatingWebhookConfiguration` to be reset and kruise-manager will add the real caBundle into them again.

**Comment by LeoWenxiang** [comment]
you can reproduced it as follow: 
(1)  helm template kruise https://github.com/openkruise/kruise/releases/download/v0.6.1/kruise-chart.tgz > kruise.yaml
(2) kubectl apply -f kruise.yaml
(3) kubectl apply -f kruise.yaml
(4) kubectl get  mutatingwebhookconfigurations kruise-mutating-webhook-configuration -oyaml |grep caBun
      {"apiVersion":"admissionregistration.k8s.io/v1beta1","kind":"MutatingWebhookConfiguration","metadata":{"annotations":{"template":""},"creationTimestamp":null,"name":"kruise-mutating-webhook-configuration"},"webhooks":[{"clientConfig":{"caBundle":"Cg==","service":{"name":"kruise-webhook-service","namespace":"kruise-system","path":"/mutate-apps-kruise-io-v1alpha1-sidecarset"}},"failurePolicy":"Fail","name":"msidecarset.kb.io","rules":[{"apiGroups":["apps.kruise.io"],"apiVersions":["v1alpha1"],"operations":["CREATE","UPDATE"],"resources":["sidecarsets"]}]},{"clientConfig":{"caBundle":"Cg==","service":{"name":"kruise-webhook-service","namespace":"kruise-system","path":"/mutate-pod"}},"failurePolicy":"Ignore","name":"mpod.kb.io","namespaceSelector":{"matchExpressions":[{"key":"control-plane","operator":"DoesNotExist"}]},"rules":[{"apiGroups":[""],"apiVersions":["v1"],"operations":["CREATE"],"resources":["pods"]}]},{"clientConfig":{"caBundle":"Cg==","service":{"name":"kruise-webhook-service","namespace":"kruise-system","path":"/mutate-apps-kruise-io-v1alpha1-broadcastjob"}},"failurePolicy":"Fail","name":"mbroadcastjob.kb.io","rules":[{"apiGroups":["apps.kruise.io"],"apiVersions":["v1alpha1"],"operations":["CREATE","UPDATE"],"resources":["broadcastjobs"]}]},{"clientConfig":{"caBundle":"Cg==","service":{"name":"kruise-webhook-service","namespace":"kruise-system","path":"/mutate-apps-kruise-io-v1alpha1-cloneset"}},"failurePolicy":"Fail","name":"mcloneset.kb.io","rules":[{"apiGroups":["apps.kruise.io"],"apiVersions":["v1alpha1"],"operations":["CREATE","UPDATE"],"resources":["clonesets"]}]},{"clientConfig":{"caBundle":"Cg==","service":{"name":"kruise-webhook-service","namespace":"kruise-system","path":"/mutate-apps-kruise-io-v1alpha1-daemonset"}},"failurePolicy":"Fail","name":"mdaemonset.kb.io","rules":[{"apiGroups":["apps.kruise.io"],"apiVersions":["v1alpha1"],"operations":["CREATE","UPDATE"],"resources":["daemonsets"]}]},{"clientConfig":{"caBundle":"Cg==","service":{"name":"kruise-webhook-service","namespace":"kruise-system","path":"/mutate-apps-kruise-io-v1alpha1-statefulset"}},"failurePolicy":"Fail","name":"mstatefulset.kb.io","rules":[{"apiGroups":["apps.kruise.io"],"apiVersions":["v1alpha1"],"operations":["CREATE","UPDATE"],"resources":["statefulsets"]}]},{"clientConfig":{"caBundle":"Cg==","service":{"name":"kruise-webhook-service","namespace":"kruise-system","path":"/mutate-apps-kruise-io-v1alpha1-uniteddeployment"}},"failurePolicy":"Fail","name":"muniteddeployment.kb.io","rules":[{"apiGroups":["apps.kruise.io"],"apiVersions":["v1alpha1"],"operations":["CREATE","UPDATE"],"resources":["uniteddeployments"]}]}]}
            f:caBundle: {}
            f:caBundle: {}
            f:caBundle: {}
            f:caBundle: {}
            f:caBundle: {}
            f:caBundle: {}
            f:caBundle: {}
    caBundle: Cg==
    caBundle: Cg==
    caBundle: Cg==
    caBundle: Cg==
    caBundle: Cg==
    caBundle: Cg==
    caBundle: Cg==

**Comment by LeoWenxiang** [comment]
> you can reproduced it as follow:
> (1) helm template kruise https://github.com/openkruise/kruise/releases/download/v0.6.1/kruise-chart.tgz > kruise.yaml
> (2) kubectl apply -f kruise.yaml
> (3) kubectl apply -f kruise.yaml
> (4) kubectl get mutatingwebhookconfigurations kruise-mutating-webhook-configuration -oyaml |grep caBun
> {"apiVersion":"admissionregistration.k8s.io/v1beta1","kind":"MutatingWebhookConfiguration","metadata":{"annotations":{"template":""},"creationTimestamp":null,"name":"kruise-mutating-webhook-configuration"},"webhooks":[{"clientConfig":{"caBundle":"Cg==","service":{"name":"kruise-webhook-service","namespace":"kruise-system","path":"/mutate-apps-kruise-io-v1alpha1-sidecarset"}},"failurePolicy":"Fail","name":"msidecarset.kb.io","rules":[{"apiGroups":["apps.kruise.io"],"apiVersions":["v1alpha1"],"operations":["CREATE","UPDATE"],"resources":["sidecarsets"]}]},{"clientConfig":{"caBundle":"Cg==","service":{"name":"kruise-webhook-service","namespace":"kruise-system","path":"/mutate-pod"}},"failurePolicy":"Ignore","name":"mpod.kb.io","namespaceSelector":{"matchExpressions":[{"key":"control-plane","operator":"DoesNotExist"}]},"rules":[{"apiGroups":[""],"apiVersions":["v1"],"operations":["CREATE"],"resources":["pods"]}]},{"clientConfig":{"caBundle":"Cg==","service":{"name":"kruise-webhook-service","namespace":"kruise-system","path":"/mutate-apps-kruise-io-v1alpha1-broadcastjob"}},"failurePolicy":"Fail","name":"mbroadcastjob.kb.io","rules":[{"apiGroups":["apps.kruise.io"],"apiVersions":["v1alpha1"],"operations":["CREATE","UPDATE"],"resources":["broadcastjobs"]}]},{"clientConfig":{"caBundle":"Cg==","service":{"name":"kruise-webhook-service","namespace":"kruise-system","path":"/mutate-apps-kruise-io-v1alpha1-cloneset"}},"failurePolicy":"Fail","name":"mcloneset.kb.io","rules":[{"apiGroups":["apps.kruise.io"],"apiVersions":["v1alpha1"],"operations":["CREATE","UPDATE"],"resources":["clonesets"]}]},{"clientConfig":{"caBundle":"Cg==","service":{"name":"kruise-webhook-service","namespace":"kruise-system","path":"/mutate-apps-kruise-io-v1alpha1-daemonset"}},"failurePolicy":"Fail","name":"mdaemonset.kb.io","rules":[{"apiGroups":["apps.kruise.io"],"apiVersions":["v1alpha1"],"operations":["CREATE","UPDATE"],"resources":["daemonsets"]}]},{"clientConfig":{"caBundle":"Cg==","service":{"name":"kruise-webhook-service","namespace":"kruise-system","path":"/mutate-apps-kruise-io-v1alpha1-statefulset"}},"failurePolicy":"Fail","name":"mstatefulset.kb.io","rules":[{"apiGroups":["apps.kruise.io"],"apiVersions":["v1alpha1"],"operations":["CREATE","UPDATE"],"resources":["statefulsets"]}]},{"clientConfig":{"caBundle":"Cg==","service":{"name":"kruise-webhook-service","namespace":"kruise-system","path":"/mutate-apps-kruise-io-v1alpha1-uniteddeployment"}},"failurePolicy":"Fail","name":"muniteddeployment.kb.io","rules":[{"apiGroups":["apps.kruise.io"],"apiVersions":["v1alpha1"],"operations":["CREATE","UPDATE"],"resources":["uniteddeployments"]}]}]}
> f:caBundle: {}
> f:caBundle: {}
> f:caBundle: {}
> f:caBundle: {}
> f:caBundle: {}
> f:caBundle: {}
> f:caBundle: {}
> caBundle: Cg==
> caBundle: Cg==
> caBundle: Cg==
> caBundle: Cg==
> caBundle: Cg==
> caBundle: Cg==
> caBundle: Cg==

@FillZpp

**Comment by FillZpp** [comment]
@LeoWenxiang The MutatingWebhookConfiguration/ValidatingWebhookConfiguration yamls in chart do have empty caBundles, and kruise-controller-manager will add real certs into them when started.

**Comment by 27149chen** [comment]
@FillZpp , I just installed kruise once.
I met this issue several times today when trying to update a cloneSet. please guide me how to dig into it, thanks.
Also, please tell me how to get rid of it if you know.

**Comment by FillZpp** [comment]
@27149chen 

1. First, you can get the caBundle from `kubectl get mutatingwebhookconfigurations kruise-mutating-webhook-configuration` and decode it using base64 to get ca-cert.
2. Then, you can use exec to get into the two kruise-controller-manager and read `/tmp/kruise-webhook-certs/ca-cert.pem`.
3. You should check these three ca-cert should be the same.

**Comment by jiyeyuran** [comment]
I am also stuck with the same problem. `kruise-controller-manager`  is running for a quite long time.

**Comment by FillZpp** [comment]
This problem should be solved in the latest `v0.7.0`. Would you please upgrade Kruise and check it again? @jiyeyuran @27149chen @LeoWenxiang @alandtsang

**Comment by alandtsang** [comment]
Cool, we will try it.

**Comment by FillZpp** [comment]
This problem should be solved since `v0.7.0`.

**Comment by tclh123** [comment]
@FillZpp Why is this bugfix not mentioned in the CHANGELOG? If you can reference the bugfix commit to this issue, it would be helpful.

**Comment by FillZpp** [comment]
@tclh123 Sure, I can add it into CHANGELOG later, thanks.
