### ISSUE TITLE
[QUESTION] How to rollback a CloneSet

### ISSUE THREAD

**Issue by 27149chen** [openkruise/kruise#467]
I find that CloneSet use ControllerRevision like StatefulSet and DaemonSet, is there a way to easily rollback a cloneSet?
Kubernetes don't have a specific API, instead, `kubectl rollout` implements it by combining several Kubernetes APIs. But it is not extendable, so I wonder how to easily rollback a cloneSet?

**Comment by FillZpp** [comment]
@27149chen Currently `kubectl rollout` can only recognize built-in workload like Deployment. The easy way to rollback a CloneSet is to choose the historic ControllerRuntime and overwrite its data into CloneSet template, but there is no command-line tool to do this yet. Maybe it can be supported in https://github.com/openkruise/kruise-tools.

**Comment by 27149chen** [comment]
@FillZpp thanks for you reply, https://github.com/openkruise/kruise-tools is a good place to support it
