### ISSUE TITLE
A BroadcastCronjob is needed？

### ISSUE THREAD

**Issue by yehaifeng** [openkruise/kruise#47]
**What would you like to be added**:
I want to run cronjob in the kubernetes nodes for labels

**Why is this needed**:
I think this is useful. For example, synchronous time, check file.

**Comment by FillZpp** [comment]
Exactly. Maybe we should add a `selector` into `BroadcastJobSpec`. @jian-he

**Comment by jian-he** [comment]
sounds good to me. 
We should think about whether adding another CRD BroadcastCronjob, or just add a cron field into the BroadcastJob spec,

**Comment by jian-he** [comment]
> Exactly. Maybe we should add a `selector` into `BroadcastJobSpec`. @jian-he
Do you mean node selector ?

**Comment by FillZpp** [comment]
@jian-he Yes, sometimes users just want to run jobs on part of nodes.

**Comment by yehaifeng** [comment]
> @jian-he Yes, sometimes users just want to run jobs on part of nodes.

Yes, maybe it is need.

**Comment by yehaifeng** [comment]
I think if BroadcastCronjob can replace the cronjob in os

**Comment by jian-he** [comment]
> @jian-he Yes, sometimes users just want to run jobs on part of nodes.

actually, the podTemplate already has a `nodeSelector` field , which currently is supported by BroadcastJob.  So user can specify the nodes with the `nodeSelector` @FillZpp @yehaifeng

**Comment by xiang90** [comment]
> actually, the podTemplate already has a nodeSelector field , which currently is supported by BroadcastJob. So user can specify the nodes with the nodeSelector

let us convert this to a doc issue. we should provide an example.

**Comment by jian-he** [comment]
> > actually, the podTemplate already has a nodeSelector field , which currently is supported by BroadcastJob. So user can specify the nodes with the nodeSelector
> 
> let us convert this to a doc issue. we should provide an example.

https://github.com/openkruise/kruise/pull/55 adds the doc

**Comment by rishi-anand** [comment]
Is there any way, I can run BroadcastJob as cron job @FillZpp, @jian-he , @xiang90

**Comment by yehaifeng** [comment]
> > @jian-he Yes, sometimes users just want to run jobs on part of nodes.
> 
> Yes, maybe it is need.

**Comment by rishi-anand** [comment]
@yehaifeng, @jian-he, @xiang90 
I have submitted a proposal for AdvancedCronJob which can be used for any cron type resource.
https://github.com/openkruise/kruise/blob/master/docs/proposals/20201024-advancedcronjob.md
