### ISSUE TITLE
[feature request] Distribute kruise controller binary (rhel/CentOs, etc)

### ISSUE THREAD

**Issue by wgitg** [openkruise/kruise#475]
**What would you like to be added**:
We'd like to have the kruise controller binary distribution, at least for linux arch (rhel/centOS).

**Why is this needed**:
Currently we are using the kruise controllers. However, we will need to hook up the kruise controller within our own infrastructure:
1. containerize the image and push to the internal image registry
2. hook up with our internal deployment system and infra (e.g. we are not yet using helm, and we need to control the deployment fabric to fabric and cluster by cluster, etc... )

With the binary distribution, we can just customize our own configs both in the image and for deployment internally.

**Comment by Fei-Guo** [comment]
For compatibility and security reasons, it is not suggested to distribute binary directly. 

I will close this issue for now and we would like to help with any image building request if the problem can be worked around with image.
