### ISSUE TITLE
[BUG] Failed to start kruise-manager when CR has been created before webhook injection

### ISSUE THREAD

**Issue by ntboot** [openkruise/kruise#48]
**What happened**:

Error deploying kruise-controller-manager
![image](https://user-images.githubusercontent.com/22340224/60165886-b2f99a80-9832-11e9-929f-6b18334d1947.png)

**Environment**:
- Kruise version:
![image](https://user-images.githubusercontent.com/22340224/60165860-a6754200-9832-11e9-92c5-a92864ec51a9.png)

**Comment by FillZpp** [comment]
Em...Let me guess your operations:

1. First, you applied the CRDs into your cluster.
2. Then, you created a `StatefulSet.apps.kruise.io` resource.
3. After that, you tried to install the kruise-controller-manager, and unfortunately you got an error.

Am i right?

**Comment by ntboot** [comment]
1. extend CRD 
2. then deploy kruise-manager

Reference document: https://github.com/openkruise/kruise/blob/master/docs/tutorial/kruise-install.md

**Comment by FillZpp** [comment]
@ntboot Could you show me `kubectl get statefulset.apps.kruise.io`

**Comment by ntboot** [comment]
I don't understand why kruise-controller-manager will miss restart once my guest book is installed.

![image](https://user-images.githubusercontent.com/22340224/60187156-a8a1c580-985f-11e9-9cb2-0ec3647a63d8.png)
![Uploading image.png…]()

**Comment by FillZpp** [comment]
@jian-he @resouer I think this is a bug of guestbook-kruise chart. 

We can not put both kruise-manager and `StatefulSet.apps.kruise.io` resources in chart, because the manager must be started before users create the AdvancedStatefulSet. But we can not define the order that yamls in chart which should be applied first and others shouldn't be applied util the first one has been ready.

**Comment by ntboot** [comment]
I know what you mean, you have to deploy kruise-controller-manager correctly first, and then you can't deploy the related resources of astatefulset controller correctly. But I also follow the document step by step, but still encountered the above problems.

**Comment by ntboot** [comment]
I like this project very much, and I hope that the elastic expansion behind you will open up as soon as possible. So now I want to solve this problem

**Comment by resouer** [comment]
@FillZpp If I'm understanding it correctly, you are suggesting we should very kruise-manager is running before deploy any applications?

> We can not put both kruise-manager and StatefulSet.apps.kruise.io resources in chart

 kruise-manager  is not part of guestbook-kruise charts, it's started separately by following https://github.com/openkruise/kruise/blob/master/docs/tutorial/kruise-install.md

**Comment by FillZpp** [comment]
@resouer Got it.

@ntboot  So i think the problem is, after kruise-manager installed, you went to install guestbook chart immediately, but the kruise-manager had not been ready yet.

This could be a regular problem, i have to think of how to avoid it.

**Comment by ntboot** [comment]
I guess so. I did a test waiting for kruise-manger to start for 8 minutes. Then I started an astatefuleset controller, and finally kruise-manger was restart.

**Comment by ntboot** [comment]
@FillZpp

**Comment by FillZpp** [comment]
#50 will fix this problem.

After deployed kruise into a cluster, users can not create resources defined in kruise util kurise-manager has been started.

**Comment by ntboot** [comment]
I changed a new cluster operation and succeeded! Thank you



However, the cluster that had problems before cleaned up the relevant resources, and then try again is not good. My understanding is that the order of deleting resources should be:

1. sts. apps. kruise. IO

2. kruise-manger



Am I right? @FillZpp

**Comment by FillZpp** [comment]
@ntboot Delete all `sts.apps.kruise.io` resources, then delete the pod `kubectl delete pod -n kruise-system kruise-controller-manager-0`. 
After that, the StatefulSet named `kruise-controller-manager` will create a new Pod which should be Ready.

**Comment by ntboot** [comment]
got it
