### ISSUE TITLE
[feature request] UnitedDeployment support `Blue/Green` and `Canary` update strategy type

### ISSUE THREAD

**Issue by LeoLiuYan** [openkruise/kruise#487]
**What would you like to be added**:
As the title,  when use unitedDeployment,  we want to support more strategy, like `Blue/Green` or `Canary`.  Whether the strategy is `Beta` or `Batch` or `Blue/Green`,  for unitedDeployment the logic is common.  When use `Blue/Green` or `Canary`  strategy, the traffic ratio should be not considered by this workload.

**Why is this needed**:
In some case,  users may want use `Blue/Green` or `Canary` strategy when they do one publish.

**Comment by LeoLiuYan** [comment]
For example,  there is three AZ: AZ1,AZ2,AZ3,  there also one subset in each AZ: AZ1-Subset1, AZ2-Subset1, AZ3-Subset1. 

When use `Green/Blue` strategy,  the unitedDeployment workload will create three new subset in each AZ: AZ1-Subset2, AZ2-Subset2, AZ3-Subset2.

When use `Canary` strategy, the unitedDeployment workload will update pods in the present subnet.

**Comment by Fei-Guo** [comment]
I think UD currently supports canary release by using statefulset as subset workload. For Green/Blue rollout, I think we can consider adding deployment as the subset workload (which is in our roadmap).

**Comment by LeoLiuYan** [comment]
`Blue/Green` and `Canary`  publish may be use cloneset as the subset workload.

**Comment by LeoLiuYan** [comment]
Can we start designing features that support `Blue/green` and `Canary`?

**Comment by Fei-Guo** [comment]
@FillZpp Doesn't cloneset already support blue/green (via maxsurge) and canary (via partition) release?

**Comment by LeoLiuYan** [comment]
The maxSurge strategy may not enough for blue/green release. In a blue/green release, blue and green represent different publish version,  they have different labels for traffic rules to distinguish.

**Comment by LeoLiuYan** [comment]
ping @Fei-Guo @FillZpp

**Comment by Fei-Guo** [comment]
@LeoLiuYan I don't exactly understand your quest since the blue/green, canary like behavior can be implemented in multiple ways in UnitedDeployment. Do you prefer different subsets to having different versions for blue/green? E.g., UD have two subsets : A and B. They share the same template in the beginning. During update, Subset A has version 2 but Subset B keeps version A.
