### ISSUE TITLE
[feature request] Allow sidecar to be injected to existing pods

### ISSUE THREAD

**Issue by zzxwill** [openkruise/kruise#488]
**What would you like to be added**:
Currently sidecarset won't support injection of sidecar to existing pods until the pods are recreated by the upper business workload. I would like to sidecarset expose the ability of recreating pods to business users.

```
type SidecarSetSpec struct {
	// Containers is the list of sidecar containers to be injected into the selected pod
	Containers []SidecarContainer `json:"containers,omitempty"`

        InjectionStrategy InjectionStrategy        # newly added field.
}

type InjectionStrategy struct {
       RecreatePod bool
}
```

If possible, providing RollingUpdate strategy for business Pods would be better. Thanks.

**Why is this needed**:
In this way, I can easily inject sidecar, like logging system, security component, to my business pods, or I will have to update my business workload to trigger the recreation but, in fact, I don't want to update the workload.

**Comment by furykerry** [comment]
inject containers to existing pod is not possible in official k8s, since k8s apiserver will reject any container removal or addition in existing pod. You may change k8s apiserver admission plugin code to remove this restriction

**Comment by Fei-Guo** [comment]
To me, this request is too risky. Sidecarset is a cluster scoped crd. It may affects multiple workloads belonging to multiple orgs. Any operation that may break existing business needs extra care for safety. You may get horrible result if this flag is abused.
