### ISSUE TITLE
[BUG] Observed a panic: "invalid memory address or nil pointer dereference" 

### ISSUE THREAD

**Issue by danche** [openkruise/kruise#489]
**What happened**:
E1220 03:13:23.644716       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory addr
ess or nil pointer dereference)                                                                                                                       goroutine 804 [running]:                                                                                                                              k8s.io/apimachinery/pkg/util/runtime.logPanic(0x18d75a0, 0x2bc9c00)                                                                                           /workspace/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3                                                                    k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /workspace/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82                                                                    panic(0x18d75a0, 0x2bc9c00)
        /usr/local/go/src/runtime/panic.go:969 +0x166                                                                                                 github.com/openkruise/kruise/pkg/controller/statefulset.(*defaultStatefulSetControl).truncateHistory(0xc0003bc280, 0xc002c00000, 0xc001ea6520, 0x3, 0x
4, 0xc00290a780, 0x1, 0x1, 0xc0000226b0, 0xc0000226b0, ...)                                                                                                   /workspace/pkg/controller/statefulset/stateful_set_control.go:190 +0x34a
github.com/openkruise/kruise/pkg/controller/statefulset.(*defaultStatefulSetControl).UpdateStatefulSet(0xc0003bc280, 0xc002c00000, 0xc001ea6520, 0x3, 0x4, 0x3, 0x3)                                                                                                                                                /workspace/pkg/controller/statefulset/stateful_set_control.go:142 +0x68a                                                                      github.com/openkruise/kruise/pkg/controller/statefulset.(*ReconcileStatefulSet).syncStatefulSet(0xc0003bc2d0, 0xc0001b53b0, 0xc001ea6520, 0x3, 0x4, 0x3, 0x4)                                                                                                                                                       /workspace/pkg/controller/statefulset/statefulset_controller.go:320 +0x18d                                                                    github.com/openkruise/kruise/pkg/controller/statefulset.(*ReconcileStatefulSet).Reconcile(0xc0003bc2d0, 0xc002691f80, 0x6, 0xc002695fa0, 0x20, 0xc0027c7d00, 0x0, 0x0, 0x0)                                                                                                                                         /workspace/pkg/controller/statefulset/statefulset_controller.go:252 +0x708
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00257b4a0, 0x19590c0, 0xc0026740e0, 0x0)
        /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:246 +0x161
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00257b4a0, 0xc002a32500)
        /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:222 +0xae
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc00257b4a0)
        /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:201 +0x2b                                              k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc002a19fc0)
        /workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5f
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc002a19fc0, 0x3b9aca00, 0x0, 0x1bdd801, 0xc000b925a0)
        /workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc002a19fc0, 0x3b9aca00, 0xc000b925a0)
        /workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
        /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:183 +0x426
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x172750a]

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**: 
- Kruise version: 0.7.0
- Kubernetes version (use `kubectl version`): modify base 1.16
- OS (e.g: `cat /etc/os-release`): centos7
- Kernel (e.g. `uname -a`):
- Install tools: helm3
- Others:

**Comment by danche** [comment]
more logs 
I1220 03:30:13.866141       1 stateful_set_control.go:126] StatefulSet inplace20-pd pod status replicas=3 ready=2 available
=2 current=3 updated=3
I1220 03:30:13.866154       1 stateful_set_control.go:135] StatefulSet inplace20-pd revisions current=blade-blade-dbatest4i
nplace20-pd-5458c68d85 update=blade-blade-dbatest4inplace20-pd-5458c68d85
I1220 03:30:13.866179       1 statefulset_controller.go:218] Finished syncing statefulset "inplace20-pd" (3.651028ms)
I1220 03:30:13.872388       1 http.go:84] controller-runtime/webhook/webhooks "msg"="received request" "webhook"="/validate-apps-kruise-io-statefulset" "UID"="126f8225-e710-478d-918e-ebfb4d6cf98d" "kind"={"group":"apps.kruise.io","version":"v1beta1","kind":"StatefulSet"} "resource"={"group":"apps.kr
uise.io","version":"v1beta1","resource":"statefulsets"}
I1220 03:30:13.949050       1 shared_informer.go:227] caches populated                                                                                I1220 03:30:13.949339       1 controller.go:152] controller-runtime/controller "msg"="Starting EventSource" "controller"="uniteddeployment-controller"
 "source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{"selector":null,"template":{"metadata":{"creationTimestamp":null},"spec":{"containers
":null}},"updateStrategy":{}},"status":{"replicas":0,"readyReplicas":0,"availableReplicas":0,"currentReplicas":0,"updatedReplicas":0}}}               I1220 03:30:13.949743       1 reflector.go:120] Starting reflector *v1alpha1.StatefulSet (9h7m5.668689459s) from sigs.k8s.io/controller-runtime/pkg/ca
che/internal/informers_map.go:224
I1220 03:30:13.949765       1 reflector.go:158] Listing and watching *v1alpha1.StatefulSet from sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:224
I1220 03:30:13.954580       1 shared_informer.go:227] caches populated
I1220 03:30:13.954623       1 shared_informer.go:227] caches populated
E1220 03:30:13.866274       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory addr
ess or nil pointer dereference)

**Comment by FillZpp** [comment]
Turns out this asts is created during uninstall and install Kruise, so it has no default fields like `revisionHistoryLimit` injected by webhook.
