### ISSUE TITLE
[feature request] Container Restart

### ISSUE THREAD

**Issue by takakawa** [openkruise/kruise#495]
**What would you like to be added**:
We want the ability to restart Container only, not to create the whole Pod.

**Why is this needed**:
 There is always some reason to restart the services running in Pod. In baremetals everything is easy.`systemctl restart xxxx.service` is enough.but when in k8s you need to recreate a new Pod to just restart a Container. THAT IS TOO EXPENSIVE.

**Comment by FillZpp** [comment]
It has provided in [v0.9.0 release](https://github.com/openkruise/kruise/releases/tag/v0.9.0).
