### ISSUE TITLE
[QUSESTION]

### ISSUE THREAD

**Issue by naiveboy96** [openkruise/kruise#496]
当更新UnitedDeployment的时候，会创建一个新的ControllerRevision，如果版本并未和历史版本发生冲突则会创建。但是newRevision和createControllerRevision好像创建了两次name。
![image](https://user-images.githubusercontent.com/38353946/103127061-54cda200-46cb-11eb-95fa-19e9f8913681.png)
![image](https://user-images.githubusercontent.com/38353946/103127073-62832780-46cb-11eb-880b-f2c10a89a589.png)

**Comment by Fei-Guo** [comment]
What is your question? or what the potential problem it is?

**Comment by naiveboy96** [comment]
这里创建两次name是出于什么原因呢，而且createControllerRevision里面的for循环每次都会创建name，是出于什么考虑呢

**Comment by Fei-Guo** [comment]
The loop in CreateControllerRevision is to handle a case of hash collision. i.e., if the name is used by a different revision already, we have to choose a new name. 

For the first question, the `hash` parameter in the ControllerRevisionName call seems to be different.

**Comment by naiveboy96** [comment]
谢谢，我再仔细看一下
