### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by phoenixwu0229** [openkruise/kruise#497]
how to  upgrade kruise

**Comment by FillZpp** [comment]
@phoenixwu0229 Use helm `upgrade` instead of `install`:

```
helm upgrade kruise https://github.com/openkruise/kruise/releases/download/v0.7.0/kruise-chart.tgz
```

**Comment by phoenixwu0229** [comment]
> @phoenixwu0229 Use helm `upgrade` instead of `install`:
> 
> ```
> helm upgrade kruise https://github.com/openkruise/kruise/releases/download/v0.7.0/kruise-chart.tgz
> ```

helm upgrade kruise ./kruise  in k8s 1.14, report unknown field "x-kubernetes-int-or-string" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, no --disable-openapi-validation with helm upgrade

**Comment by phoenixwu0229** [comment]
> > @phoenixwu0229 Use helm `upgrade` instead of `install`:
> > ```
> > helm upgrade kruise https://github.com/openkruise/kruise/releases/download/v0.7.0/kruise-chart.tgz
> > ```
> 
> helm upgrade kruise ./kruise in k8s 1.14, report unknown field "x-kubernetes-int-or-string" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, no --disable-openapi-validation with helm upgrade

my helm version is old, ignore it
