### ISSUE TITLE
[feature request] how to add podmanagepolicy in uniteddeploy combine with asts

### ISSUE THREAD

**Issue by phoenixwu0229** [openkruise/kruise#502]
**What would you like to be added**:
how to add podmanagepolicy in uniteddeploy combine with asts

**Why is this needed**:
not work add like blow
![image](https://user-images.githubusercontent.com/49689460/103628306-c6cea280-4f79-11eb-8e51-d44d9d4238af.png)

**Comment by FillZpp** [comment]
@phoenixwu0229 The `P` in `PodManagementPolicy` should be lower case.

```yaml
        podManagementPolicy: Parallel
```
