### ISSUE TITLE
[BUG] Excessive Permissions

### ISSUE THREAD

**Issue by kfox1111** [openkruise/kruise#507]
**What happened**:

I looked through the permissions granted in the chart and it has a large amount of permissions granted. I was trying to deploy openkruise to be able to do cronjobs with broadcast jobs and not sure why read/write all secrets in all namespaces is needed. customresourcedefinitions read/write/create/delete is also concerning. The crd's should be uploaded as part of the helm install and not changed at runtime.

I'm also concerned with the enabling / disabling of privilege flag. It shouldn't be needed. I would have expected that the serviceaccount specified in the CR's would be used for creating the subobjects so podsecuritypolicy would drive the privilege flag. Is that not true?

**Environment**:
- Kruise version:
 0.7.0

**Comment by FillZpp** [comment]
> I'm also concerned with the enabling / disabling of privilege flag. It shouldn't be needed. I would have expected that the serviceaccount specified in the CR's would be used for creating the subobjects so podsecuritypolicy would drive the privilege flag. Is that not true?

@kfox1111 The `allowPrivileged` is not used [here](https://github.com/openkruise/kruise/blob/master/main.go#L93) to allow users to create Kruise workloads like CloneSet or BroadcastJob with privileged containers ( #409 ).
