### ISSUE TITLE
[BUG] helm CRD's

### ISSUE THREAD

**Issue by kfox1111** [openkruise/kruise#508]
**What happened**:

CRD's are not disableable.

**What you expected to happen**:

The CRD's should be in the crds/ directory of the chart as per https://helm.sh/docs/chart_best_practices/custom_resource_definitions/ section: "Method 1: Let helm Do It For You"

I prefer to disable helm from ever managing a CRD because its been quite buggy in the past so I need a way to disable helm from ever touching them to prevent breakage in production

I also would need a way to fetch the crds to apply with kubectl apply -f <someurl> manually outside of the chart.

**How to reproduce it (as minimally and precisely as possible)**:

helm install / upgrade always touches the CRDS. No way to disable that.

**Anything else we need to know?**:

**Environment**:
- Kruise version: 0.7.0

**Comment by FillZpp** [comment]
> The CRD's should be in the crds/ directory of the chart

@kfox1111  I tried to put the CRDs in `crds/` directory in the original `v0.7.0` chart, but I found the CRDs will be deleted during `helm upgrade` from an old version. So I have no choice but to move them back to `template/`.

Besides, our CRDs will always be changed between different versions. Are you sure it is ok to put them in `crds/` directory during `helm upgrade`?

**Comment by kfox1111** [comment]
ouch. :(

Thats why I don't trust helm managing crd's at all. I've seen way too many bugs with it. What about wrapping the crds in the template/ directory in:
```
{{- if .Values.crds.managed }}
{{- end }}
```

That would at least allow helm to not manage them.

**Comment by FillZpp** [comment]
@kfox1111 We can do this, but I'm not really understand why do you need this and how will you manage CRDs without helm?

**Comment by kfox1111** [comment]
Manually. kubectl apply -f <crds>

**Comment by kfox1111** [comment]
Thanks! :)
