### ISSUE TITLE
[feature request] cert-manager support

### ISSUE THREAD

**Issue by kfox1111** [openkruise/kruise#509]
**What would you like to be added**:

The webhooks should support a helm value for creating cert-manager certificate / ca requests so that cert-manager secures the webhooks rather then generating the certs in the container.

**Why is this needed**:

This centralizes all the certificate management code in one place that can be much more easily monitored and secured. It is difficult to manage lots of different webhooks in the cluster each with their own certificate infrastructure.

**Examples**
There are examples of how this works here: https://cert-manager.io/docs/concepts/ca-injector/

**Comment by FillZpp** [comment]
> It is difficult to manage lots of different webhooks in the cluster each with their own certificate infrastructure.

@kfox1111  Users need not to care about the certificate management of Kruise. Actually, we don't want to make OpenKruise relied on cert-manager, lots of our users do not have cert-manager in their clusters.

We expect OpenKruise to be an independent component and anyone could easily install it with one command in any Kubernetes clusters.

**Comment by kfox1111** [comment]
I have increasing numbers of webhooks on my systems which means more  and more time spend dealing with security issues. Your webhook doesn't exist in isolation. It exists on production clusters along with many others. The sum total of them is relevant to your users who care about strong security. This can hamper adoption of openkruise in certain environments...

I'm not saying you must require cert-manager as a dependency and force everyone to use it. I'm saying, for those that already have it as a certificate management system, you shouldn't force them to run a second set of security sensitive certificate related code when they already have vetted one. This greatly reduces the security footprint for those that care about such things. It can easily be made an option to the helm chart certManager.enable and just skip doing the cert management stuff when enabled. This still allows the ease of use your looking for and better security for those that want it.

**Comment by FillZpp** [comment]
@kfox1111 Understand. We can add a flag in chart which allows users to install Kruise with certificate managed by cert-manager.

**Comment by kfox1111** [comment]
not stale.
