### ISSUE TITLE
[BUG] `make manager` changes source code of project

### ISSUE THREAD

**Issue by allencloud** [openkruise/kruise#51]
**What happened**:
`make manager` changes source code of project:

**What you expected to happen**:
`make manager` does no change to source code

**How to reproduce it (as minimally and precisely as possible)**:
```
kruise (master) $ make manager
go generate ./pkg/... ./cmd/...
go fmt ./pkg/... ./cmd/...
pkg/controller/statefulset/stateful_inplace_utils_test.go
go vet ./pkg/... ./cmd/...
go build -o bin/manager github.com/openkruise/kruise/cmd/manager
kruise (master) $ git status
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   pkg/controller/statefulset/stateful_inplace_utils_test.go

no changes added to commit (use "git add" and/or "git commit -a")
kruise (master) $ git diff pkg/controller/statefulset/stateful_inplace_utils_test.go
diff --git a/pkg/controller/statefulset/stateful_inplace_utils_test.go b/pkg/controller/statefulset/stateful_inplace_utils_test.go
index 84017390..f2b328c2 100644
--- a/pkg/controller/statefulset/stateful_inplace_utils_test.go
+++ b/pkg/controller/statefulset/stateful_inplace_utils_test.go
@@ -136,7 +136,7 @@ func TestShouldDoInPlaceUpdate(t *testing.T) {
                        },
                },
                {
-                       name:                  "podUpdatePolicy is not InPlaceIfPossible",
+                       name: "podUpdatePolicy is not InPlaceIfPossible",
                        rollingUpdateStrategy: &appsv1alpha1.RollingUpdateStatefulSetStrategy{},
                        updateRevision: &apps.ControllerRevision{
                                Data: runtime.RawExtension{Raw: []byte(`{"spec":{"template":{"$patch":"replace","spec":{"containers":[{"name":"c1","image":"foo2"}]}}}}`)},
kruise (master) $ 
```

**Anything else we need to know?**:
none

**Environment**:
- Kruise version: master node
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by jian-he** [comment]
I tried to fix the format and run the "make manager" command, in fact, it will reset to current format.
is this because of some kind of format setting ?

**Comment by FillZpp** [comment]
I tried to run the command, nothing changed.
```
$ make manager
go generate ./pkg/... ./cmd/...
go fmt ./pkg/... ./cmd/...
go vet ./pkg/... ./cmd/...
go build -o bin/manager github.com/openkruise/kruise/cmd/manager
$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

**Comment by xiang90** [comment]
what is the go version on your machines? @allencloud @FillZpp

**Comment by FillZpp** [comment]
Go version on my machine `go version go1.11.6 darwin/amd64`.
Is your go version up to 1.12+ ? @allencloud

**Comment by allencloud** [comment]
```
kruise (master) $ go version
go version go1.10.4 darwin/amd64
kruise (master) $
```
I am afraid it is only 1.10.4. Do we need a restriction that upgrade golang version to the 1.12+.
@xiang90 @FillZpp

**Comment by xiang90** [comment]
can we add a go version check in the `make` script? @jian-he @FillZpp @allencloud

**Comment by jian-he** [comment]
we could add a warning in the script. 
failing it would hurt user experience, IMO.
And this looks to be a common problem for all Golang projects

**Comment by FillZpp** [comment]
Common users will not use `make`, they should install kruise using `helm install` or `kubectl apply`.
I think it is ok to return a failure of go-version check to kruise developers.

**Comment by FillZpp** [comment]
@xiang90 @jian-he @allencloud  Add a go version check #54
