### ISSUE TITLE
[feature request] configurable sidecar webhook selector

### ISSUE THREAD

**Issue by kfox1111** [openkruise/kruise#510]
**What would you like to be added**:

Right now the selector for pods is everything but namespaces labeled as control-plane.

I'd like the option to set it on my clusters to only apply to pods in namespaces with specific labels applied and not namespaces without the label.

Probably best to just pass through the entire configuration of the namespace selector via helm values?

**Why is this needed**:
It may be undesirable to find and label all namespaces you want to protect from pods running through openkruise but instead may be easier to label just the namespaces you want to be able to use sidecars

**Comment by FillZpp** [comment]
> Probably best to just pass through the entire configuration of the namespace selector via helm values?

Sounds reasonable, like the `istio-injection=enabled` namespace selector in Istio? But we should think of how could this be compatible with the existing sidecarset usage scenarios.

**Comment by kfox1111** [comment]
Yeah. That's kind of what I was thinking.

Maybe have a selector in the values. If the selector is set in values, use that. if not set, use the existing selector as a default? Then it would continue to work the way it always had, and can still be overridden by those that want to.
