### ISSUE TITLE
[feature request] Java client needed

### ISSUE THREAD

**Issue by lyj8330328** [openkruise/kruise#513]
**What would you like to be added**:
Are there any plans to open java-client?
**Why is this needed**:
I hope to use openkruise in a java project and use Kubernetes Java Client to automatically generate crd model failure.

**Comment by FillZpp** [comment]
@lyj8330328 Now we have https://github.com/openkruise/client-java to store the Java API of Kruise, but we have not upload the jar to official maven repository yet. Can you temporarily download it and package manually for your project?

**Comment by lyj8330328** [comment]
> @lyj8330328 Now we have https://github.com/openkruise/client-java to store the Java API of Kruise, but we have not uploaded the jar to official maven repository yet. Can you temporarily download it and package manually for your project?

thanks a lot
