### ISSUE TITLE
[feature request]image pre-download这个功能希望可以包含节点筛选

### ISSUE THREAD

**Issue by yutinghua** [openkruise/kruise#517]
**What would you like to be added**:
ImagePullJob的用法和实现可以开源

**Why is this needed**:
之前提过希望开源：https://github.com/openkruise/kruise/issues/479；但是我看目前的实现没有对node进行筛选，我希望的任务是一部分选中的node拉镜像，不知道什么时候可以开源，谢谢！

**Comment by yutinghua** [comment]
我觉得原地发版应该是需要选择节点的，即只需要将镜像预热到正在运行的app对应的node上即可。

**Comment by FillZpp** [comment]
@yutinghua The `ImagePullJob` do have a node selector. You can put a list of node name or a selector for node labels in the spec of ImagePullJob. https://github.com/openkruise/kruise/blob/master/apis/apps/v1alpha1/imagepulljob_types.go#L56

And the implementation of ImagePullJob and NodeImage will be coming this week.

**Comment by yutinghua** [comment]
That's GREAT!
