### ISSUE TITLE
[BUG]convertToRegistryAuthInfo没有给registry加上https，导致无法与secret中的auth匹配

### ISSUE THREAD

**Issue by yutinghua** [openkruise/kruise#526]
**What happened**:
现象：
W0129 11:57:05.720466   10356 puller.go:333] Worker failed to pull image xxx, cost 15.041022179s, err: imagePullSecret {ns}/{secret} contains neither .dockercfg nor .dockerconfigjson
原因：ImagePullJob.Spec.PullSecrets指定拉镜像需要的secret列表，secret.data[".dockerconfigjson"]的内容解析后的key是registry，一般是"https://xxx"，而镜像名没有"https://"，所以无法匹配，导致找不到拉镜像所需的user:password

**What you expected to happen**:
请参考kubelet拉镜像的认证方式，根据镜像名寻找对应的user:password时，自动加上"https://"
https://github.com/kubernetes/kubernetes/blob/b77c886043ef318768f4317c6d7862ef8320a688/pkg/credentialprovider/keyring.go#L190
其中target是BasicDockerKeyring拉镜像的镜像名，然后`ParseSchemelessURL`会加上"https://"，后面就能匹配成功。

**How to reproduce it (as minimally and precisely as possible)**:
这个应该比较容易复现。我的环境中，secret中的registry是有"https://"的，然后创建pod时指定imagePullSecrets就可以正常拉取镜像。

**Anything else we need to know?**:

**Environment**:
- Kruise version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by FillZpp** [comment]
@yutinghua 感谢反馈！我已经在 #520 中新增一个 commit 解决这个 pull secrets 解析问题，可以再验证一下 😄

**Comment by yutinghua** [comment]
已验证

**Comment by yutinghua** [comment]
已验证
