### ISSUE TITLE
[feature request]Is There Any Chinese Doc?

### ISSUE THREAD

**Issue by KaiwenWang** [openkruise/kruise#53]
**What would you like to be added**:
Chinese Doc

**Why is this needed**:
Not all coders are good at reading englist docs

**Comment by jian-he** [comment]
we will try to write one, thanks

**Comment by allencloud** [comment]
I think we should provide the Chinese docs, while maybe the core team of openkruise could avoid doing this but focuses on the core developing and English docs.
I will find a way to provide this with less effort. @KaiwenWang @jian-he @xiang90

**Comment by fengzixu** [comment]
Hi, Is this issue has been solved? I am delighted to finish it for the community. @allencloud @jian-he

**Comment by jian-he** [comment]
> Hi, Is this issue has been solved? I am delighted to finish it for the community. @allencloud @jian-he

not yet.  It'll be great if you can spend time on this. Thank you !

**Comment by fengzixu** [comment]
Hey guys. Sorry for responding late. I'm a little busy in recent days. I plan to start translating the doc of Kruise this weekend. But I want to ask one question in advance:

Which document should be translated firstly? Readme or doc in the docs dictionary?

@jian-he

**Comment by vinnyzhaowenyu** [comment]
me too!
come on

**Comment by jian-he** [comment]
> Hey guys. Sorry for responding late. I'm a little busy in recent days. I plan to start translating the doc of Kruise this weekend. But I want to ask one question in advance:
> 
> Which document should be translated firstly? Readme or doc in the docs dictionary?
> 
> @jian-he

sorry for the late reply, you may start with this overview page: https://github.com/openkruise/kruise/blob/master/docs/README.md

and then the tutorials https://github.com/openkruise/kruise/blob/master/docs/tutorial/README.md
thanks

**Comment by FillZpp** [comment]
@KaiwenWang @fengzixu @vinnyzhaowenyu  We have moved docs from github to [openkruise.io](https://openkruise.io/), and we also provided both English and Chinese docs there. 😃
