### ISSUE TITLE
[BUG] CloneSet name length can't be greater than 63

### ISSUE THREAD

**Issue by fatedier** [openkruise/kruise#531]
**What happened**:
Create a CloneSet with name `sample-long-long-long-long-long-long-long-long-long-long-long-long-name`.

CloneSet controller will create a pod with label `controller-revision-hash` and value is `{CloneSet name}-{hash}`.

Label value length must be less than 64 bytes, so pod create request will be rejected by kube-apiserver.

**What you expected to happen**:
Allowed to create a CloneSet with name length <= 253

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Same issue for StatefulSet: https://github.com/kubernetes/kubernetes/issues/79337

I prefer to change `controller-revision-hash` label format and remove `CloneSet name` from it, so it will not be affected by CloneSet name length.

From `controller-revision-hash: sample-long-long-long-long-long-long-long-long-long-long-long-long-name-54d7c84944` to `controller-revision-hash: 54d7c84944`

To compatible with exist cloneset and pod, we can add a new function such as:

```go
func IsPodRevisionEqual(pod *v1.Pod, revision *apps.ControllerRevision) bool {
    podRevision := GetPodRevision(pod)
    if podRevision == revision.Name || podRevision == GetRevisionHash(revision) {
        return true
    }
    return false
}
```

**Environment**:
- Kruise version: 0.7.0
- Kubernetes version (use `kubectl version`): 1.14
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by FillZpp** [comment]
@fatedier Good point, we can do this. And also a flag should be added to let users choose to use the feature, because I'm afraid some users may already depend on the `controller-revision-hash` label to be the full name of ControllerRevision.

So... are you interested in implementing it? 😄

**Comment by fatedier** [comment]
Sure.
