### ISSUE TITLE
Webhook TimeoutSeconds in values.yaml

### ISSUE THREAD

**Issue by Daxcor69** [openkruise/kruise#534]
I am hosted with Digital Ocean using a managed kuberenetes.  They have an auto upgrade feature for the cluster software.  However the upgrade is  blocked if the TimeoutSeconds > 30 secs.  Which it what you have set as a default.  I need this to be a value that I can set.  I don't want to mess with the deployment outside of the normal way of editing values.yaml. I am not experienced enough to dive into this.  Please I hope you can help.

Brad

**Comment by Fei-Guo** [comment]
Are you requesting to make Timeoutseconds configurable in future releases (which I think we can support) or asking for changes in current releases?  

For current release, you can modify Values.yaml and template/webhookconfiguration.yaml accordingly following the example of webhook "failurePolicy"  in Values.yaml.

**Comment by Daxcor69** [comment]
yeah, I think it would be a good addition to your helm chart for future versions.  I will have a look at the repo as suggested and see. I just used the tgz link for the install of the helm chart.  So I will clone the repo and have a look.

Thank you for your time.
Brad

**Comment by FillZpp** [comment]
Closed in #543
