### ISSUE TITLE
In-place update --Support resize resources

### ISSUE THREAD

**Issue by riverzhang** [openkruise/kruise#541]
**What would you like to be added**:
     I want to modify the cpu and memory size of the pod. Currently, it will go through the recreate process. not to update locally, or restart the container to take effect. At the same time, the scheduler needs to be aware of resource changes. 
     Does openkruise have any plans for this? Hope to discuss this with everyone.

**Why is this needed**:
Reduce processes such as controller management, scheduling, and network recreate...  Rebuild applications quickly. The basic operation of k8s is more stable.

**Comment by wgitg** [comment]
+1 on this feature. Our org needs to use this too.

**Comment by Fei-Guo** [comment]
The same has been asked before but Kubelet does not support inplace updating Pod size. This feature requires the changes to Kubelet and scheduler which is out of the scope of Kruise.

**Comment by furykerry** [comment]
it is supported in recent 1.8 release, stay tuned for the document update. You can checkout the changelog
https://github.com/openkruise/kruise/blob/master/CHANGELOG.md
