### ISSUE TITLE
[feature request] support to configure timezone for kruise-controller-manager 

### ISSUE THREAD

**Issue by cvvz** [openkruise/kruise#546]
**What would you like to be added**:
support to configure timezone for kruise-controller-manager 

**Why is this needed**:
The timestamp of log in `kruise-controller-manager ` is based on `UTC` timezone, but timezone in China is `UTC+8`, which makes it difficult to analyze logs.

**Comment by Fei-Guo** [comment]
Are you sure the timestamp is not consistent with your hardware machine where the container is running?

**Comment by qixiaobo** [comment]
https://kubernetes.io/zh/docs/concepts/workloads/controllers/cron-jobs/
So in cronjob spec

>Caution:
>All CronJob schedule: times are based on the timezone of the kube-controller-manager.
>
>If your control plane runs the kube-controller-manager in Pods or bare containers, the timezone set for the kube->controller-manager container determines the timezone that the cron job controller uses.

The same we should pay attention to kruise-controller

**Comment by qixiaobo** [comment]
So maybe helm need provide a parameter like manager.timezone ?

**Comment by FillZpp** [comment]
> So maybe helm need provide a parameter like manager.timezone ?

#974 will provide a timezone field in acj spec. @qixiaobo

**Comment by qixiaobo** [comment]
> 

Thanks for reply. We will have a try
