### ISSUE TITLE
有没有前台管理工具类似rancher那样便于维护的？

### ISSUE THREAD

**Issue by chaishiqi** [openkruise/kruise#555]
RT

**Comment by liangyuanpeng** [comment]
As far as I know, there is no. What do you need UI for?

**Comment by chaishiqi** [comment]
就是给相对不熟悉k8s和openkruise的运维和开发一个个管理的渠道，点点点就能管理的那种^_^

**Comment by Fei-Guo** [comment]
Sorry we don't have UI in Kruise. We always recommend new users to start with tutorials (we have plenty of them and they are proven to be useful).
