### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by oldshipmaster** [openkruise/kruise#556]
#helm install kruise https://github.com/openkruise/kruise/releases/download/v0.8.0/kruise-chart.tgz
Error: failed to download "https://github.com/openkruise/kruise/releases/download/v0.8.0/kruise-chart.tgz" (hint: running `helm repo update` may help)

helm install openkruise ./ -n kube-system
Error: rendered manifests contain a resource that already exists. Unable to continue with install: Namespace "kruise-system" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "openkruise"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "kube-system"

**Comment by FillZpp** [comment]
@oldshipmaster `helm install openkruise ./ -n kube-system` is not the recommended way to install Kruise.

If `helm repo update` can not solved the error of `helm install kruise https://github.com/openkruise/kruise/releases/download/v0.8.0/kruise-chart.tgz`, you can try to firstly download the chart

```
wget https://github.com/openkruise/kruise/releases/download/v0.8.0/kruise-chart.tgz
```

then install

```
helm install kruise ./kruise-chart.tgz
```
