### ISSUE TITLE
broadcastjob 状态不对，无法自动删除

### ISSUE THREAD

**Issue by TonyBian** [openkruise/kruise#580]
Kruise 版本：0.8.0

Kubernetes 版本：1.18.16

broadcastjob 配置及状态：
spec:
  completionPolicy:
    activeDeadlineSeconds: 600
    ttlSecondsAfterFinished: 30
    type: Always
  failurePolicy:
    type: FailFast
  parallelism: 2147483647
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - command:
            ......
status:
  active: 8
  desired: 8
  failed: 0
  phase: running
  startTime: "2021-04-02T08:05:00Z"
  succeeded: 0

pod 状态：
[root@kube-node-1810-01 ~]# kubectl get pod -n kruise-instance
NAME                                                         READY   STATUS      RESTARTS   AGE
cronjob-broadcastjob-prune-expired-images-1617350700-4w58x   0/1     Error       0          3m16s
cronjob-broadcastjob-prune-expired-images-1617350700-577fv   0/1     Completed   0          3m16s
cronjob-broadcastjob-prune-expired-images-1617350700-5rpp9   0/1     Completed   0          3m16s
cronjob-broadcastjob-prune-expired-images-1617350700-cqx2p   0/1     Completed   0          3m16s
cronjob-broadcastjob-prune-expired-images-1617350700-mmv8d   0/1     Completed   0          3m16s
cronjob-broadcastjob-prune-expired-images-1617350700-mwbwm   0/1     Error       0          3m16s
cronjob-broadcastjob-prune-expired-images-1617350700-tk67q   0/1     Completed   0          3m16s
cronjob-broadcastjob-prune-expired-images-1617350700-xfx49   0/1     Completed   0          3m16s
cronjob-broadcastjob-prune-expired-images-1617350760-99jnz   0/1     Completed   0          2m16s
cronjob-broadcastjob-prune-expired-images-1617350760-9tt8m   0/1     Completed   0          2m16s
cronjob-broadcastjob-prune-expired-images-1617350760-fhjn5   0/1     Completed   0          2m16s
cronjob-broadcastjob-prune-expired-images-1617350760-lt5c8   0/1     Completed   0          2m16s
cronjob-broadcastjob-prune-expired-images-1617350760-sfbz5   0/1     Completed   0          2m16s
cronjob-broadcastjob-prune-expired-images-1617350760-st4wj   0/1     Completed   0          2m16s
cronjob-broadcastjob-prune-expired-images-1617350760-wmpc8   0/1     Completed   0          2m16s
cronjob-broadcastjob-prune-expired-images-1617350760-zhs6z   0/1     Completed   0          2m16s
cronjob-broadcastjob-prune-expired-images-1617350820-4lqjn   0/1     Completed   0          76s
cronjob-broadcastjob-prune-expired-images-1617350820-89k8l   0/1     Completed   0          76s
cronjob-broadcastjob-prune-expired-images-1617350820-kzg6g   0/1     Completed   0          76s
cronjob-broadcastjob-prune-expired-images-1617350820-mspd8   0/1     Completed   0          76s
cronjob-broadcastjob-prune-expired-images-1617350820-mvh26   0/1     Completed   0          76s
cronjob-broadcastjob-prune-expired-images-1617350820-prhrl   0/1     Completed   0          76s
cronjob-broadcastjob-prune-expired-images-1617350820-qp44g   0/1     Completed   0          76s
cronjob-broadcastjob-prune-expired-images-1617350820-w4bwj   0/1     Completed   0          76s
cronjob-broadcastjob-prune-expired-images-1617350880-ds2q8   0/1     Completed   0          16s
cronjob-broadcastjob-prune-expired-images-1617350880-hx5c7   0/1     Completed   0          16s
cronjob-broadcastjob-prune-expired-images-1617350880-ld6vj   0/1     Completed   0          16s
cronjob-broadcastjob-prune-expired-images-1617350880-md52k   0/1     Completed   0          16s
cronjob-broadcastjob-prune-expired-images-1617350880-mk2cs   0/1     Completed   0          16s
cronjob-broadcastjob-prune-expired-images-1617350880-mrjcs   0/1     Completed   0          16s
cronjob-broadcastjob-prune-expired-images-1617350880-nqgsf   0/1     Completed   0          16s
cronjob-broadcastjob-prune-expired-images-1617350880-pbpwf   0/1     Completed   0          16s

[root@kube-node-1810-01 ~]# kubectl get broadcastjobs.apps.kruise.io -n kruise-instance
NAME                                                   DESIRED   ACTIVE   SUCCEEDED   FAILED   AGE
cronjob-broadcastjob-prune-expired-images-1617350700   8         8        0           0        3m26s
cronjob-broadcastjob-prune-expired-images-1617350760   8         8        0           0        2m26s
cronjob-broadcastjob-prune-expired-images-1617350820   8         8        0           0        86s
cronjob-broadcastjob-prune-expired-images-1617350880   8         8        0           0        26s

**Comment by FillZpp** [comment]
@TonyBian Sorry for the trouble. We have released `v0.8.1` that fixes this bug, please update kruise version if you need.
https://openkruise.io/en-us/docs/installation.html#upgrade-with-helm-charts
