### ISSUE TITLE
[DOC] Shortcut name for BroadcastJob is `bcj` not `bj`

### ISSUE THREAD

**Issue by hantmac** [openkruise/kruise#581]
![image](https://user-images.githubusercontent.com/7600925/113399893-88f3e580-93d3-11eb-89c0-94b05ce145bd.png)

Shortcut name for BroadcastJob is `bcj` not `bj`, the docs `https://openkruise.io/en-us/docs/broadcastjob.html` need fix.

**Comment by FillZpp** [comment]
closed by https://github.com/openkruise/website/pull/47
