### ISSUE TITLE
[Question/Feature request] Terraform support and/or helm subcharts support

### ISSUE THREAD

**Issue by LiuVII** [openkruise/kruise#583]
Would be great if openkruise could be efficiently used with Terraform.

1) I couldn't find an existing provider for it, but I'll ask here anyway: is there one? are there any plans to make one?

2) If not direct terrafrom support, I noticed that openkruise has helm charts support but charts/templates are not hosted in any repo one can easily access iiuc. An awesome way to go would be if templates can be used a subcharts so like this [terraform resource](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release) can be used to install and modify it. Or is there some way to use it with the existing structure?

**Comment by FillZpp** [comment]
@LiuVII Thanks for the advice.

Could the [helm release with chart URL](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release#example-usage---chart-url) helps you use openkruise in Terraform?
