### ISSUE TITLE
[BUG]kruise预热镜像导致docker.sock连接数暴增

### ISSUE THREAD

**Issue by yutinghua** [openkruise/kruise#586]
**What happened**:
现象：使用kruise预热镜像时，docker.sock连接数暴增，导致拉镜像卡住，必须重启docker才能恢复。
初步排查：查看docker.sock 发现数量非常多，达到好几万，拉镜像会非常慢，甚至卡住，然后重启kruise-daemon，docker的连接会慢慢下降。但是目前看代码，发现kruise查看镜像和实际拉镜像，都是使用了pullWorker.runtime，里面使用使用的client应该是单例的，不知道哪里创建了这些连接
![image](https://user-images.githubusercontent.com/20547895/113827405-d8605a00-97b5-11eb-8ad8-5ea1e8d28809.png)

**Environment**:
- Kruise version: https://github.com/openkruise/kruise/pull/520 （目前基于这个分支的代码）
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by FillZpp** [comment]
@yutinghua You can firstly get the pid of kruise-daemon: `ps -ef | grep kruise-daemon`, then look for the number of socket it connected `ls /proc/${PID}/fd -l | grep socket:`

**Comment by yutinghua** [comment]
排查发现应该不是kruise的问题，抱歉，我再继续排查一下
