### ISSUE TITLE
[feature request] we want a feature like one time daemonset

### ISSUE THREAD

**Issue by manifoldyu** [openkruise/kruise#61]
**What would you like to be added**:

broadcastJob will run on all worker node that already exists, but we want broadcastJob can support that run on all new comming worker node,like one time daemonset.

**Why is this needed**:

**Comment by allencloud** [comment]
I think set `terminationPolicy` to be `never`. Then you request can be realized. @manifoldyu

**Comment by Fei-Guo** [comment]
Close it as the feature is available.

**Comment by xiang90** [comment]
@Fei-Guo we should add this in the documentation as a use case.

**Comment by xiang90** [comment]
See this example: https://github.com/openkruise/kruise/blob/master/docs/concepts/broadcastJob/README.md#automatically-launch-pods-on-newly-added-nodes-by-keeping-the-job-active-using-never-completionpolicy
