### ISSUE TITLE
[Discussion] How to make sure the data is up-to-date when the events of the same instance are reconciled in more than one worker at the same time?

### ISSUE THREAD

**Issue by littletiger123** [openkruise/kruise#611]
I notice that the log shows the worker number is 3 when installing the kruise. I want to know that when the events of the same instance are reconciled in more than one worker at the same time, how to make sure the instance info got by one worker is up-to-date because the info may be modified by the other workers.

**Comment by Fei-Guo** [comment]
Client-go workerqueue ensures that there is only one worker that actively handles a reconciled object (no parallel reconciling).

Check this out for details.
http://openkruise.io/en-us/blog/blog2.html

**Comment by littletiger123** [comment]
> Client-go workerqueue ensures that there is only one worker that actively handles a reconciled object (no parallel reconciling).
> 
> Check this out for details.
> http://openkruise.io/en-us/blog/blog2.html

Get, thanks a lot.
