### ISSUE TITLE
[BUG] Helm chart 0.8.1 uses system namespace instead of kruise-system namespace

### ISSUE THREAD

**Issue by lowkeyliesmyth** [openkruise/kruise#614]
**What happened**: Upgrading helm install from 0.7.0 -> 0.8.1 fails to install Statefulset CRD, validating-webhook and mutating webhook correctly as they reference namespace `system` instead of `kruise-system`. Helm chart does not include `system` namespace.

**What you expected to happen**: Applying helm chart 0.8.1 would update and install all objects correctly.

**How to reproduce it (as minimally and precisely as possible)**:  
* Install 0.7.0 from helm, see that everything install successfully.
    helm install kruise https://github.com/openkruise/kruise/releases/download/v0.7.0/kruise-chart.tgz
* Upgrade to 0.8.1 
    helm install kruise https://github.com/openkruise/kruise/releases/download/v0.8.1/kruise-chart.tgz
*  See that the new Kruise Statefulset CRD, mutatingwebhookconfiguration and validatingwebhookconfigurations are not applied correctly.

**Anything else we need to know?**:

**Environment**:
- Kruise version: 0.8.1
- Kubernetes version (use `kubectl version`): Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.8-eks-96780e", GitCommit:"96780e1b30acbf0a52c38b6030d7853e575bcdf3", GitTreeState:"clean", BuildDate:"2021-03-10T21:32:29Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g: `cat /etc/os-release`): Amazon linux 2
- Kernel (e.g. `uname -a`): 4.14.200-155.322.amzn2
- Install tools: helm, kustomize, argoCD
- Others:

**Comment by FillZpp** [comment]
@lowkeyliesmyth Thanks for reporting! I have fixed the yamls and upload the new chart.
