### ISSUE TITLE
[feature request]Pods rolling running in BroadcastJob

### ISSUE THREAD

**Issue by yangjunsss** [openkruise/kruise#618]
**What would you like to be added**:
Add Pods rolling running policy in BroadcastJob to prevent  Job Pod breaking down all node in cluster.

**Why is this needed**:
BroadcastJob is very suitable for patching bug in master&node, but  we hope running job step by step . What do you think?

**Comment by FillZpp** [comment]
@yangjunsss Sorry for this late reply... Unfortunately, BroadcastJob are guaranteed to run the job **once** on each node.
If it supports rolling update by recreating jobs, this might cause the jobs ran multiple times on a same node, which will break the promise.

**Comment by yangjunsss** [comment]
@FillZpp Happy for your reply, I means each jobs running each node step by step according some strategry to prevent cluster disaster, because we can't ensure the node or cluster avaiable even the job's status is successful. 

I would like to run the *patch job* on each node but we need leave some time to watch the cluster's health.

**Comment by FillZpp** [comment]
@yangjunsss  How about use the Advanced CronJob, which can create and run BroadcastJobs periodically? You could set the cron to make the job run once on nodes everyday.

**Comment by yangjunsss** [comment]
I think CronJob can't resolve my problem. I concern the broadcast job which includes all pods break the cluster's node and master down even the Job's status is successful, so I perfer running each Job Pod gradually to run meantime. How do you think?

**Comment by FillZpp** [comment]
@yangjunsss Oh, do you mean the `parallelism` provided in BroadcastJob spec? It specifies the maximum desired number of pods the job should run at any given time. Not setting this value means no limit.
https://openkruise.io/en-us/docs/broadcastjob.html#parallelism

**Comment by yangjunsss** [comment]
We don't think `parallelism` is enough. We expect to run Pods in exponential growth like x^(y-1). And the controller can export a way like hook to let us to check cluster health after each batch execution.

Pods: 10
base count(x) : 2

Process:
start --- P0 --- hook point --- P1P2 --- hook point --- P[3-6] --- hook point --- P[7-9] --- finish
