### ISSUE TITLE
[feature request] 在自定义namespace中运行 open-kruise

### ISSUE THREAD

**Issue by zeusro** [openkruise/kruise#619]
**What would you like to be added**:
在自定义  namespace 中运行 open-kruise

**Why is this needed**:
定制化需求

目前的问题是，我clone了这个项目，用 .VALUES.namespace 替换掉了默认的运行命名空间 ”kruise-system“ 。启动运行之后发现一个选主错误

```bash
E0514 04:08:31.396459       1 leaderelection.go:334] error initially creating leader election record: namespaces "kruise-system" not found
I0514 04:08:31.396473       1 leaderelection.go:246] failed to acquire lease kruise-system/kruise-manager
```
检查代码发现是 main.go 里面使用了，而部署的启动参数中没有能够修改的地方。

```go
flag.StringVar(&leaderElectionNamespace, "leader-election-namespace", "kruise-system",
```

希望在下一个版本，能够支持其他 namespace 下运行 open-kruise。

**Comment by zeusro** [comment]
另外，制作 helm 包的时候建议把 crd 抽取出来（建一个crds 目录，跟template 同级），这样比较符合 helm 的最佳实践

https://helm.sh/docs/chart_best_practices/custom_resource_definitions/

**Comment by moluzhui** [comment]
我在kruise 1.5.0版本也遇到这个问题，并且我没有改变namespaces，使用的就是kruise-system命名空间。两个pod实例均报错如下：
`
I0115 14:24:20.308265       1 leaderelection.go:352] lock is held by kruise-controller-manager-xxx and has not yet expired
I0115 14:24:20.308281       1 leaderelection.go:253] failed to acquire lease kruise-system/kruise-manager
I0115 14:24:22.399333       1 leaderelection.go:352] lock is held by kruise-controller-manager-xxx and has not yet expired
I0115 14:24:22.399349       1 leaderelection.go:253] failed to acquire lease kruise-system/kruise-manager
`
