### ISSUE TITLE
[feature request] Make enabled controllers configurable

### ISSUE THREAD

**Issue by ilyee** [openkruise/kruise#633]
**What would you like to be added**:

Make setup for controllers configurable in `/pkg/controller/controllers.go` which means we can choose specific controllers to enable.

**Why is this needed**:

Now all the controllers are enabled by default, but in some cases we only need to enable some features and don't need others.

So is it better to make controllers' setup configurable by controllers' name provided from an new option?

**Comment by FillZpp** [comment]
@ilyee For those features that might have effects on user's k8s clusters, like kruise-daemon/deletion-protection, we have provided feature-gates to let users disable them.

But for other controllers, there is no need for users to choose. Just like the controllers in kube-controller-manager, you need not to disable some of them, such as cronjob controller, even if you never use them.

**Comment by ilyee** [comment]
I agree with that never used controllers don't have effects.

But I think there still exists one scene where we don't want users to use several features provided by kruise(for example we have a web page for k8s cluster but the page don't support the display of some workloads). Sure we can control their creations using `ClusterRole` or `Webhook`, but I think we can take less steps by disabling them when starting kruise.

WDYT? @FillZpp

**Comment by FillZpp** [comment]
@ilyee Understand. But in that case, if we disabled controllers like cloneset-controller, end users can still create a cloneset object on the web page or via kubectl, but the object will remain there with no controller handle it.

Will this be more confused?

**Comment by ilyee** [comment]
@FillZpp Yes that will be more confused if `cloneset` crd is applyed. 

But can we do this "disable" while installing kruise? I mean we can skip some crds' installation, so `cloneset` won't be available for end users.

**Comment by FillZpp** [comment]
> But can we do this "disable" while installing kruise? I mean we can skip some crds' installation, so cloneset won't be available for end users.

That might have risk that if someone had already installed Kruise, then he upgrade Kruise with a parameter which remove the CRD yaml in helm chart. It will cause the CRD installed previously been deleted by helm, and all CRs belongs to it will also be deleted.

How about a crd-disable-gate that just forbids users to create the CR? For example, you can put 'CloneSet' into the gate when install or upgrade Kruise. Then kruise-webhook will reject creation of all new cloneset objects, but the existing clonesets (before this upgrade) remain there and the cloneset-controller is still working.

**Comment by ilyee** [comment]
> How about a crd-disable-gate that just forbids users to create the CR? For example, you can put 'CloneSet' into the gate when install or upgrade Kruise. Then kruise-webhook will reject creation of all new cloneset objects, but the existing clonesets (before this upgrade) remain there and the cloneset-controller is still working.

crd-disable-gate sounds pretty good to me, can I make a pr for this?

**Comment by fatedier** [comment]
@ilyee I think it's a good way to control user's permission and ability by RBAC.

**Comment by furykerry** [comment]
> crd-disable-gate sounds pretty good to me, could you assign me for this issue if possible @FillZpp ? I'll make a pr for this soon.

crd-disable-gate  looks pretty weird to me,  i think stop related controller is more effective and more general. For example, there is use cases where for security  reasons, OpenKruise must not run some controllers, simply reject users requests is not enough.

**Comment by ilyee** [comment]
@fatedier Yes I think it may be the best way if we don't want to make some change in kruise, though it may takes a few more steps to configure users' permission

**Comment by ilyee** [comment]
> For example, there is use cases where for security reasons, OpenKruise must not run some controllers, simply reject users requests is not enough.

@furykerry  So you think it's better not running those forbidden controllers during kruise's initialization? Or stop them after init?
