### ISSUE TITLE
[feature request] In-place update supports env modification and images with the same imageID

### ISSUE THREAD

**Issue by FillZpp** [openkruise/kruise#644]
**What would you like to be added**:
In-place update supports env modification and images with the same imageID.

**Why is this needed**:
Formerly, kruise-manager can only check completion of in-place update according to pod status, which makes it can only distinguish the images with different imageID.

Now we have kruise-daemon running on the node, we can judge the real imageID through CRI and trigger the container to update when the envFrom annotations changed.

Issue related: #635

**Comment by wdwangcumt** [comment]
I have an idea that if we consider using kruise-daemon to do this, then we can also consider supporting pod's inplace-update after modifying the configmaps, such as adding or deleting a configmap in the spec of the pod, the need is reasonable.

**Comment by FillZpp** [comment]
@wdwangcumt yes, we can do this, and may be supported in next minor release.
