### ISSUE TITLE
[feature request] better GOVERNANCE

### ISSUE THREAD

**Issue by daixiang0** [openkruise/kruise#665]
**What would you like to be added**:

I want requirements for members and approvers.

**Why is this needed**:

Now https://github.com/openkruise/kruise/blob/master/GOVERNANCE.md only comment how to be a maintainer, not for members and approvers, so that there is a big gap between contributors and maintainers.

BTW, the current doc comments an unclear process to become a maintainer -- only need to talk to existing maintainers and get nominated, no issues or mails track.

**Comment by FillZpp** [comment]
@daixiang0 Yes, currently the GOVERNANCE is imperfect, I will update it next week. Thank you for the advice and we also welcome you to our community.
/unassign @jian-he 
/assign @FillZpp
