### ISSUE TITLE
[BUG] Pod with Updated state cannot update/rollback

### ISSUE THREAD

**Issue by shiyan2016** [openkruise/kruise#676]
**What happened**:
Setting cloneset with inplace update lifecycle hook, when pod enter to Updated state, make cloneset rollback the image or update to new image, the pod with Updated state will skip to update.

**What you expected to happen**:
can update Updated pod in the premise of not loss traffic

**How to reproduce it (as minimally and precisely as possible)**:
Create a cloneset with replicas 1, lifecycle hook, InPlaceIfPossible strategy. Update the cloneset image to some bad image(which will make pod not ready). When pod enter into Updated state, rollback cloneset, it will stuck.

**Anything else we need to know?**:

**Environment**:
- Kruise version: v0.9.0
- Kubernetes version (use `kubectl version`): v1.19.3
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by hantmac** [comment]
In your debug process, if you want to rollback cloneSet quickly, recommend to use the kubectl plugin of `OpenKruise` - [kubectl-kruise](https://github.com/openkruise/kruise-tools).  Then just use `kubectl-kruise rollout undo clone/abc` to rollback.

**Comment by hantmac** [comment]
I reproduced this scene, and found when  `diffRes.updateNum > 0` 
 
 so `waitUpdate` is true, run into in this code https://github.com/openkruise/kruise/blob/96371e2e7d6ca71d6c140e4c7f6a8ebfc3494ab4/pkg/controller/cloneset/sync/cloneset_update.go#L89 , pod with status `updated` wil be skipped to update.

The log is :

```
I0721 03:11:32.919482       1 cloneset_update.go:104] CloneSet local-test/12122-dev-10010 find pod 12122-dev-10010-sfzq9 in state Updated, so skip to update it
I0721 03:11:32.919512       1 cloneset_controller.go:180] Finished syncing CloneSet local-test/12122-dev-10010, cost 2.324492ms
I0721 03:11:32.919537       1 controller.go:272] controller-runtime/controller "msg"="Successfully Reconciled" "controller"="cloneset-controller" "name"="12122-dev-10010" "namespace"="local-test"
```

**Comment by FillZpp** [comment]
> pod with status updated wil be skipped to update.

Yes, and we are discussing whether the controller should patch the hook labels to Pod when it goes into PreparingUpdate state.

**Comment by shiyan2016** [comment]
> > pod with status updated wil be skipped to update.
> 
> Yes, and we are discussing whether the controller should patch the hook labels to Pod when it goes into PreparingUpdate state.

The result of discussion is patching the hook labels to Pod when pod state from Updated to PreparingUpdate state. I will submit a PR to fix it.
