### ISSUE TITLE
[BUG]cloneset 的镜像预热好像不符合预期？

### ISSUE THREAD

**Issue by pllsxyc** [openkruise/kruise#677]
使用镜像预热的功能+原地更新，是不是更新的时候，在镜像没拉完之前，这个pod上的流量是没有损失的？
场景：
我是用一个nginx的镜像，pod副本为1，使用curl while true进行请求
接下来更新镜像，使用了镜像预热，希望是镜像在没有拉完之前，这个pod上的流量是没有损失的，
整个过程中只有在镜像拉完后进行重启这个时间段内会出现502，但是现在看来是在一开始更新就出现502，整个更新过程都是502，请问这个镜像预热设计是否和我的预期一致？还是说我使用方式有误，并不能达到这个效果？

**Comment by FillZpp** [comment]
@pllsxyc 原地升级配合的镜像预热功能目前几个前提：
1. [cloneset 副本数 > 3](https://github.com/openkruise/kruise/blob/master/pkg/controller/cloneset/cloneset_predownload_image.go#L54)，避免太多小 cloneset 升级导致大量的镜像预热任务
2. [在灰度升级时候执行](https://github.com/openkruise/kruise/blob/master/pkg/controller/cloneset/cloneset_predownload_image.go#L62)，也就是说 cloneset 发布策略要么设置 partition，要么 maxUnavailable 算出来要小于 replicas 总数。因为镜像预热是要在实际 pod 原地升级之前做，如果所有 pod 发布立即就开始升级，那镜像预热就没有意义了

因此，你可以修改下测试场景。首先，确保 cloneset 副本数大于 3（假设是 5）。其次，在发布的时候修改 image 的同时先把 partition 改为 5，此时 cloneset 暂时不会升级任何 pod，只会创建 imagepulljob 来做预热。你可以根据预热的进度，逐渐调小 partition 来触发对 pod 做原地升级。

**Comment by pllsxyc** [comment]
哦哦，感谢回复解答，我现在的业务场景是这个pod只能有1个，所以我想使用镜像预热的功能尽可能缩短变更过程导致的流量受损（业务是可以只有一个pod）


| |
彭林林
|
|
***@***.***
|
签名由网易邮箱大师定制


在2021年07月22日 18:32，Siyu ***@***.***> 写道：

@pllsxyc 原地升级配合的镜像预热功能目前几个前提：

cloneset 副本数 > 3，避免太多小 cloneset 升级导致大量的镜像预热任务
在灰度升级时候执行，也就是说 cloneset 发布策略要么设置 partition，要么 maxUnavailable 算出来要小于 replicas 总数。因为镜像预热是要在实际 pod 原地升级之前做，如果所有 pod 发布立即就开始升级，那镜像预热就没有意义了

因此，你可以修改下测试场景。首先，确保 cloneset 副本数大于 3（假设是 5）。其次，在发布的时候修改 image 的同时先把 partition 改为 5，此时 cloneset 暂时不会升级任何 pod，只会创建 imagepulljob 来做预热。你可以根据预热的进度，逐渐调小 partition 来触发对 pod 做原地升级。

**Comment by FillZpp** [comment]
了解。你可以把这个 issue 修改下，比如说明是需要 replicas=1 的镜像预热，我们下个版本可以提供一个参数让你可以配置做镜像预热的 replicas 阈值（比如从默认 3 改为 1）。

但即使改为 1，也要在发布的时候先使用 partition=1，等镜像预热做完之后再改为 partition=0 真正触发 pod 升级。你看是否可以满足？

**Comment by FillZpp** [comment]
我们目前还在针对直播、游戏这类场景做一些整体调研和设计，这类业务往往有一些特殊需求（比如长连接、不可随意中断或旧版本进程不能立即退出等），面向这些垂直领域需求做一些通用性的解决方案。

其实这类 nginx 升级中断的问题，在 SidecarSet 中有 hot upgrade 是能对 sidecar 容器做[流量无损的原地热升级](https://openkruise.io/zh-cn/docs/sidecarset.html#sidecar%E7%83%AD%E5%8D%87%E7%BA%A7%E7%89%B9%E6%80%A7)，原理上是通过一个 Pod 中两个容器之间做交替升级和流量切换，但是 CloneSet 自身是不支持的，这块我们会整体考虑下。

**Comment by pllsxyc** [comment]
好的好的，非常感谢
