### ISSUE TITLE
source code question: about pilot-agent  pass the epoch

### ISSUE THREAD

**Issue by lilihongjava** [openkruise/kruise#678]
https://github.com/istio/istio/issues/28265

“We need to let the old pilot-agent pass the epoch to the new pilot-agent and then complete the upgrade of the Envoy with the help of the hot upgrade of the envoy.”

I looked at the latest code. Not found old pilot-agent pass the epoch to the new pilot-agent。

Can you point out where the source code is？

**Comment by zmberg** [comment]
You can see the [hot upgrade docs](https://openkruise.io/en-us/docs/sidecarset.html#hot-upgrade-sidecar), kruise's hot upgrade mechanism is a generic approach. In envoy's scenario, there is still some integration needed (envoy supports hot restart capability, but it needs to be integrated into the kruise mechanism).

**Comment by lilihongjava** [comment]
> You can see the [hot upgrade docs](https://openkruise.io/en-us/docs/sidecarset.html#hot-upgrade-sidecar), kruise's hot upgrade mechanism is a generic approach. In envoy's scenario, there is still some integration needed (envoy supports hot restart capability, but it needs to be integrated into the kruise mechanism).

Thank you for your reply.
Is there an example of  hot upgrade istio sidercar through kruise？

**Comment by zmberg** [comment]
There is no direct envoy example here, but I have implemented a simple [demo hot upgrade](https://github.com/openkruise/samples/tree/master/hotupgrade). It is simple, but contains key points in the hot upgrade process. In case of envoy, it needs to be integrated in using a similar approach.

**Comment by lilihongjava** [comment]
> There is no direct envoy example here, but I have implemented a simple [demo hot upgrade](https://github.com/openkruise/samples/tree/master/hotupgrade). It is simple, but contains key points in the hot upgrade process. In case of envoy, it needs to be integrated in using a similar approach.

I've tried. It doesn't work in istio version 1.6. The pod can't start. The main reason is that istio has done a lot of work in istio-init of Init Containers.

**Comment by zmberg** [comment]
Do you have Istio up and running now using sidecarSet? Did you not inject the init container?

**Comment by lilihongjava** [comment]
I don't understand 2 points now：
1、How to let the old pilot-agent pass the epoch to the new pilot-agent and then complete the hot upgrade of the envoy.Need to change the kruise source code？
2、How to inject the Istio init container?Copy the yaml generated by istio to the sidecarset？

**Comment by huanghuangzym** [comment]
where to find the difference between  registry.cn-hangzhou.aliyuncs.com/acs/asm-istio-proxy-empty:feature-1.6.x-511e4bb6e85be2c753a46d620efb1973251c1778  and istio-proxy image?

**Comment by zmberg** [comment]
> 1、How to let the old pilot-agent pass the epoch to the new pilot-agent and then complete the hot upgrade of the envoy. Need to change the kruise source code？
It's a complicated matter, and I've been hoping to answer your question, so I hope you'll take a good look at this article [OpenKruise helps Mesh Containers Hot Upgrade](https://mp.weixin.qq.com/s/J5tVtdhVLmjbb6kPgw0Qow).
Envoy Image needs to provide a hot upgrade script in PostStartHook, just like etcd using kubernetes Statefulset, which requires you to do some extra work. OpenKruise alone is not a complete implementation of Envoy hot upgrade.

> 2、How to inject the Istio init container?Copy the yaml generated by istio to the sidecarset？
yes

**Comment by luckymrwang** [comment]
@lilihongjava Have you accomplished the hot upgrade?

**Comment by jiangguoqing** [comment]
any one could give the hint to continue?it's no clue to achieve it.
