### ISSUE TITLE
[BUG] make test failed

### ISSUE THREAD

**Issue by rubinus** [openkruise/kruise#684]
**What happened**: when run make test is failed

**What you expected to happen**:  imagejob_reader_test.go:55] failed to start the controlplane. retried 5 times: timeout waiting for process etcd to start

**How to reproduce it (as minimally and precisely as possible)**: 
befor run make test.
1: install kubebuilder;
the binary kubebuilder must in:  /usr/local/kubebuilder/bin/
2: the etcd binary must in: /usr/local/kubebuilder/bin/

**Anything else we need to know?**:

**Environment**:
- Kruise version: 0.9.0
- Kubernetes version (use `kubectl version`): 1.19.7
- OS (e.g: `cat /etc/os-release`): mac
- Kernel (e.g. `uname -a`):
- Install tools: goland
- Others:

**Comment by yxxhero** [comment]
@rubinus please show your env **PATH**.
