### ISSUE TITLE
[BUG] cloneset deploy failed about forbidden set blockOwnerDeletion

### ISSUE THREAD

**Issue by yehaifeng** [openkruise/kruise#692]
**What happened**:
I deployed the kruise using the tool helm. But it failed when I test it.
I use the platform is `Openshift4`
```
[ocp4 kruise-test]$ k get clonesets.apps.kruise.io sample
NAME     DESIRED   UPDATED   UPDATED_READY   READY   TOTAL   AGE
sample   5                                                   34m
```

I found the error in the Pod `kruise-controller-manager` 
```
E0805 08:57:02.724992       1 cloneset_controller.go:191] Failed syncing CloneSet lab/sample: controllerrevisions.apps "sample-d4d4fb5bd" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>
E0805 08:57:02.725123       1 controller.go:248] controller-runtime/controller "msg"="Reconciler error" "error"="controllerrevisions.apps \"sample-d4d4fb5bd\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , \u003cnil\u003e" "controller"="cloneset-controller" "name"="sample" "namespace"="lab"
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kruise version: v0.9
- Kubernetes version (use `kubectl version`): 1.19.0, Openshift4.6
- OS (e.g: `cat /etc/os-release`): RHCOS 4.6
- Kernel (e.g. `uname -a`): 4.18
- Install tools: Openshift4
- Others:

**Comment by FillZpp** [comment]
@yehaifeng It seems the `cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on` error usually due to not having permission to the resource. Do you install Kruise using helm and v0.9.0 chart?

**Comment by yehaifeng** [comment]
@FillZpp Yes, that is opened default by Openshift4.6.
I add the permission of the `finalizers` .
