### ISSUE TITLE
[feature request] Does sidecarSet need to support the ability to pause, rolling update as well as injections are paused?

### ISSUE THREAD

**Issue by zmberg** [openkruise/kruise#694]
**What would you like to be added**:
Not like updateStrategy.Paused only pause rolling update, in some scenarios, I want to stop injecting capabilities at the same time.

**Why is this needed**:
In some extreme scenarios, the Sidecar container may affect the business expansion (sidecar container keeps failing to start), so it is necessary to suspend the injection of sidecar container at this time.

**Proposals**
We can add filed _**SidecarSetSpec.Paused**_, when SidecarSetSpec.Paused = true, siecarSet webhook will suspend to inject sidecar container, and the sidecarSet controller will pause rolling update at the same time. And the injected sidecar container remains running.

**Comment by FillZpp** [comment]
@zmberg How about a new `spec.injectionStrategy.paused` to indicate whether to pause new pod injection?

**Comment by zmberg** [comment]
@veophi

**Comment by veophi** [comment]
> @veoph
Request received.
