### ISSUE TITLE
[feature request]Support version control for SidecarSet

### ISSUE THREAD

**Issue by veophi** [openkruise/kruise#710]
**What would you like to be added**:
Support version control for SidecarSet ( e.g., using ControllerRevision).

**Why is this needed**:

- Perform a rollback on a SidecarSet;
- Specify version  when SidecarSet injection;

**Comment by FillZpp** [comment]
/reopen
#715 just stores the revisions but not support control yet

**Comment by willise** [comment]
Will SidecarSet support `CloneSetPartitionRollback` feature like CloneSet? CloneSet(v1.0.1) status has saved  "currentRevision" and "updateRevision" to be used for partition and that means there only have two different versions at same time. But SidecarSet now can has multi sidecar image versions, I think it may be a little complex and the sidecar is out of version control.

**Comment by FillZpp** [comment]
@willise Actually, in CloneSet, `currentRevision` means the stable version and `updateRevision` the latest version. They can be the same version, but it doesn't mean there is only one or two versions.

For example, the default version is `v1`, then update `v2` with partition and then update to `v3` with bigger partition. At this time, `currentRevision` is `v1` and `updateRevision` is `v3`, but there also exists some pods with `v2`.

**Comment by willise** [comment]
@FillZpp Thanks for your explanation and I get what you mean. So the `partition` field means "make sure there has (1-partition) percent of latest version instances at least". If I understand correctly, maybe the `partition` definition makes me feel confused and `1-percent` can be a good choice.
