### ISSUE TITLE
[feature request]OpenKruise provides REST APIs that can be accessed outside the cluster.

### ISSUE THREAD

**Issue by houweilong** [openkruise/kruise#719]
**What would you like to be added**:
REST APIs that can be accessed outside the cluster.

**Why is this needed**:
I want to create resources of Kruise in my own code

**Comment by FillZpp** [comment]
@houweilong Don't really understand your description.

> I want to create resources of Kruise in my own code

You can use `kruise-api` to define Kruise resources in your project. https://openkruise.io/zh-cn/docs/go_client.html

> REST APIs that can be accessed outside the cluster.

You can connect kube-apiserver outside cluster via kubeconfig, and create Kruise resources with the client above.

**Comment by houweilong** [comment]
But my client is developed using Python, Can I create Kruise resources in Python wuthout the client?

**Comment by FillZpp** [comment]
Unfortunately now we have no Python client of Kruise. Maybe you can use the https://github.com/kubernetes-client/python and create Kruise resources via its [custom resource api](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CustomObjectsApi.md#create_namespaced_custom_object).

**Comment by houweilong** [comment]
ok, Thanks. I will try it.
