### ISSUE TITLE
[doc request] specific explanation of broadcast job's authorization management

### ISSUE THREAD

**Issue by allencloud** [openkruise/kruise#72]
**What would you like to be added**:
Currently, Broadcast Job is used to control a non-long-running job on each node of k8s cluster, such as image preheat job, cleanup job and so on.

While for a job in container to finish a task on a node, it sometimes requires more authorization management. For example, how to gain privilege access on host to execute corresponding commands?

What kind of guidance can kruise provide for community end users? 

**Why is this needed**:
Foe end users, they have no idea that whether a broadcast job can be used in every scenario due to potential authorization lack issues.

**Comment by jian-he** [comment]
@allencloud do you mean how to enable the job container with privilege mode ?

**Comment by FillZpp** [comment]
Rotten issues close after 90d of inactivity.
