### ISSUE TITLE
[BUG] unpredictable numbers of pods when interval of reserveOrdinals > ordinals of pods

### ISSUE THREAD

**Issue by vegazmaoning** [openkruise/kruise#746]
**What happened**:
    unpredictable numbers of pods when interval of reserveOrdinals > ordinals of pods

**What you expected to happen**:
    when interval of reserveOrdinals > ordinals of pods, if delete item of reserveOrdinals, don`t create pods.
    
**How to reproduce it (as minimally and precisely as possible)**:
    for example

     step1: create a statefulset with 3 replicas ---> [pod-0, pod-1, pod-2]
     step2: update statefulset.Spec.ReserveOrdinals to [3, 4, 5]
     step3: update statefulset.Spec.ReserveOrdinals to [4, 5]

     After the above operation， the pods will become [pod-0, pod-1, pod-2, pod-3], but Spec.Replicas is 3.
    
     

**Anything else we need to know?**:

**Environment**:
- Kruise version: v0.9.0
- Kubernetes version (use `kubectl version`): v1.19.3

**Comment by FillZpp** [comment]
@vegazmaoning I test it with Kruise v0.9.0 and it did not create pod-3 when modified `reserveOrdinals` from [3, 4, 5] to [4, 5].

**Comment by FillZpp** [comment]
Can you paste your statefulset yaml and kruise-manager image?

**Comment by vegazmaoning** [comment]
> @vegazmaoning I test it with Kruise v0.9.0 and it did not create pod-3 when modified `reserveOrdinals` from [3, 4, 5] to [4, 5].

@FillZpp Sorry, I provided the wrong version， I was uesd v0.7.0, v0.7.0 had this problem, look like caused by [replicaCount](https://github.com/openkruise/kruise/blob/release-0.7/pkg/controller/statefulset/stateful_set_control.go#L317) define.  I had test with 0.9.0, without this problem. I will upgrade the version of kruise, thanks.
