### ISSUE TITLE
[feature request] Support kubectl rollout restart/history/undo/status for cloneset

### ISSUE THREAD

**Issue by wgitg** [openkruise/kruise#753]
**What would you like to be added**:
Support kubectl rollout restart/history/undo/status for cloneset

**Why is this needed**:
We have advertised that CloneSet is a enhanced version of k8s deployment in the org. We are expecting the enhancement with the assumption that we can operate the cloneset similar way as we operate other k8s native resources, such as deployment, daemonset, etc. However, this is not the case. CloneSet rollout operations are not supported in kubectl and users can not really treat the operations transparently like other K8s resources which causes the communication cost and can hinder the adoption

**Comment by FillZpp** [comment]
It is supported in https://github.com/openkruise/kruise-tools

Currently you can download this project and build the `kubectl-kruise` on your machine.

/unassign @jian-he

**Comment by wgitg** [comment]
@FillZpp Thanks for the information very much! So it is expected for users to use kubectl-kruise entirely? 

Our customers are just about to getting used to kubectl, yet now we are introducing another CLI seems a little bit too much.. so Is there some way to add the plugin seamlessly to the kubectl so that users does not need to switch to kubectl-kruise?

**Comment by FillZpp** [comment]
kubectl-kruise is the plugin of kubectl. After you put it in the PATH of your system, you can execute

```bash
$ kubectl kruise rollout ...
```

which is equal to

```bash
$ kubectl-kruise rollout ...
```

You can read the introduction of kubectl plugins: https://kubernetes.io/zh/docs/tasks/extend-kubectl/kubectl-plugins/#%E5%AE%89%E8%A3%85-kubectl-%E6%8F%92%E4%BB%B6

**Comment by wgitg** [comment]
Gotcha!   `kubectl kruise rollout` may work better in UX than asking users to use kubectl-kruise. Will see if our customers/SREs will complain about it :)

Cloing the ticket for now. Thanks @FillZpp

**Comment by FillZpp** [comment]
> Is there other way to make the regular kubectl rollout UX work for openkruise resources?

Kubectl can't do this by itself, unless you hack its code to support Kruise resources.
