### ISSUE TITLE
Add Changelog and release plan of project

### ISSUE THREAD

**Issue by xiang90** [openkruise/kruise#76]
We need to have changelog after the initial release of the project.

**Comment by allencloud** [comment]
I will try to finish this. While I think we should first nail down the release plan of kruise. Here are some thoughts of mine:

* follow the version rule on the basis of SemVer. Briefly speaking, we follow version number of MAJOR.MINOR.PATCH, such as 0.2.1, 1.1.3. For more details, please refer to [SemVer](http://semver.org/)；
* settle down that 1.0.0 is the GA version, PATH of MAJOR.MINOR.PATCH increment means a patch version; MINOR increment means a feature or architecture change version; MAJOR increment means GA, huge change or direction change, some big change or big milestone.
* Before official release, we could introduce rc(release candidate) version rule, for example, 0.1.0-rc; for several rc version, we can add the rc version number, like 0.1.0-rc1, 0.2.0-rc4. 
* In addition, we usually do not take PATCH rc version, 0.1.2-rc will never appear, while for MINOR and MAJOR version we must follow rc version.

/cc @FillZpp @Fei-Guo @jian-he @xiang90 WDYT?

**Comment by jian-he** [comment]
above looks good to me. what should we include in the release artifacts,
1. code tar ball , 2. docker image ?

**Comment by FillZpp** [comment]
We do have a [CHANGELOG](https://github.com/openkruise/kruise/blob/master/CHANGELOG.md) now :)
