### ISSUE TITLE
[feature request] Does SidecarSet support injecting annotations and labels to Pod?

### ISSUE THREAD

**Issue by veophi** [openkruise/kruise#764]
**What would you like to be added**:
SidecarSet inject annotations/labels to pods.

**Why is this needed**:
Some customized k8s systems configure their extended abilities via annotations/labels (e.g., configure kernel parameters in kubelet/containerd), some of which may work only when scheduling pods.  Thus, I think sidecarset should support injecting annotations/labels so as to satisfy these needs.

**Comment by zmberg** [comment]
https://github.com/openkruise/kruise/pull/993
