### ISSUE TITLE
[feature request] Support SidecarSet update strategy when pod recreate or inject

### ISSUE THREAD

**Issue by a630140621** [openkruise/kruise#783]
**What would you like to be added**:

Support SidecarSet update strategy when pod recreate or inject

**Why is this needed**:

There are two teams under one organizational structure. Team A maintain SidecarSet. Team B maintain Application which can use Deployment.

Team A inject SidecarSet to Pod which may controlled by Team B. Now, Team A want to update SidecarSet to new version. They use a partition update strategy.

At the same time, Team B want to release a new application version which may fix an emergency bug. Unfortunately, SidecarSet is all new version now.

So, I want to apply update strategy when pod inject.

**Comment by zmberg** [comment]
https://github.com/openkruise/kruise/pull/1021
