### ISSUE TITLE
Values.daemon.log.level [BUG]

### ISSUE THREAD

**Issue by shker-tt** [openkruise/kruise#790]
**What happened**:

https://github.com/openkruise/kruise/blob/9a0879c43f29f314c71cee2a6d6239b5b335fcc4/charts/kruise/v0.10.0/templates/manager.yaml#L153

https://github.com/openkruise/kruise/blob/9a0879c43f29f314c71cee2a6d6239b5b335fcc4/charts/kruise/v0.10.0/values.yaml#L52

这个配置好像漏了

**What you expected to happen**:
`- --v={{ .Values.daemon.log.level }}`

**Comment by FillZpp** [comment]
@shkerh Em... My mistake. Would you mind fixing it [here](https://github.com/openkruise/charts/blob/master/charts/kruise/templates/manager.yaml#L155), because the charts in this repo has been moved to `openkruise/charts` repo. Or I will fix it in the next release.

**Comment by shkerh** [comment]
你改吧

**Comment by FillZpp** [comment]
solved
