### ISSUE TITLE
[BUG] webhook configuration caBundle gets updated automatically in 0.9.0

### ISSUE THREAD

**Issue by dragondscv** [openkruise/kruise#803]
**What happened**:
When we upgrade kruise-manager from 0.6.1 to 0.9.0, we found that caBundles in validatingwebhookconfiguration and mutatingwebhookconfiguration are updated automatically from the default value `Cg==`. It seems kruise-manager generates new certs automatically if the caBundle is not valid? Is that expected behavior?

**What you expected to happen**:
The default value `Cg==` of caBundle is updated automatically after deploying kruise-manager 0.9.0.

**How to reproduce it (as minimally and precisely as possible)**:
1. Deploy kruise-manager 0.6.1.
2. Make sure validatingwebhookconfiguration and mutatingwebhookconfiguration uses default value `Cg==` for `caBundle`.
3. Deploy kruise-manager 0.9.0. The `caBundle` in webhook configurations will be updated automatically to some other value.

**Anything else we need to know?**:

**Environment**:
- Kruise version: 0.9.0
- Kubernetes version (use `kubectl version`): 1.17
- OS (e.g: `cat /etc/os-release`): CentOS 7
- Kernel (e.g. `uname -a`): 4.19.59
- Install tools: kubectl
- Others:

**Comment by FillZpp** [comment]
> How to reproduce it (as minimally and precisely as possible):
> 1. Deploy kruise-manager 0.6.1.
> 2. Make sure validatingwebhookconfiguration and mutatingwebhookconfiguration uses default value Cg== for caBundle.

@dragondscv I'm not sure if I understand your point. The `caBundle` in helm chart defaults to `Cg==`. But after you deployed v0.6.1, kruise-manager should update it to a real generated cert.

**Comment by dragondscv** [comment]
That's what confuses me. I deployed 0.6.1 and the default `caBundle`(`Cg==`) was not updated, while 0.9.0 did update it. So I guess update `caBundle` to a cert generated by kruise-manager is the expected behavior then.

**Comment by FillZpp** [comment]
> So I guess update caBundle to a cert generated by kruise-manager is the expected behavior then.

Yes, it is the expected behavior. Although I still not figure out why your 0.6.1 didn't update the `caBundle`.
