### ISSUE TITLE
[feature request] Add support for CRI-O

### ISSUE THREAD

**Issue by HudsonWu** [openkruise/kruise#804]
**What would you like to be added**:
希望增加对CRI-O运行时的支持

我使用的OKD搭建的k8s集群，部署时，kruise-daemon无法正常启动，原因是进程没有正常获取CRI-O的socket文件，crio的socket文件为/var/run/crio/crio.sock，我看到代码中有定义pouch、docker、containerd这三个容器运行时的socket路径，但没有CRI-O的，希望能支持

**Why is this needed**:
CRI-O同样是一个流行的容器运行时实现，很多集群搭建时都用的CRI-O，比如redhat发布的k8s发行版 - OKD，使用的是CRI-O

**Comment by zmberg** [comment]
@HudsonWu good，如果方便的话，你可以提一个pr，我们来合入

**Comment by FillZpp** [comment]
> 我看到代码中有定义pouch、docker、containerd这三个容器运行时的socket路径，但没有CRI-O的，希望能支持

这个提的很好。过去之所以特定 pouch、docker、containerd 这三种 Runtime，是为了 pull image 的时候上报 progress（拉取的进度）。但是 CRI 通用接口里拉镜像并没有返回 progress，因此是识别并采用 pouch、docker、containerd 他们自己的 client sdk 来拉取的。

不过目前看来，用户在实际使用 imagepulljob 的时候几乎没有查询 nodeimage 拉取进度的需求，因此在 kruise-daemon 中应该可以让不属于 pouch、docker、containerd 这三种的 Runtime（比如 CRI-O）直接使用 CRI 拉取镜像，这样就不受限于用户所使用的 Runtime 类型了。

这个改动可能稍微有点大，如果你有兴趣非常欢迎共建，如果不方便的话，我稍后会在下个版本中支持。 @HudsonWu WDYT？

**Comment by HudsonWu** [comment]
感谢关注，已经提了一个PR，当前还没有完全熟悉代码，可能有些不成熟的地方
