### ISSUE TITLE
kueb-apiserver出现错误：ERROR $root.definitions.io.kruise.apps.... has invalid property: anyOf

### ISSUE THREAD

**Issue by LiYiPeng-1** [openkruise/kruise#810]
当我使用openkruise的时候，升级k8s版本后kube-apiserver出现这样的错误：
k8s版本v1.14.7升级到v1.17.2
openkruise版本：kruise-0.10.0
请问是什么原因，非常感谢

11月 16 10:44:56 node982 kube-apiserver[4614]: ERROR $root.definitions.io.kruise.apps.v1alpha1.UnitedDeployment.properties.spec.properties.template.properties.cloneSetTemplate.properties.spec.properties.updateStrategy.properties.maxSurge has invalid property: anyOf
11月 16 10:44:56 node982 kube-apiserver[4614]: ERROR $root.definitions.io.kruise.apps.v1alpha1.UnitedDeployment.properties.spec.properties.template.properties.cloneSetTemplate.properties.spec.properties.updateStrategy.properties.maxUnavailable has invalid property: anyOf
11月 16 10:44:56 node982 kube-apiserver[4614]: ERROR $root.definitions.io.kruise.apps.v1alpha1.UnitedDeployment.properties.spec.properties.template.properties.cloneSetTemplate.properties.spec.properties.updateStrategy.properties.partition has invalid property: anyOf
11月 16 10:44:56 node982 kube-apiserver[4614]: ERROR $root.definitions.io.kruise.apps.v1alpha1.UnitedDeployment.properties.spec.properties.topology.properties.subsets.items.<array>.properties.replicas has invalid property: anyOf
11月 16 10:44:56 node982 kube-apiserver[4614]: E1116 10:44:56.665183    4614 customresource_handler.go:655] error building openapi models for imagepulljobs.apps.kruise.io: ERROR $root.definitions.io.kruise.apps.v1alpha1.ImagePullJob.properties.spec.properties.parallelism has invalid property: anyOf
11月 16 10:52:27 node982 kube-apiserver[4614]: E1116 10:52:27.767489    4614 customresource_handler.go:655] error building openapi models for clonesets.apps.kruise.io: ERROR $root.definitions.io.kruise.apps.v1alpha1.CloneSet.properties.spec.properties.updateStrategy.properties.maxSurge has invalid property: anyOf
11月 16 10:52:27 node982 kube-apiserver[4614]: ERROR $root.definitions.io.kruise.apps.v1alpha1.CloneSet.properties.spec.properties.updateStrategy.properties.maxUnavailable has invalid property: anyOf
11月 16 10:52:27 node982 kube-apiserver[4614]: ERROR $root.definitions.io.kruise.apps.v1alpha1.CloneSet.properties.spec.properties.updateStrategy.properties.partition has invalid property: anyOf

**Comment by FillZpp** [comment]
@LiYiPeng-1 It seems to be a bug in kube-apiserver and has been fixed in 1.21.0 https://github.com/kubernetes/kubernetes/issues/90902

**Comment by LiYiPeng-1** [comment]
多谢你的回复 @FillZpp
