### ISSUE TITLE
[feature request] UnitedDeployment support patch workload by subset

### ISSUE THREAD

**Issue by wehug** [openkruise/kruise#811]
**What would you like to be added**:
In UnitedDeployment, allow subset patch workload template, can customize the workload by subset.

**Why is this needed**:
We need manage multiple deployment or statefulset, most of their configurations are the same, but some environment variables or image is different, so UnitedDeployment need patch workload feature by subset.

**Comment by fengshunli** [comment]
Can be assigned to me to complete this requirement together @wxyh

**Comment by furykerry** [comment]
> Can be assigned to me to complete this requirement together @wxyh

fsl, thanks for your effort. But a  new LFX mentorship project had been created for this issue last week , and some students overseas has already apply for this project. I think you can work on other issues

**Comment by alexr018350** [comment]
@furykerry 

Hello mentor, 

I am interested in the UnitedDeployment feature of the CNCF OpenKruise project for the LFX mentorship program. I would like to work on adding a feature that allows for patching workload templates by subset, which will enable customization of workloads for different environments.

What else do I need to submit along with my resume and cover letter?

**Comment by xuyangwang0825** [comment]
Hi @furykerry,
May I ask if I'm not receiving any notifications means that I'm not selected for the project? My status on the LFX portal still shows as pending.

**Comment by furykerry** [comment]
> Hi @furykerry, May I ask if I'm not receiving any notifications means that I'm not selected for the project? My status on the LFX portal still shows as pending.

yes, the mentee are ready selected. thanks for your application, there is many open issue in the community, we welcome any contribution if you're interested
