### ISSUE TITLE
[feature request] refactor transferEnv in sidecarset 

### ISSUE THREAD

**Issue by pigletfly** [openkruise/kruise#818]
**What would you like to be added**:

https://github.com/openkruise/kruise/blob/679714ffe3c7cf7c2a00cec0daec5b91c0e65efe/apis/apps/v1alpha1/sidecarset_types.go#L100-L103

refactor tranferEnv into 

```
type TransferEnvVar struct {
	SourceContainerName string `json:"sourceContainerName,omitempty"`
	SourceContainerIndex int32 `json:"sourceContainerIndex,omitempty"`
	EnvName             []string `json:"envName,omitempty"`
}
```

**Why is this needed**:

1. if one want transfer many envs from a same container,`sourceContainerName` seems a little redundant
2. if selector in the sidecarset matches multiple pods from different application which have different container name, then `sourceContainerName` can't locate the right container.So I want to introduce `sourceContainerIndex` to make this work.We can put biz container in the first position,then set setcarset `podInjectPolicy` to `AfterAppContainer`,now we may have a stable containers position,so that it's possible to transfer env from container in a specific index.

**Comment by pigletfly** [comment]
@FillZpp

**Comment by FillZpp** [comment]
> if one want transfer many envs from a same container,sourceContainerName seems a little redundant

I think this is reasonable. We can define an env list for a source container.

> if selector in the sidecarset matches multiple pods from different application which have different container name, then sourceContainerName can't locate the right container

I don't think so. If the container names are different for multiple applications, how could you ensure they have the same container indexes? (Generally, different applications may have different containers in their workloads)

WDYT? @zmberg

**Comment by pigletfly** [comment]
> 

yes, if end users maintain their own workloads manifests,the container index  may be unstable,but if end users can't decide the container index,the manifests are generate by platform,we could have a stable container indexes.

**Comment by FillZpp** [comment]
> but if end users can't decide the container index,the manifests are generate by platform,we could have a stable container indexes.

If the manifests are generated by platform, why not give them the same container name, such main or app?

**Comment by zmberg** [comment]
@FillZpp Is it possible to add a field **containerDownwardAPI** to get the containerName from pod annotations or labels

**Comment by FillZpp** [comment]
> @FillZpp Is it possible to add a field **containerDownwardAPI** to get the containerName from pod annotations or labels?

Good idea. How about:

```
type TransferEnvVar struct {
	SourceContainerName     string `json:"sourceContainerName,omitempty"`
	SourceContainerNameFrom *SourceContainerNameSource `json:"sourceContainerNameFrom,omitempty"`
	EnvName                 string `json:"envName,omitempty"`
        EnvNames                string `json:"envNames,omitempty"`
}
```

`EnvNames` could also be `EnvNameList`

**Comment by pigletfly** [comment]
> > @FillZpp Is it possible to add a field **containerDownwardAPI** to get the containerName from pod annotations or labels?
> 
> Good idea. How about:
> 
> ```
> type TransferEnvVar struct {
> 	SourceContainerName     string `json:"sourceContainerName,omitempty"`
> 	SourceContainerNameFrom *SourceContainerNameSource `json:"sourceContainerNameFrom,omitempty"`
> 	EnvName                 string `json:"envName,omitempty"`
>         EnvNames                string `json:"envNames,omitempty"`
> }
> ```
> 
> `EnvNames` could also be `EnvNameList`

EnvNames should be []string ? EnvName is used for backward compatibility ?

**Comment by FillZpp** [comment]
> EnvNames should be []string ? EnvName is used for backward compatibility ?

Yeh, fixed.

**Comment by pigletfly** [comment]
and sourceContainerNameFrom should be 
```
type EnvVarSource struct {
	// Selects a field of the pod: supports metadata.name, `metadata.labels['<KEY>']`, `metadata.annotations['<KEY>']`,
	// +optional
	FieldRef *ObjectFieldSelector `json:"fieldRef,omitempty" protobuf:"bytes,1,opt,name=fieldRef"`
}
```


ref: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/types.go#L2008

**Comment by pigletfly** [comment]
I'd like to send a draft PR.
