### ISSUE TITLE
[BUG]Sidecarset status is incorrect when UpdateStrategy type is NotUpdate

### ISSUE THREAD

**Issue by andrewshaoyu** [openkruise/kruise#825]
**What happened**:
Sidecarset status Ready Pods is incorrect,when Sidecarset UpdateStrategy type is NotUpdateSidecarSetStrategyType.
Only update Sidecarset status when sidecarset is updated or new Pod create.
**What you expected to happen**:
when pods update trigger sidecarset reconcile, then update sidecarset status.
**How to reproduce it (as minimally and precisely as possible)**:
https://github.com/openkruise/kruise/blob/b465e29452f3b1432b3a348c129e670591d8c798/pkg/controller/sidecarset/sidecarset_pod_event_handler.go#L68-L83

I find that pods update event will trigger sidecarset reconcile ,but when sidecarset UpdateStrategy type is NotUpdateSidecarSetStrategyType, it will be ignored.

Is this by design?

**Environment**:
- Kruise version:
v.0.10.0

**Comment by FillZpp** [comment]
> I find that pods update event will trigger sidecarset reconcile ,but when sidecarset UpdateStrategy type is NotUpdateSidecarSetStrategyType, it will be ignored.

Yep, it seems to be a bug that `readyPods` might not be updated in this case. PTAL @zmberg

**Comment by zmberg** [comment]
@andrewshaoyu thanks, you are right. Do you have time to fix this bug?

**Comment by andrewshaoyu** [comment]
> @andrewshaoyu thanks, you are right. Do you have time to fix this bug?

Ok, I can try.
