### ISSUE TITLE
[feature request] sidecarSet can support mosn hotUpgrade?

### ISSUE THREAD

**Issue by Cole-GG** [openkruise/kruise#827]
I want to use openKurise to host the mosn sidercar container, but I encountered a port conflict when debugging the hot upgrade. How should I resolve it?

**Comment by zmberg** [comment]
This requires mosn students for compatibility, adaptation. So you can submit an issue on Github of mosn

**Comment by FillZpp** [comment]
@Cole-GG MOSN has provided [a blog for this](https://mosn.io/blog/posts/mosn-sidecarset-hotupgrade/).

/close
