### ISSUE TITLE
[feature request]Specify which controllers can be started by openkruise

### ISSUE THREAD

**Issue by compactcfusr** [openkruise/kruise#849]
**What would you like to be added**:
We'd like to specify which controllers can be started.

**Why is this needed**:
We only use CloneSet and want to disable other controllers, just like the kube-controller-manager does. Because we don’t want to expose redundant functions.

What do I want to ask for help?
Could you please help to give me a solution to this issue?Thanks very much.
Of course，it is the best to plan this feature to openkruise.

**Comment by veophi** [comment]
An Interim approach: ensure that only the CRDs you needs are installed before installing kruise-controller-manager

**Comment by compactcfusr** [comment]
> An Interim approach: ensure that only the CRDs you need are installed before installing kruise-controller-manager

Sorry, it's not particularly clear. Can you please suggest to CRDs and controllers?

**Comment by compactcfusr** [comment]
> An Interim approach: ensure that only the CRDs you need are installed before installing kruise-controller-manager

In fact, I also do this now, but I have three ideas: 
(1) crop CRDs
(2) crop controllers
(3) crop both.

Could you please give any suggestions?Thks.

**Comment by veophi** [comment]
> 

If you **do not** install a CRD, its corresponding controller **will not** be enabled as well (i.e., it will not be added to kruise-controller-manager when starting).

Maybe you can specify your case in detail if this approach cannot satisfy your requirements.

**Comment by compactcfusr** [comment]
Let's discuss this use case.
**In my case, I'd like to relieve performence pressure.**According to source code, different controllers will list-watch different resource.I'd like to crop the controller as thin as possible so that ensure openkruise can list-watch the least resource. 

**My necessary CRDs are just CloneSet and CRR**.But I found it will go wrong if NodeImage and ImagePullJob is not installed. At last, **I decide to maintain 4 CRDs and controllers: CloneSet and CRR,NodeImage and ImagePullJob.**

I tried just croping CRDs but found other controllers not work but some of their resource(e.g. job) is still watched.I found the unsure answer and it maybe kubebuilder's problem.So I gave up this way.

**Then I tried just croping controllers by supporting parameter "--controllers" like kube-controller-manager.It's a not bad solution and seems working well.**I almost apply it. But in this solution, it is strange that other CRDs can be created and not work because all CRDs is installed.I'd like to find the better way to slove it.

I'm think whether should I crop CRDs and controllers both.Or some other better way. Can you  give me some good suggestion or idea, friends?

**Comment by FillZpp** [comment]
> I tried just croping CRDs but found other controllers not work but some of their resource(e.g. job) is still watched.

Have you restarted or recreated kruise-manager pods after croping CRDs?

**Comment by compactcfusr** [comment]
> Have you restarted or recreated kruise-manager pods after croping CRDs?

In croping CRDs way, I don't install unnecessary CRDs by installing openkruise with a manifest without unnecessary CRDs

**Comment by FillZpp** [comment]
> In croping CRDs way, I don't install unnecessary CRDs by installing openkruise with a manifest without unnecessary CRDs

If so, the reason for you found job is still watched is that [we always register index for it](https://github.com/openkruise/kruise/blob/master/pkg/util/fieldindex/register.go#L103), not the kubebuilder's problem. So even if you disable some controllers, it will still be watched.

So you might have to update the file above, do not register index for job if AdvancedCronJob is not installed.

**Comment by compactcfusr** [comment]
> > In croping CRDs way, I don't install unnecessary CRDs by installing openkruise with a manifest without unnecessary CRDs
> 
> If so, the reason for you found job is still watched is that [we always register index for it](https://github.com/openkruise/kruise/blob/master/pkg/util/fieldindex/register.go#L103), not the kubebuilder's problem. So even if you disable some controllers, it will still be watched.
> 
> So you might have to update the file above, do not register index for job if AdvancedCronJob is not installed.

It looks like reasonable and I'll try it by not updating this file's code later.Thanks a lot.

**Comment by FillZpp** [comment]
@compactcfusr Thanks. Also we are considering to provide a helm flag to let users disable some CRDs during install or upgrade Kruise. So that you have no need to corp them manually. We are glad to see you and talk about this in next bi-weekly meeting.

**Comment by FillZpp** [comment]
@compactcfusr Hey, robot, we are going to discuss this issue at the community meeting this week https://shimo.im/docs/gXqmeQOYBehZ4vqo . Would you like to join it? (If you can speak Chinese)

**Comment by compactcfusr** [comment]
> https://shimo.im/docs/gXqmeQOYBehZ4vqo
haha,I can speak Chinese.I'll try my best to join the community meeting this week if I have time.

**Comment by zmberg** [comment]
https://github.com/openkruise/kruise/issues/697
