### ISSUE TITLE
[feature request] multiple runtime socket paths for kruise-daemon

### ISSUE THREAD

**Issue by vikas027** [openkruise/kruise#851]
**What would you like to be added**:
I use Bottlerocket on my EKS nodes which use `containerd`, it would be great to have the support for the same.

**Why is this needed**:
Docker is deprecated now :)

**Comment by FillZpp** [comment]
@vikas027 Thanks for your feedback, but Kruise does support `containerd`. What problem did you encounter?

Note that kruise-daemon mounts the `/var/run` node path by default to find the runtime socket, including:
```
/var/run/docker.sock
/var/run/dockershim.sock
/var/run/containerd.sock
/var/run/containerd/containerd.sock
```

If your containerd socket is in some special path, please set the [helm chart parameter](https://openkruise.io/docs/installation#optional-chart-parameters) `daemon.socketLocation` when you install Kruise. Here is [the example for k3s](https://openkruise.io/docs/installation#installation-parameters-for-k3s), you might need to check the runtime path on your nodes.

**Comment by vikas027** [comment]
Oh nice, I may have missed it. What is the recommended way if I have a mix of instances using both _dockerd_ and _containerd_?

**Comment by FillZpp** [comment]
> What is the recommended way if I have a mix of instances using both dockerd and containerd?

Usually we just have to set `daemon.socketLocation` to the directory path of the dockerd and containerd sockets. For example the path is `/var/run/xxx/`, then kruise-daemon will search sockert files with path `/var/run/xxx/docker.sock`, `/var/run/xxx/containerd.sock`, `/var/run/xxx/containerd/containerd.sock`.

So if the dockerd and containerd you are using on different nodes have the same socket directory, that will be fine. Kruise-daemon on node with docker will find the docker socket. So does the kruise-daemon on node with containerd.

But if the dockerd and containerd have different socket directory, that would be a problem.

**Comment by vikas027** [comment]
> But if the dockerd and containerd have different socket directory, that would be a problem.

Yeah, I think this is exactly what has happened in my case. Can this be taken as a feature request i.e. one can optionally specify the paths of the sockets?

**Comment by FillZpp** [comment]
> Can this be taken as a feature request i.e. one can optionally specify the paths of the sockets?

It can be, which means multiple node paths will be mounted in kruise-daemon pod and it will find the socket in those paths.

/retitle [feature request] multiple runtime socket paths for kruise-daemon

> Can the workaround for now be to have two sets of daemonsets, one for containerd and one for dockerd?

You can do this, although it is a little hard. You may take the steps:
1. Install Kruise with `daemon.affinity` to only deploy kruise-daemon on the nodes with dockerd.
2. Create a daemonset manually to deploy kruise-daemon on the nodes with containerd, which should have affinity to containerd and mount path to containerd socket path.

Then if you want to upgrade Kruise to next version that supports multiple runtime socket paths in the future, you have to firstly delete the containerd daemonset you created manually, then use `helm upgrade`, reset `daemon.affinity` to all nodes and set the new runtime paths parameter.

**Comment by vikas027** [comment]
Thanks, @FillZpp 

I think I can automate the process 😃 I will give it a go and let you know.

**Comment by vikas027** [comment]
Hey @FillZpp ,
I have realized (actually recalled) that Bottlerocket does not let us mount the `containerd` socket as `hostPath`. AFAIK, we don't have any option. I had hit the same issue while using GitHub Actions too.
