### ISSUE TITLE
[feature request] - add nodeSelector for deamonset as well

### ISSUE THREAD

**Issue by vikas027** [openkruise/kruise#856]
**What would you like to be added**:
It would be great to have `daemon.nodeSelector` just like we have `manager.nodeSelector`

**Why is this needed**:
If we don't have this, then the `daemonset` creates a `pod` on `containerd` instances (like bottlerocket) and fails. Bottlerocket does not expose `containerd` socket as a `hostPath`

**Comment by FillZpp** [comment]
Actually, you can use `daemon.affinity` to configure the node affinity, which is more flexible than `nodeSelector`.

**Comment by vikas027** [comment]
I agree affinity is better but sometimes you just need something simple, having an option wouldn't be a bad idea IMHO.

**Comment by FillZpp** [comment]
closed by https://github.com/openkruise/charts/pull/7
