### ISSUE TITLE
[feature request]show current working container in sidecarset

### ISSUE THREAD

**Issue by pigletfly** [openkruise/kruise#857]
**What would you like to be added**:

add current working container in sidecarset status,so that we can find working container in sidecarset.Otherwise, we have to find it in corresponding pod's annotations.

**Why is this needed**:

**Comment by FillZpp** [comment]
I'm not sure. What do you mean *working container*?

**Comment by pigletfly** [comment]
If use HotUpgrade feature,then sidecar container name will switch between sidecarContainerName-1 and sidecarContainerName-2.Although we can get working-hotupgrade-container from Pod annotation `kruise.io/sidecarset-working-hotupgrade-container`, but it's not convenient.

**Comment by zmberg** [comment]
This is not fixed, the pod working container under a sidecarset is very likely to be different, and sidecar-1 and sidecar-2 exist at the same time, e.g., in the middle of expansion, rebuild, etc.

**Comment by FillZpp** [comment]
@pigletfly Welcome to join us in the community meeting this week https://shimo.im/docs/gXqmeQOYBehZ4vqo , we can have some discussion on it.

**Comment by pigletfly** [comment]
sure,I'd love to have some discussion with the community.
