### ISSUE TITLE
[feature request] - Allow multiple images in ImagePullJob

### ISSUE THREAD

**Issue by vikas027** [openkruise/kruise#858]
**What would you like to be added**:
It will be great to have multiple images in [ImagePullJob](https://openkruise.io/docs/user-manuals/imagepulljob). Maybe it can be a comma separate string.

**Why is this needed**:
It will help to reduce the number of manifests.

**Comment by FillZpp** [comment]
@vikas027 Yeah, some users of Kruise used to mention it too. But it is a little hard to implement. Are you willing to do this? Or you may ask if @hantmac is still interested in this.

**Comment by vikas027** [comment]
I can definitely try to have a look as time permits, totally swamped up these days :) I hope to get some free time in the new year.

**Comment by vikas027** [comment]
I can definitely try to have a look as time permits, totally swamped up these days :) I hope to get some free time in the new year.

**Comment by hantmac** [comment]
Same as i thought,  and I will hava a look these days.
