### ISSUE TITLE
[feature request] - Allow annotation on service account for IRSA

### ISSUE THREAD

**Issue by vikas027** [openkruise/kruise#859]
**What would you like to be added**:
I would like to have annotation to be added on the service account to be used on EKS [IRSA](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html)

**Why is this needed**:
To give permission to the service account to pull images from ECR

**Comment by FillZpp** [comment]
@vikas027 I'm not sure. Do you need a chart variable to customize your own annotations to be applied on the kruise service account?

**Comment by vikas027** [comment]
Yeah, a map for `annotations` just like `tolerations` would be awesome.

**Comment by FillZpp** [comment]
closed by https://github.com/openkruise/charts/pull/7
