### ISSUE TITLE
ImagePullJob Support ECR (STS tokens) Repositories

### ISSUE THREAD

**Issue by vikas027** [openkruise/kruise#866]
**What would you like to be added**:
I am trying to use an ECR Image in  PumagePullJob which fails with these errors

```
kruise-daemon-czjtm daemon W1225 08:08:02.435660       1 imagepuller_worker.go:328] Worker failed to pull image 111111111111.dkr.ecr.ap-southeast-2.amazonaws.com/traefik:v2.5.3, cost 15.097071799s, err: Error response from daemon: Head "https://111111111111.dkr.ecr.us-east-1.amazonaws.com/v2/traefik/manifests/v2.5.3": no basic auth credentials
```

My EKS nodes have IAM Roles configured to pull images from the ECR repositories, it looks like the go library(ies) is unable to use AWS STS tokens.

**Why is this needed**:
The workaround is to have a kubernetes docker secret with the token and then keep on renewing it, but it would be better to use the IAM roles and use STS tokens (just like native EKS workloads)

**Comment by FillZpp** [comment]
IMHO, Kruise should not care about cloud providers. It just works on pure Kubernetes API.

> The workaround is to have a kubernetes docker secret with the token and then keep on renewing it

I think EKS should the ability to manage and renew the secret for its users.

**Comment by vikas027** [comment]
> I think EKS should the ability to manage and renew the secret for its users.

Workloads on EKS does not need secrets by default, they just work as long as the nodes have proper IAM policies. EKS already takes care of the same i.e. whenever we have a docker image (like `111111111111.dkr.ecr.ap-southeast-2.amazonaws.com/traefik:v2.5.3`), nodes can pull the docker image without worrying about the repository/registry authentication. My idea was to use the same/similar logic in Kruise too, it is just a good customer experience IMHO.

As I said earlier, I already have created a workaround which is to populate and renew the secret at regular intervals.

**Comment by FillZpp** [comment]
> nodes can pull the docker image without worrying about the repository/registry authentication

I'm not sure how it works... Maybe they have modified the code of EKS kubelet, which can pull images from ECR with IAM Roles configured somewhere. Does it have some documentations of this?

**Comment by abatilo** [comment]
Hi all. Is there something that I can do to help push this along?

**Comment by furykerry** [comment]
> Hi all. Is there something that I can do to help push this along?

Can you help us identify how EKS inject tokens into the pod? For example , can you check created pod yaml and check if pull secrets are injected by some webhook automatically.

**Comment by abatilo** [comment]
@furykerry I can definitely help with that!

The native way that EKS supports pod identity is with a feature that they call [IAM roles for service accounts](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html). The way this works is that you add an annotation to a `kind: ServiceAccount`, then use that `kind: ServiceAccount` on the pod spec.

The EKS control plane then implements the webhook injection with this [aws/amazon-eks-pod-identity](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) project, which will inject a `kind: Secret` with the `kind: ServiceAccount` token, and will inject environment variables into the pod spec.

All AWS SDKs for every programming language looks to see if certain environment variables exist, and if they do, they will use the service account token and the identity of the pod to fetch AWS credentials which can then be used to call the AWS API.

Please let me know if any part of that doesn't make sense!

**Comment by abatilo** [comment]
To anyone who comes across this topic, here's the terraform that I wrote to automate fetching an ECR token that OpenKruise can use for things like an `ImagePullJob`

https://gist.github.com/abatilo/d9234c85c420d08688fd353c591fef6d

**Comment by furykerry** [comment]
aliyun also have similar technology: 
https://help.aliyun.com/document_detail/159703.htm?spm=a2c4g.177224.0.0.50bb64f2XPn8yE#task-2456294

**Comment by zmberg** [comment]
This is GLCC project, and if you are student, you can apply for it in glcc.
