### ISSUE TITLE
[feature request] - remove default serviceAccount in kruise-controller-manager

### ISSUE THREAD

**Issue by vikas027** [openkruise/kruise#867]
**What would you like to be added**:
Create a ServiceAccount, and give it the required privileges and remove the dependency on the default ServiceAccount.

**Why is this needed**:
Here are a few references why we need it for security:-
- https://github.com/kubernetes/kubernetes/issues/57601
- https://hackersvanguard.com/abuse-kubernetes-with-the-automountserviceaccounttoken/
- https://docs.bridgecrew.io/docs/bc_k8s_38

**Comment by FillZpp** [comment]
closed by https://github.com/openkruise/charts/pull/7
