### ISSUE TITLE
LFX-Mentorship-Fall: StatefulSet support volume claim resize

### ISSUE THREAD

**Issue by tianzichenone** [openkruise/kruise#905]
**What would you like to be added**:
Auto resize PVC capacity when updating volume claim template in Advanced StatefulSet and CloneSet.

And should consider the following things:
- How to check StorageClass(CSI Driver) support resize capacity of PV?
- How to let users know whether the resize is successful?
- Should we rebuild Pod (and PVC) if the CSI Driver does not support resize PV (especially for CloneSet)? 
- Align with the design of upstream: https://github.com/kubernetes/enhancements/pull/3412

**Why is this needed**:
When we want to expand all PVCs of StatefulSet or CloneSet ， we should update PVCs manually.
When we update capacity in volume claim template, the newly created Pods will use updated capacity, but the old Pods not, this confusing the user.

**Comment by FillZpp** [comment]
@tianzichenone Thanks. If upstream is working on this https://github.com/kubernetes/enhancements/pull/2842 , we'd better wait for it and then rebase into Kruise, to make sure the behavior is consistent with upstream.

**Comment by y-ykcir** [comment]
@veophi @zmberg Hi, is this issue an LFX Mentorship Fall issue? I haven't seen any related links to this issue in [term3](https://github.com/cncf/mentoring/blob/main/programs/lfx-mentorship/2023/03-Sep-Nov/README.md)

**Comment by ABNER-1** [comment]
Please consider assigning this issue to me.

**Comment by ABNER-1** [comment]
A new proposal of upstream: https://github.com/kubernetes/enhancements/pull/4651
