### ISSUE TITLE
[BUG] Install into existing namespace

### ISSUE THREAD

**Issue by BryanDollery** [openkruise/kruise#913]
**What happened**:
I tried installing kruise into a pre-existing namespace and it failed with the following error

> Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: Namespace "platform" in namespace "" exists and 
> cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; 
> annotation validation error: missing key "meta.helm.sh/release-name": must be set to "openkruise"; annotation validation error: missing key "meta.helm.sh/release-
> namespace": must be set to "platform"

But, I don't want this namespace controlled by helm or kruise. I don't want every tool in its own namespace. I'm perfectly capable of testing my platform to confirm that there are no conflicts when tools share a namespace and it works for me. I have a namespace for all my platform tools, another for automation pipelines, and one for each bounded context -- I don't want dozens of tool-specific namespaces messing up my beautifully constructed architecture.

**What you expected to happen**:
I expected kruise to be installed in the specified namespace without complaint, just like all my other tools.

**How to reproduce it (as minimally and precisely as possible)**:
Create a namespace, install helm with the correct flags:
```
helm install openkruise openkruise/kruise --set installation.namespace=platform
```
(I also tried `helm install openkruise openkruise/kruise -n platform --set installation.namespace=platform`)

**Anything else we need to know?**:
I don't expect either kruise or helm to take ownership of a pre-existing namespace.

**Environment**:

- Kruise version:
1.0.1 (I think -- latest at time of writing anyway)

- Kubernetes version (use `kubectl version`):

> Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b4d7da0049ead870833a07a1c24ad5ad218fb36c", GitTreeState:"clean", BuildDate:"2022-02-01T10:32:31Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}

- Install details (e.g. helm install args):
- Others:

**Comment by FillZpp** [comment]
Emm... I thought a separate namespace might be easier for install and lower risk for uninstall. But it's fine, we can add a helm  parameter in the next release, to let user install Kruise in an existing namespace. @BryanDollery

**Comment by BryanDollery** [comment]
> Emm... I thought a separate namespace might be easier for install and lower risk for uninstall. But it's fine, we can add a helm parameter in the next release, to let user install Kruise in an existing namespace. @BryanDollery

You're probably right in most cases, but I'm special :) 

It would be a lot easier if K8S supported nested namespaces (and if it supported a globally accessible namespace too), but it doesn't so we have to live with what we've got. For now, I'm putting all my toys in one basket and trying to control namespace proliferation. Shared application services go in `platform` (things like kruise, mongo, kafka, etc.), logging and monitoring tools go into the `operations` namespace. And I have a separate namespace for each bounded context following the `ctx-*` naming convention. I find that this makes things pretty easy to find.

On the subject of uninstalling -- you're right of course, it's pretty easy to blow away a single namespace, but helm does a pretty good job of uninstalling the individual components, and your naming conventions (putting 'kruise' in everything) makes it easy to tidy up if that fails (especially using the `get-all` krew plugin with a bit of linux grep/sed magic).

And, ultimately, you don't have to reverse your decision, as you say, a flag to let engineers with a different model implement things their way and otherwise keep things your way would be perfect. Best of both worlds.

Thanks,
B

**Comment by FillZpp** [comment]
Supported in https://github.com/openkruise/charts/pull/14
