### ISSUE TITLE
[feature request]

### ISSUE THREAD

**Issue by YoghurtFree** [openkruise/kruise#914]
**What would you like to be added**:
当我通过给pod增加注解  “apps.kruise.io/container-launch-priority: Ordered” 来控制pod内多个容器启动顺序的时候，会创建一个{podname}-barrier的configmap，通过更新configmap里面的key，来实现多容器的顺序启动。但是每次创建一个带相关注解的pod，都会生成一个configmap，如果集群中需要ordered pod数量特别大情况下，会产生数量可观的无用configmap。我希望能在pod内容器按照顺序启动成功之后，删除configmap。

**Why is this needed**:
 只是因为控制pod内多容器的启动顺序，创建的configmap，容易给k8s运维造成误解。

**Comment by FillZpp** [comment]
@YoghurtFree 谢谢反馈。目前 configmap 设置的 owner 是 pod，因此 pod 删除后对应 configmap 也会被删除。但是当 pod 还在运行时，我们是不推荐删除 configmap 的，这会导致 pod 里容器如果发生重启（不管是 liveness 触发还是创建 CRR 主动触发）、原地升级等操作时，新容器无法拉起（因为 kubelet 找不到这个 configmap）。

**Comment by YoghurtFree** [comment]
> @YoghurtFree 谢谢反馈。目前 configmap 设置的 owner 是 pod，因此 pod 删除后对应 configmap 也会被删除。但是当 pod 还在运行时，我们是不推荐删除 configmap 的，这会导致 pod 里容器如果发生重启（不管是 liveness 触发还是创建 CRR 主动触发）、原地升级等操作时，新容器无法拉起（因为 kubelet 找不到这个 configmap）。

但是我用 openkruise 1.0.1版本测试的时候，创建ordered pod后，我手动删除{podname}-barrier 这些configmap，然后触发原地升级、kill进程强制容器重启等操作，都会重新创建{podname}-barrier 。我理解只要pod容器发生重启，都是pod的一个更新操作。是不是openkruise的controller里面已经处理了pod更新事件，然后重新创建的configmap.如果是这样的话，那么删除configmap没有任何影响啊。

**Comment by FillZpp** [comment]
那么删除 configmap 后，任意对 pod 的更新（包括 labels/annotations、spec、status）都会触发 controller 再创建出来 configmap。而这又引发一个新问题：再次创建出来之后，是不是要再次删除？从而会导致 configmap 处于频繁的创建、删除过程。这样其实是更坏的情况。

**Comment by YoghurtFree** [comment]
> 那么删除 configmap 后，任意对 pod 的更新（包括 labels/annotations、spec、status）都会触发 controller 再创建出来 configmap。而这又引发一个新问题：再次创建出来之后，是不是要再次删除？从而会导致 configmap 处于频繁的创建、删除过程。这样其实是更坏的情况。

确实是这个道理，其实是一个取舍吧。感谢！我关了这个issue。
