### ISSUE TITLE
[BUG] Percent partitions always round up causing no updates

### ISSUE THREAD

**Issue by perek** [openkruise/kruise#926]
**What happened**:
The use case I am wishing to model is allowing for deploying only 1 pod on the new revision and then removing that split. I would expect that setting a partition to 99% should effectively behave like the maxSurge in Deployment and default to at least 1 replica, it seems we round up tho, so we end up with no replicas.

**What you expected to happen**:
99% Partition
3 pods, expect 1 pod to get new revision

**How to reproduce it (as minimally and precisely as possible)**:
Make a cloneset with under 100 replicas
updateStrategy:
    maxSurge: 1
    maxUnavailable: 50%
    partition: 99%
    type: ReCreate

**Anything else we need to know?**:

**Environment**: 
- Kruise version: Latest
- Kubernetes version (use `kubectl version`):  v1.19.2
- Install details (e.g. helm install args): helm install kruise openkruise/kruise --version 1.0.1
- Others:

**Comment by perek** [comment]
https://go.dev/play/p/inrhAHw4v6q

**Comment by perek** [comment]
you can see the code causing this issue here https://github.com/openkruise/kruise/blob/11771e1d784e2206d4b69afdaee8c0e320dbeeab/vendor/k8s.io/apimachinery/pkg/util/intstr/intstr.go#L177

**Comment by perek** [comment]
it seems the old code we had a way to turn this off by setting maxSurge to 0, but in the latest version it is hard coded. I am not sure what other issues it would cause to swap this

**Comment by FillZpp** [comment]
> it seems we round up tho, so we end up with no replicas.

Yeah, we think it is more safe to make partition round up. If you upgrade a CloneSet with replicas=3 & partition=30%, and then Kruise upgrade all replicas to new version that may have problems.

> it seems the old code we had a way to turn this off by setting maxSurge to 0, but in the latest version it is hard coded.

No. `partition` is always round up. It is `maxUnavailable` that will be round down if maxSurge is not 0.

**Comment by perek** [comment]
I agree with that design choice overall, but there is no reliable way to test on a single pod afaik given this restriction. The issue I am having is that I desire to test a single pod on an auto scaled deployment. I cannot accurately define a single replica, for instance in Argo rollout if I set a weight of 1% I will always get at least one canary replica. Does that make sense? I feel like it should round up still, but min update of 1 replica is the weight is not 100% or == replicas count

**Comment by perek** [comment]
A good example of this is a 10 pod deployment

Partition of 90-99 update 1 replica
100 updates none
89 updates 2

**Comment by FillZpp** [comment]
> A good example of this is a 10 pod deployment
> Partition of 90-99 update 1 replica
> 100 updates none
> 89 updates 2

Then if partition is 0-9, it will upgrade all pods?

**Comment by perek** [comment]
That is an interesting question, I would say all of them. I believe in the deployment controller today if I put maxSurge 0 and maxUnavail 29% it will finish in 3 iterations not 4. I could also see the argument in the partition case that N-1 and 1 are special cases where they will sit on these numbers until reaching 0 and 100 respectively. Another solution would be to allow the partitions to count up rather than down as an option, I think most people think in how much of the New version they want rollout out, not how much of the old one they want remaining. What do you think about that? I could see the point in allowing either calculuation.
