### ISSUE TITLE
admission webhook "vsidecarset.kb.io" denied the request: [spec.volumes[0].name: Required value, spec.containers[0].volumeMounts[0].name: Not found: "log-volume"]

### ISSUE THREAD

**Issue by haobiaosheng** [openkruise/kruise#933]
**What happened**:
I follow the page:https://openkruise.io/zh/docs/user-manuals/sidecarset, to create a sidecar, but I meet a mistake：Error from server: error when creating "sidecarset.yaml": admission webhook "vsidecarset.kb.io" denied the request: [spec.volumes[0].name: Required value, spec.containers[0].volumeMounts[0].name: Not found: "log-volume"]. And I google this mistake, it said that this mistake has solved in issues list, but I install the latest Kruise version, and it still appear.

**Environment**:
- Kruise version:1.0.1
- Kubernetes version (use `kubectl version`): v1.23.3
- Install details (e.g. helm install args):helm install kruise openkruise/kruise --version 1.0.1
- Others:

**Comment by haobiaosheng** [comment]
when I in the v1.22.0 version of k8s,it can create sidecar normally

**Comment by zsdyx** [comment]
I also encountered this error. The k8s version is 1.24. Is it related to the version

**Comment by haobiaosheng** [comment]
It really related to the k8s version

when I in the v1.22.0 version of k8s,it can create sidecar normally.

You can try this version: v1.22.0

**Comment by iambowen** [comment]
ran into the same issue, I think there should be a fix on this problem instead of asking user to shift the k8s version.
