### ISSUE TITLE
[feature request]kubectl-plugin support helm install/upgrade

### ISSUE THREAD

**Issue by anjia0532** [openkruise/kruise#935]
**What would you like to be added**:
https://openkruise.io/docs/cli-tool/kubectl-plugin

**Why is this needed**:

Dingtalk group screenshots

![image](https://user-images.githubusercontent.com/15098916/159203512-3280cced-fc8e-4ead-8a7f-9fab71cd73d8.png)
![image](https://user-images.githubusercontent.com/15098916/159203538-3343e195-7f80-4da8-879a-75c5c599d4a7.png)
![image](https://user-images.githubusercontent.com/15098916/159203562-2ea6a0d8-8f71-4c28-9c1e-e37154a0caf8.png)

**Comment by veophi** [comment]
you have better move this issue to this repo: https://github.com/openkruise/kruise-tools.

**Comment by anjia0532** [comment]
OK
