### ISSUE TITLE
sidecarset support different resource config for diffrent app

### ISSUE THREAD

**Issue by kfhanjie** [openkruise/kruise#942]
**What would you like to be added**:
希望sidecarset可以按应用支持不同的sidecar资源限制，比如注入sidecar时，可以根据pod上的sidecar资源标签来配置不同的cpu,mem的request/limit

**Why is this needed**:
不同的应用有不同的负载，一刀切的sidecar资源限制，要么会出现sidecar资源不足导致的瓶颈，或者资源浪费

**Comment by kfhanjie** [comment]
可以参考https://github.com/istio/istio/issues/16126 的issues，我们的场景也是service mesh

**Comment by zmberg** [comment]
Whether the following annotations are added, and if they exist, the annotations will be used to assign sidecar resources:
```
sidecarset.istio.io/{sidecarName}-RequestsCPU: "200m"
sidecarset.istio.io/{sidecarName}-RequestsMemory: "512Mi"
sidecarset.istio.io/{sidecarName}-LimitsCPU: "300m"
sidecarset.istio.io/{sidecarName}-LimitsMemory: "1Gi"
```

@FillZpp @furykerry @kfhanjie

**Comment by FillZpp** [comment]
> Whether the following annotations are added, and if they exist, the annotations will be used to assign sidecar resources:

Yeah, we can support the annotations defined by Istio. And should Kruise has it own annotations, so that users without Istio have not to use the Istio annotations?

**Comment by kfhanjie** [comment]
> 
we don't  use istio for sevice mesh.  It feels strange to use istio annotation
