### ISSUE TITLE
[feature request] set pod not ready in PreparingUpdate and PreparingDelete lifecycle hook

### ISSUE THREAD

**Issue by ZYecho** [openkruise/kruise#944]
**What would you like to be added**:
set pod not ready in PreparingUpdate and PreparingDelete lifecycle hook

**Why is this needed**:
ccm（https://github.com/kubernetes/cloud-provider-alibaba-cloud） is responsible for create loadbalancer in cloud environment. ccm starts working when pod not ready, it removes the pod from LB.

we want to use cloneset PreparingUpdate and PreparingDelete lifecycle hook to inject some code to implement pod's graceful offline. without pod's not ready, ccm can't start working.

**Comment by FillZpp** [comment]
closed by #979 
/close
