### ISSUE TITLE
[BUG] Cloneset controller seems to not cleanup ‘Failed’ Pods.

### ISSUE THREAD

**Issue by maxking** [openkruise/kruise#947]
**What happened**:
This is mostly me retroactively trying to determine the root cause of an issue that I am currently observing in the cluster and wanted to ask here in case folks here would have better ideas than me.

I am observing that there are about 47 Pods currently there that have there `ownerReferences` pointing to 1 CloneSet. The CloneSet itself has replcas=1 set. 46 of these Pods are in a `Failed` state, except one that is ‘Running’ and seems healthy.

I am trying to understand why weren’t these Pods deleted when the New pods were created by cloneset controller during an upgrade procedure. All 46 of these Pods were created by the controller during a 2min window, which makes me think _something_ must’ve happened from our end at that time that I don’t know of. 

But that led me to try to understand why didn’t CloneSet adopt and delete them since they match the labelSelectors and also have an ownerReference to the Pod. 

So, I have some questions that I am trying to answer:
1. Any guesses on what _could’ve_ led to this siatuation?. 
1. Why isn’t CloneSet controller deleting these Pods (they have status.phase = Failed and deletionTimestamp = nul, which makes me believe that it isn’t being GC’d by K8s due to owner ref but CloneSet controller seems to have forgot about it too). 

Something peculiar about these Pods is that they are all assigned to the same node and are failing due to the same reason (missing space on the node!). It is also a mystery how they all got assigned the same pod, as-if someone “cloned” a single Pod along with the “node” fields. 
  
**What you expected to happen**:
I would expect Cloneset controller to clean-up after upgrading a Pod to new revision.

**How to reproduce it (as minimally and precisely as possible)**:
This is hard to say, since I have only encountered it in a running cluster, the steps that led to this situation are still a myster.

**Anything else we need to know?**:

**Environment**:
- Kruise version: 0.10.1
- Kubernetes version (use `kubectl version`): 1.18.14
- Install details (e.g. helm install args):
- Others:

**Comment by maxking** [comment]
If I am reading the code correctly, it does seem like cloneset acts only on ‘Active’ Pods and doesn’t consider ‘Failed’ or ‘Completed’ Pods or that aren’t ‘Deleted’: https://github.com/openkruise/kruise/blob/a25a9fb8eb3c0b1cc6f364412e43f3dadf950540/pkg/controller/cloneset/cloneset_controller.go#L234 

Is that it is expected behavior?

**Comment by FillZpp** [comment]
> Is that it is expected behavior?

Yeah, it is the same behavior to Deployment/ReplicaSet https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/replicaset/replica_set.go#L699

The inactive pods will be cleanup by the [podgc controller](https://github.com/kubernetes/kubernetes/tree/master/pkg/controller/podgc), but the defailt value of `terminated-pod-gc-threshold` is a little high. https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-garbage-collection

**Comment by maxking** [comment]
Thanks @FillZpp, this makes sense. I should’ve read the docs better :-) Closing this issue, I think I now understand what really happened.
