### ISSUE TITLE
[BUG] preDelete of Advanced StatefulSet not working

### ISSUE THREAD

**Issue by wkai886** [openkruise/kruise#950]
advanced statefulset  在 设置了   生命周期hook  preDelete 和 inPlaceUpdate 时：
           podUpdatePolicy 为 ReCreate 时， 升级或者重建无法触发 predeleting 状态。

ps：  保留序号的缩容 可以触发 predeleting
          podUpdatePolicy 为 InPlaceIfPossible 的升级可以正常触发 preUpdating 状态。

**Environment**:
- Kruise version:  0.9.0  0.10.0  1.0.0 （测试三个版本均有问题）
- Kubernetes version (use `kubectl version`):  1.18
- Install details (e.g. helm install args):  只改了镜像参数，镜像为内网相同tag 镜像
- Others:

**Comment by FillZpp** [comment]
/retitle [BUG] preDelete of Advanced StatefulSet not working

**Comment by FillZpp** [comment]
fixed in #979 

/close
