### ISSUE TITLE
[feature request] Add pod specified-delete for advanced statefulset

### ISSUE THREAD

**Issue by wkai886** [openkruise/kruise#951]
**What would you like to be added**:

advanced statefulset 添加类似 cloneset 的  在pod 上添加label    apps.kruise.io/specified-delete: true   去实现指定pod的重建，并且pod名字不变， 或者 基于 advanced statefulset 的 序号保留扩展下，可以实现重名pod的重建。

**Why is this needed**:

需要实现 advanced statefulset 的指定 pod重建的时候 能触发 preDelete 的 生命周期hook， 目前通过 序号保留将 某个序号的pod的删除的时候 可以触发 preDelete 的生命周期hook，但是不能覆盖住 同名pod 重建的场景。
如果可以支持 在pod 上添加label    apps.kruise.io/specified-delete: true   是最好的，能和cloneset 的 重建逻辑保持一致。

**Comment by FillZpp** [comment]
/retitle [feature request] Add pod specified-delete for advanced statefulset

**Comment by YTGhost** [comment]
@FillZpp  Maybe I can try to take over this job, can you assign this job to me? It would be nice to have some notes or help.
