### ISSUE TITLE
[Feat] Support upgrade sidecar container when main container in the notReady status 

### ISSUE THREAD

**Issue by dengqian** [openkruise/kruise#957]
![image](https://user-images.githubusercontent.com/6399971/163937668-698d826f-c80a-40f3-a0d5-f2d70b8a941b.png)

After the old empty container upgraded to new version of sidecar container, if the main container's status remains in the notReady status, the old sidecar container cannot be replaced by empty container.

Since the status of main container not always depends on sidecar container, can we add a configuration item to support ignore the status of main container?

**Comment by zmberg** [comment]
Is it possible to additionally record the ready situation of other containers in annotations before upgrading sidecar, if it is originally a not ready scenario, it feels like it can be ignored after upgrading?

@furykerry @dengqian
