### ISSUE TITLE
[feature request] add more detail info. in "kubectl kruise rollout status"

### ISSUE THREAD

**Issue by feveee** [openkruise/kruise#964]
kubectl kruise rollout status clonesets/pod-mv-vqqq -n testns1
Waiting for 5 pods to be ready...
Waiting for 4 pods to be ready...
Waiting for 2 pods to be ready...
Waiting for 1 pods to be ready...
CloneSet rolling update complete 5 pods at revision pod-mv-vqq
>>> only above info. output from kruise rollout stats  when run "helm upgrade"

**What would you like to be added**:

add  podName, Pod status，CloneSet name etc.  in rollout status

**Why is this needed**:   it's helpful to monitor  helm upgrade flow

**Comment by feveee** [comment]
updateStrategy:
    maxUnavailable: 1
    type: InPlaceIfPossible
    inPlaceUpdateStrategy:
      gracePeriodSeconds: 10
    priorityStrategy:
      weightPriority:
      - weight: 50
        matchSelector:
          matchLabels:
            upgrade-mode: standby
      - weight: 30
        matchSelector:
          matchLabels:
            upgrade-mode: active

>>>
we also want to check k8 logs/event about how k8 api do helm upgrade base on above strategy "weightPriority" "matchLabels"
but  no detail from   "kubectl  logs xxx/kubectl get events"

**Comment by hantmac** [comment]
[This PR](https://github.com/openkruise/kruise-tools/pull/65) Add more detail info like this:
```
Waiting for 1 pods to be ready...
Updated ready pods: [sample-clone-lkvtn]
Updated not ready pods: [sample-clone-khjv5]
CloneSet sample-clone rolling update complete 2 pods at revision sample-clone-7945cb487...
Updated ready pods: [sample-clone-khjv5 sample-clone-lkvtn]
Updated not ready pods: []
```

**Comment by FillZpp** [comment]
> https://github.com/openkruise/kruise-tools/pull/65 Add more detail info like this:

@hantmac Will it be too more pod names in the message? What's the output of `kubectl rollout status`?
