### ISSUE TITLE
[BUG] In-placeupdate  are slower than rollingupdate

### ISSUE THREAD

**Issue by CharlesQQ** [openkruise/kruise#966]
**What happened**:
deployment  applications by in-place update is found to be slower than rollingupdate

**What you expected to happen**:
In-placeupdate  should faster than rollingupdate

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
when a pod updated by in-placeupdate, it's image is changed, and must wait for old image be destroyed; However use rollingUpdate to update a pod,  new pod is created  when old pod's metedata.deleteTimestamp != null, destroy old pod and create new pod concurrently
**Environment**:
- Kruise version:
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Others:

**Comment by furykerry** [comment]
> when a pod updated by in-placeupdate, it's image is changed, and must wait for old image be destroyed;
if the container stop very slowly ( e.g. very long prestop process), inplace update indeed can be slower than rollingUpdate, and this is expected.  we cannot start container with new image without kill the old container, which may leads to two running container

**Comment by CharlesQQ** [comment]
@furykerry is there any way to faster inplaceupdate?

**Comment by furykerry** [comment]
inplace update that allow old and new container running in the same time can be too complex for both app developer and Kruise. app developer must ensure that the applications runs and stops correctly if there is multiple application process running and listening the same port. You can check the sidecar [hotupgrade](https://openkruise.io/docs/user-manuals/sidecarset#hot-upgrade) to see how complex such solution can be. 

you may check the container stop logic, and try to reduce the stopping process. If it is not possible, simply go to rollingUpdate.

**Comment by CharlesQQ** [comment]
`if the container stop very slowly ( e.g. very long prestop process), inplace update indeed can be slower than rollingUpdate`
