### ISSUE TITLE
[BUG] kruise-controller-manager pod fails to start

### ISSUE THREAD

**Issue by cerebrate** [openkruise/kruise#989]
**What happened**:

This has been occurring ever since a power-failure induced node restart on the cluster, although I am uncertain how that may be connected to the issue. Essentially, the kruise-controller-manager pod fails to start:

```
❯ kgpn kruise-system
NAME                                         READY   STATUS             RESTARTS       AGE
kruise-controller-manager-6d4f6c7f7c-ggw6l   0/1     CrashLoopBackOff   5 (112s ago)   5m52s
kruise-daemon-826q4                          1/1     Running            0              5m51s
```

Examining the pod log shows this error:

```
I0607 17:39:39.216232       1 deleg.go:130] setup "msg"="wait webhook ready"
panic: failed to new ca-cert watcher: too many open files

goroutine 488 [running]:
github.com/openkruise/kruise/pkg/webhook/util/health.Checker.func1()
        /workspace/pkg/webhook/util/health/checker.go:117 +0x187
sync.(*Once).doSlow(0x0, 0x0)
        /usr/local/go/src/sync/once.go:68 +0xd2
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:59
github.com/openkruise/kruise/pkg/webhook/util/health.Checker(0xc0a00136cce44519)
        /workspace/pkg/webhook/util/health/checker.go:111 +0x5e
github.com/openkruise/kruise/pkg/webhook.Checker(0x1e22213)
        /workspace/pkg/webhook/server.go:137 +0x35
github.com/openkruise/kruise/pkg/webhook.WaitReady()
        /workspace/pkg/webhook/server.go:145 +0x71
main.main.func2()
        /workspace/main.go:187 +0x65
created by main.main
        /workspace/main.go:185 +0xc8
```

The full pod log is included here:

[kruise-fail-log.txt](https://github.com/openkruise/kruise/files/8855403/kruise-fail-log.txt)

**What you expected to happen**:

The kruise-controller-manager pod to start normally.

**How to reproduce it (as minimally and precisely as possible)**:

I have not yet found a way to reproduce it on another system, unfortunately. I can confirm that on this system uninstalling and reinstalling OpenKruise via the helm chart does not resolve the issue.

**Environment**:
- Kruise version: 1.2.0, although the problem started with 1.1.0
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-04T02:28:17Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4+k3s1", GitCommit:"43b1cb48200d8f6af85c16ed944d68fcc96b6506", GitTreeState:"clean", BuildDate:"2022-02-24T22:38:17Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Install details (e.g. helm install args):

Installed by `helm upgrade kruise openkruise/kruise --version 1.2.0 -f kruise.hv.yaml`

kruise.hv.yaml:

```
manager:
  replicas: 1

daemon:
  socketLocation: "/var/run/k3s"
```

**Comment by FillZpp** [comment]
Hey @cerebrate , looks like it failed to create a fsnotify watcher because of the kernel error `too many open files`.

https://github.com/openkruise/kruise/blob/052979046e879fd1a7fae302d685b006229b6b13/pkg/webhook/util/health/checker.go#L115-L118

It is probably forbidden by the inotify limit of the OS. You could use `sysctl fs.inotify` to see the limit policies. Usually it is caused by the small `fs.inotify.max_user_instances` value.

**Comment by cerebrate** [comment]
Thanks - it turned out the problem went away with an unrelated Kubernetes upgrade (to 1.23.6), but I went ahead and bumped the fs.inotify.max_user_instances anyway just to be on the safe side.
