### ISSUE TITLE
[BUG] statefulset cannot updated to advanced sts in place

### ISSUE THREAD

**Issue by gotosre** [openkruise/kruise#995]
- version: 1.2
- kubernetes version: 1.18
- log:
`* : Invalid value: "The edited file failed validation": ValidationError(StatefulSet.status): missing required field "availableReplicas" in io.kruise.apps.v1beta1.StatefulSet.status`

**Comment by veophi** [comment]
How do you upgrade your kruise? Did you upgrade kruise CRDs?

**Comment by FillZpp** [comment]
Please paste your YAML with the new `apiVersion`.
