### ISSUE TITLE
[BUG] Kruise and Kubelet updated podReady, making podReady inconsistent

### ISSUE THREAD

**Issue by xigang** [openkruise/kruise#996]
**What happened**:
Kruise and Kubelet update podReady condition at the same time, and podReady = True overwrites podReady= False
```
{"type":"Ready","status":"False","lastProbeTime":null,"lastTransitionTime":null,"reason":"ReadinessGatesNotReady","message":"the status of pod readiness gate \"InPlaceUpdateReady\" is not \"True\", but False"}
{"type":"Ready","status":"False","lastProbeTime":null,"lastTransitionTime":null,"reason":"ReadinessGatesNotReady","message":"the status of pod readiness gate \"InPlaceUpdateReady\" is not \"True\", but False"}
{"type":"Ready","status":"False","lastProbeTime":null,"lastTransitionTime":"2022-06-01T02:06:51Z","reason":"ReadinessGatesNotReady","message":"the status of pod readiness gate \"InPlaceUpdateReady\" is not \"True\", but False"}
{"type":"Ready","status":"True","lastProbeTime":null,"lastTransitionTime":"2022-06-01T02:06:53Z"}																											
{"type":"Ready","status":"False","lastProbeTime":null,"lastTransitionTime":"2022-06-01T02:06:51Z","reason":"ReadinessGatesNotReady","message":"the status of pod readiness gate \"InPlaceUpdateReady\" is not \"True\", but False"}
{"type":"Ready","status":"True","lastProbeTime":null,"lastTransitionTime":"2022-06-01T02:10:31Z"},		
```
https://github.com/openkruise/kruise/blob/0434cfaa30b01317e4d70bd903fb86ba14736bf1/pkg/util/inplaceupdate/inplace_update.go#L173

When InPlaceUpdateReady = False will be update podReady=False. InPlaceUpdateReady = True, kriuse will update podReady=True. If kubelet updates podReady=False, it overwrites kriuse updates podReady= True.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kruise version:
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Others:

**Comment by FillZpp** [comment]
@xigang Hey, which version of kruise do you use? This should be solved in #537 and released since v0.10.0. After that, kruise will only set `InPlaceUpdateReady` condition to `True` and wait for kubelet updating the `Ready` condition to `True`.

**Comment by jiazhiguang** [comment]
In v0.10.0 kruise can set `Ready` condition to `False`,   this may conflict with the behavior of the kubelet.

**Comment by xigang** [comment]
> @xigang Hey, which version of kruise do you use? This should be solved in #537 and released since v0.10.0. After that, kruise will only set `InPlaceUpdateReady` condition to `True` and wait for kubelet updating the `Ready` condition to `True`.
hanks for replying. we are currently using version < 0.10.0. Kruise will update podReady=False when looking at the latest code when InPlaceUpdateReady=False. When InPlaceUpdateReady=True, podReady is set to True. Kruise and Kubelet update podReady at the same time. Kubelet sets podRready=False to overwrite kruise podReady=True?

```
func (c *realControl) updateCondition(pod *v1.Pod, condition v1.PodCondition) error {
	return retry.RetryOnConflict(retry.DefaultBackoff, func() error {
		clone, err := c.podAdapter.GetPod(pod.Namespace, pod.Name)
		if err != nil {
			return err
		}

		util.SetPodCondition(clone, condition)
		// We only update the ready condition to False, and let Kubelet update it to True
		if condition.Status == v1.ConditionFalse {
			util.SetPodReadyCondition(clone)
		}
		return c.podAdapter.UpdatePodStatus(clone)
	})
}
```

```
func SetPodReadyCondition(pod *v1.Pod) {
	podReady := GetCondition(pod, v1.PodReady)
	if podReady == nil {
		return
	}

	containersReady := GetCondition(pod, v1.ContainersReady)
	if containersReady == nil || containersReady.Status != v1.ConditionTrue {
		return
	}

	var unreadyMessages []string
	for _, rg := range pod.Spec.ReadinessGates {
		c := GetCondition(pod, rg.ConditionType)
		if c == nil {
			unreadyMessages = append(unreadyMessages, fmt.Sprintf("corresponding condition of pod readiness gate %q does not exist.", string(rg.ConditionType)))
		} else if c.Status != v1.ConditionTrue {
			unreadyMessages = append(unreadyMessages, fmt.Sprintf("the status of pod readiness gate %q is not \"True\", but %v", string(rg.ConditionType), c.Status))
		}
	}

	newPodReady := v1.PodCondition{
		Type:               v1.PodReady,
		Status:             v1.ConditionTrue,
		LastTransitionTime: metav1.Now(),
	}
	// Set "Ready" condition to "False" if any readiness gate is not ready.
	if len(unreadyMessages) != 0 {
		unreadyMessage := strings.Join(unreadyMessages, ", ")
		newPodReady = v1.PodCondition{
			Type:    v1.PodReady,
			Status:  v1.ConditionFalse,
			Reason:  "ReadinessGatesNotReady",
			Message: unreadyMessage,
		}
	}

	SetPodCondition(pod, newPodReady)
}
```

**Comment by xigang** [comment]
> Kruise version < v0.10:
> 
> 1. it sets `InPlaceUpdateReady=False` with `Ready=False` when the in-place update starts
> 2. it sets `InPlaceUpdateReady=True` with `Ready=True` when the in-place update completed
> 
> Kruise version >= v0.10:
> 
> 1. it sets `InPlaceUpdateReady=False` with `Ready=False` when the in-place update starts
> 2. **it only sets `InPlaceUpdateReady=True` and wait for kubelet updating `Ready=True`**
> 
> It mainly because:
> 
> * we don't want to make the starting of in-place update to be asynchronous, which has to wait for kubelet updating the `Ready` condition and it may be blocked if the node or kubelet is in some abnormal states.
> * (1) will not lead to the repetitions of `UpdatedReadyReplicas` changed, which may break the user's logic

I known that. Kruise version >= v0.10:

**Comment by xigang** [comment]
> Kruise version < v0.10:
> 
> 1. it sets `InPlaceUpdateReady=False` with `Ready=False` when the in-place update starts
> 2. it sets `InPlaceUpdateReady=True` with `Ready=True` when the in-place update completed
> 
> Kruise version >= v0.10:
> 
> 1. it sets `InPlaceUpdateReady=False` with `Ready=False` when the in-place update starts
> 2. **it only sets `InPlaceUpdateReady=True` and wait for kubelet updating `Ready=True`**
> 
> It mainly because:
> 
> * we don't want to make the starting of in-place update to be asynchronous, which has to wait for kubelet updating the `Ready` condition and it may be blocked if the node or kubelet is in some abnormal states.
> * (1) will not lead to the repetitions of `UpdatedReadyReplicas` changed, which may break the user's logic

I known that, only kubelet can set `Ready=True`.   When `InPlaceUpdateReady=False`, Kruise can set `Ready=False`.

But because of network latency and so on, At this time, Kubelet updates `InPlaceUpdateReady=True` and `Ready=True` later than Kruise. The pod condition updated by Kubelet overrides the correct condition updated by Kruise.

**Comment by xigang** [comment]
ping @FillZpp

**Comment by xigang** [comment]
@FillZpp Sorry, Looking at the latest version of the code, this problem has been solved .
