### ISSUE TITLE
[BUG] controller crashed and cannot start

### ISSUE THREAD

**Issue by gotosre** [openkruise/kruise#997]
**What happened**:
controller crashed and cannot start

**What you expected to happen**:
running normal

**Environment**:
- Kruise version: 1.2
- Kubernetes version (use `kubectl version`): 1.18

**log**

![image](https://user-images.githubusercontent.com/97461479/174243480-95ed7120-1623-46c8-84c9-e47c0300581d.png)
![image](https://user-images.githubusercontent.com/97461479/174243493-708bed56-b0a4-448e-8338-7ab1d2c7c43f.png)

**Comment by gotosre** [comment]
@veophi when i enable StatefulSetAutoDeletePVC feagate, controller rolling update and then crashed. any comparability problem with kube 1.18?

**Comment by gotosre** [comment]
reproduce:
1. install kruise without featuregate StatefulSetAutoDeletePVC
2. run advancedstatefulset
3. upgrade kruise with featuregate StatefulSetAutoDeletePVC
4. controller crashlooping!!!

repair:
1. rollback kruise without feagate
2. delete advsts
3. upgrade kruise with feagate StatefulSetAutoDeletePVC
4. redeploy advsts
5. succ.

---

so feagate cannot set when sts exists? expected result or not?

**Comment by veophi** [comment]
> @veophi when i enable StatefulSetAutoDeletePVC feagate, controller rolling update and then crashed. any comparability problem with kube 1.18?

Do you open `Kruise Webhook`？

plz show `kubectl get mutatingwebhookconfigurations  kruise-mutating-webhook-configuration`

**Comment by FillZpp** [comment]
Hey @gotosre , thanks for reporting, looks like it is a compatible issue. I have cherry-picked #999 to release-1.2 and rebuild the v1.2.0 image. Could you please recreate the kruise-controller-manager pod and see if it works well?

**Comment by gotosre** [comment]
> > @veophi when i enable StatefulSetAutoDeletePVC feagate, controller rolling update and then crashed. any comparability problem with kube 1.18?
> 
> Do you open `Kruise Webhook`？
> 
> plz show `kubectl get mutatingwebhookconfigurations kruise-mutating-webhook-configuration`

install kruise via chart.
---
$ kubectl get mutatingwebhookconfigurations kruise-mutating-webhook-configuration
NAME                                    WEBHOOKS   AGE
kruise-mutating-webhook-configuration   11         37h

**Comment by gotosre** [comment]
> Hey @gotosre , thanks for reporting, looks like it is a compatible issue. I have cherry-picked #999 to release-1.2 and rebuild the v1.2.0 image. Could you please recreate the kruise-controller-manager pod and see if it works well?

it works.

**Comment by gotosre** [comment]
> Hey @gotosre , thanks for reporting, looks like it is a compatible issue. I have cherry-picked #999 to release-1.2 and rebuild the v1.2.0 image. Could you please recreate the kruise-controller-manager pod and see if it works well?

but another question, my atst manifest below:
`~~~omitted~~~  
  volumeClaimTemplates:
  - metadata:
      name: loki-ingester-data
    spec:
      persistentVolumeClaimRetentionPolicy:
        whenDeleted: Retain
        whenScaled: Delete
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 200Gi
      storageClassName: cbs-wff`
with `persistentVolumeClaimRetentionPolicy` specified, but when i apply it, 
manifest below
`    volumeClaimTemplates:
    - metadata:
        creationTimestamp: null
        name: loki-ingester-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 200Gi
        storageClassName: cbs-wff
      status:
        phase: Pending`

persistentVolumeClaimRetentionPolicy is missing..

i dont know what happened?
not compatile with kubernetes 1.18?

**Comment by FillZpp** [comment]
closed by https://github.com/openkruise/kruise/issues/1000#issuecomment-1159935130
/close
